**SQL AND PANDAS EXCERSIZE**

In [1]:
import pandas as pd

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://chaiaurcode:[password]@localhost:5432/sqlnotes

Connecting to 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

In [ ]:
%%sql 
CREATE TABLE products(
    product_id SERIAL PRIMARY KEY ,
    product_name VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    order_state VARCHAR(50) NOT NULL,

    product_price NUMERIC(10,2) NOT NULL
        CHECK(product_price >= 0),

    product_quantity INT NOT NULL
        CHECK (product_quantity > 0),
    
    discount NUMERIC(5,2) DEFAULT 0 
        CHECK (discount >= 0 AND discount <= 50),

    gross_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        (product_price * product_quantity) 
        STORED,

    net_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        ((product_price * product_quantity) * (1 - discount / 100)) 
        STORED
);

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

RuntimeError: (psycopg2.errors.DuplicateTable) relation "products" already exists

[SQL: CREATE TABLE products(
    product_id SERIAL PRIMARY KEY ,
    product_name VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    order_state VARCHAR(50) NOT NULL,

    product_price NUMERIC(10,2) NOT NULL
        CHECK(product_price >= 0),

    product_quantity INT NOT NULL
        CHECK (product_quantity > 0),

    discount NUMERIC(5,2) DEFAULT 0
        CHECK (discount >= 0 AND discount <= 50),

    gross_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        (product_price * product_quantity)
        STORED,

    net_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        ((product_price * product_quantity) * (1 - discount / 100))
        STORED
);]
(Background on this error at: https://sqlalche.me/e/20/f405)

product_id, product_name, order_data, customer_name, order_state, product_price, product_quantity, discount, gross_amount, net_amount

In [5]:
%%sql
INSERT INTO products 
(product_name, order_date, customer_name, order_state, product_price, product_quantity, discount)
VALUES
('table', '2020-05-09', 'kiran', 'MH', 2200, 3, 6),
('fan', '2020-05-10', 'sonam', 'RJ', 2000, 2, 2),
('sopa', '2020-05-11', 'sima', 'RJ', 4300, 1, 16),
('sopa', '2020-05-11', 'sima', 'RJ', 4300, 1, 16),
('chair', '2020-05-12', 'satish', 'GJ', 1200, 10, 0),
('bulps', '2020-05-14', 'karim', 'JK', 20, 100, 2),
('fan', '2020-05-15', 'kushal', 'CN', 2000, 2, 2),
('bulps', '2020-05-16', 'sunam', 'BR', 20, 10, 2),
('watch', '2020-05-17', 'jaya', 'UP', 220, 1, 2),
('cooler', '2020-05-18', 'manish', 'RJ', 3200, 2, 20),
('table', '2020-05-19', 'mahendra', 'KR', 2200, 4, 6),
('sopa', '2020-05-20', 'sushant', 'KR', 4300, 2, 16);

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

++
||
++
++

In [6]:
%%sql 
SELECT * FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

36 rows affected.

+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
| product_id | product_name | order_date | customer_name | order_state | product_price | product_quantity | discount | gross_amount | net_amount |
+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
|     1      |    table     | 2020-05-09 |     kiran     |      MH     |    2200.00    |        3         |   6.00   |   6600.00    |  6204.00   |
|     2      |     fan      | 2020-05-10 |     sonam     |      RJ     |    2000.00    |        2         |   2.00   |   4000.00    |  3920.00   |
|     3      |     sopa     | 2020-05-11 |      sima     |      RJ     |    4300.00    |        1         |  16.00   |   4300.00    |  3612.00   |
|     4      |     sopa     | 2020-05-11 |      sima     |      RJ     |    4300.00    |        1         |  16.00   |   4300.00    |  3612.00   |
|     5      |    chair     | 2020-05-12 |     satish    |      GJ     |    1200.00    |        10        |   0.00   |   12000.00   |  12000.00  |
|     6      |    bulps     | 2020-05-14 |     karim     |      JK     |     20.00     |       100        |   2.00   |   2000.00    |  1960.00   |
|     7      |     fan      | 2020-05-15 |     kushal    |      CN     |    2000.00    |        2         |   2.00   |   4000.00    |  3920.00   |
|     8      |    bulps     | 2020-05-16 |     sunam     |      BR     |     20.00     |        10        |   2.00   |    200.00    |   196.00   |
|     9      |    watch     | 2020-05-17 |      jaya     |      UP     |     220.00    |        1         |   2.00   |    220.00    |   215.60   |
|     10     |    cooler    | 2020-05-18 |     manish    |      RJ     |    3200.00    |        2         |  20.00   |   6400.00    |  5120.00   |
+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
Truncated to displaylimit of 10.

In [7]:
products = {
    'product_id' : [i for i in range(1, 13)],
    'product_name' : ['table', 'fan', 'sopa', 'sopa', 'chair', 'bulps', 'fan', 'bulps', 'watch', 'cooler', 'table', 'sopa'],
    'order_date' : ['2020-05-09', '2020-05-10', '2020-05-09', '2020-05-11', '2020-05-12', '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19', '2020-05-20'],
    'customer_name' : ['kiran', 'sonam', 'sima', 'sima', 'satish', 'karim', 'kushal', 'sunam', 'jaya', 'manish', 'mahendra', 'sushant'],
    'order_state' : ['MH', 'RJ', 'RJ', 'RJ', 'GJ', 'JK', 'CN', 'BR', 'UP', 'RJ', 'KR', 'KR'],
    'product_price' : [2200, 2000, 4300, 4300, 1200, 20, 2000, 20, 220, 3200, 2200, 4300],
    'product_quantity' : [3, 2, 1, 1, 10, 100, 2, 10, 1, 2, 4, 2],
    'discount' : [6, 2, 16, 16, 0, 2, 2, 2, 2, 20, 6, 16]
}
products = pd.DataFrame(products)
products

,product_id,product_name,order_date,customer_name,order_state,product_price,product_quantity,discount
0,1,table,2020-05-09,kiran,MH,2200,3,6
1,2,fan,2020-05-10,sonam,RJ,2000,2,2
2,3,sopa,2020-05-09,sima,RJ,4300,1,16
3,4,sopa,2020-05-11,sima,RJ,4300,1,16
4,5,chair,2020-05-12,satish,GJ,1200,10,0
5,6,bulps,2020-05-14,karim,JK,20,100,2
6,7,fan,2020-05-15,kushal,CN,2000,2,2
7,8,bulps,2020-05-16,sunam,BR,20,10,2
8,9,watch,2020-05-17,jaya,UP,220,1,2
9,10,cooler,2020-05-18,manish,RJ,3200,2,20
10,11,table,2020-05-19,mahendra,KR,2200,4,6
11,12,sopa,2020-05-20,sushant,KR,4300,2,16

In [8]:
products['gross_amount'] = (
    products['product_price'] * products['product_quantity']
)
products['net_amount'] = (
    products['gross_amount'] - (products['gross_amount'] * products['discount']) / 100
)

In [9]:
products.head()

,product_id,product_name,order_date,customer_name,order_state,product_price,product_quantity,discount,gross_amount,net_amount
0,1,table,2020-05-09,kiran,MH,2200,3,6,6600,6204.0
1,2,fan,2020-05-10,sonam,RJ,2000,2,2,4000,3920.0
2,3,sopa,2020-05-09,sima,RJ,4300,1,16,4300,3612.0
3,4,sopa,2020-05-11,sima,RJ,4300,1,16,4300,3612.0
4,5,chair,2020-05-12,satish,GJ,1200,10,0,12000,12000.0

In [10]:
%%sql 
SELECT COUNT(product_id) AS total_orders
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

1 rows affected.

+--------------+
| total_orders |
+--------------+
|      36      |
+--------------+

In [11]:
pd.DataFrame({
    'total_orders' : [products['product_id'].count()]
})

   total_orders
0            12

In [12]:
products['product_id'].agg(total_order = 'count')

total_order    12
Name: product_id, dtype: int64

In [13]:
%%sql 
SELECT SUM(net_amount) AS total_sales_revenue
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

1 rows affected.

+---------------------+
| total_sales_revenue |
+---------------------+
|      168766.80      |
+---------------------+

In [14]:
products['net_amount'].sum()

np.float64(56255.6)

In [15]:
pd.DataFrame({
    'total_sale_revenue' : [products['net_amount'].sum()]
})

   total_sale_revenue
0             56255.6

In [16]:
products['net_amount'].agg(total_sale_revenue = 'sum')

total_sale_revenue    56255.6
Name: net_amount, dtype: float64

In [17]:
%%sql 
SELECT product_name AS expensive_product, MAX(product_price) AS price
FROM products
GROUP BY product_name
ORDER BY MAX(product_price) DESC
limit 1;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

1 rows affected.

+-------------------+---------+
| expensive_product |  price  |
+-------------------+---------+
|        sopa       | 4300.00 |
+-------------------+---------+

In [18]:
products.groupby('product_name')['product_price'].max().sort_values(ascending=False).head(1)

product_name
sopa    4300
Name: product_price, dtype: int64

In [19]:
result = (
    products.groupby('product_name')['product_price'].max().sort_values(ascending=False).head(1)
)
pd.DataFrame({
    'expensive_product' : result.index,
    'price' : result.values
})

  expensive_product  price
0              sopa   4300

In [20]:
%%sql 
SELECT order_state, SUM(net_amount) AS revenue
FROM products 
GROUP BY order_state
ORDER BY revenue DESC;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

8 rows affected.

+-------------+----------+
| order_state | revenue  |
+-------------+----------+
|      RJ     | 48792.00 |
|      KR     | 46488.00 |
|      GJ     | 36000.00 |
|      MH     | 18612.00 |
|      CN     | 11760.00 |
|      JK     | 5880.00  |
|      UP     |  646.80  |
|      BR     |  588.00  |
+-------------+----------+

In [21]:
result = products.groupby('order_state')['net_amount'].sum().sort_values(ascending=False)
result

order_state
RJ    16264.0
KR    15496.0
GJ    12000.0
MH     6204.0
CN     3920.0
JK     1960.0
UP      215.6
BR      196.0
Name: net_amount, dtype: float64

In [22]:
pd.DataFrame({
    'order_state': result.index,
    'revenue': result.values
})

  order_state  revenue
0          RJ  16264.0
1          KR  15496.0
2          GJ  12000.0
3          MH   6204.0
4          CN   3920.0
5          JK   1960.0
6          UP    215.6
7          BR    196.0

In [23]:
%%sql 
SELECT order_state, SUM(net_amount) AS revenue
FROM products
WHERE order_state = 'RJ'
GROUP BY order_state;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

1 rows affected.

+-------------+----------+
| order_state | revenue  |
+-------------+----------+
|      RJ     | 48792.00 |
+-------------+----------+

In [24]:
result = (
    products[products['order_state'] == 'RJ']
    .groupby('order_state')['net_amount'].sum()
)
result

order_state
RJ    16264.0
Name: net_amount, dtype: float64

In [25]:
pd.DataFrame({
    'order_state' : result.index,
    'revenue' : result.values
})

  order_state  revenue
0          RJ  16264.0

In [26]:
%%sql
SELECT product_name, SUM(net_amount) AS revenue
FROM products
GROUP BY product_name
HAVING SUM(net_amount) > 10000

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

5 rows affected.

+--------------+----------+
| product_name | revenue  |
+--------------+----------+
|     sopa     | 43344.00 |
|    chair     | 36000.00 |
|    cooler    | 15360.00 |
|    table     | 43428.00 |
|     fan      | 23520.00 |
+--------------+----------+

In [27]:
result = (
    products
    .groupby('product_name')['net_amount']
    .sum()
)
result[result > 10000]
# result = result.reset_index(name = 'revenue')

product_name
chair    12000.0
sopa     14448.0
table    14476.0
Name: net_amount, dtype: float64

In [28]:
pd.DataFrame({
    'product_name' : result[result > 10000].index,
    'revenue' : result[result > 10000].values
})

  product_name  revenue
0        chair  12000.0
1         sopa  14448.0
2        table  14476.0

In [29]:
result[result > 10000].reset_index()

  product_name  net_amount
0        chair     12000.0
1         sopa     14448.0
2        table     14476.0

In [30]:
result = (
    products
    .groupby('product_name')['net_amount']
    .sum()
)

print(type(result))

print(result)

print(result.index)

print(result.values)

print(result.reset_index())

print(result.reset_index(name='revenue'))

<class 'pandas.Series'>
product_name
bulps      2156.0
chair     12000.0
cooler     5120.0
fan        7840.0
sopa      14448.0
table     14476.0
watch       215.6
Name: net_amount, dtype: float64
Index(['bulps', 'chair', 'cooler', 'fan', 'sopa', 'table', 'watch'], dtype='str', name='product_name')
[ 2156.  12000.   5120.   7840.  14448.  14476.    215.6]
  product_name  net_amount
0        bulps      2156.0
1        chair     12000.0
2       cooler      5120.0
3          fan      7840.0
4         sopa     14448.0
5        table     14476.0
6        watch       215.6
  product_name  revenue
0        bulps   2156.0
1        chair  12000.0
2       cooler   5120.0
3          fan   7840.0
4         sopa  14448.0
5        table  14476.0
6        watch    215.6

In [31]:
%%sql 
SELECT customer_name, SUM(net_amount) AS revenue
FROM products
GROUP BY customer_name
ORDER BY revenue DESC
LIMIT 3;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

3 rows affected.

+---------------+----------+
| customer_name | revenue  |
+---------------+----------+
|     satish    | 36000.00 |
|    mahendra   | 24816.00 |
|    sushant    | 21672.00 |
+---------------+----------+

In [32]:
result = (
    products
    .groupby('customer_name')['net_amount']
    .sum()
    .sort_values(ascending=False)
    .head(3)
)
result

customer_name
satish      12000.0
mahendra     8272.0
sushant      7224.0
Name: net_amount, dtype: float64

In [33]:
pd.DataFrame({
    'customer_name': result.index,
    'revenue' : result.values
})

  customer_name  revenue
0        satish  12000.0
1      mahendra   8272.0
2       sushant   7224.0

In [34]:
result.reset_index(name = 'revenue')

  customer_name  revenue
0        satish  12000.0
1      mahendra   8272.0
2       sushant   7224.0

In [35]:
%%sql 
SELECT order_state, AVG(discount) AS avg_discount
FROM products
GROUP BY order_state
HAVING AVG(discount) > 5;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

3 rows affected.

+-------------+---------------------+
| order_state |     avg_discount    |
+-------------+---------------------+
|      KR     | 11.0000000000000000 |
|      MH     |  6.0000000000000000 |
|      RJ     | 13.5000000000000000 |
+-------------+---------------------+

In [36]:
result = ( 
    products
    .groupby('order_state')['discount']
    .mean()
)
result[result > 5].reset_index(name = 'discount')

  order_state  discount
0          KR      11.0
1          MH       6.0
2          RJ      13.5

In [37]:
%%sql 
SELECT order_state, MAX(product_price) AS highest_price
FROM products
GROUP BY order_state;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

8 rows affected.

+-------------+---------------+
| order_state | highest_price |
+-------------+---------------+
|      KR     |    4300.00    |
|      MH     |    2200.00    |
|      BR     |     20.00     |
|      UP     |     220.00    |
|      CN     |    2000.00    |
|      RJ     |    4300.00    |
|      JK     |     20.00     |
|      GJ     |    1200.00    |
+-------------+---------------+

In [38]:
result = (
    products
    .groupby('order_state')['product_price']
    .max()
)
result.reset_index(name = 'highest_price')

  order_state  highest_price
0          BR             20
1          CN           2000
2          GJ           1200
3          JK             20
4          KR           4300
5          MH           2200
6          RJ           4300
7          UP            220

In [39]:
%%sql 
SELECT order_state, 
COUNT(product_id) AS total_order,
SUM(net_amount) AS total_revenue,
AVG(discount) AS avg_discount,
MAX(product_price) AS highest_price
FROM products 
GROUP BY order_state;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

8 rows affected.

+-------------+-------------+---------------+---------------------+---------------+
| order_state | total_order | total_revenue |     avg_discount    | highest_price |
+-------------+-------------+---------------+---------------------+---------------+
|      KR     |      6      |    46488.00   | 11.0000000000000000 |    4300.00    |
|      MH     |      3      |    18612.00   |  6.0000000000000000 |    2200.00    |
|      BR     |      3      |     588.00    |  2.0000000000000000 |     20.00     |
|      UP     |      3      |     646.80    |  2.0000000000000000 |     220.00    |
|      CN     |      3      |    11760.00   |  2.0000000000000000 |    2000.00    |
|      RJ     |      12     |    48792.00   | 13.5000000000000000 |    4300.00    |
|      JK     |      3      |    5880.00    |  2.0000000000000000 |     20.00     |
|      GJ     |      3      |    36000.00   |        0E-20        |    1200.00    |
+-------------+-------------+---------------+---------------------+---------------+

In [40]:
result = (
    products
    .groupby('order_state')
    .agg(
        total_order = ('product_id', 'count'),
        total_revenue = ('net_amount', 'sum'),
        avg_discount = ('discount', 'mean'),
        highest_price = ('product_price', 'max')
    )
)
result.reset_index()

  order_state  total_order  total_revenue  avg_discount  highest_price
0          BR            1          196.0           2.0             20
1          CN            1         3920.0           2.0           2000
2          GJ            1        12000.0           0.0           1200
3          JK            1         1960.0           2.0             20
4          KR            2        15496.0          11.0           4300
5          MH            1         6204.0           6.0           2200
6          RJ            4        16264.0          13.5           4300
7          UP            1          215.6           2.0            220

In [41]:
%%sql
SELECT order_state, COUNT(DISTINCT product_name) AS unique_products
FROM products
GROUP BY order_state;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

8 rows affected.

+-------------+-----------------+
| order_state | unique_products |
+-------------+-----------------+
|      BR     |        1        |
|      CN     |        1        |
|      GJ     |        1        |
|      JK     |        1        |
|      KR     |        2        |
|      MH     |        1        |
|      RJ     |        3        |
|      UP     |        1        |
+-------------+-----------------+

In [42]:
result = (
    products
    .groupby('order_state', as_index = False)['product_name']
    .nunique()
)
result

  order_state  product_name
0          BR             1
1          CN             1
2          GJ             1
3          JK             1
4          KR             2
5          MH             1
6          RJ             3
7          UP             1

In [43]:
%%sql 
SELECT order_state, count(DISTINCT product_name) AS unique_products
FROM products
GROUP BY order_state
HAVING count(DISTINCT product_name) >= 2;
# MERE KO SAMAJAO KI HAVING KO ALIAS VARIABLE KYON NAHI CHALATA COMPARE KARANE KO MUJHE PURA count(DISTINCT product_name) LIKHANA PADA
# MAINE YAHA ABHI LIKHA DIYA KYOKI MERE KO BAD MEN YAD NAHI RAHENGA

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

2 rows affected.

+-------------+-----------------+
| order_state | unique_products |
+-------------+-----------------+
|      KR     |        2        |
|      RJ     |        3        |
+-------------+-----------------+

In [44]:
result = (
    products
    .groupby('order_state')['product_name']
    .nunique()
    .reset_index(name = 'unique_product')
)
result[result['unique_product'] >= 2]

  order_state  unique_product
4          KR               2
6          RJ               3

In [45]:
result = (
    products
    .groupby('order_state')['product_name']
    .nunique()
).reset_index(name = 'unique_product')
result[result['unique_product'] >= 2]

  order_state  unique_product
4          KR               2
6          RJ               3

In [57]:
%%sql 
SELECT product_name, AVG(product_price) AS avg_price
FROM products
GROUP BY product_name
HAVING AVG(product_price) > 2000;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

3 rows affected.

+--------------+-----------------------+
| product_name |       avg_price       |
+--------------+-----------------------+
|     sopa     | 4300.0000000000000000 |
|    cooler    | 3200.0000000000000000 |
|    table     | 2200.0000000000000000 |
+--------------+-----------------------+

In [59]:
result = (
    products
    .groupby('product_name')['product_price']
    .mean()
).reset_index(name = 'avg_price')
result[result['avg_price'] > 2000]

  product_name  avg_price
2       cooler     3200.0
4         sopa     4300.0
5        table     2200.0

In [60]:
%%sql 
SELECT order_state, AVG(discount) AS avg_discount, SUM(net_amount) AS total_revenue
FROM products
GROUP BY order_state
HAVING AVG(discount) >= 10 AND SUM(net_amount) > 10000;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

2 rows affected.

+-------------+---------------------+---------------+
| order_state |     avg_discount    | total_revenue |
+-------------+---------------------+---------------+
|      KR     | 11.0000000000000000 |    15496.00   |
|      RJ     | 13.5000000000000000 |    16264.00   |
+-------------+---------------------+---------------+

In [67]:
result = (
    products
    .groupby('order_state')
    .agg(
        avg_discount = ('discount', 'mean'),
        total_revenue = ('net_amount', 'sum')
    )
)
result[
    (result['avg_discount'] >= 10)
    & (result['total_revenue'] > 10000)
]

             avg_discount  total_revenue
order_state
KR                   11.0        15496.0
RJ                   13.5        16264.0

In [75]:
result = (
    products
    .groupby('customer_name')['net_amount']
    .sum()
    .sort_values(ascending = False)
    .head(3)
).reset_index(name = 'total_revenue')
result

  customer_name  total_revenue
0        satish        12000.0
1      mahendra         8272.0
2       sushant         7224.0

In [77]:
%%sql 
SELECT customer_name, SUM(net_amount) AS total_revenue
FROM products
GROUP BY customer_name
ORDER BY total_revenue DESC
LIMIT 3;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

3 rows affected.

+---------------+---------------+
| customer_name | total_revenue |
+---------------+---------------+
|     satish    |    12000.00   |
|    mahendra   |    8272.00    |
|    sushant    |    7224.00    |
+---------------+---------------+

In [80]:
%%sql 
SELECT customer_name, order_state, net_amount, SUM(net_amount)
OVER(PARTITION BY order_state) AS state_total_revenue
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+-------------+------------+---------------------+
| customer_name | order_state | net_amount | state_total_revenue |
+---------------+-------------+------------+---------------------+
|     sunam     |      BR     |   196.00   |        196.00       |
|     kushal    |      CN     |  3920.00   |       3920.00       |
|     satish    |      GJ     |  12000.00  |       12000.00      |
|     karim     |      JK     |  1960.00   |       1960.00       |
|    sushant    |      KR     |  7224.00   |       15496.00      |
|    mahendra   |      KR     |  8272.00   |       15496.00      |
|     kiran     |      MH     |  6204.00   |       6204.00       |
|      sima     |      RJ     |  3612.00   |       16264.00      |
|     sonam     |      RJ     |  3920.00   |       16264.00      |
|     manish    |      RJ     |  5120.00   |       16264.00      |
+---------------+-------------+------------+---------------------+
Truncated to displaylimit of 10.

In [88]:
products['state_total_revenue'] = (
    products
    .groupby('order_state')['net_amount']
    .transform('sum')
)
products[
    ['customer_name', 'order_state', 'net_amount', 'state_total_revenue']
]

   customer_name order_state  net_amount  state_total_revenue
0          kiran          MH      6204.0               6204.0
1          sonam          RJ      3920.0              16264.0
2           sima          RJ      3612.0              16264.0
3           sima          RJ      3612.0              16264.0
4         satish          GJ     12000.0              12000.0
5          karim          JK      1960.0               1960.0
6         kushal          CN      3920.0               3920.0
7          sunam          BR       196.0                196.0
8           jaya          UP       215.6                215.6
9         manish          RJ      5120.0              16264.0
10      mahendra          KR      8272.0              15496.0
11       sushant          KR      7224.0              15496.0

In [89]:
%%sql 
SELECT customer_name, product_name, net_amount, SUM(net_amount) 
OVER(PARTITION BY product_name) AS product_total_revenue 
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+--------------+------------+-----------------------+
| customer_name | product_name | net_amount | product_total_revenue |
+---------------+--------------+------------+-----------------------+
|     sunam     |    bulps     |   196.00   |        2156.00        |
|     karim     |    bulps     |  1960.00   |        2156.00        |
|     satish    |    chair     |  12000.00  |        12000.00       |
|     manish    |    cooler    |  5120.00   |        5120.00        |
|     kushal    |     fan      |  3920.00   |        7840.00        |
|     sonam     |     fan      |  3920.00   |        7840.00        |
|    sushant    |     sopa     |  7224.00   |        14448.00       |
|      sima     |     sopa     |  3612.00   |        14448.00       |
|      sima     |     sopa     |  3612.00   |        14448.00       |
|    mahendra   |    table     |  8272.00   |        14476.00       |
+---------------+--------------+------------+-----------------------+
Truncated to displaylimit of 10.

In [90]:
products['product_total_revenue'] = (
    products
    .groupby('product_name')['net_amount']
    .transform('sum')
)
products[
    ['customer_name', 'product_name', 'net_amount', 'product_total_revenue']
]

   customer_name product_name  net_amount  product_total_revenue
0          kiran        table      6204.0                14476.0
1          sonam          fan      3920.0                 7840.0
2           sima         sopa      3612.0                14448.0
3           sima         sopa      3612.0                14448.0
4         satish        chair     12000.0                12000.0
5          karim        bulps      1960.0                 2156.0
6         kushal          fan      3920.0                 7840.0
7          sunam        bulps       196.0                 2156.0
8           jaya        watch       215.6                  215.6
9         manish       cooler      5120.0                 5120.0
10      mahendra        table      8272.0                14476.0
11       sushant         sopa      7224.0                14448.0

In [92]:
%%sql 
SELECT customer_name, order_state, discount, AVG(discount)
OVER(PARTITION BY order_state) AS state_avg_discount
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+-------------+----------+---------------------+
| customer_name | order_state | discount |  state_avg_discount |
+---------------+-------------+----------+---------------------+
|     sunam     |      BR     |   2.00   |  2.0000000000000000 |
|     kushal    |      CN     |   2.00   |  2.0000000000000000 |
|     satish    |      GJ     |   0.00   |        0E-20        |
|     karim     |      JK     |   2.00   |  2.0000000000000000 |
|    sushant    |      KR     |  16.00   | 11.0000000000000000 |
|    mahendra   |      KR     |   6.00   | 11.0000000000000000 |
|     kiran     |      MH     |   6.00   |  6.0000000000000000 |
|      sima     |      RJ     |  16.00   | 13.5000000000000000 |
|     sonam     |      RJ     |   2.00   | 13.5000000000000000 |
|     manish    |      RJ     |  20.00   | 13.5000000000000000 |
+---------------+-------------+----------+---------------------+
Truncated to displaylimit of 10.

In [93]:
products['state_avg_discount'] = (
    products
    .groupby('order_state')['discount']
    .transform('mean')
)
products[
    ['customer_name', 'order_state', 'discount', 'state_avg_discount']
]

   customer_name order_state  discount  state_avg_discount
0          kiran          MH         6                 6.0
1          sonam          RJ         2                13.5
2           sima          RJ        16                13.5
3           sima          RJ        16                13.5
4         satish          GJ         0                 0.0
5          karim          JK         2                 2.0
6         kushal          CN         2                 2.0
7          sunam          BR         2                 2.0
8           jaya          UP         2                 2.0
9         manish          RJ        20                13.5
10      mahendra          KR         6                11.0
11       sushant          KR        16                11.0

In [94]:
%%sql 
SELECT customer_name, product_name, product_quantity, SUM(product_quantity)
OVER(PARTITION BY product_name) AS customer_total_quantity
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+--------------+------------------+-------------------------+
| customer_name | product_name | product_quantity | customer_total_quantity |
+---------------+--------------+------------------+-------------------------+
|     sunam     |    bulps     |        10        |           110           |
|     karim     |    bulps     |       100        |           110           |
|     satish    |    chair     |        10        |            10           |
|     manish    |    cooler    |        2         |            2            |
|     kushal    |     fan      |        2         |            4            |
|     sonam     |     fan      |        2         |            4            |
|    sushant    |     sopa     |        2         |            4            |
|      sima     |     sopa     |        1         |            4            |
|      sima     |     sopa     |        1         |            4            |
|    mahendra   |    table     |        4         |            7            |
+---------------+--------------+------------------+-------------------------+
Truncated to displaylimit of 10.

In [95]:
products['customer_total_quantity'] = (
    products
    .groupby('product_name')['product_quantity']
    .transform('sum')
)
products[
    ['customer_name', 'product_name', 'product_quantity', 'customer_total_quantity']
]

   customer_name product_name  product_quantity  customer_total_quantity
0          kiran        table                 3                        7
1          sonam          fan                 2                        4
2           sima         sopa                 1                        4
3           sima         sopa                 1                        4
4         satish        chair                10                       10
5          karim        bulps               100                      110
6         kushal          fan                 2                        4
7          sunam        bulps                10                      110
8           jaya        watch                 1                        1
9         manish       cooler                 2                        2
10      mahendra        table                 4                        7
11       sushant         sopa                 2                        4

In [98]:
%%sql
SELECT customer_name, product_name, order_date, COUNT(customer_name)
OVER(PARTITION BY customer_name) AS customer_total_order
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+--------------+------------+----------------------+
| customer_name | product_name | order_date | customer_total_order |
+---------------+--------------+------------+----------------------+
|      jaya     |    watch     | 2020-05-17 |          1           |
|     karim     |    bulps     | 2020-05-14 |          1           |
|     kiran     |    table     | 2020-05-09 |          1           |
|     kushal    |     fan      | 2020-05-15 |          1           |
|    mahendra   |    table     | 2020-05-19 |          1           |
|     manish    |    cooler    | 2020-05-18 |          1           |
|     satish    |    chair     | 2020-05-12 |          1           |
|      sima     |     sopa     | 2020-05-11 |          2           |
|      sima     |     sopa     | 2020-05-11 |          2           |
|     sonam     |     fan      | 2020-05-10 |          1           |
+---------------+--------------+------------+----------------------+
Truncated to displaylimit of 10.

In [100]:
products['customer_total_order'] = (
    products
    .groupby('customer_name')['customer_name']
    .transform('count')
)
products[
    ['customer_name', 'product_name', 'order_date', 'customer_total_order']
]

   customer_name product_name  order_date  customer_total_order
0          kiran        table  2020-05-09                     1
1          sonam          fan  2020-05-10                     1
2           sima         sopa  2020-05-09                     2
3           sima         sopa  2020-05-11                     2
4         satish        chair  2020-05-12                     1
5          karim        bulps  2020-05-14                     1
6         kushal          fan  2020-05-15                     1
7          sunam        bulps  2020-05-16                     1
8           jaya        watch  2020-05-17                     1
9         manish       cooler  2020-05-18                     1
10      mahendra        table  2020-05-19                     1
11       sushant         sopa  2020-05-20                     1

<pre>Har order ke saath us product ki sabse zyada discount (%) bhi dikhani hai. 
product_name	customer_name	discount	product_max_discount</pre>

In [ ]:
%%sql 
SELECT product_name, customer_name, discount, MAX(discount) 
OVER(PARTITION BY product_name) AS product_max_discount
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+--------------+---------------+----------+----------------------+
| product_name | customer_name | discount | product_max_discount |
+--------------+---------------+----------+----------------------+
|    bulps     |     sunam     |   2.00   |         2.00         |
|    bulps     |     karim     |   2.00   |         2.00         |
|    chair     |     satish    |   0.00   |         0.00         |
|    cooler    |     manish    |  20.00   |        20.00         |
|     fan      |     kushal    |   2.00   |         2.00         |
|     fan      |     sonam     |   2.00   |         2.00         |
|     sopa     |    sushant    |  16.00   |        16.00         |
|     sopa     |      sima     |  16.00   |        16.00         |
|     sopa     |      sima     |  16.00   |        16.00         |
|    table     |    mahendra   |   6.00   |         6.00         |
+--------------+---------------+----------+----------------------+
Truncated to displaylimit of 10.

In [102]:
products['product_max_discount'] = (
    products
    .groupby('product_name')['discount']
    .transform('max')
)
products[
    ['product_name', 'customer_name', 'discount', 'product_max_discount']
]

   product_name customer_name  discount  product_max_discount
0         table         kiran         6                     6
1           fan         sonam         2                     2
2          sopa          sima        16                    16
3          sopa          sima        16                    16
4         chair        satish         0                     0
5         bulps         karim         2                     2
6           fan        kushal         2                     2
7         bulps         sunam         2                     2
8         watch          jaya         2                     2
9        cooler        manish        20                    20
10        table      mahendra         6                     6
11         sopa       sushant        16                    16

<pre>Har order ke saath us state me sabse kam (minimum) product price bhi dikhani hai.
customer_name	order_state	product_price	state_min_price</pre>

In [107]:
%%sql 
SELECT customer_name, order_state, product_price, MIN(product_price)
OVER (PARTITION BY order_state) AS state_min_price
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+-------------+---------------+-----------------+
| customer_name | order_state | product_price | state_min_price |
+---------------+-------------+---------------+-----------------+
|     sunam     |      BR     |     20.00     |      20.00      |
|     kushal    |      CN     |    2000.00    |     2000.00     |
|     satish    |      GJ     |    1200.00    |     1200.00     |
|     karim     |      JK     |     20.00     |      20.00      |
|    sushant    |      KR     |    4300.00    |     2200.00     |
|    mahendra   |      KR     |    2200.00    |     2200.00     |
|     kiran     |      MH     |    2200.00    |     2200.00     |
|      sima     |      RJ     |    4300.00    |     2000.00     |
|     sonam     |      RJ     |    2000.00    |     2000.00     |
|     manish    |      RJ     |    3200.00    |     2000.00     |
+---------------+-------------+---------------+-----------------+
Truncated to displaylimit of 10.

In [106]:
products['state_min_price'] = (
    products
    .groupby('order_state')['product_price']
    .transform('min')
)
products[
    ['customer_name', 'order_state', 'product_price', 'state_min_price']
]

   customer_name order_state  product_price  state_min_price
0          kiran          MH           2200             2200
1          sonam          RJ           2000             2000
2           sima          RJ           4300             2000
3           sima          RJ           4300             2000
4         satish          GJ           1200             1200
5          karim          JK             20               20
6         kushal          CN           2000             2000
7          sunam          BR             20               20
8           jaya          UP            220              220
9         manish          RJ           3200             2000
10      mahendra          KR           2200             2200
11       sushant          KR           4300             2200

<pre>Har order ke saath us state ka:

1. Total Revenue
2. Maximum Product Price
customer_name   order_state   net_amount   product_price   state_total_revenue   state_max_price</pre>

In [120]:
%%sql 
SELECT customer_name, order_state, net_amount, product_price, SUM(net_amount)
OVER(PARTITION BY order_state) AS state_total_revenue,
MAX(product_price)
OVER(PARTITION BY order_state) AS state_max_price
FROM products;

Running query in 'postgresql://chaiaurcode:***@localhost:5432/sqlnotes'

12 rows affected.

+---------------+-------------+------------+---------------+---------------------+-----------------+
| customer_name | order_state | net_amount | product_price | state_total_revenue | state_max_price |
+---------------+-------------+------------+---------------+---------------------+-----------------+
|     sunam     |      BR     |   196.00   |     20.00     |        196.00       |      20.00      |
|     kushal    |      CN     |  3920.00   |    2000.00    |       3920.00       |     2000.00     |
|     satish    |      GJ     |  12000.00  |    1200.00    |       12000.00      |     1200.00     |
|     karim     |      JK     |  1960.00   |     20.00     |       1960.00       |      20.00      |
|    sushant    |      KR     |  7224.00   |    4300.00    |       15496.00      |     4300.00     |
|    mahendra   |      KR     |  8272.00   |    2200.00    |       15496.00      |     4300.00     |
|     kiran     |      MH     |  6204.00   |    2200.00    |       6204.00       |     2200.00     |
|      sima     |      RJ     |  3612.00   |    4300.00    |       16264.00      |     4300.00     |
|     sonam     |      RJ     |  3920.00   |    2000.00    |       16264.00      |     4300.00     |
|     manish    |      RJ     |  5120.00   |    3200.00    |       16264.00      |     4300.00     |
+---------------+-------------+------------+---------------+---------------------+-----------------+
Truncated to displaylimit of 10.

In [116]:
products['state_total_revenue'] = (
    products
    .groupby('order_state')['net_amount']
    .transform('sum')
)
products['state_max_price'] = (
    products
    .groupby('order_state')['product_price']
    .transform('max')
)
products[
    ['customer_name', 'order_state', 'net_amount', 'product_price', 'state_total_revenue', 'state_max_price']
]

,customer_name,order_state,net_amount,product_price,state_total_revenue,state_max_price
0,kiran,MH,6204.0,2200,6204.0,2200
1,sonam,RJ,3920.0,2000,16264.0,4300
2,sima,RJ,3612.0,4300,16264.0,4300
3,sima,RJ,3612.0,4300,16264.0,4300
4,satish,GJ,12000.0,1200,12000.0,1200
5,karim,JK,1960.0,20,1960.0,20
6,kushal,CN,3920.0,2000,3920.0,2000
7,sunam,BR,196.0,20,196.0,20
8,jaya,UP,215.6,220,215.6,220
9,manish,RJ,5120.0,3200,16264.0,4300
10,mahendra,KR,8272.0,2200,15496.0,4300
11,sushant,KR,7224.0,4300,15496.0,4300

In [55]:
products.head(1)

,product_id,product_name,order_date,customer_name,order_state,product_price,product_quantity,discount,gross_amount,net_amount
0,1,table,2020-05-09,kiran,MH,2200,3,6,6600,6204.0