In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [3]:
import pandas as pd

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [10]:
%%sql 
CREATE TABLE products01(
    product_id SERIAL PRIMARY KEY,
    customer_name VARCHAR(50) NOT NULL,
    order_state VARCHAR(5) NOT NULL,
    product_name VARCHAR(50) NOT NULL,

    product_quantity INT NOT NULL
        CHECK(product_quantity > 0),

    product_price DECIMAL(8, 1) NOT NULL
        CHECK(product_price > 0),

    discount INT DEFAULT 0
        CHECK(discount >= 0 AND DISCOUNT <= 50),

    net_amount DECIMAL(10, 1)
        GENERATED ALWAYS AS (
            product_price * product_quantity
        ) STORED,
    
    order_date DATE NOT NULL

);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

++
||
++
++

In [11]:
%%sql 
INSERT INTO products01
(customer_name, order_state, product_name, product_quantity, product_price, discount, order_date)
VALUES
('Amit', 'MH', 'Laptop', 2, 50000, 10, '2026-01-05'),
('Amit', 'MH', 'Mouse', 2, 2000, 15, '2026-01-12'),
('Ravi', 'MH', 'Laptop', 1, 50000, 5, '2026-01-08'),
('Ravi', 'GJ', 'Keyboard', 3, 3000, 10, '2026-01-15'),
('Neha', 'GJ', 'Monitor', 2, 12000, 20, '2026-01-10'),
('Neha', 'GJ', 'Mouse', 2, 2000, 20, '2026-01-18'),
('Kiran', 'RJ', 'Laptop', 1, 50000, 5, '2026-01-09'),
('Kiran', 'RJ', 'Keyboard', 1, 3000, 5, '2026-01-20'),
('Sita', 'RJ', 'Monitor', 2, 12000, 15, '2026-01-14'),
('Sita', 'RJ', 'Mouse', 2, 2000, 15, '2026-01-22');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

++
||
++
++

In [5]:
data = {
    'product_id' : [i for i in range(1, 11)],
    'customer_name' : ['Amit', 'Amit', 'Ravi', 'Ravi', 'Neha', 'Neha', 'Kiran', 'Kiran', 'Sita', 'Sita'],
    'order_state' : ['MH', 'MH', 'MH', 'GJ', 'GJ', 'GJ', 'RJ', 'RJ', 'RJ', 'RJ'],
    'product_name' : ['Laptop', 'Mouse', 'Laptop', 'Keyboard', 'Monitor', 'Mouse', 'Laptop', 'Keyboard', 'Monitor', 'Mouse'],
    'product_quantity' : [2, 2, 1, 3, 2, 2, 1, 1, 2, 2],
    'product_price' : [50000, 2000, 50000, 3000, 12000, 2000, 50000, 3000, 12000, 2000],
    'discount' : [10, 15, 5, 10, 20, 20, 5, 5, 15, 15],
    'order_date' : ['2026-01-05', '2026-01-12', '2026-01-08', '2026-01-15', '2026-01-10', '2026-01-18', '2026-01-09', '2026-01-20', '2026-01-14', '2026-01-22'],
        
}

In [6]:
products = pd.DataFrame(data)

In [7]:
products['net_amount'] = (
    products['product_price'] * products['product_quantity']
)

In [8]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

In [9]:
%%sql 
SELECT * FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
| product_id | customer_name | order_state | product_name | product_quantity | product_price | discount | net_amount | order_date |
+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
|     1      |      Amit     |      MH     |    Laptop    |        2         |    50000.0    |    10    |  100000.0  | 2026-01-05 |
|     2      |      Amit     |      MH     |    Mouse     |        2         |     2000.0    |    15    |   4000.0   | 2026-01-12 |
|     3      |      Ravi     |      MH     |    Laptop    |        1         |    50000.0    |    5     |  50000.0   | 2026-01-08 |
|     4      |      Ravi     |      GJ     |   Keyboard   |        3         |     3000.0    |    10    |   9000.0   | 2026-01-15 |
|     5      |      Neha     |      GJ     |   Monitor    |        2         |    12000.0    |    20    |  24000.0   | 2026-01-10 |
|     6      |      Neha     |      GJ     |    Mouse     |        2         |     2000.0    |    20    |   4000.0   | 2026-01-18 |
|     7      |     Kiran     |      RJ     |    Laptop    |        1         |    50000.0    |    5     |  50000.0   | 2026-01-09 |
|     8      |     Kiran     |      RJ     |   Keyboard   |        1         |     3000.0    |    5     |   3000.0   | 2026-01-20 |
|     9      |      Sita     |      RJ     |   Monitor    |        2         |    12000.0    |    15    |  24000.0   | 2026-01-14 |
|     10     |      Sita     |      RJ     |    Mouse     |        2         |     2000.0    |    15    |   4000.0   | 2026-01-22 |
+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
Truncated to displaylimit of 10.

In [10]:
products

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,order_date,net_amount
0,1,Amit,MH,Laptop,2,50000,10,2026-01-05,100000
1,2,Amit,MH,Mouse,2,2000,15,2026-01-12,4000
2,3,Ravi,MH,Laptop,1,50000,5,2026-01-08,50000
3,4,Ravi,GJ,Keyboard,3,3000,10,2026-01-15,9000
4,5,Neha,GJ,Monitor,2,12000,20,2026-01-10,24000
5,6,Neha,GJ,Mouse,2,2000,20,2026-01-18,4000
6,7,Kiran,RJ,Laptop,1,50000,5,2026-01-09,50000
7,8,Kiran,RJ,Keyboard,1,3000,5,2026-01-20,3000
8,9,Sita,RJ,Monitor,2,12000,15,2026-01-14,24000
9,10,Sita,RJ,Mouse,2,2000,15,2026-01-22,4000

In [11]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        10 non-null     int64
 1   customer_name     10 non-null     str
 2   order_state       10 non-null     str
 3   product_name      10 non-null     str
 4   product_quantity  10 non-null     int64
 5   product_price     10 non-null     int64
 6   discount          10 non-null     int64
 7   order_date        10 non-null     datetime64[us]
 8   net_amount        10 non-null     int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 852.0 bytes

**RANK()**

<pre>Har state ke products ko product price ke hisaab se sabse mehange se sabse saste tak rank do.
Agar do products ki price same ho, to dono ko same rank milna chahiye.</pre>

In [15]:
%%sql
SELECT order_state, product_name, product_price,
RANK()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC
) AS product_price_rank_bottom_top
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+--------------+---------------+-------------------------------+
| order_state | product_name | product_price | product_price_rank_bottom_top |
+-------------+--------------+---------------+-------------------------------+
|      GJ     |   Monitor    |    12000.0    |               1               |
|      GJ     |   Keyboard   |     3000.0    |               2               |
|      GJ     |    Mouse     |     2000.0    |               3               |
|      MH     |    Laptop    |    50000.0    |               1               |
|      MH     |    Laptop    |    50000.0    |               1               |
|      MH     |    Mouse     |     2000.0    |               3               |
|      RJ     |    Laptop    |    50000.0    |               1               |
|      RJ     |   Monitor    |    12000.0    |               2               |
|      RJ     |   Keyboard   |     3000.0    |               3               |
|      RJ     |    Mouse     |     2000.0    |               4               |
+-------------+--------------+---------------+-------------------------------+
Truncated to displaylimit of 10.

In [49]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending=[True, False]
    )
)
products['product_price_rank_bottom_top'] = (
    products
    .groupby('order_state')['product_price']
    .rank(
        ascending=False,
        method = 'min'
    )
)
products[
    ['order_state', 'product_name', 'product_price', 'product_price_rank_bottom_top']
]

  order_state product_name  product_price  product_price_rank_bottom_top
4          GJ      Monitor          12000                            1.0
3          GJ     Keyboard           3000                            2.0
5          GJ        Mouse           2000                            3.0
0          MH       Laptop          50000                            1.0
2          MH       Laptop          50000                            1.0
1          MH        Mouse           2000                            3.0
6          RJ       Laptop          50000                            1.0
8          RJ      Monitor          12000                            2.0
7          RJ     Keyboard           3000                            3.0
9          RJ        Mouse           2000                            4.0

**Method = 'average' (default)**
<pre>Value	Rank
50000	1.5
50000	1.5
2000	3.0</pre>
<pre>2 times 50000, so (1+2)/2 = 1.5 rank</pre>

**method='min' ⭐ (SQL RANK())**
<pre>Value	Rank
50000	1
50000	1
2000	3</pre>

**method='dense' ⭐ (SQL DENSE_RANK())**
<pre>Value	Rank
50000	1
50000	1
2000	2</pre>

**method='first'** \
like **cumcount** of pandas and **row_number** of sql
<pre>Value	Rank
50000	1
50000	2
2000	3</pre>

<pre>Har customer ke products ko sabse zyada discount se sabse kam discount tak rank do.
Agar do orders ka discount same ho, to dono ko same rank milna chahiye aur agla rank skip hona chahiye.

SQL Output Columns
customer_name
product_name
discount
discount_rank_high_to_low</pre>

In [53]:
%%sql 
SELECT customer_name, product_name, discount, 
RANK()
OVER(
    PARTITION BY customer_name
    ORDER BY discount DESC
) AS discount_rank_high_to_low
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+--------------+----------+---------------------------+
| customer_name | product_name | discount | discount_rank_high_to_low |
+---------------+--------------+----------+---------------------------+
|      Amit     |    Mouse     |    15    |             1             |
|      Amit     |    Laptop    |    10    |             2             |
|     Kiran     |   Keyboard   |    5     |             1             |
|     Kiran     |    Laptop    |    5     |             1             |
|      Neha     |    Mouse     |    20    |             1             |
|      Neha     |   Monitor    |    20    |             1             |
|      Ravi     |   Keyboard   |    10    |             1             |
|      Ravi     |    Laptop    |    5     |             2             |
|      Sita     |   Monitor    |    15    |             1             |
|      Sita     |    Mouse     |    15    |             1             |
+---------------+--------------+----------+---------------------------+
Truncated to displaylimit of 10.

In [55]:
products = (
    products
    .sort_values(
        ['customer_name', 'discount'],
        ascending=[True, False]
    )
)
products['discount_rank_high_to_low'] = (
    products
    .groupby('customer_name')['discount']
    .rank(
        ascending=False,
        method='min'
    )
)
products[
    ['customer_name', 'product_name', 'discount', 'discount_rank_high_to_low']
]

  customer_name product_name  discount  discount_rank_high_to_low
1          Amit        Mouse        15                        1.0
0          Amit       Laptop        10                        2.0
6         Kiran       Laptop         5                        1.0
7         Kiran     Keyboard         5                        1.0
4          Neha      Monitor        20                        1.0
5          Neha        Mouse        20                        1.0
3          Ravi     Keyboard        10                        1.0
2          Ravi       Laptop         5                        2.0
8          Sita      Monitor        15                        1.0
9          Sita        Mouse        15                        1.0

<pre>Har state ke products ko sabse mehange se sabse saste tak RANK() do.
Agar do products ki price same ho, to same rank mile.
Phir sirf Top 2 ranks wale products hi dikhao.</pre>

In [66]:
%%sql
WITH ranked_order AS (
    SELECT order_state, product_name, product_price,
    RANK()
    OVER(
        PARTITION BY order_state
        ORDER BY product_price DESC
    ) AS product_price_high_to_low
    FROM products01
)
SELECT order_state, product_name, product_price, product_price_high_to_low
FROM ranked_order
WHERE product_price_high_to_low <= 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+-------------+--------------+---------------+---------------------------+
| order_state | product_name | product_price | product_price_high_to_low |
+-------------+--------------+---------------+---------------------------+
|      GJ     |   Monitor    |    12000.0    |             1             |
|      GJ     |   Keyboard   |     3000.0    |             2             |
|      MH     |    Laptop    |    50000.0    |             1             |
|      MH     |    Laptop    |    50000.0    |             1             |
|      RJ     |    Laptop    |    50000.0    |             1             |
|      RJ     |   Monitor    |    12000.0    |             2             |
+-------------+--------------+---------------+---------------------------+

In [78]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending=[True, False]
    )
)
products['product_price_high_to_low'] = (
    products
    .groupby('order_state')['product_price']
    .rank(
        ascending=False,
        method='min'
    )
)
products[
    ['order_state', 'product_name', 'product_price', 'product_price_high_to_low']
][products['product_price_high_to_low'] <= 2]

  order_state product_name  product_price  product_price_high_to_low
4          GJ      Monitor          12000                        1.0
3          GJ     Keyboard           3000                        2.0
0          MH       Laptop          50000                        1.0
2          MH       Laptop          50000                        1.0
6          RJ       Laptop          50000                        1.0
8          RJ      Monitor          12000                        2.0

<pre>Har product ke liye customers ko unke kharide hue **net_amount** ke hisaab se rank do.
Sabse zyada **net_amount** wale customer ko Rank 1 mile. 
Agar do customers ka **net_amount** same ho, to dono ko same rank mile aur agla rank skip ho.

product_name
customer_name
net_amount
customer_rank_by_net_amount</pre>

In [80]:
%%sql 
SELECT product_name, customer_name, net_amount,
RANK()
OVER(
    PARTITION BY product_name
    ORDER BY net_amount DESC
) AS customer_rank_by_net_amount
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+---------------+------------+-----------------------------+
| product_name | customer_name | net_amount | customer_rank_by_net_amount |
+--------------+---------------+------------+-----------------------------+
|   Keyboard   |      Ravi     |   9000.0   |              1              |
|   Keyboard   |     Kiran     |   3000.0   |              2              |
|    Laptop    |      Amit     |  100000.0  |              1              |
|    Laptop    |      Ravi     |  50000.0   |              2              |
|    Laptop    |     Kiran     |  50000.0   |              2              |
|   Monitor    |      Sita     |  24000.0   |              1              |
|   Monitor    |      Neha     |  24000.0   |              1              |
|    Mouse     |      Sita     |   4000.0   |              1              |
|    Mouse     |      Amit     |   4000.0   |              1              |
|    Mouse     |      Neha     |   4000.0   |              1              |
+--------------+---------------+------------+-----------------------------+
Truncated to displaylimit of 10.

In [81]:
products = (
    products
    .sort_values(
        ['product_name', 'net_amount'],
        ascending=[True, False]
    )
)
products['customer_rank_by_net_amount'] = (
    products
    .groupby('product_name')['net_amount']
    .rank(
        ascending=False,
        method='min'
    )
)
products[
    ['product_name', 'customer_name', 'net_amount', 'customer_rank_by_net_amount']
]

  product_name customer_name  net_amount  customer_rank_by_net_amount
3     Keyboard          Ravi        9000                          1.0
7     Keyboard         Kiran        3000                          2.0
0       Laptop          Amit      100000                          1.0
2       Laptop          Ravi       50000                          2.0
6       Laptop         Kiran       50000                          2.0
4      Monitor          Neha       24000                          1.0
8      Monitor          Sita       24000                          1.0
5        Mouse          Neha        4000                          1.0
1        Mouse          Amit        4000                          1.0
9        Mouse          Sita        4000                          1.0

<pre>Har state ke products ko pehle product_price (high to low)
ke hisaab se rank do. Agar product_price same ho,
to jiski order_date purani ho (oldest), usko upar rank milni
chahiye.

order_state
product_name
product_price
order_date
price_rank_if_same_old_order_first</pre>

In [14]:
%%sql 
SELECT order_state, product_name, product_price, order_date,
RANK()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC, order_date ASC
) AS price_rank_if_same_old_order_first
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+--------------+---------------+------------+------------------------------------+
| order_state | product_name | product_price | order_date | price_rank_if_same_old_order_first |
+-------------+--------------+---------------+------------+------------------------------------+
|      GJ     |   Monitor    |    12000.0    | 2026-01-10 |                 1                  |
|      GJ     |   Keyboard   |     3000.0    | 2026-01-15 |                 2                  |
|      GJ     |    Mouse     |     2000.0    | 2026-01-18 |                 3                  |
|      MH     |    Laptop    |    50000.0    | 2026-01-05 |                 1                  |
|      MH     |    Laptop    |    50000.0    | 2026-01-08 |                 2                  |
|      MH     |    Mouse     |     2000.0    | 2026-01-12 |                 3                  |
|      RJ     |    Laptop    |    50000.0    | 2026-01-09 |                 1                  |
|      RJ     |   Monitor    |    12000.0    | 2026-01-14 |                 2                  |
|      RJ     |   Keyboard   |     3000.0    | 2026-01-20 |                 3                  |
|      RJ     |    Mouse     |     2000.0    | 2026-01-22 |                 4                  |
+-------------+--------------+---------------+------------+------------------------------------+
Truncated to displaylimit of 10.

In [19]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price', 'order_date'],
        ascending=[True, False, True]
    )
)
products['price_rank_if_same_old_order_first'] = (
    products
    .groupby('order_state')[['product_price','order_date']]
    .rank(
        ascending=[False, True],
        method='min'
    )
)
products[
    ['order_state', 'product_name', 'product_price', 'order_date', 'price_rank_if_same_old_order_first']
]

ValueError: Columns must be same length as key

<pre>🎯 Question 1 (DENSE_RANK)

Har state ke products ko sabse mehange se sabse saste tak DENSE_RANK() do. 
Agar do products ki price same ho, to dono ko same rank mile.
Agli alag price ko skip kiye bina agla rank milna chahiye.

order_state
product_name
product_price
product_price_dense_rank_high_to_low</pre>

In [26]:
%%sql 
SELECT order_state, product_name, product_price,
DENSE_RANK()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC
) AS product_price_dense_rank_high_to_low
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+--------------+---------------+--------------------------------------+
| order_state | product_name | product_price | product_price_dense_rank_high_to_low |
+-------------+--------------+---------------+--------------------------------------+
|      GJ     |   Monitor    |    12000.0    |                  1                   |
|      GJ     |   Keyboard   |     3000.0    |                  2                   |
|      GJ     |    Mouse     |     2000.0    |                  3                   |
|      MH     |    Laptop    |    50000.0    |                  1                   |
|      MH     |    Laptop    |    50000.0    |                  1                   |
|      MH     |    Mouse     |     2000.0    |                  2                   |
|      RJ     |    Laptop    |    50000.0    |                  1                   |
|      RJ     |   Monitor    |    12000.0    |                  2                   |
|      RJ     |   Keyboard   |     3000.0    |                  3                   |
|      RJ     |    Mouse     |     2000.0    |                  4                   |
+-------------+--------------+---------------+--------------------------------------+
Truncated to displaylimit of 10.

In [28]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending=[True, False]
    )
)
products['product_price_dense_rank_high_to_low'] = (
    products
    .groupby('order_state')['product_price']
    .rank(
        ascending=False,
        method='dense'
    )
)
products[
    ['order_state', 'product_name', 'product_price', 'product_price_dense_rank_high_to_low']
]

,order_state,product_name,product_price,product_price_dense_rank_high_to_low
4,GJ,Monitor,12000,1.0
3,GJ,Keyboard,3000,2.0
5,GJ,Mouse,2000,3.0
0,MH,Laptop,50000,1.0
2,MH,Laptop,50000,1.0
1,MH,Mouse,2000,2.0
6,RJ,Laptop,50000,1.0
8,RJ,Monitor,12000,2.0
7,RJ,Keyboard,3000,3.0
9,RJ,Mouse,2000,4.0

<pre>Har state ke products ko DENSE_RANK() do aur sirf Top 2 dense ranks wale products dikhao.

order_state
product_name
product_price
product_price_dense_rank_high_to_low</pre>

In [30]:
%%sql 
WITH ranked_order AS (
    SELECT order_state, product_name, product_price,
    DENSE_RANK()
    OVER(
        PARTITION BY order_state
        ORDER BY product_price DESC
    ) AS product_price_dense_rank_high_to_low
    FROM products01
)
SELECT order_state, product_name, product_price, product_price_dense_rank_high_to_low
FROM ranked_order
WHERE product_price_dense_rank_high_to_low <= 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-------------+--------------+---------------+--------------------------------------+
| order_state | product_name | product_price | product_price_dense_rank_high_to_low |
+-------------+--------------+---------------+--------------------------------------+
|      GJ     |   Monitor    |    12000.0    |                  1                   |
|      GJ     |   Keyboard   |     3000.0    |                  2                   |
|      MH     |    Laptop    |    50000.0    |                  1                   |
|      MH     |    Laptop    |    50000.0    |                  1                   |
|      MH     |    Mouse     |     2000.0    |                  2                   |
|      RJ     |    Laptop    |    50000.0    |                  1                   |
|      RJ     |   Monitor    |    12000.0    |                  2                   |
+-------------+--------------+---------------+--------------------------------------+

In [36]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending=[True, False]
    )
)
products['product_price_dense_rank_high_to_low'] = (
    products
    .groupby('order_state')['product_price']
    .rank(
        ascending=False,
        method='dense'
    )
)
products[
    ['order_state', 'product_name', 'product_price', 'product_price_dense_rank_high_to_low']
][products['product_price_dense_rank_high_to_low'] <= 2]

,order_state,product_name,product_price,product_price_dense_rank_high_to_low
4,GJ,Monitor,12000,1.0
3,GJ,Keyboard,3000,2.0
0,MH,Laptop,50000,1.0
2,MH,Laptop,50000,1.0
1,MH,Mouse,2000,2.0
6,RJ,Laptop,50000,1.0
8,RJ,Monitor,12000,2.0

<pre>Har customer ke products ko sabse zyada **net_amount** se sabse kam **net_amount** tak DENSE_RANK() do.
Agar do products ka *net_amount* same ho, to dono ko same rank mile aur agla rank skip na ho.

customer_name
product_name
net_amount
net_amount_dense_rank_high_to_low</pre>

In [37]:
%%sql 
SELECT customer_name, product_name, net_amount,
DENSE_RANK()
OVER(
    PARTITION BY customer_name
    ORDER BY net_amount DESC
) AS net_amount_dense_rank_high_to_low
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+--------------+------------+-----------------------------------+
| customer_name | product_name | net_amount | net_amount_dense_rank_high_to_low |
+---------------+--------------+------------+-----------------------------------+
|      Amit     |    Laptop    |  100000.0  |                 1                 |
|      Amit     |    Mouse     |   4000.0   |                 2                 |
|     Kiran     |    Laptop    |  50000.0   |                 1                 |
|     Kiran     |   Keyboard   |   3000.0   |                 2                 |
|      Neha     |   Monitor    |  24000.0   |                 1                 |
|      Neha     |    Mouse     |   4000.0   |                 2                 |
|      Ravi     |    Laptop    |  50000.0   |                 1                 |
|      Ravi     |   Keyboard   |   9000.0   |                 2                 |
|      Sita     |   Monitor    |  24000.0   |                 1                 |
|      Sita     |    Mouse     |   4000.0   |                 2                 |
+---------------+--------------+------------+-----------------------------------+
Truncated to displaylimit of 10.

In [44]:
products = (
    products
    .sort_values(
        ['customer_name', 'net_amount'],
        ascending=[True, False]
    )
)
products['net_amount_dense_rank_high_to_low'] = (
    products
    .groupby('customer_name')['net_amount']
    .rank(
        ascending=False,
        method='dense'
    )
)
products[
    ['customer_name', 'product_name', 'net_amount', 'net_amount_dense_rank_high_to_low']
]

  customer_name product_name  net_amount  net_amount_dense_rank_high_to_low
0          Amit       Laptop      100000                                1.0
1          Amit        Mouse        4000                                2.0
6         Kiran       Laptop       50000                                1.0
7         Kiran     Keyboard        3000                                2.0
4          Neha      Monitor       24000                                1.0
5          Neha        Mouse        4000                                2.0
2          Ravi       Laptop       50000                                1.0
3          Ravi     Keyboard        9000                                2.0
8          Sita      Monitor       24000                                1.0
9          Sita        Mouse        4000                                2.0

<pre>Har product ke customers ko discount ke hisaab se DENSE_RANK() do. 
Agar discount same ho, to same rank mile aur agla rank skip na ho. 
Phir sirf Top 2 dense ranks wale customers dikhao.

product_name
customer_name
discount
discount_dense_rank_high_to_low</pre>

In [52]:
products = (
    products
    .sort_values(
        ['product_name', 'discount'],
        ascending=[True, False]
    )
)
products['discount_dense_rank_high_to_low'] = (
    products
    .groupby('product_name')['discount']
    .rank(
        ascending=False,
        method='dense'
    )
)
products[
    ['product_name', 'customer_name', 'discount', 'discount_dense_rank_high_to_low']
][products['discount_dense_rank_high_to_low'] <= 2]

  product_name customer_name  discount  discount_dense_rank_high_to_low
3     Keyboard          Ravi        10                              1.0
7     Keyboard         Kiran         5                              2.0
0       Laptop          Amit        10                              1.0
2       Laptop          Ravi         5                              2.0
6       Laptop         Kiran         5                              2.0
4      Monitor          Neha        20                              1.0
8      Monitor          Sita        15                              2.0
5        Mouse          Neha        20                              1.0
1        Mouse          Amit        15                              2.0
9        Mouse          Sita        15                              2.0

In [50]:
%%sql 
WITH ranked_order AS (
    SELECT product_name, customer_name, discount,
    DENSE_RANK()
    OVER(
        PARTITION  BY product_name
        ORDER BY discount DESC
    ) AS discount_dense_rank_high_to_low
    FROM products01
)
SELECT product_name, customer_name, discount, discount_dense_rank_high_to_low
FROM ranked_order
WHERE discount_dense_rank_high_to_low <= 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+---------------+----------+---------------------------------+
| product_name | customer_name | discount | discount_dense_rank_high_to_low |
+--------------+---------------+----------+---------------------------------+
|   Keyboard   |      Ravi     |    10    |                1                |
|   Keyboard   |     Kiran     |    5     |                2                |
|    Laptop    |      Amit     |    10    |                1                |
|    Laptop    |      Ravi     |    5     |                2                |
|    Laptop    |     Kiran     |    5     |                2                |
|   Monitor    |      Neha     |    20    |                1                |
|   Monitor    |      Sita     |    15    |                2                |
|    Mouse     |      Neha     |    20    |                1                |
|    Mouse     |      Amit     |    15    |                2                |
|    Mouse     |      Sita     |    15    |                2                |
+--------------+---------------+----------+---------------------------------+
Truncated to displaylimit of 10.

In [56]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,order_date,net_amount
0,1,Amit,MH,Laptop,2,50000,10,2026-01-05,100000

In [54]:
products.drop('discount_dense_rank_high_to_low', axis = 1, inplace=True)

In [55]:
products.sort_values('product_id', ascending=True, inplace=True)