In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
products = pd.read_sql(
    'SELECT * FROM products01;',
    con = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
)

In [6]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **condition and window**

<pre>Har **order_state** ke andar **net_amount** DESC ke hisaab se Rank nikalo.

Uske baad:

Rank = 1 → "Winner"
Rank = 2 → "Runner Up"
Baaki sab → "Participant"</pre>

In [9]:
%%sql
WITH products_rank AS ( 
    SELECT order_state, net_amount, 
    DENSE_RANK()
    OVER(
        PARTITION BY order_state
        ORDER BY net_amount DESC
    ) AS net_amount_rank
    FROM products01
)
SELECT order_state, net_amount, net_amount_rank, 
    CASE
        WHEN net_amount_rank = 1 THEN 'Winner'
        WHEN net_amount_rank = 2 THEN 'Runner Up'
        ELSE 'Participant'
    END AS net_amount_ranking
FROM products_rank;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+-----------------+--------------------+
| order_state | net_amount | net_amount_rank | net_amount_ranking |
+-------------+------------+-----------------+--------------------+
|      GJ     |  24000.0   |        1        |       Winner       |
|      GJ     |   9000.0   |        2        |     Runner Up      |
|      GJ     |   4000.0   |        3        |    Participant     |
|      MH     |  100000.0  |        1        |       Winner       |
|      MH     |  50000.0   |        2        |     Runner Up      |
|      MH     |   4000.0   |        3        |    Participant     |
|      RJ     |  50000.0   |        1        |       Winner       |
|      RJ     |  24000.0   |        2        |     Runner Up      |
|      RJ     |   4000.0   |        3        |    Participant     |
|      RJ     |   3000.0   |        4        |    Participant     |
+-------------+------------+-----------------+--------------------+
Truncated to displaylimit of 10.

In [12]:
products = (
    products
    .sort_values(
        ['order_state', 'net_amount'],
        ascending=[True, False]
    )
)
products['net_amount_rank'] = (
    products
    .groupby('order_state')['net_amount']
    .rank(
        ascending=False,
        method='dense'
    )
)
label = {
    1 : 'Winner', 
    2 : 'Runner Up'
}
products['net_amount_ranking'] = (
    products['net_amount_rank']
    .map(label)
    .fillna('Participant')
)
products[
    ['order_state', 'net_amount', 'net_amount_rank', 'net_amount_ranking']
]

  order_state  net_amount  net_amount_rank net_amount_ranking
4          GJ     24000.0              1.0             Winner
3          GJ      9000.0              2.0          Runner Up
5          GJ      4000.0              3.0        Participant
0          MH    100000.0              1.0             Winner
2          MH     50000.0              2.0          Runner Up
1          MH      4000.0              3.0        Participant
6          RJ     50000.0              1.0             Winner
8          RJ     24000.0              2.0          Runner Up
9          RJ      4000.0              3.0        Participant
7          RJ      3000.0              4.0        Participant

In [7]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05