In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT *  FROM products01;'
products = pd.read_sql(query, con=engine)

In [6]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **Cumulative Operation**

| Net Amount | Running Total / Cumulative Sum |
| ---------: | -----------------------------: |
|        100 |                            100 |
|        200 |                            300 |
|        150 |                            450 |
|         50 |                            500 |

<pre>Puri table me **order_date** ASC ke according **net_amount** ka Running Total dikhao.</pre>

In [27]:
%%sql 
SELECT order_date, net_amount,
SUM(net_amount)
OVER(
    ORDER BY order_date ASC
) AS cumsum_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+-------------------+
| order_date | net_amount | cumsum_net_amount |
+------------+------------+-------------------+
| 2026-01-05 |  100000.0  |      100000.0     |
| 2026-01-08 |  50000.0   |      150000.0     |
| 2026-01-09 |  50000.0   |      200000.0     |
| 2026-01-10 |  24000.0   |      224000.0     |
| 2026-01-12 |   4000.0   |      228000.0     |
| 2026-01-14 |  24000.0   |      252000.0     |
| 2026-01-15 |   9000.0   |      261000.0     |
| 2026-01-18 |   4000.0   |      265000.0     |
| 2026-01-20 |   3000.0   |      268000.0     |
| 2026-01-22 |   4000.0   |      272000.0     |
+------------+------------+-------------------+
Truncated to displaylimit of 10.

In [30]:
products = (
    products
    .sort_values('order_date')
)
products['cumsum_net_amount'] = (
    products['net_amount']
    .cumsum()
)
products[
    ['order_date', 'net_amount', 'cumsum_net_amount']
]

  order_date  net_amount  cumsum_net_amount
0 2026-01-05    100000.0           100000.0
2 2026-01-08     50000.0           150000.0
6 2026-01-09     50000.0           200000.0
4 2026-01-10     24000.0           224000.0
1 2026-01-12      4000.0           228000.0
8 2026-01-14     24000.0           252000.0
3 2026-01-15      9000.0           261000.0
5 2026-01-18      4000.0           265000.0
7 2026-01-20      3000.0           268000.0
9 2026-01-22      4000.0           272000.0

<pre>**order_date** ke according **net_amount** ka Running Total (Cumulative Sum) dikhao.</pre>

In [15]:
%%sql 
SELECT order_state, net_amount,
SUM(net_amount)
OVER(
    PARTITION BY order_state
    ORDER BY net_amount DESC # cumulative sum 😂
) AS running_sum_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+------------------------+
| order_state | net_amount | running_sum_net_amount |
+-------------+------------+------------------------+
|      GJ     |  24000.0   |        24000.0         |
|      GJ     |   9000.0   |        33000.0         |
|      GJ     |   4000.0   |        37000.0         |
|      MH     |  100000.0  |        100000.0        |
|      MH     |  50000.0   |        150000.0        |
|      MH     |   4000.0   |        154000.0        |
|      RJ     |  50000.0   |        50000.0         |
|      RJ     |  24000.0   |        74000.0         |
|      RJ     |   4000.0   |        78000.0         |
|      RJ     |   3000.0   |        81000.0         |
+-------------+------------+------------------------+
Truncated to displaylimit of 10.

In [16]:
products = (
    products
    .sort_values(
        ['order_state', 'net_amount'],
        ascending=[True, False]
    )
)
products['running_sum_net_amount'] = (
    products
    .groupby('order_state')['net_amount']
    .cumsum()
)
products[
    ['order_state', 'net_amount', 'running_sum_net_amount']
]

  order_state  net_amount  running_sum_net_amount
4          GJ     24000.0                 24000.0
3          GJ      9000.0                 33000.0
5          GJ      4000.0                 37000.0
0          MH    100000.0                100000.0
2          MH     50000.0                150000.0
1          MH      4000.0                154000.0
6          RJ     50000.0                 50000.0
8          RJ     24000.0                 74000.0
9          RJ      4000.0                 78000.0
7          RJ      3000.0                 81000.0

### **Running Percentage (Cumulative Percentage)**

$$
Running\ Percentage = \frac{Running\ Total}{Grand\ Total} \times 100
$$

| Order Date | Net Amount | Running Total | Running % |
| ---------- | ---------: | ------------: | --------: |
| 1 Jan      |        100 |           100 |       10% |
| 2 Jan      |        200 |           300 |       30% |
| 3 Jan      |        300 |           600 |       60% |
| 4 Jan      |        400 |          1000 |      100% |

<pre>**order_date ASC** ke according **net_amount** ka Running Percentage dikhao.</pre>

In [38]:
%%sql 
WITH running_total AS (
    SELECT order_date, net_amount,
    SUM(net_amount)
    OVER(
        ORDER BY order_date ASC
    ) AS net_amount_run_sum
    FROM products01
)

SELECT order_date, net_amount, net_amount_run_sum,
(net_amount_run_sum * 100) / SUM(net_amount)
OVER() AS net_amount_run_percent
FROM running_total;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+--------------------+------------------------+
| order_date | net_amount | net_amount_run_sum | net_amount_run_percent |
+------------+------------+--------------------+------------------------+
| 2026-01-05 |  100000.0  |      100000.0      |  36.7647058823529412   |
| 2026-01-08 |  50000.0   |      150000.0      |  55.1470588235294118   |
| 2026-01-09 |  50000.0   |      200000.0      |  73.5294117647058824   |
| 2026-01-10 |  24000.0   |      224000.0      |  82.3529411764705882   |
| 2026-01-12 |   4000.0   |      228000.0      |  83.8235294117647059   |
| 2026-01-14 |  24000.0   |      252000.0      |  92.6470588235294118   |
| 2026-01-15 |   9000.0   |      261000.0      |  95.9558823529411765   |
| 2026-01-18 |   4000.0   |      265000.0      |  97.4264705882352941   |
| 2026-01-20 |   3000.0   |      268000.0      |  98.5294117647058824   |
| 2026-01-22 |   4000.0   |      272000.0      |  100.0000000000000000  |
+------------+------------+--------------------+------------------------+
Truncated to displaylimit of 10.

In [37]:
products = (
    products
    .sort_values('order_date')
)
products['net_amount_cumsum'] = (
    products['net_amount']
    .cumsum()
)
products['net_amount_run_percent'] =  (
    (products['net_amount_cumsum'] / products['net_amount'].sum()) * 100
)
products[ 
    ['order_date', 'net_amount', 'net_amount_cumsum', 'net_amount_run_percent']
]

  order_date  net_amount  net_amount_cumsum  net_amount_run_percent
0 2026-01-05    100000.0           100000.0               36.764706
2 2026-01-08     50000.0           150000.0               55.147059
6 2026-01-09     50000.0           200000.0               73.529412
4 2026-01-10     24000.0           224000.0               82.352941
1 2026-01-12      4000.0           228000.0               83.823529
8 2026-01-14     24000.0           252000.0               92.647059
3 2026-01-15      9000.0           261000.0               95.955882
5 2026-01-18      4000.0           265000.0               97.426471
7 2026-01-20      3000.0           268000.0               98.529412
9 2026-01-22      4000.0           272000.0              100.000000

<pre>Har **order_state** ke andar **order_date ASC** ke according **net_amount** ka Running Percentage nikalo.<pre>

In [59]:
%%sql
WITH cumsum AS (
    SELECT order_state, order_date, net_amount,
    SUM(net_amount)
    OVER(
        PARTITION BY order_state
        ORDER BY order_date ASC
    ) AS cumsum_net_amount,
    SUM(net_amount)
    OVER(
        PARTITION BY order_state
    ) AS state_sum_net_amount
    FROM products01
)
SELECT order_state, order_date, net_amount, state_sum_net_amount, cumsum_net_amount,
(cumsum_net_amount * 100) / state_sum_net_amount AS cum_net_amount_percent
FROM cumsum;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+------------+----------------------+-------------------+------------------------+
| order_state | order_date | net_amount | state_sum_net_amount | cumsum_net_amount | cum_net_amount_percent |
+-------------+------------+------------+----------------------+-------------------+------------------------+
|      GJ     | 2026-01-10 |  24000.0   |       37000.0        |      24000.0      |  64.8648648648648649   |
|      GJ     | 2026-01-15 |   9000.0   |       37000.0        |      33000.0      |  89.1891891891891892   |
|      GJ     | 2026-01-18 |   4000.0   |       37000.0        |      37000.0      |  100.0000000000000000  |
|      MH     | 2026-01-05 |  100000.0  |       154000.0       |      100000.0     |  64.9350649350649351   |
|      MH     | 2026-01-08 |  50000.0   |       154000.0       |      150000.0     |  97.4025974025974026   |
|      MH     | 2026-01-12 |   4000.0   |       154000.0       |      154000.0     |  100.0000000000000000  |
|      RJ     | 2026-01-09 |  50000.0   |       81000.0        |      50000.0      |  61.7283950617283951   |
|      RJ     | 2026-01-14 |  24000.0   |       81000.0        |      74000.0      |  91.3580246913580247   |
|      RJ     | 2026-01-20 |   3000.0   |       81000.0        |      77000.0      |  95.0617283950617284   |
|      RJ     | 2026-01-22 |   4000.0   |       81000.0        |      81000.0      |  100.0000000000000000  |
+-------------+------------+------------+----------------------+-------------------+------------------------+
Truncated to displaylimit of 10.

In [63]:
products = (
    products
    .sort_values(
        ['order_state', 'order_date'],
        ascending=[True, True]
    )
)
g = products.groupby('order_state')
products['state_sum_net_amount'] = (
    g['net_amount']
    .transform('sum')
)
products['cumsum_net_amount'] = (
    g['net_amount']
    .cumsum()
)
products['cum_net_amount_percent'] = (
    (products['cumsum_net_amount'] / products['state_sum_net_amount']) * 100
)
products[
    ['order_state', 'order_date', 'net_amount', 'state_sum_net_amount',  'cumsum_net_amount', 'cum_net_amount_percent']
]

,order_state,order_date,net_amount,state_sum_net_amount,cumsum_net_amount,cum_net_amount_percent
4,GJ,2026-01-10,24000.0,37000.0,24000.0,64.864865
3,GJ,2026-01-15,9000.0,37000.0,33000.0,89.189189
5,GJ,2026-01-18,4000.0,37000.0,37000.0,100.000000
0,MH,2026-01-05,100000.0,154000.0,100000.0,64.935065
2,MH,2026-01-08,50000.0,154000.0,150000.0,97.402597
1,MH,2026-01-12,4000.0,154000.0,154000.0,100.000000
6,RJ,2026-01-09,50000.0,81000.0,50000.0,61.728395
8,RJ,2026-01-14,24000.0,81000.0,74000.0,91.358025
7,RJ,2026-01-20,3000.0,81000.0,77000.0,95.061728
9,RJ,2026-01-22,4000.0,81000.0,81000.0,100.000000