In [1]:
print('welcome')

welcome

In [3]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01;'
products = pd.read_sql(query, con = engine)

### **LAST_VALUE()**
**Returns the last value in the current window.**

<PRE>Window Function =

1. PARTITION BY
2. ORDER BY
3. WINDOW FRAME</PRE>

<pre>Table ke **order_date** ke adhar par last **net_amount** dikhao.</pre>

In [36]:
%%sql 
SELECT order_date, net_amount,
LAST_VALUE(net_amount)
OVER(
    ORDER BY order_date ASC
    ROWS BETWEEN UNBOUNDED PRECEDING
    AND UNBOUNDED FOLLOWING
) AS last_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+-----------------+
| order_date | net_amount | last_net_amount |
+------------+------------+-----------------+
| 2026-01-05 |  100000.0  |      4000.0     |
| 2026-01-08 |  50000.0   |      4000.0     |
| 2026-01-09 |  50000.0   |      4000.0     |
| 2026-01-10 |  24000.0   |      4000.0     |
| 2026-01-12 |   4000.0   |      4000.0     |
| 2026-01-14 |  24000.0   |      4000.0     |
| 2026-01-15 |   9000.0   |      4000.0     |
| 2026-01-18 |   4000.0   |      4000.0     |
| 2026-01-20 |   3000.0   |      4000.0     |
| 2026-01-22 |   4000.0   |      4000.0     |
+------------+------------+-----------------+
Truncated to displaylimit of 10.

In [44]:
products = (
    products
    .sort_values('order_date')
)
products['last_net_amount'] = (
    products['net_amount']
    .iloc[-1]
)
products[
    ['order_date', 'net_amount', 'last_net_amount']
]

   order_date  net_amount  last_net_amount
0  2026-01-05    100000.0           4000.0
2  2026-01-08     50000.0           4000.0
6  2026-01-09     50000.0           4000.0
4  2026-01-10     24000.0           4000.0
1  2026-01-12      4000.0           4000.0
8  2026-01-14     24000.0           4000.0
3  2026-01-15      9000.0           4000.0
5  2026-01-18      4000.0           4000.0
7  2026-01-20      3000.0           4000.0
9  2026-01-22      4000.0           4000.0

<pre>Har **customer_name** ke andar **order_date** ke adhar par last **net_amount** dikhao.</pre>

In [53]:
%%sql 
SELECT customer_name, order_date, net_amount,
LAST_VALUE(net_amount)
OVER(
    PARTITION BY customer_name
    ORDER BY order_date ASC
    ROWS BETWEEN UNBOUNDED PRECEDING
    AND UNBOUNDED FOLLOWING
) AS last_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+------------+------------+-----------------+
| customer_name | order_date | net_amount | last_net_amount |
+---------------+------------+------------+-----------------+
|      Amit     | 2026-01-05 |  100000.0  |      4000.0     |
|      Amit     | 2026-01-12 |   4000.0   |      4000.0     |
|     Kiran     | 2026-01-09 |  50000.0   |      3000.0     |
|     Kiran     | 2026-01-20 |   3000.0   |      3000.0     |
|      Neha     | 2026-01-10 |  24000.0   |      4000.0     |
|      Neha     | 2026-01-18 |   4000.0   |      4000.0     |
|      Ravi     | 2026-01-08 |  50000.0   |      9000.0     |
|      Ravi     | 2026-01-15 |   9000.0   |      9000.0     |
|      Sita     | 2026-01-14 |  24000.0   |      4000.0     |
|      Sita     | 2026-01-22 |   4000.0   |      4000.0     |
+---------------+------------+------------+-----------------+
Truncated to displaylimit of 10.

In [55]:
products = (
    products
    .sort_values(
        ['customer_name', 'order_date'],
        ascending=[True, True]
    )
)
products['last_net_amount'] = (
    products
    .groupby('customer_name')['net_amount']
    .transform('last')
)
products[ 
    ['customer_name', 'order_date', 'net_amount', 'last_net_amount']
]

  customer_name  order_date  net_amount  last_net_amount
0          Amit  2026-01-05    100000.0           4000.0
1          Amit  2026-01-12      4000.0           4000.0
6         Kiran  2026-01-09     50000.0           3000.0
7         Kiran  2026-01-20      3000.0           3000.0
4          Neha  2026-01-10     24000.0           4000.0
5          Neha  2026-01-18      4000.0           4000.0
2          Ravi  2026-01-08     50000.0           9000.0
3          Ravi  2026-01-15      9000.0           9000.0
8          Sita  2026-01-14     24000.0           4000.0
9          Sita  2026-01-22      4000.0           4000.0

In [11]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05