In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [3]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01'
products = pd.read_sql(query, con=engine)

In [9]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **LEAD()**
**Returns the next row's value.**

<pre>Table ka **order_date** ke adhar par next **net_amount** dikhao.</pre>

In [12]:
%%sql 
SELECT order_date, net_amount,
LEAD(net_amount)
OVER(
    ORDER BY order_date ASC
) AS next_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+-----------------+
| order_date | net_amount | next_net_amount |
+------------+------------+-----------------+
| 2026-01-05 |  100000.0  |     50000.0     |
| 2026-01-08 |  50000.0   |     50000.0     |
| 2026-01-09 |  50000.0   |     24000.0     |
| 2026-01-10 |  24000.0   |      4000.0     |
| 2026-01-12 |   4000.0   |     24000.0     |
| 2026-01-14 |  24000.0   |      9000.0     |
| 2026-01-15 |   9000.0   |      4000.0     |
| 2026-01-18 |   4000.0   |      3000.0     |
| 2026-01-20 |   3000.0   |      4000.0     |
| 2026-01-22 |   4000.0   |       None      |
+------------+------------+-----------------+
Truncated to displaylimit of 10.

In [13]:
products = (
    products
    .sort_values('order_date')
)
products['next_net_amount'] = (
    products['net_amount']
    .shift(-1)
)
products[ 
    ['order_date', 'net_amount', 'next_net_amount']
]

  order_date  net_amount  next_net_amount
0 2026-01-05    100000.0          50000.0
2 2026-01-08     50000.0          50000.0
6 2026-01-09     50000.0          24000.0
4 2026-01-10     24000.0           4000.0
1 2026-01-12      4000.0          24000.0
8 2026-01-14     24000.0           9000.0
3 2026-01-15      9000.0           4000.0
5 2026-01-18      4000.0           3000.0
7 2026-01-20      3000.0           4000.0
9 2026-01-22      4000.0              NaN

<pre>Har **customer_name** ke andar **order_date** ke adhar par next **discount** dikhao.</pre>

In [16]:
products = (
    products
    .sort_values(
        ['customer_name', 'order_date'],
        ascending=[True, True]
    )
)
products['next_discount'] = (
    products
    .groupby('customer_name')['discount']
    .shift(-1)
)
products[ 
    ['customer_name', 'order_date', 'discount', 'next_discount']
]

  customer_name order_date  discount  next_discount
0          Amit 2026-01-05        10           15.0
1          Amit 2026-01-12        15            NaN
6         Kiran 2026-01-09         5            5.0
7         Kiran 2026-01-20         5            NaN
4          Neha 2026-01-10        20           20.0
5          Neha 2026-01-18        20            NaN
2          Ravi 2026-01-08         5           10.0
3          Ravi 2026-01-15        10            NaN
8          Sita 2026-01-14        15           15.0
9          Sita 2026-01-22        15            NaN

In [15]:
%%sql 
SELECT customer_name, order_date, discount,
LEAD(discount)
OVER(
    PARTITION BY customer_name
    ORDER BY order_date ASC
) AS next_discount FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+------------+----------+---------------+
| customer_name | order_date | discount | next_discount |
+---------------+------------+----------+---------------+
|      Amit     | 2026-01-05 |    10    |       15      |
|      Amit     | 2026-01-12 |    15    |      None     |
|     Kiran     | 2026-01-09 |    5     |       5       |
|     Kiran     | 2026-01-20 |    5     |      None     |
|      Neha     | 2026-01-10 |    20    |       20      |
|      Neha     | 2026-01-18 |    20    |      None     |
|      Ravi     | 2026-01-08 |    5     |       10      |
|      Ravi     | 2026-01-15 |    10    |      None     |
|      Sita     | 2026-01-14 |    15    |       15      |
|      Sita     | 2026-01-22 |    15    |      None     |
+---------------+------------+----------+---------------+
Truncated to displaylimit of 10.

In [10]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        10 non-null     int64
 1   customer_name     10 non-null     str
 2   order_state       10 non-null     str
 3   product_name      10 non-null     str
 4   product_quantity  10 non-null     int64
 5   product_price     10 non-null     float64
 6   discount          10 non-null     int64
 7   net_amount        10 non-null     float64
 8   order_date        10 non-null     datetime64[s]
dtypes: datetime64[s](1), float64(2), int64(3), str(3)
memory usage: 852.0 bytes