In [1]:
print('hello')

hello

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:{password}@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01;'
products = pd.read_sql(query, con=engine)

In [21]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **Moving Operations**

| Day | Sales |
| --: | ----: |
|   1 |    10 |
|   2 |    20 |
|   3 |    30 |
|   4 |    40 |
|   5 |    50 |

| Day | Last 3 Values | Moving Avg |
| --: | ------------- | ---------: |
|   1 | 10            |         10 |
|   2 | 10,20         |         15 |
|   3 | 10,20,30      |         20 |
|   4 | 20,30,40      |         30 |
|   5 | 30,40,50      |         40 |

**Average**

<pre>**order_date ASC** ke according current row aur uske pichhli 2 rows 
ka **net_amount** ka **Moving Average** (3-row Rolling Average) dikhao.</pre>

In [10]:
%%sql 
SELECT order_date, net_amount, 
AVG(net_amount)
OVER(
    ORDER BY order_date ASC
    ROWS BETWEEN 2 PRECEDING
    AND CURRENT ROW # 2 PRECEDING + CURRENT ROW = 3
) AS moving_avg_3
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+------------------------+
| order_date | net_amount |      moving_avg_3      |
+------------+------------+------------------------+
| 2026-01-05 |  100000.0  |  100000.000000000000   |
| 2026-01-08 |  50000.0   |   75000.000000000000   |
| 2026-01-09 |  50000.0   |   66666.666666666667   |
| 2026-01-10 |  24000.0   |   41333.333333333333   |
| 2026-01-12 |   4000.0   |   26000.000000000000   |
| 2026-01-14 |  24000.0   |   17333.333333333333   |
| 2026-01-15 |   9000.0   | 12333.3333333333333333 |
| 2026-01-18 |   4000.0   | 12333.3333333333333333 |
| 2026-01-20 |   3000.0   | 5333.3333333333333333  |
| 2026-01-22 |   4000.0   | 3666.6666666666666667  |
+------------+------------+------------------------+
Truncated to displaylimit of 10.

In [22]:
products = (
    products
    .sort_values('order_date')
)
products['moving_avg_3'] = (
    products['net_amount']
    .rolling(window=3, min_periods=1) # min_periods means ki starting ke 1,2 rows should not be NaN
    .mean()
)
products[
    ['order_date', 'net_amount', 'moving_avg_3']
]

  order_date  net_amount   moving_avg_3
0 2026-01-05    100000.0  100000.000000
2 2026-01-08     50000.0   75000.000000
6 2026-01-09     50000.0   66666.666667
4 2026-01-10     24000.0   41333.333333
1 2026-01-12      4000.0   26000.000000
8 2026-01-14     24000.0   17333.333333
3 2026-01-15      9000.0   12333.333333
5 2026-01-18      4000.0   12333.333333
7 2026-01-20      3000.0    5333.333333
9 2026-01-22      4000.0    3666.666667

<pre>**order_date ASC** ke according current row aur uski pichhli 4 rows
ka **discount** ka 5-row Moving Average nikalo.</pre>

In [13]:
%%sql 
SELECT order_date, discount,
AVG(discount)
OVER(
    ORDER BY order_date ASC
    ROWS BETWEEN 4 PRECEDING
    AND CURRENT ROW
) AS moving_avg_5
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+----------+---------------------+
| order_date | discount |     moving_avg_5    |
+------------+----------+---------------------+
| 2026-01-05 |    10    | 10.0000000000000000 |
| 2026-01-08 |    5     |  7.5000000000000000 |
| 2026-01-09 |    5     |  6.6666666666666667 |
| 2026-01-10 |    20    | 10.0000000000000000 |
| 2026-01-12 |    15    | 11.0000000000000000 |
| 2026-01-14 |    15    | 12.0000000000000000 |
| 2026-01-15 |    10    | 13.0000000000000000 |
| 2026-01-18 |    20    | 16.0000000000000000 |
| 2026-01-20 |    5     | 13.0000000000000000 |
| 2026-01-22 |    15    | 13.0000000000000000 |
+------------+----------+---------------------+
Truncated to displaylimit of 10.

In [23]:
products = (
    products
    .sort_values('order_date')
)
products['moving_avg_5'] = (
    products['discount']
    .rolling(window=5, min_periods=1)
    .mean()
)
products[
    ['order_date', 'discount', 'moving_avg_5']
]

  order_date  discount  moving_avg_5
0 2026-01-05        10     10.000000
2 2026-01-08         5      7.500000
6 2026-01-09         5      6.666667
4 2026-01-10        20     10.000000
1 2026-01-12        15     11.000000
8 2026-01-14        15     12.000000
3 2026-01-15        10     13.000000
5 2026-01-18        20     16.000000
7 2026-01-20         5     13.000000
9 2026-01-22        15     13.000000

<pre>Har **customer_name** ke andar **order_date ASC** ke according current row aur 
uski pichhli 2 rows ka **net_amount** ka 3-row Moving Average nikalo.</pre>

In [17]:
%%sql 
SELECT customer_name, order_date, net_amount,
AVG(net_amount)
OVER(
    PARTITION BY customer_name
    ORDER BY order_date ASC
    ROWS BETWEEN 2 PRECEDING
    AND CURRENT ROW
) AS moving_avg_3
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+------------+------------+------------------------+
| customer_name | order_date | net_amount |      moving_avg_3      |
+---------------+------------+------------+------------------------+
|      Amit     | 2026-01-05 |  100000.0  |  100000.000000000000   |
|      Amit     | 2026-01-12 |   4000.0   |   52000.000000000000   |
|     Kiran     | 2026-01-09 |  50000.0   |   50000.000000000000   |
|     Kiran     | 2026-01-20 |   3000.0   |   26500.000000000000   |
|      Neha     | 2026-01-10 |  24000.0   |   24000.000000000000   |
|      Neha     | 2026-01-18 |   4000.0   | 14000.0000000000000000 |
|      Ravi     | 2026-01-08 |  50000.0   |   50000.000000000000   |
|      Ravi     | 2026-01-15 |   9000.0   |   29500.000000000000   |
|      Sita     | 2026-01-14 |  24000.0   |   24000.000000000000   |
|      Sita     | 2026-01-22 |   4000.0   | 14000.0000000000000000 |
+---------------+------------+------------+------------------------+
Truncated to displaylimit of 10.

In [ ]:
products = (
    products
    .sort_values('order_date')
)
products['moving_avg_3'] = (
    products
    .groupby('customer_name')['net_amount']
    .rolling(window=3, min_periods = 1)
    .mean()
)
products[ 
    ['customer_name', 'order_date', 'net_amount', 'moving_avg_3']
]

TypeError: incompatible index of inserted column with frame index

In [ ]:
products = (
    products
    .sort_values('order_date')
)
products['moving_avg_3'] = (
    products
    .groupby('customer_name')['net_amount']
    .rolling(window=3, min_periods = 1)
    .mean()
    .reset_index(level=0, drop=True) # to skip error
)
products[ 
    ['customer_name', 'order_date', 'net_amount', 'moving_avg_3']
]

  customer_name order_date  net_amount  moving_avg_3
0          Amit 2026-01-05    100000.0      100000.0
2          Ravi 2026-01-08     50000.0       50000.0
6         Kiran 2026-01-09     50000.0       50000.0
4          Neha 2026-01-10     24000.0       24000.0
1          Amit 2026-01-12      4000.0       52000.0
8          Sita 2026-01-14     24000.0       24000.0
3          Ravi 2026-01-15      9000.0       29500.0
5          Neha 2026-01-18      4000.0       14000.0
7         Kiran 2026-01-20      3000.0       26500.0
9          Sita 2026-01-22      4000.0       14000.0

In [31]:
products = (
    products
    .sort_values('order_date')
)
products['moving_avg_3'] = (
    products
    .groupby('customer_name')['net_amount']
    .transform(
        lambda x : x.rolling(window=3, min_periods=1)
        .mean()
    )
)
products[
    ['customer_name', 'order_date', 'net_amount', 'moving_avg_3']
]

  customer_name order_date  net_amount  moving_avg_3
0          Amit 2026-01-05    100000.0      100000.0
2          Ravi 2026-01-08     50000.0       50000.0
6         Kiran 2026-01-09     50000.0       50000.0
4          Neha 2026-01-10     24000.0       24000.0
1          Amit 2026-01-12      4000.0       52000.0
8          Sita 2026-01-14     24000.0       24000.0
3          Ravi 2026-01-15      9000.0       29500.0
5          Neha 2026-01-18      4000.0       14000.0
7         Kiran 2026-01-20      3000.0       26500.0
9          Sita 2026-01-22      4000.0       14000.0

<pre>Har **order_state** ke andar **order_date ASC** ke according current 
row aur uski pichhli 1 row ka **discount** ka 2-row Moving Average nikalo</pre>

In [37]:
products = (
    products
    .sort_values(
        ['order_state','order_date'],
        ascending=[False,True]
    )
)
products['moving_avg_3'] = (
    products
    .groupby('order_state')['discount']
    .transform(
        lambda x : x.rolling(window = 2, min_periods = 1)
        .mean()
    )
)
products[
    ['order_state', 'order_date', 'discount', 'moving_avg_3']
]

  order_state order_date  discount  moving_avg_3
6          RJ 2026-01-09         5           5.0
8          RJ 2026-01-14        15          10.0
7          RJ 2026-01-20         5          10.0
9          RJ 2026-01-22        15          10.0
0          MH 2026-01-05        10          10.0
2          MH 2026-01-08         5           7.5
1          MH 2026-01-12        15          10.0
4          GJ 2026-01-10        20          20.0
3          GJ 2026-01-15        10          15.0
5          GJ 2026-01-18        20          15.0

In [38]:
%%sql 
SELECT order_state, order_date, discount,
AVG(discount)
OVER(
    PARTITION BY order_state
    ORDER BY order_date ASC
    ROWS BETWEEN 1 PRECEDING
    AND CURRENT ROW
) AS moving_avg_3
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+----------+---------------------+
| order_state | order_date | discount |     moving_avg_3    |
+-------------+------------+----------+---------------------+
|      GJ     | 2026-01-10 |    20    | 20.0000000000000000 |
|      GJ     | 2026-01-15 |    10    | 15.0000000000000000 |
|      GJ     | 2026-01-18 |    20    | 15.0000000000000000 |
|      MH     | 2026-01-05 |    10    | 10.0000000000000000 |
|      MH     | 2026-01-08 |    5     |  7.5000000000000000 |
|      MH     | 2026-01-12 |    15    | 10.0000000000000000 |
|      RJ     | 2026-01-09 |    5     |  5.0000000000000000 |
|      RJ     | 2026-01-14 |    15    | 10.0000000000000000 |
|      RJ     | 2026-01-20 |    5     | 10.0000000000000000 |
|      RJ     | 2026-01-22 |    15    | 10.0000000000000000 |
+-------------+------------+----------+---------------------+
Truncated to displaylimit of 10.

In [6]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05