In [1]:
print('welcome')

welcome

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01;'
products = pd.read_sql(query, con=engine)

In [7]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **NTH_VALUE()**
**Returns the nth value from the current window.**

<PRE>Table ke **order_date** ke adhar par second **net_amount** dikhao.</PRE>

In [14]:
%%sql 
SELECT order_date, net_amount,
NTH_VALUE(net_amount, 2)
OVER(
    ORDER BY order_date ASC
) AS second_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+-------------------+
| order_date | net_amount | second_net_amount |
+------------+------------+-------------------+
| 2026-01-05 |  100000.0  |        None       |
| 2026-01-08 |  50000.0   |      50000.0      |
| 2026-01-09 |  50000.0   |      50000.0      |
| 2026-01-10 |  24000.0   |      50000.0      |
| 2026-01-12 |   4000.0   |      50000.0      |
| 2026-01-14 |  24000.0   |      50000.0      |
| 2026-01-15 |   9000.0   |      50000.0      |
| 2026-01-18 |   4000.0   |      50000.0      |
| 2026-01-20 |   3000.0   |      50000.0      |
| 2026-01-22 |   4000.0   |      50000.0      |
+------------+------------+-------------------+
Truncated to displaylimit of 10.

In [15]:
%%sql 
SELECT order_date, net_amount,
NTH_VALUE(net_amount, 2)
OVER(
    ORDER BY order_date ASC
    ROWS BETWEEN UNBOUNDED PRECEDING
    AND UNBOUNDED FOLLOWING
) AS second_net_amount 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+------------+-------------------+
| order_date | net_amount | second_net_amount |
+------------+------------+-------------------+
| 2026-01-05 |  100000.0  |      50000.0      |
| 2026-01-08 |  50000.0   |      50000.0      |
| 2026-01-09 |  50000.0   |      50000.0      |
| 2026-01-10 |  24000.0   |      50000.0      |
| 2026-01-12 |   4000.0   |      50000.0      |
| 2026-01-14 |  24000.0   |      50000.0      |
| 2026-01-15 |   9000.0   |      50000.0      |
| 2026-01-18 |   4000.0   |      50000.0      |
| 2026-01-20 |   3000.0   |      50000.0      |
| 2026-01-22 |   4000.0   |      50000.0      |
+------------+------------+-------------------+
Truncated to displaylimit of 10.

In [9]:
products = (
    products
    .sort_values('order_date')
)
products['second_net_amount'] = (
    products['net_amount']
    .iloc[1]
)
products[
    ['order_date', 'net_amount', 'second_net_amount']
]

  order_date  net_amount  second_net_amount
0 2026-01-05    100000.0            50000.0
2 2026-01-08     50000.0            50000.0
6 2026-01-09     50000.0            50000.0
4 2026-01-10     24000.0            50000.0
1 2026-01-12      4000.0            50000.0
8 2026-01-14     24000.0            50000.0
3 2026-01-15      9000.0            50000.0
5 2026-01-18      4000.0            50000.0
7 2026-01-20      3000.0            50000.0
9 2026-01-22      4000.0            50000.0

<pre>Har **order_state** ke andar **order_date** ke adhar par second **net_amount** dikhao.</pre>

In [12]:
%%sql 
SELECT order_state, order_date, net_amount,
NTH_VALUE(net_amount, 2)
OVER(
    PARTITION BY order_state
    ORDER BY order_date ASC
    ROWS BETWEEN UNBOUNDED PRECEDING
    AND UNBOUNDED FOLLOWING
) AS second_net_amount
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+------------+-------------------+
| order_state | order_date | net_amount | second_net_amount |
+-------------+------------+------------+-------------------+
|      GJ     | 2026-01-10 |  24000.0   |       9000.0      |
|      GJ     | 2026-01-15 |   9000.0   |       9000.0      |
|      GJ     | 2026-01-18 |   4000.0   |       9000.0      |
|      MH     | 2026-01-05 |  100000.0  |      50000.0      |
|      MH     | 2026-01-08 |  50000.0   |      50000.0      |
|      MH     | 2026-01-12 |   4000.0   |      50000.0      |
|      RJ     | 2026-01-09 |  50000.0   |      24000.0      |
|      RJ     | 2026-01-14 |  24000.0   |      24000.0      |
|      RJ     | 2026-01-20 |   3000.0   |      24000.0      |
|      RJ     | 2026-01-22 |   4000.0   |      24000.0      |
+-------------+------------+------------+-------------------+
Truncated to displaylimit of 10.

In [25]:
products = (
    products
    .sort_values(
        ['order_state','order_date'],
        ascending=[True,True]
    )
)
products['second_net_amount'] = (
    products
    .groupby('order_state')['net_amount']
    .transform(lambda x : x.iloc[1])
)
products[
    ['order_state', 'order_date', 'net_amount', 'second_net_amount']
]

  order_state order_date  net_amount  second_net_amount
4          GJ 2026-01-10     24000.0             9000.0
3          GJ 2026-01-15      9000.0             9000.0
5          GJ 2026-01-18      4000.0             9000.0
0          MH 2026-01-05    100000.0            50000.0
2          MH 2026-01-08     50000.0            50000.0
1          MH 2026-01-12      4000.0            50000.0
6          RJ 2026-01-09     50000.0            24000.0
8          RJ 2026-01-14     24000.0            24000.0
7          RJ 2026-01-20      3000.0            24000.0
9          RJ 2026-01-22      4000.0            24000.0

In [10]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05

In [9]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        10 non-null     int64
 1   customer_name     10 non-null     str
 2   order_state       10 non-null     str
 3   product_name      10 non-null     str
 4   product_quantity  10 non-null     int64
 5   product_price     10 non-null     float64
 6   discount          10 non-null     int64
 7   net_amount        10 non-null     float64
 8   order_date        10 non-null     datetime64[s]
dtypes: datetime64[s](1), float64(2), int64(3), str(3)
memory usage: 852.0 bytes