In [49]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [51]:
import pandas as pd

In [4]:
from sqlalchemy import create_engine

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [53]:
%%sql 
SELECT * FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
| product_id | customer_name | order_state | product_name | product_quantity | product_price | discount | net_amount | order_date |
+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
|     1      |      Amit     |      MH     |    Laptop    |        2         |    50000.0    |    10    |  100000.0  | 2026-01-05 |
|     2      |      Amit     |      MH     |    Mouse     |        2         |     2000.0    |    15    |   4000.0   | 2026-01-12 |
|     3      |      Ravi     |      MH     |    Laptop    |        1         |    50000.0    |    5     |  50000.0   | 2026-01-08 |
|     4      |      Ravi     |      GJ     |   Keyboard   |        3         |     3000.0    |    10    |   9000.0   | 2026-01-15 |
|     5      |      Neha     |      GJ     |   Monitor    |        2         |    12000.0    |    20    |  24000.0   | 2026-01-10 |
|     6      |      Neha     |      GJ     |    Mouse     |        2         |     2000.0    |    20    |   4000.0   | 2026-01-18 |
|     7      |     Kiran     |      RJ     |    Laptop    |        1         |    50000.0    |    5     |  50000.0   | 2026-01-09 |
|     8      |     Kiran     |      RJ     |   Keyboard   |        1         |     3000.0    |    5     |   3000.0   | 2026-01-20 |
|     9      |      Sita     |      RJ     |   Monitor    |        2         |    12000.0    |    15    |  24000.0   | 2026-01-14 |
|     10     |      Sita     |      RJ     |    Mouse     |        2         |     2000.0    |    15    |   4000.0   | 2026-01-22 |
+------------+---------------+-------------+--------------+------------------+---------------+----------+------------+------------+
Truncated to displaylimit of 10.

In [62]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01'
products = pd.read_sql(query, con=engine)

In [63]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

**NTILE() GROUPING**

<pre>Sabhi orders ko **net_amount** ke hisaab se (high to low) 4 groups me baanto. 
Group 1 me sabse bade **net_amount** wale orders hone chahiye aur Group 4 me sabse chhote.</pre>

In [8]:
products['net_amount_group'] = pd.qcut(
    products['net_amount'],
    q = 4,
    labels = [4,3,2,1]
)
products[
    ['customer_name', 'net_amount', 'net_amount_group']
].sort_values('net_amount', ascending = False)

  customer_name  net_amount net_amount_group
0          Amit    100000.0                1
2          Ravi     50000.0                1
6         Kiran     50000.0                1
8          Sita     24000.0                2
4          Neha     24000.0                2
3          Ravi      9000.0                3
1          Amit      4000.0                4
5          Neha      4000.0                4
9          Sita      4000.0                4
7         Kiran      3000.0                4

In [9]:
%%sql 
SELECT customer_name, net_amount,
NTILE(4)
OVER(
    ORDER BY net_amount DESC
) AS net_amount_group
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+------------+------------------+
| customer_name | net_amount | net_amount_group |
+---------------+------------+------------------+
|      Amit     |  100000.0  |        1         |
|     Kiran     |  50000.0   |        1         |
|      Ravi     |  50000.0   |        1         |
|      Sita     |  24000.0   |        2         |
|      Neha     |  24000.0   |        2         |
|      Ravi     |   9000.0   |        2         |
|      Sita     |   4000.0   |        3         |
|      Amit     |   4000.0   |        3         |
|      Neha     |   4000.0   |        4         |
|     Kiran     |   3000.0   |        4         |
+---------------+------------+------------------+
Truncated to displaylimit of 10.

<pre>**Har state ke orders ko** **net_amount** ke hisaab se (high to low) 3 groups me baanto.

order_state
customer_name
net_amount
net_amount_group</pre>

In [10]:
%%sql 
SELECT order_state, customer_name, net_amount,
NTILE(3)
OVER(
    PARTITION BY order_state
    ORDER BY net_amount DESC
) net_amount_group
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+---------------+------------+------------------+
| order_state | customer_name | net_amount | net_amount_group |
+-------------+---------------+------------+------------------+
|      GJ     |      Neha     |  24000.0   |        1         |
|      GJ     |      Ravi     |   9000.0   |        2         |
|      GJ     |      Neha     |   4000.0   |        3         |
|      MH     |      Amit     |  100000.0  |        1         |
|      MH     |      Ravi     |  50000.0   |        2         |
|      MH     |      Amit     |   4000.0   |        3         |
|      RJ     |     Kiran     |  50000.0   |        1         |
|      RJ     |      Sita     |  24000.0   |        1         |
|      RJ     |      Sita     |   4000.0   |        2         |
|      RJ     |     Kiran     |   3000.0   |        3         |
+-------------+---------------+------------+------------------+
Truncated to displaylimit of 10.

### Row-Based Grouping ✅ (SQL NTILE())

In [11]:
%%sql 
SELECT net_amount,
NTILE(4)
OVER(
    ORDER BY net_amount DESC
) AS row_group 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+-----------+
| net_amount | row_group |
+------------+-----------+
|  100000.0  |     1     |
|  50000.0   |     1     |
|  50000.0   |     1     |
|  24000.0   |     2     |
|  24000.0   |     2     |
|   9000.0   |     2     |
|   4000.0   |     3     |
|   4000.0   |     3     |
|   4000.0   |     4     |
|   3000.0   |     4     |
+------------+-----------+
Truncated to displaylimit of 10.

<pre>(row_number - 1) * groups // total_rows + 1</pre>

<pre>
 1 - 1 = 0 X 4 =  0 // 10 = 0 + 1= 1
 2 - 1 = 1 X 4 =  4 // 10 = 0 + 1= 1
 3 - 1 = 2 X 4 =  8 // 10 = 0 + 1= 1
 4 - 1 = 3 X 4 = 12 // 10 = 1 + 1= 2
 5 - 1 = 4 X 4 = 16 // 10 = 1 + 1= 2
 6 - 1 = 5 X 4 = 20 // 10 = 2 + 1= 3
 7 - 1 = 6 X 4 = 24 // 10 = 2 + 1= 3
 8 - 1 = 7 X 4 = 28 // 10 = 2 + 1= 3
 9 - 1 = 8 X 4 = 32 // 10 = 3 + 1= 4
10 - 1 = 9 X 4 = 36 // 10 = 3 + 1= 4
</pre>

In [12]:
products = (
    products
    .sort_values(
        'net_amount',
        ascending=False
    )
)
products['row_number'] = range(1, len(products) + 1)
products['row_group'] = (
    (products['row_number'] - 1) * 4 // len(products)
) + 1

In [13]:
products[['net_amount', 'row_number', 'row_group']]

   net_amount  row_number  row_group
0    100000.0           1          1
2     50000.0           2          1
6     50000.0           3          1
8     24000.0           4          2
4     24000.0           5          2
3      9000.0           6          3
1      4000.0           7          3
5      4000.0           8          3
9      4000.0           9          4
7      3000.0          10          4

<pre>Divide all orders into 2 groups based on product_price (highest to lowest).</pre>

In [ ]:
products = (
    products.sort_values('product_price', ascending=False)
)
products['row_number'] = range(1, len(products)+1)

products['group_of_2_desc'] = (
    (products['row_number'] - 1) * 2 // len(products)
) + 1
products[
    ['order_state', 'product_price', 'group_of_2_desc']
]

  order_state  product_price  group_of_2_desc
0          MH        50000.0                1
2          MH        50000.0                1
6          RJ        50000.0                1
8          RJ        12000.0                1
4          GJ        12000.0                1
3          GJ         3000.0                2
7          RJ         3000.0                2
1          MH         2000.0                2
5          GJ         2000.0                2
9          RJ         2000.0                2

In [15]:
%%sql 
SELECT order_state, product_price,
NTILE(2)
OVER(
    ORDER BY product_price DESC
) AS group_of_2_desc
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+---------------+-----------------+
| order_state | product_price | group_of_2_desc |
+-------------+---------------+-----------------+
|      MH     |    50000.0    |        1        |
|      RJ     |    50000.0    |        1        |
|      MH     |    50000.0    |        1        |
|      RJ     |    12000.0    |        1        |
|      GJ     |    12000.0    |        1        |
|      GJ     |     3000.0    |        2        |
|      RJ     |     3000.0    |        2        |
|      RJ     |     2000.0    |        2        |
|      MH     |     2000.0    |        2        |
|      GJ     |     2000.0    |        2        |
+-------------+---------------+-----------------+
Truncated to displaylimit of 10.

<pre>Har state ke orders ko **product_price** ke hisaab se (high to low) 2 groups me baanto.</pre>

In [62]:
products = (
    products.sort_values(
        ['order_state', 'product_price'],
        ascending=[True, False]
    )
)
g = products.groupby('order_state')

products['row_number'] = (
    g.cumcount()
    + 1
)
products['state_group_size'] = (
    g['product_price']
    .transform('count')
)
products['price_group_of_2_desc'] = (
    (products['row_number'] - 1) * 2 // products['state_group_size']
) + 1

products[
    ['order_state', 'product_price', 'row_number', 'state_group_size', 'price_group_of_2_desc']
]

,order_state,product_price,row_number,state_group_size,price_group_of_2_desc
4,GJ,12000.0,1,3,1
3,GJ,3000.0,2,3,1
5,GJ,2000.0,3,3,2
0,MH,50000.0,1,3,1
2,MH,50000.0,2,3,1
1,MH,2000.0,3,3,2
6,RJ,50000.0,1,4,1
8,RJ,12000.0,2,4,1
7,RJ,3000.0,3,4,2
9,RJ,2000.0,4,4,2

In [25]:
%%sql 
SELECT order_state, product_price,
NTILE(2)
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC
) AS price_group_of_2_desc 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+---------------+-----------------------+
| order_state | product_price | price_group_of_2_desc |
+-------------+---------------+-----------------------+
|      GJ     |    12000.0    |           1           |
|      GJ     |     3000.0    |           1           |
|      GJ     |     2000.0    |           2           |
|      MH     |    50000.0    |           1           |
|      MH     |    50000.0    |           1           |
|      MH     |     2000.0    |           2           |
|      RJ     |    50000.0    |           1           |
|      RJ     |    12000.0    |           1           |
|      RJ     |     3000.0    |           2           |
|      RJ     |     2000.0    |           2           |
+-------------+---------------+-----------------------+
Truncated to displaylimit of 10.

<pre>Har customer ke orders ko discount ke hisaab se (high to low) 2 groups me baanto.</pre>

In [65]:
# customer_name, discount, row_number, customer_group_size, discount_group_of_2_desc
products = (
    products
    .sort_values(
        ['customer_name', 'discount'],
        ascending=[True, False]
    )
)
products['row_number'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products['customer_group_size'] = (
    products.groupby('customer_name')['row_number']
    .transform('count')
)
products['discount_group_of_2_desc'] = (
    (products['row_number'] - 1) * 2 // products['customer_group_size']
) + 1
products[
    ['customer_name', 'discount', 'row_number', 'customer_group_size', 'discount_group_of_2_desc']
]

,customer_name,discount,row_number,customer_group_size,discount_group_of_2_desc
1,Amit,15,1,2,1
0,Amit,10,2,2,2
6,Kiran,5,1,2,1
7,Kiran,5,2,2,2
4,Neha,20,1,2,1
5,Neha,20,2,2,2
3,Ravi,10,1,2,1
2,Ravi,5,2,2,2
8,Sita,15,1,2,1
9,Sita,15,2,2,2

In [45]:
%%sql 
SELECT customer_name, discount,
NTILE(2)
OVER(
    PARTITION BY customer_name
    ORDER BY discount DESC
) AS discount_group_of_2_desc
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+---------------+----------+--------------------------+
| customer_name | discount | discount_group_of_2_desc |
+---------------+----------+--------------------------+
|      Amit     |    15    |            1             |
|      Amit     |    10    |            2             |
|     Kiran     |    5     |            1             |
|     Kiran     |    5     |            2             |
|      Neha     |    20    |            1             |
|      Neha     |    20    |            2             |
|      Ravi     |    10    |            1             |
|      Ravi     |    5     |            2             |
|      Sita     |    15    |            1             |
|      Sita     |    15    |            2             |
+---------------+----------+--------------------------+
Truncated to displaylimit of 10.

<pre>Har product ke orders ko **order_date** ke hisaab se (oldest to newest) 3 groups me baanto.</pre>

In [ ]:
# product_name, order_date, group_row_number, product_group_size, order_date_group_of_3_asc
products = (
    products
    .sort_values( 
        ['product_name', 'order_date'],
        ascending=[True, True]
    )
)
products['group_row_number'] = (
    products
    .groupby('product_name')
    .cumcount()
    + 1
)
products['product_group_size'] = (
    products
    .groupby('product_name')['product_name']
    .transform('count')
)
products['order_date_group_of_3_asc'] = (
    (products['group_row_number'] - 1) * 3 // products['product_group_size']
) + 1

products[
    ['product_name', 'order_date', 'group_row_number', 'product_group_size', 'order_date_group_of_3_asc']
]

,product_name,order_date,group_row_number,product_group_size,order_date_group_of_3_asc
3,Keyboard,2026-01-15,1,2,1
7,Keyboard,2026-01-20,2,2,2
0,Laptop,2026-01-05,1,3,1
2,Laptop,2026-01-08,2,3,2
6,Laptop,2026-01-09,3,3,3
4,Monitor,2026-01-10,1,2,1
8,Monitor,2026-01-14,2,2,2
1,Mouse,2026-01-12,1,3,1
5,Mouse,2026-01-18,2,3,2
9,Mouse,2026-01-22,3,3,3

In [66]:
%%sql 
SELECT product_name, order_date,
NTILE(3)
OVER(
    PARTITION BY product_name
    ORDER BY order_date ASC
) AS order_date_group_of_3_asc 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+------------+---------------------------+
| product_name | order_date | order_date_group_of_3_asc |
+--------------+------------+---------------------------+
|   Keyboard   | 2026-01-15 |             1             |
|   Keyboard   | 2026-01-20 |             2             |
|    Laptop    | 2026-01-05 |             1             |
|    Laptop    | 2026-01-08 |             2             |
|    Laptop    | 2026-01-09 |             3             |
|   Monitor    | 2026-01-10 |             1             |
|   Monitor    | 2026-01-14 |             2             |
|    Mouse     | 2026-01-12 |             1             |
|    Mouse     | 2026-01-18 |             2             |
|    Mouse     | 2026-01-22 |             3             |
+--------------+------------+---------------------------+
Truncated to displaylimit of 10.

<pre>Har **order_state** ke orders ko **net_amount** ke hisaab se (high to low) 3 groups me baanto.</pre>

In [72]:
# 'order_state', 'net_amount', 'group_row_number', 'state_group_size', 'net_amount_group_of_3_desc'
products = (
    products
    .sort_values(
        ['order_state', 'net_amount'],
        ascending=[True,False]
    )
)
g = products.groupby('order_state')

products['group_row_number'] = (
    g.cumcount() + 1
)
products['state_group_size'] = (
    g['order_state']
    .transform('count')
)
products['net_amount_group_of_3_desc'] = (
    (products['row_number'] - 1) * 3 // products['state_group_size']
) + 1

products[
    ['order_state', 'net_amount', 'group_row_number', 'state_group_size', 'net_amount_group_of_3_desc']
]

,order_state,net_amount,group_row_number,state_group_size,net_amount_group_of_3_desc
4,GJ,24000.0,1,3,1
3,GJ,9000.0,2,3,2
5,GJ,4000.0,3,3,3
0,MH,100000.0,1,3,1
2,MH,50000.0,2,3,2
1,MH,4000.0,3,3,3
6,RJ,50000.0,1,4,1
8,RJ,24000.0,2,4,1
9,RJ,4000.0,3,4,2
7,RJ,3000.0,4,4,3

In [70]:
%%sql 
SELECT order_state, net_amount, 
NTILE(3)
OVER(
    PARTITION BY order_state
    ORDER BY net_amount DESC
) AS net_amount_group_of_3_desc 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+----------------------------+
| order_state | net_amount | net_amount_group_of_3_desc |
+-------------+------------+----------------------------+
|      GJ     |  24000.0   |             1              |
|      GJ     |   9000.0   |             2              |
|      GJ     |   4000.0   |             3              |
|      MH     |  100000.0  |             1              |
|      MH     |  50000.0   |             2              |
|      MH     |   4000.0   |             3              |
|      RJ     |  50000.0   |             1              |
|      RJ     |  24000.0   |             1              |
|      RJ     |   4000.0   |             2              |
|      RJ     |   3000.0   |             3              |
+-------------+------------+----------------------------+
Truncated to displaylimit of 10.

<pre>Har **product_name** ke orders ko **discount** ke hisaab se (high to low) 4 groups me baanto.</pre>

In [ ]:
# 'product_name', 'discount', 'product_group_row_number', 'product_group_size', 'discount_group_of_4_desc'
products = (
    products
    .sort_values(
        ['product_name', 'discount'],
        ascending=[True, False]
    )
)
g = products.groupby('product_name')

products['product_group_row_number'] = (
    g.cumcount() + 1 
)
products['product_group_size'] = (
    g['product_name']
    .transform('count')
)
products['discount_group_of_4_desc'] = (
    (products['product_group_row_number'] - 1) * 4 // products['product_group_size']
) + 1

products[
    ['product_name', 'discount', 'product_group_row_number', 'product_group_size', 'discount_group_of_4_desc']
]

,product_name,discount,product_group_row_number,product_group_size,discount_group_of_4_desc
3,Keyboard,10,1,2,1
7,Keyboard,5,2,2,3
0,Laptop,10,1,3,1
2,Laptop,5,2,3,2
6,Laptop,5,3,3,3
4,Monitor,20,1,2,1
8,Monitor,15,2,2,3
5,Mouse,20,1,3,1
1,Mouse,15,2,3,2
9,Mouse,15,3,3,3

In [73]:
%%sql 
SELECT product_name, discount,
NTILE(4)
OVER(
    PARTITION BY product_name
    ORDER BY discount DESC
) AS discount_group_of_4_desc
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+----------+--------------------------+
| product_name | discount | discount_group_of_4_desc |
+--------------+----------+--------------------------+
|   Keyboard   |    10    |            1             |
|   Keyboard   |    5     |            2             |
|    Laptop    |    10    |            1             |
|    Laptop    |    5     |            2             |
|    Laptop    |    5     |            3             |
|   Monitor    |    20    |            1             |
|   Monitor    |    15    |            2             |
|    Mouse     |    20    |            1             |
|    Mouse     |    15    |            2             |
|    Mouse     |    15    |            3             |
+--------------+----------+--------------------------+
Truncated to displaylimit of 10.

### **Grouping and labeling ✅**

<pre>Puri table ke **net_amount** ko high to low order me 4 groups me baanto. Fir har group ko business label do.</pre>
| Group | Label    |
| ----: | -------- |
|     1 | Platinum |
|     2 | Gold     |
|     3 | Silver   |
|     4 | Bronze   |

In [107]:
# 'product_name', 'net_amount', row_number, 'net_amount_group_of_4_desc', 'net_amount_level'
products = (
    products
    .sort_values('net_amount',  ascending=False)
)
products['row_number'] = range(1,len(products) + 1)
products['net_amount_group_of_4_desc'] = (
    (products['row_number'] - 1) * 4 // len(products)
) + 1
label = {
    1 : 'Platinum',
    2 : 'Gold',
    3 : 'Silver',
    4 : 'Bronze'
}
products['net_amount_level'] = (
    products['net_amount_group_of_4_desc']
    .map(label)
)
products[ 
    ['product_name', 'net_amount', 'row_number', 'net_amount_group_of_4_desc', 'net_amount_level']
]

,product_name,net_amount,row_number,net_amount_group_of_4_desc,net_amount_level
0,Laptop,100000.0,1,1,Platinum
2,Laptop,50000.0,2,1,Platinum
6,Laptop,50000.0,3,1,Platinum
4,Monitor,24000.0,4,2,Gold
8,Monitor,24000.0,5,2,Gold
3,Keyboard,9000.0,6,3,Silver
1,Mouse,4000.0,7,3,Silver
5,Mouse,4000.0,8,3,Silver
9,Mouse,4000.0,9,4,Bronze
7,Keyboard,3000.0,10,4,Bronze

In [93]:
%%sql 
WITH net_amount_group AS (
    SELECT product_name, net_amount,
    NTILE(4)
    OVER(
        ORDER BY net_amount DESC
    ) AS net_amount_group_of_4_desc 
    FROM products01
)
SELECT product_name, net_amount, net_amount_group_of_4_desc,
    CASE
        WHEN net_amount_group_of_4_desc = 1 THEN 'Platinum'
        WHEN net_amount_group_of_4_desc = 2 THEN 'Gold'
        WHEN net_amount_group_of_4_desc = 3 THEN 'Silver'
        WHEN net_amount_group_of_4_desc = 4 THEN 'Bronze'
    END AS net_amount_level 
FROM net_amount_group;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+------------+----------------------------+------------------+
| product_name | net_amount | net_amount_group_of_4_desc | net_amount_level |
+--------------+------------+----------------------------+------------------+
|    Laptop    |  100000.0  |             1              |     Platinum     |
|    Laptop    |  50000.0   |             1              |     Platinum     |
|    Laptop    |  50000.0   |             1              |     Platinum     |
|   Monitor    |  24000.0   |             2              |       Gold       |
|   Monitor    |  24000.0   |             2              |       Gold       |
|   Keyboard   |   9000.0   |             2              |       Gold       |
|    Mouse     |   4000.0   |             3              |      Silver      |
|    Mouse     |   4000.0   |             3              |      Silver      |
|    Mouse     |   4000.0   |             4              |      Bronze      |
|   Keyboard   |   3000.0   |             4              |      Bronze      |
+--------------+------------+----------------------------+------------------+
Truncated to displaylimit of 10.

<pre>Har product ke **discount_group_of_4_desc** ko business label me convert karo.

Agar group 1 ho to Platinum
Agar group 2 ho to Gold
Agar group 3 ho to Silver
Agar group 4 ho to Bronze</pre>

In [90]:
# 'product_name', 'discount', 'product_group_row_number', 'row_number_count', 'discount_group_of_4_desc', 'label'
products = (
    products
    .sort_values(
        ['product_name', 'discount'],
        ascending=[True, False]
    )
)
g = products.groupby('product_name')
products['product_group_row_number'] = (
    g.cumcount() + 1
)
products['row_number_count'] = (
    g['product_name']
    .transform('count')
)
products['discount_group_of_4_desc'] = (
    (products['product_group_row_number'] - 1) * 4 // products['row_number_count']
) + 1
group_label = {
    1 : 'Platinum',
    2 : 'Gold',
    3 : 'Silver',
    4 : 'Bronze'
}
products['discount_level'] = (
    products['discount_group_of_4_desc']
    .map(group_label)
)
products[
    ['product_name', 'discount', 'product_group_row_number', 'row_number_count', 'discount_group_of_4_desc', 'discount_level']
]

,product_name,discount,product_group_row_number,row_number_count,discount_group_of_4_desc,discount_level
3,Keyboard,10,1,2,1,Platinum
7,Keyboard,5,2,2,3,Silver
0,Laptop,10,1,3,1,Platinum
2,Laptop,5,2,3,2,Gold
6,Laptop,5,3,3,3,Silver
4,Monitor,20,1,2,1,Platinum
8,Monitor,15,2,2,3,Silver
5,Mouse,20,1,3,1,Platinum
1,Mouse,15,2,3,2,Gold
9,Mouse,15,3,3,3,Silver

In [89]:
%%sql 
WITH discount_group AS (
    SELECT product_name, discount,
    NTILE(4)
    OVER(
        PARTITION BY product_name
        ORDER BY discount DESC
    ) AS discount_group_of_4_desc 
    FROM products01
)
SELECT product_name, discount, discount_group_of_4_desc,
    CASE
        WHEN discount_group_of_4_desc = 1 THEN 'Platinum'
        WHEN discount_group_of_4_desc = 2 THEN 'Gold'
        WHEN discount_group_of_4_desc = 3 THEN 'Silver'
        WHEN discount_group_of_4_desc = 4 THEN 'Bronze'
    END AS discount_level
FROM discount_group;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+----------+--------------------------+----------------+
| product_name | discount | discount_group_of_4_desc | discount_level |
+--------------+----------+--------------------------+----------------+
|   Keyboard   |    10    |            1             |    Platinum    |
|   Keyboard   |    5     |            2             |      Gold      |
|    Laptop    |    10    |            1             |    Platinum    |
|    Laptop    |    5     |            2             |      Gold      |
|    Laptop    |    5     |            3             |     Silver     |
|   Monitor    |    20    |            1             |    Platinum    |
|   Monitor    |    15    |            2             |      Gold      |
|    Mouse     |    20    |            1             |    Platinum    |
|    Mouse     |    15    |            2             |      Gold      |
|    Mouse     |    15    |            3             |     Silver     |
+--------------+----------+--------------------------+----------------+
Truncated to displaylimit of 10.

### **Value-Based Categorization**

<pre>Puri table ke discount ko value ke hisaab se 3 groups me divide karo.</pre>

In [17]:
products = (
    products
    .sort_values('discount', ascending=False)
)
products['discount_group_of_3'] = (
    pd.qcut(
        products['discount'],
        q=3,
        labels = False,
    ) + 1
)
products[
    ['product_name', 'discount', 'discount_group_of_3']
]

  product_name  discount  discount_group_of_3
5        Mouse        20                    3
4      Monitor        20                    3
1        Mouse        15                    2
8      Monitor        15                    2
9        Mouse        15                    2
0       Laptop        10                    1
3     Keyboard        10                    1
2       Laptop         5                    1
6       Laptop         5                    1
7     Keyboard         5                    1

<pre>Puri table ke **product_price** ko value ke hisaab se 4 groups me divide karo,
jahan sabse badi price ko Group 1 aur sabse chhoti price ko Group 4 milna chahiye.</pre>

In [34]:
products = (
    products
    .sort_values('product_price', ascending=False)
)
products['product_price_group_of_5'] = (
    pd.qcut(
        products['product_price'],
        q = 4,
        labels = range(4,0,-1)
    )
)
products[
    ['product_name', 'product_price', 'product_price_group_of_5']
]

  product_name  product_price product_price_group_of_5
2       Laptop        50000.0                        1
0       Laptop        50000.0                        1
6       Laptop        50000.0                        1
4      Monitor        12000.0                        2
8      Monitor        12000.0                        2
3     Keyboard         3000.0                        3
7     Keyboard         3000.0                        3
5        Mouse         2000.0                        4
9        Mouse         2000.0                        4
1        Mouse         2000.0                        4

In [39]:
products = (
    products
    .sort_values('product_price', ascending=False)
)
products['product_price_group_of_5'] = (
    pd.qcut(
        products['product_price'],
        q = 5,
        labels = range(4,0,-1)
    )
)
products[
    ['product_name', 'product_price', 'product_price_group_of_5']
]

ValueError: Bin edges must be unique: Index([2000.0, 2000.0, 3000.0, 12000.0, 50000.0, 50000.0], dtype='float64', name='product_price').
You can drop duplicate edges by setting the 'duplicates' kwarg

**only 4 unique values to divide so q = 4 is an error \
instead of do this**

In [43]:
products = (
    products
    .sort_values('product_price', ascending=False)
)
unique_price = products['product_price'].nunique() # n of unique values
products['product_price_group_of_4'] = (
    pd.qcut(
        products['product_price'],
        q = unique_price,
        labels = range(unique_price,0,-1)
    )
)
products[
    ['product_name', 'product_price', 'product_price_group_of_4']
]

  product_name  product_price product_price_group_of_4
2       Laptop        50000.0                        1
0       Laptop        50000.0                        1
6       Laptop        50000.0                        1
4      Monitor        12000.0                        2
8      Monitor        12000.0                        2
3     Keyboard         3000.0                        3
7     Keyboard         3000.0                        3
5        Mouse         2000.0                        4
9        Mouse         2000.0                        4
1        Mouse         2000.0                        4

<pre>Puri table ke discount ko value ke hisaab se 3 groups me divide karo.</pre>

In [48]:
products = (
    products.sort_values('discount', ascending=False)
)
products['discount_group_of_3'] = (
    pd.qcut(
        products['discount'],
        q = 3,
        labels = range(3,0,-1)
    )
)
products[ 
    ['product_name', 'discount', 'discount_group_of_3']
]

  product_name  discount discount_group_of_3
5        Mouse        20                   1
4      Monitor        20                   1
1        Mouse        15                   2
8      Monitor        15                   2
9        Mouse        15                   2
0       Laptop        10                   3
3     Keyboard        10                   3
2       Laptop         5                   3
6       Laptop         5                   3
7     Keyboard         5                   3

In [50]:
%%sql
SELECT
    product_name,
    discount,
    NTILE(3) OVER (
        ORDER BY discount DESC
    ) AS discount_group_of_3_desc
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+--------------+----------+--------------------------+
| product_name | discount | discount_group_of_3_desc |
+--------------+----------+--------------------------+
|    Mouse     |    20    |            1             |
|   Monitor    |    20    |            1             |
|    Mouse     |    15    |            1             |
|    Mouse     |    15    |            1             |
|   Monitor    |    15    |            2             |
|    Laptop    |    10    |            2             |
|   Keyboard   |    10    |            2             |
|    Laptop    |    5     |            3             |
|    Laptop    |    5     |            3             |
|   Keyboard   |    5     |            3             |
+--------------+----------+--------------------------+
Truncated to displaylimit of 10.

**cut()**

<pre>Puri table ke net_amount ko 4 equal-width groups me divide karo.</pre>
<pre>
10
20
30
40
50
60
70
80
-------------------------------
max - min = range
80 - 10 = 70
------------------------------
range / bins
70 / 4 = 17.5
------------------------------
4 equal width interval
10   ───── 27.5

27.5 ───── 45

45   ───── 62.5

62.5 ───── 80
</pre>

In [83]:
products = (
    products
    .sort_values('net_amount')
)
products['net_amount_4_equal_width_group'] = (
    pd.cut(
        products['net_amount'],
        bins=4,
        labels=False
    ) + 1
)

products[
    ['customer_name', 'net_amount','net_amount_4_equal_width_group']
]

  customer_name  net_amount  net_amount_4_equal_width_group
7         Kiran      3000.0                               1
1          Amit      4000.0                               1
5          Neha      4000.0                               1
9          Sita      4000.0                               1
3          Ravi      9000.0                               1
4          Neha     24000.0                               1
8          Sita     24000.0                               1
2          Ravi     50000.0                               2
6         Kiran     50000.0                               2
0          Amit    100000.0                               4

<pre>Puri table ke discount ko cut() ka use karke 3 equal-width groups me divide karo.</pre>

In [88]:
products = (
    products
    .sort_values('discount')
)
products['discount_3_equal_width_group'] = (
    pd.cut(
        products['discount'],
        bins = 3,
        labels=False
    ) + 1
)
products[ 
    ['product_name', 'discount', 'discount_3_equal_width_group']
]

  product_name  discount  discount_3_equal_width_group
7     Keyboard         5                             1
2       Laptop         5                             1
6       Laptop         5                             1
3     Keyboard        10                             1
0       Laptop        10                             1
9        Mouse        15                             2
8      Monitor        15                             2
1        Mouse        15                             2
4      Monitor        20                             3
5        Mouse        20                             3

<pre>Puri table ke **product_price** ko cut() ka use karke 5 equal-width groups me divide karo.</pre>

In [100]:
products = (
    products
    .sort_values('product_price')
)
products['product_price_5_equal_width_group'] = (
    pd.cut(
        products['product_price'],
        bins = 5,
        labels = False
    ) + 1
)
products[
    ['product_name', 'product_price', 'product_price_5_equal_width_group']
]

  product_name  product_price  product_price_5_equal_width_group
1        Mouse         2000.0                                  1
5        Mouse         2000.0                                  1
9        Mouse         2000.0                                  1
7     Keyboard         3000.0                                  1
3     Keyboard         3000.0                                  1
4      Monitor        12000.0                                  2
8      Monitor        12000.0                                  2
0       Laptop        50000.0                                  5
6       Laptop        50000.0                                  5
2       Laptop        50000.0                                  5

In [97]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05

In [96]:
products.sort_values('product_id', inplace=True)

In [90]:
lst = ['discount_3_equal_width_group']
products.drop(lst, axis = 1, inplace = True)

In [96]:
products.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 3 to 9
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_id                10 non-null     int64
 1   customer_name             10 non-null     str
 2   order_state               10 non-null     str
 3   product_name              10 non-null     str
 4   product_quantity          10 non-null     int64
 5   product_price             10 non-null     float64
 6   discount                  10 non-null     int64
 7   net_amount                10 non-null     float64
 8   order_date                10 non-null     datetime64[s]
 9   product_group_row_number  10 non-null     int64
 10  row_number_count          10 non-null     int64
 11  discount_group_of_4_desc  10 non-null     int64
 12  lable                     10 non-null     str
 13  label                     10 non-null     str
 14  discount_level            10 non-null     str
dtypes: datetime64[s](1), float64(2), int64(6), str(6)
memory usage: 1.2 KB