In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01;'
products = pd.read_sql(query, con=engine)

In [7]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **PERCENT_RANK()**
**Returns the relative rank of a row between 0 and 1.**

$
Percent\ Rank = \frac{Rank - 1}{Total\ rank\ - 1}
$

<pre>**net_amount** ke adhar par highest amount ko pehle rakhte hue har row ka **PERCENT_RANK**() nikalo.</pre>

In [15]:
%%sql 
SELECT net_amount,
PERCENT_RANK()
OVER(
    ORDER BY net_amount DESC
) AS percent_rank
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+-------------------+
| net_amount |    percent_rank   |
+------------+-------------------+
|  100000.0  |        0.0        |
|  50000.0   | 0.111111111111111 |
|  50000.0   | 0.111111111111111 |
|  24000.0   | 0.333333333333333 |
|  24000.0   | 0.333333333333333 |
|   9000.0   | 0.555555555555556 |
|   4000.0   | 0.666666666666667 |
|   4000.0   | 0.666666666666667 |
|   4000.0   | 0.666666666666667 |
|   3000.0   |        1.0        |
+------------+-------------------+
Truncated to displaylimit of 10.

In [ ]:
products = (
    products
    .sort_values('net_amount', ascending=False)
)
products['rank'] = (
    products['net_amount']
    .rank(
        ascending=False,
        method='min'
    )
)
products['percent_rank'] = (
    (products['rank'] - 1) /
    (len(products['rank']) - 1)
)
products[
    ['net_amount', 'rank', 'percent_rank']
]

   net_amount  rank  percent_rank
0    100000.0   1.0      0.000000
2     50000.0   2.0      0.111111
6     50000.0   2.0      0.111111
8     24000.0   4.0      0.333333
4     24000.0   4.0      0.333333
3      9000.0   6.0      0.555556
1      4000.0   7.0      0.666667
5      4000.0   7.0      0.666667
9      4000.0   7.0      0.666667
7      3000.0  10.0      1.000000

<pre>using PARTITION BY </PRE>

In [16]:
%%sql 
SELECT order_state, net_amount,
PERCENT_RANK()
OVER(
    PARTITION BY order_state
    ORDER BY net_amount DESC
) AS percent_rank 
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+-------------------+
| order_state | net_amount |    percent_rank   |
+-------------+------------+-------------------+
|      GJ     |  24000.0   |        0.0        |
|      GJ     |   9000.0   |        0.5        |
|      GJ     |   4000.0   |        1.0        |
|      MH     |  100000.0  |        0.0        |
|      MH     |  50000.0   |        0.5        |
|      MH     |   4000.0   |        1.0        |
|      RJ     |  50000.0   |        0.0        |
|      RJ     |  24000.0   | 0.333333333333333 |
|      RJ     |   4000.0   | 0.666666666666667 |
|      RJ     |   3000.0   |        1.0        |
+-------------+------------+-------------------+
Truncated to displaylimit of 10.

In [ ]:
products = (
    products
    .sort_values(
        ['order_state', 'net_amount'],
        ascending=[True, False]
    )
)
products['rank'] = (
    products
    .groupby('order_state')['net_amount']
    .rank(
        ascending=False,
        method='min'
    )
)
group_size = products.groupby('rank')['rank'].transform('count')

products['percent_rank'] = (
    (products['rank'] - 1) /
    (group_size - 1)
)
products[ 
    ['order_state', 'net_amount', 'rank', 'percent_rank']
]

  order_state  net_amount  rank  percent_rank
4          GJ     24000.0   1.0           0.0
3          GJ      9000.0   2.0           1.0
5          GJ      4000.0   3.0           2.0
0          MH    100000.0   1.0           0.0
2          MH     50000.0   2.0           1.0
1          MH      4000.0   3.0           2.0
6          RJ     50000.0   1.0           0.0
8          RJ     24000.0   2.0           1.0
9          RJ      4000.0   3.0           2.0
7          RJ      3000.0   4.0          -3.0

In [6]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05