In [1]:
print('welcome')

welcome

In [3]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[paswword]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres')
query = 'SELECT * FROM products01;'
products = pd.read_sql(query, con=engine)

In [16]:
products['order_date'] = pd.to_datetime(
    products['order_date']
)

### **Percentage of Total**
**Har row poori table ke total ka kitna % contribute karti hai?**

$
Percentag\ of\ Total = \frac{Current\ Value}{Total\ of\ Whole\ Table} \times 100
$

| Product | Net Amount | % of Total |
| ------- | ---------: | ---------: |
| A       |        100 |        10% |
| B       |        200 |        20% |
| C       |        700 |        70% |

<pre>Har row ka **net_amount** poori table ke total **net_amount** ka kitna percentage hai?</pre>

In [ ]:
%%sql 
SELECT net_amount, 
(net_amount * 100) /
SUM(net_amount)
OVER() AS percentage_of_total
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+---------------------+
| net_amount | percentage_of_total |
+------------+---------------------+
|  100000.0  | 36.7647058823529412 |
|   4000.0   |  1.4705882352941176 |
|  50000.0   | 18.3823529411764706 |
|   9000.0   |  3.3088235294117647 |
|  24000.0   |  8.8235294117647059 |
|   4000.0   |  1.4705882352941176 |
|  50000.0   | 18.3823529411764706 |
|   3000.0   |  1.1029411764705882 |
|  24000.0   |  8.8235294117647059 |
|   4000.0   |  1.4705882352941176 |
+------------+---------------------+
Truncated to displaylimit of 10.

In [35]:
%%sql 
SELECT net_amount,
(net_amount / SUM(net_amount) OVER()) * 100 
AS percentage_of_total
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+------------+-------------------------+
| net_amount |   percentage_of_total   |
+------------+-------------------------+
|  100000.0  | 36.76470588235294117600 |
|   4000.0   |  1.47058823529411764700 |
|  50000.0   | 18.38235294117647058800 |
|   9000.0   |  3.30882352941176470600 |
|  24000.0   |  8.82352941176470588200 |
|   4000.0   |  1.47058823529411764700 |
|  50000.0   | 18.38235294117647058800 |
|   3000.0   |  1.10294117647058823500 |
|  24000.0   |  8.82352941176470588200 |
|   4000.0   |  1.47058823529411764700 |
+------------+-------------------------+
Truncated to displaylimit of 10.

In [17]:
products['percentage_of_total'] = (
    (products['net_amount'] / products['net_amount'].sum()) * 100
)
products[
    ['net_amount', 'percentage_of_total']
]

   net_amount  percentage_of_total
0    100000.0            36.764706
1      4000.0             1.470588
2     50000.0            18.382353
3      9000.0             3.308824
4     24000.0             8.823529
5      4000.0             1.470588
6     50000.0            18.382353
7      3000.0             1.102941
8     24000.0             8.823529
9      4000.0             1.470588

<pre>Har row ka **discount** poori table ke total discount ka kitna percentage hai?</pre>

In [ ]:
%%sql 
SELECT discount, 
(discount * 100.0) / 
SUM(discount) OVER()
AS percentage_of_total_discount
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+----------+------------------------------+
| discount | percentage_of_total_discount |
+----------+------------------------------+
|    10    |      8.3333333333333333      |
|    15    |     12.5000000000000000      |
|    5     |      4.1666666666666667      |
|    10    |      8.3333333333333333      |
|    20    |     16.6666666666666667      |
|    20    |     16.6666666666666667      |
|    5     |      4.1666666666666667      |
|    5     |      4.1666666666666667      |
|    15    |     12.5000000000000000      |
|    15    |     12.5000000000000000      |
+----------+------------------------------+
Truncated to displaylimit of 10.

In [46]:
products['discount'].sum()

np.int64(120)

In [36]:
products['percentage_of_total_discount'] = (
    (products['discount'] / products['discount'].sum()) * 100
)
products[
    ['discount', 'percentage_of_total_discount']
]

   discount  percentage_of_total_discount
0        10                      8.333333
1        15                     12.500000
2         5                      4.166667
3        10                      8.333333
4        20                     16.666667
5        20                     16.666667
6         5                      4.166667
7         5                      4.166667
8        15                     12.500000
9        15                     12.500000

<pre>Har **order_state** ke andar **net_amount** us state ke total **net_amount** ka kitna percentage contribute karta hai?</pre>

In [48]:
%%sql 
SELECT order_state, net_amount,
(net_amount * 100) / SUM(net_amount)
OVER(
    PARTITION BY order_state
) AS percentage_of_each_state_net_amount
FROM products01;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

10 rows affected.

+-------------+------------+-------------------------------------+
| order_state | net_amount | percentage_of_each_state_net_amount |
+-------------+------------+-------------------------------------+
|      GJ     |   9000.0   |         24.3243243243243243         |
|      GJ     |  24000.0   |         64.8648648648648649         |
|      GJ     |   4000.0   |         10.8108108108108108         |
|      MH     |  100000.0  |         64.9350649350649351         |
|      MH     |   4000.0   |          2.5974025974025974         |
|      MH     |  50000.0   |         32.4675324675324675         |
|      RJ     |  50000.0   |         61.7283950617283951         |
|      RJ     |   3000.0   |          3.7037037037037037         |
|      RJ     |  24000.0   |         29.6296296296296296         |
|      RJ     |   4000.0   |          4.9382716049382716         |
+-------------+------------+-------------------------------------+
Truncated to displaylimit of 10.

In [51]:
products['state_net_amount'] = (
    products
    .groupby('order_state')['net_amount']
    .transform('sum')
)
products['percentage_of_each_state_net_amount'] = (
    (products['net_amount'] / products['state_net_amount']) * 100
)
products[
    ['order_state', 'net_amount', 'state_net_amount', 'percentage_of_each_state_net_amount']
]

,order_state,net_amount,state_net_amount,percentage_of_each_state_net_amount
0,MH,100000.0,154000.0,64.935065
1,MH,4000.0,154000.0,2.597403
2,MH,50000.0,154000.0,32.467532
3,GJ,9000.0,37000.0,24.324324
4,GJ,24000.0,37000.0,64.864865
5,GJ,4000.0,37000.0,10.810811
6,RJ,50000.0,81000.0,61.728395
7,RJ,3000.0,81000.0,3.703704
8,RJ,24000.0,81000.0,29.629630
9,RJ,4000.0,81000.0,4.938272

In [7]:
products.head(1)

,product_id,customer_name,order_state,product_name,product_quantity,product_price,discount,net_amount,order_date
0,1,Amit,MH,Laptop,2,50000.0,10,100000.0,2026-01-05