In [1]:
print('hello')

hello

In [2]:
%load_ext sql

In [3]:
import pandas as pd

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [5]:
%%sql 
CREATE TABLE products(
    product_id SERIAL PRIMARY KEY ,
    product_name VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    order_state VARCHAR(50) NOT NULL,

    product_price NUMERIC(10,2) NOT NULL
        CHECK(product_price >= 0),

    product_quantity INT NOT NULL
        CHECK (product_quantity > 0),
    
    discount NUMERIC(5,2) DEFAULT 0 
        CHECK (discount >= 0 AND discount <= 50),

    gross_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        (product_price * product_quantity) 
        STORED,

    net_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        ((product_price * product_quantity) * (1 - discount / 100)) 
        STORED
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

RuntimeError: (psycopg2.errors.DuplicateTable) relation "products" already exists

[SQL: CREATE TABLE products(
    product_id SERIAL PRIMARY KEY ,
    product_name VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    order_state VARCHAR(50) NOT NULL,

    product_price NUMERIC(10,2) NOT NULL
        CHECK(product_price >= 0),

    product_quantity INT NOT NULL
        CHECK (product_quantity > 0),

    discount NUMERIC(5,2) DEFAULT 0
        CHECK (discount >= 0 AND discount <= 50),

    gross_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        (product_price * product_quantity)
        STORED,

    net_amount NUMERIC(10,2)
        GENERATED ALWAYS AS
        ((product_price * product_quantity) * (1 - discount / 100))
        STORED
);]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [4]:
%%sql
INSERT INTO products 
(product_name, order_date, customer_name, order_state, product_price, product_quantity, discount)
VALUES
('table', '2020-05-09', 'kiran', 'MH', 2200, 3, 6),
('fan', '2020-05-10', 'sonam', 'RJ', 2000, 2, 2),
('sopa', '2020-05-11', 'sima', 'RJ', 4300, 1, 16),
('sopa', '2020-05-11', 'sima', 'RJ', 4300, 1, 16),
('chair', '2020-05-12', 'satish', 'GJ', 1200, 10, 0),
('bulps', '2020-05-14', 'karim', 'JK', 20, 100, 2),
('fan', '2020-05-15', 'kushal', 'CN', 2000, 2, 2),
('bulps', '2020-05-16', 'sunam', 'BR', 20, 10, 2),
('watch', '2020-05-17', 'jaya', 'UP', 220, 1, 2),
('cooler', '2020-05-18', 'manish', 'RJ', 3200, 2, 20),
('table', '2020-05-19', 'mahendra', 'KR', 2200, 4, 6),
('sopa', '2020-05-20', 'sushant', 'KR', 4300, 2, 16);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

++
||
++
++

In [7]:
%%sql 
SELECT * FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
| product_id | product_name | order_date | customer_name | order_state | product_price | product_quantity | discount | gross_amount | net_amount |
+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
|     1      |    table     | 2020-05-09 |     kiran     |      MH     |    2200.00    |        3         |   6.00   |   6600.00    |  6204.00   |
|     2      |     fan      | 2020-05-10 |     sonam     |      RJ     |    2000.00    |        2         |   2.00   |   4000.00    |  3920.00   |
|     3      |     sopa     | 2020-05-11 |      sima     |      RJ     |    4300.00    |        1         |  16.00   |   4300.00    |  3612.00   |
|     4      |     sopa     | 2020-05-11 |      sima     |      RJ     |    4300.00    |        1         |  16.00   |   4300.00    |  3612.00   |
|     5      |    chair     | 2020-05-12 |     satish    |      GJ     |    1200.00    |        10        |   0.00   |   12000.00   |  12000.00  |
|     6      |    bulps     | 2020-05-14 |     karim     |      JK     |     20.00     |       100        |   2.00   |   2000.00    |  1960.00   |
|     7      |     fan      | 2020-05-15 |     kushal    |      CN     |    2000.00    |        2         |   2.00   |   4000.00    |  3920.00   |
|     8      |    bulps     | 2020-05-16 |     sunam     |      BR     |     20.00     |        10        |   2.00   |    200.00    |   196.00   |
|     9      |    watch     | 2020-05-17 |      jaya     |      UP     |     220.00    |        1         |   2.00   |    220.00    |   215.60   |
|     10     |    cooler    | 2020-05-18 |     manish    |      RJ     |    3200.00    |        2         |  20.00   |   6400.00    |  5120.00   |
+------------+--------------+------------+---------------+-------------+---------------+------------------+----------+--------------+------------+
Truncated to displaylimit of 10.

In [5]:
products = {
    'product_id' : [i for i in range(1, 13)],
    'product_name' : ['table', 'fan', 'sopa', 'sopa', 'chair', 'bulps', 'fan', 'bulps', 'watch', 'cooler', 'table', 'sopa'],
    'order_date' : ['2020-05-09', '2020-05-10', '2020-05-09', '2020-05-11', '2020-05-12', '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19', '2020-05-20'],
    'customer_name' : ['kiran', 'sonam', 'sima', 'sima', 'satish', 'karim', 'kushal', 'sunam', 'jaya', 'manish', 'mahendra', 'sushant'],
    'order_state' : ['MH', 'RJ', 'RJ', 'RJ', 'GJ', 'JK', 'CN', 'BR', 'UP', 'RJ', 'KR', 'KR'],
    'product_price' : [2200, 2000, 4300, 4300, 1200, 20, 2000, 20, 220, 3200, 2200, 4300],
    'product_quantity' : [3, 2, 1, 1, 10, 100, 2, 10, 1, 2, 4, 2],
    'discount' : [6, 2, 16, 16, 0, 2, 2, 2, 2, 20, 6, 16]
}
products = pd.DataFrame(products)
products

,product_id,product_name,order_date,customer_name,order_state,product_price,product_quantity,discount
0,1,table,2020-05-09,kiran,MH,2200,3,6
1,2,fan,2020-05-10,sonam,RJ,2000,2,2
2,3,sopa,2020-05-09,sima,RJ,4300,1,16
3,4,sopa,2020-05-11,sima,RJ,4300,1,16
4,5,chair,2020-05-12,satish,GJ,1200,10,0
5,6,bulps,2020-05-14,karim,JK,20,100,2
6,7,fan,2020-05-15,kushal,CN,2000,2,2
7,8,bulps,2020-05-16,sunam,BR,20,10,2
8,9,watch,2020-05-17,jaya,UP,220,1,2
9,10,cooler,2020-05-18,manish,RJ,3200,2,20
10,11,table,2020-05-19,mahendra,KR,2200,4,6
11,12,sopa,2020-05-20,sushant,KR,4300,2,16

In [6]:
products['gross_amount'] = (
    products['product_price'] * products['product_quantity']
)
products['net_amount'] = (
    products['gross_amount'] - (products['gross_amount'] * products['discount']) / 100
)

**WINDOW ROW_NUMBER() FUNCTION**

<pre>Har state ke andar products ko <i>product_price</i> ke hisaab se sabse mehange se sabse saste tak rank nahi, balki ek serial number dena hai.

Expected Output (Example):

order_state  	product_name	product_price	row_number</pre>

In [8]:
%%sql 
SELECT order_state, product_name, product_price, 
ROW_NUMBER()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC
) AS row_number
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+-------------+--------------+---------------+------------+
| order_state | product_name | product_price | row_number |
+-------------+--------------+---------------+------------+
|      BR     |    bulps     |     20.00     |     1      |
|      CN     |     fan      |    2000.00    |     1      |
|      GJ     |    chair     |    1200.00    |     1      |
|      JK     |    bulps     |     20.00     |     1      |
|      KR     |     sopa     |    4300.00    |     1      |
|      KR     |    table     |    2200.00    |     2      |
|      MH     |    table     |    2200.00    |     1      |
|      RJ     |     sopa     |    4300.00    |     1      |
|      RJ     |     sopa     |    4300.00    |     2      |
|      RJ     |    cooler    |    3200.00    |     3      |
+-------------+--------------+---------------+------------+
Truncated to displaylimit of 10.

In [14]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending = [True, False]
    )
)
products['row_number'] = (
    products
    .groupby('order_state')
    .cumcount()
    + 1
)
products[
    ['order_state', 'product_name', 'product_price', 'row_number']
]

   order_state product_name  product_price  row_number
7           BR        bulps             20           1
6           CN          fan           2000           1
4           GJ        chair           1200           1
5           JK        bulps             20           1
11          KR         sopa           4300           1
10          KR        table           2200           2
0           MH        table           2200           1
2           RJ         sopa           4300           1
3           RJ         sopa           4300           2
9           RJ       cooler           3200           3
1           RJ          fan           2000           4
8           UP        watch            220           1

<pre>Har customer ke orders ko order_date ke hisaab se purane se naye tak serial number do.

Expected Output (Example)

customer_name	order_date	product_name	order_number</pre>

In [24]:
%%sql
SELECT customer_name, order_date, product_name,
ROW_NUMBER()
OVER(
    PARTITION BY customer_name
    ORDER BY order_date ASC
) AS order_number
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+---------------+------------+--------------+--------------+
| customer_name | order_date | product_name | order_number |
+---------------+------------+--------------+--------------+
|      jaya     | 2020-05-17 |    watch     |      1       |
|     karim     | 2020-05-14 |    bulps     |      1       |
|     kiran     | 2020-05-09 |    table     |      1       |
|     kushal    | 2020-05-15 |     fan      |      1       |
|    mahendra   | 2020-05-19 |    table     |      1       |
|     manish    | 2020-05-18 |    cooler    |      1       |
|     satish    | 2020-05-12 |    chair     |      1       |
|      sima     | 2020-05-11 |     sopa     |      1       |
|      sima     | 2020-05-11 |     sopa     |      2       |
|     sonam     | 2020-05-10 |     fan      |      1       |
+---------------+------------+--------------+--------------+
Truncated to displaylimit of 10.

In [23]:
products = (
    products
    .sort_values(
        ['customer_name', 'order_date'],
        ascending = [True, True]
    )
)
products['order_number'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products[
    ['customer_name', 'order_date', 'product_price', 'order_number']
]

   customer_name  order_date  product_price  order_number
8           jaya  2020-05-17            220             1
5          karim  2020-05-14             20             1
0          kiran  2020-05-09           2200             1
6         kushal  2020-05-15           2000             1
10      mahendra  2020-05-19           2200             1
9         manish  2020-05-18           3200             1
4         satish  2020-05-12           1200             1
2           sima  2020-05-09           4300             1
3           sima  2020-05-11           4300             2
1          sonam  2020-05-10           2000             1
7          sunam  2020-05-16             20             1
11       sushant  2020-05-20           4300             1

<pre>Har customer ke orders ko naye se purane tak serial number do.</pre>

In [26]:
%%sql 
SELECT customer_name, order_date, 
ROW_NUMBER()
OVER(
    PARTITION BY customer_name
    ORDER BY order_date DESC
) AS serial_new_to_old
FROM products
ORDER BY order_date DESC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+---------------+------------+-------------------+
| customer_name | order_date | serial_new_to_old |
+---------------+------------+-------------------+
|    sushant    | 2020-05-20 |         1         |
|    mahendra   | 2020-05-19 |         1         |
|     manish    | 2020-05-18 |         1         |
|      jaya     | 2020-05-17 |         1         |
|     sunam     | 2020-05-16 |         1         |
|     kushal    | 2020-05-15 |         1         |
|     karim     | 2020-05-14 |         1         |
|     satish    | 2020-05-12 |         1         |
|      sima     | 2020-05-11 |         1         |
|      sima     | 2020-05-11 |         2         |
+---------------+------------+-------------------+
Truncated to displaylimit of 10.

In [10]:
products = (
    products
    .sort_values(
        ['customer_name', 'order_date'],
        ascending = [True, False]
    )
)
products['serial_new_to_old'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products[
    ['customer_name', 'order_date', 'serial_new_to_old']
]

   customer_name  order_date  serial_new_to_old
8           jaya  2020-05-17                  1
5          karim  2020-05-14                  1
0          kiran  2020-05-09                  1
6         kushal  2020-05-15                  1
10      mahendra  2020-05-19                  1
9         manish  2020-05-18                  1
4         satish  2020-05-12                  1
3           sima  2020-05-11                  1
2           sima  2020-05-09                  2
1          sonam  2020-05-10                  1
7          sunam  2020-05-16                  1
11       sushant  2020-05-20                  1

<pre>Har product ke orders ko sabse kam discount se sabse zyada discount tak serial number do.</pre>

In [13]:
%%sql 
SELECT product_name, discount, 
ROW_NUMBER()
OVER(
    PARTITION BY product_name
    ORDER BY discount ASC
) AS discount_top_to_bottom
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+--------------+----------+------------------------+
| product_name | discount | discount_top_to_bottom |
+--------------+----------+------------------------+
|    bulps     |   2.00   |           1            |
|    bulps     |   2.00   |           2            |
|    chair     |   0.00   |           1            |
|    cooler    |  20.00   |           1            |
|     fan      |   2.00   |           1            |
|     fan      |   2.00   |           2            |
|     sopa     |  16.00   |           1            |
|     sopa     |  16.00   |           2            |
|     sopa     |  16.00   |           3            |
|    table     |   6.00   |           1            |
+--------------+----------+------------------------+
Truncated to displaylimit of 10.

In [14]:
products = (
    products
    .sort_values(
        ['product_name', 'discount'],
        ascending = [True, True]
    )
)
products['discount_top_to_bottom'] = (
    products
    .groupby('product_name')
    .cumcount()
    + 1
)
products[
    ['product_name', 'discount', 'discount_top_to_bottom']
]

   product_name  discount  discount_top_to_bottom
5         bulps         2                       1
7         bulps         2                       2
4         chair         0                       1
9        cooler        20                       1
6           fan         2                       1
1           fan         2                       2
3          sopa        16                       1
2          sopa        16                       2
11         sopa        16                       3
0         table         6                       1
10        table         6                       2
8         watch         2                       1

<pre>Har state me sabse mehange product ko 1 number milna chahiye, uske baad doosra mehanga product 2, aur aise hi aage.</pre>

In [28]:
%%sql 
SELECT order_state, product_price,
ROW_NUMBER()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC
) AS price_bottom_top
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+-------------+---------------+------------------+
| order_state | product_price | price_bottom_top |
+-------------+---------------+------------------+
|      BR     |     20.00     |        1         |
|      CN     |    2000.00    |        1         |
|      GJ     |    1200.00    |        1         |
|      JK     |     20.00     |        1         |
|      KR     |    4300.00    |        1         |
|      KR     |    2200.00    |        2         |
|      MH     |    2200.00    |        1         |
|      RJ     |    4300.00    |        1         |
|      RJ     |    4300.00    |        2         |
|      RJ     |    3200.00    |        3         |
+-------------+---------------+------------------+
Truncated to displaylimit of 10.

In [29]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price'],
        ascending = [True, False]
    )
)
products['price_bottom_top'] = (
    products
    .groupby('order_state')
    .cumcount()
    + 1
)
products[
    ['order_state', 'product_price', 'price_bottom_top']
]

   order_state  product_price  price_bottom_top
7           BR             20                 1
6           CN           2000                 1
4           GJ           1200                 1
5           JK             20                 1
11          KR           4300                 1
10          KR           2200                 2
0           MH           2200                 1
3           RJ           4300                 1
2           RJ           4300                 2
9           RJ           3200                 3
1           RJ           2000                 4
8           UP            220                 1

<pre>Har customer ne jis product ko sabse mehanga kharida hai, us order ko 1 number do.</pre>

In [30]:
%%sql 
SELECT customer_name, product_name, product_price,
ROW_NUMBER()
OVER(
    PARTITION BY customer_name
    ORDER BY product_price DESC
) AS order_bottom_top
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+---------------+--------------+---------------+------------------+
| customer_name | product_name | product_price | order_bottom_top |
+---------------+--------------+---------------+------------------+
|      jaya     |    watch     |     220.00    |        1         |
|     karim     |    bulps     |     20.00     |        1         |
|     kiran     |    table     |    2200.00    |        1         |
|     kushal    |     fan      |    2000.00    |        1         |
|    mahendra   |    table     |    2200.00    |        1         |
|     manish    |    cooler    |    3200.00    |        1         |
|     satish    |    chair     |    1200.00    |        1         |
|      sima     |     sopa     |    4300.00    |        1         |
|      sima     |     sopa     |    4300.00    |        2         |
|     sonam     |     fan      |    2000.00    |        1         |
+---------------+--------------+---------------+------------------+
Truncated to displaylimit of 10.

In [31]:
products = (
    products
    .sort_values(
        ['customer_name', 'product_price'],
        ascending = [True, False]
    )
)
products['order_bottom_top'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products[
    ['customer_name', 'product_name', 'product_price', 'order_bottom_top']
]

   customer_name product_name  product_price  order_bottom_top
8           jaya        watch            220                 1
5          karim        bulps             20                 1
0          kiran        table           2200                 1
6         kushal          fan           2000                 1
10      mahendra        table           2200                 1
9         manish       cooler           3200                 1
4         satish        chair           1200                 1
3           sima         sopa           4300                 1
2           sima         sopa           4300                 2
1          sonam          fan           2000                 1
7          sunam        bulps             20                 1
11       sushant         sopa           4300                 1

<pre>Har state ke orders ko order date ke hisaab se purane se naye tak serial number do.</pre>

In [20]:
%%sql 
SELECT order_state, order_date,
ROW_NUMBER()
OVER(
    PARTITION BY order_state
    ORDER BY order_date ASC
) AS old_new
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+-------------+------------+---------+
| order_state | order_date | old_new |
+-------------+------------+---------+
|      BR     | 2020-05-16 |    1    |
|      CN     | 2020-05-15 |    1    |
|      GJ     | 2020-05-12 |    1    |
|      JK     | 2020-05-14 |    1    |
|      KR     | 2020-05-19 |    1    |
|      KR     | 2020-05-20 |    2    |
|      MH     | 2020-05-09 |    1    |
|      RJ     | 2020-05-10 |    1    |
|      RJ     | 2020-05-11 |    2    |
|      RJ     | 2020-05-11 |    3    |
+-------------+------------+---------+
Truncated to displaylimit of 10.

In [21]:
products = (
    products
    .sort_values(
        ['order_state', 'order_date'],
        ascending = [True, True]
    )
)
products['old_new'] = (
    products
    .groupby('order_state')
    .cumcount()
    + 1
)
products[
    ['order_state', 'order_date', 'old_new']
]

   order_state  order_date  old_new
7           BR  2020-05-16        1
6           CN  2020-05-15        1
4           GJ  2020-05-12        1
5           JK  2020-05-14        1
10          KR  2020-05-19        1
11          KR  2020-05-20        2
0           MH  2020-05-09        1
2           RJ  2020-05-09        1
1           RJ  2020-05-10        2
3           RJ  2020-05-11        3
9           RJ  2020-05-18        4
8           UP  2020-05-17        1

<pre>Har product ke liye sabse recent order ko 1 number milna chahiye.</pre>

In [66]:
%%sql 
WITH ranked_orders AS (
    SELECT product_name, order_date,
    ROW_NUMBER()
    OVER(
        PARTITION BY product_name
        ORDER BY order_date DESC
    ) AS recent_order
    FROM products
)
SELECT product_name, order_date, recent_order
FROM ranked_orders
WHERE recent_order < 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+--------------+------------+--------------+
| product_name | order_date | recent_order |
+--------------+------------+--------------+
|    bulps     | 2020-05-16 |      1       |
|    chair     | 2020-05-12 |      1       |
|    cooler    | 2020-05-18 |      1       |
|     fan      | 2020-05-15 |      1       |
|     sopa     | 2020-05-20 |      1       |
|    table     | 2020-05-19 |      1       |
|    watch     | 2020-05-17 |      1       |
+--------------+------------+--------------+

In [22]:
products = (
    products
    .sort_values(
        ['product_name', 'order_date'],
        ascending = [True, False]
    )
)
products['recent_order'] = (
    products
    .groupby('product_name')
    .cumcount()
    + 1 
)
products.loc[
    products['recent_order'] == 1,
    ['product_name', 'order_date', 'recent_order']
]

   product_name  order_date  recent_order
7         bulps  2020-05-16             1
4         chair  2020-05-12             1
9        cooler  2020-05-18             1
6           fan  2020-05-15             1
11         sopa  2020-05-20             1
10        table  2020-05-19             1
8         watch  2020-05-17             1

<pre>Har state ke andar sabse zyada quantity wale order ko 1 number do.</pre>

In [ ]:
%%sql 
SELECT product_id AS order_id, order_state, product_quantity,
ROW_NUMBER()
OVER(
    PARTITION BY order_state
    ORDER BY product_quantity DESC
) AS most_quantity_by_order
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+----------+-------------+------------------+--------------------------+
| order_id | order_state | product_quantity | most_quantity_by_product |
+----------+-------------+------------------+--------------------------+
|    8     |      BR     |        10        |            1             |
|    7     |      CN     |        2         |            1             |
|    5     |      GJ     |        10        |            1             |
|    6     |      JK     |       100        |            1             |
|    11    |      KR     |        4         |            1             |
|    12    |      KR     |        2         |            2             |
|    1     |      MH     |        3         |            1             |
|    10    |      RJ     |        2         |            1             |
|    2     |      RJ     |        2         |            2             |
|    4     |      RJ     |        1         |            3             |
+----------+-------------+------------------+--------------------------+
Truncated to displaylimit of 10.

In [23]:
products = (
    products
    .sort_values(
        ['order_state', 'product_quantity'],
        ascending = [True, False]
    )
)
products['most_quantity_by_order'] = (
    products
    .groupby('order_state')
    .cumcount()
    + 1
)
products[
    ['product_id', 'order_state', 'product_quantity', 'most_quantity_by_order']
].rename(columns = {'product_id': 'order_id'})

    order_id order_state  product_quantity  most_quantity_by_order
7          8          BR                10                       1
6          7          CN                 2                       1
4          5          GJ                10                       1
5          6          JK               100                       1
10        11          KR                 4                       1
11        12          KR                 2                       2
0          1          MH                 3                       1
9         10          RJ                 2                       1
1          2          RJ                 2                       2
3          4          RJ                 1                       3
2          3          RJ                 1                       4
8          9          UP                 1                       1

<pre>Har customer ke orders ko sabse zyada discount se sabse kam discount tak serial number do.</pre>

In [65]:
%%sql 
SELECT customer_name, discount,
ROW_NUMBER()
OVER(
    PARTITION BY customer_name
    ORDER BY discount DESC
) AS discount_bottom_top
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+---------------+----------+---------------------+
| customer_name | discount | discount_bottom_top |
+---------------+----------+---------------------+
|      jaya     |   2.00   |          1          |
|     karim     |   2.00   |          1          |
|     kiran     |   6.00   |          1          |
|     kushal    |   2.00   |          1          |
|    mahendra   |   6.00   |          1          |
|     manish    |  20.00   |          1          |
|     satish    |   0.00   |          1          |
|      sima     |  16.00   |          1          |
|      sima     |  16.00   |          2          |
|     sonam     |   2.00   |          1          |
+---------------+----------+---------------------+
Truncated to displaylimit of 10.

In [25]:
products = (
    products
    .sort_values(
        ['customer_name', 'discount'],
        ascending = [True, False]
    )
)
products['discount_bottom_top'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products[
    ['customer_name', 'discount', 'discount_bottom_top']
]

   customer_name  discount  discount_bottom_top
8           jaya         2                    1
5          karim         2                    1
0          kiran         6                    1
6         kushal         2                    1
10      mahendra         6                    1
9         manish        20                    1
4         satish         0                    1
3           sima        16                    1
2           sima        16                    2
1          sonam         2                    1
7          sunam         2                    1
11       sushant        16                    1

<pre>Har state ke orders ko pehle product price (high to low) aur agar price same ho to order date (old to new) ke hisaab se serial number do.</pre>

In [33]:
%%sql 
SELECT order_state, product_price,
ROW_NUMBER()
OVER(
    PARTITION BY order_state
    ORDER BY product_price DESC, order_date ASC
) AS product_price_high_low
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+-------------+---------------+------------------------+
| order_state | product_price | product_price_high_low |
+-------------+---------------+------------------------+
|      BR     |     20.00     |           1            |
|      CN     |    2000.00    |           1            |
|      GJ     |    1200.00    |           1            |
|      JK     |     20.00     |           1            |
|      KR     |    4300.00    |           1            |
|      KR     |    2200.00    |           2            |
|      MH     |    2200.00    |           1            |
|      RJ     |    4300.00    |           1            |
|      RJ     |    4300.00    |           2            |
|      RJ     |    3200.00    |           3            |
+-------------+---------------+------------------------+
Truncated to displaylimit of 10.

In [47]:
products = (
    products
    .sort_values(
        ['order_state', 'product_price', 'order_date'],
        ascending=[True, False, True]
    )
)
products['price_high_to_low_if_same_date_old_to_new'] = (
    products
    .groupby('order_state')
    .cumcount()
    + 1
)
products[
    ['order_state', 'product_price', 'price_high_to_low_if_same_date_old_to_new']
]

   order_state  product_price  price_high_to_low_if_same_date_old_to_new
7           BR             20                                          1
6           CN           2000                                          1
4           GJ           1200                                          1
5           JK             20                                          1
11          KR           4300                                          1
10          KR           2200                                          2
0           MH           2200                                          1
2           RJ           4300                                          1
3           RJ           4300                                          2
9           RJ           3200                                          3
1           RJ           2000                                          4
8           UP            220                                          1

<pre>Har customer ke orders ko pehle quantity (high to low), aur agar quantity same ho to discount (high to low) ke hisaab se serial number do.</pre>

In [53]:
%%sql 
SELECT customer_name, product_quantity,
ROW_NUMBER()
OVER(
    PARTITION BY customer_name
    ORDER BY product_quantity DESC, discount DESC
) AS quantity_high_to_low_if_same_discount_high_to_low
FROM products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+---------------+------------------+---------------------------------------------------+
| customer_name | product_quantity | quantity_high_to_low_if_same_discount_high_to_low |
+---------------+------------------+---------------------------------------------------+
|      jaya     |        1         |                         1                         |
|     karim     |       100        |                         1                         |
|     kiran     |        3         |                         1                         |
|     kushal    |        2         |                         1                         |
|    mahendra   |        4         |                         1                         |
|     manish    |        2         |                         1                         |
|     satish    |        10        |                         1                         |
|      sima     |        1         |                         1                         |
|      sima     |        1         |                         2                         |
|     sonam     |        2         |                         1                         |
+---------------+------------------+---------------------------------------------------+
Truncated to displaylimit of 10.

In [50]:
products = (
    products
    .sort_values(
        ['customer_name', 'product_quantity', 'discount'],
        ascending = (True, False, False)
    )
)
products['quantity_high_to_low_if_same_discount_high_to_low'] = (
    products
    .groupby('customer_name')
    .cumcount()
    + 1
)
products[
    ['customer_name', 'product_quantity', 'quantity_high_to_low_if_same_discount_high_to_low']
]

,customer_name,product_quantity,quantity_high_to_low_if_same_discount_high_to_low
8,jaya,1,1
5,karim,100,1
0,kiran,3,1
6,kushal,2,1
10,mahendra,4,1
9,manish,2,1
4,satish,10,1
2,sima,1,1
3,sima,1,2
1,sonam,2,1
7,sunam,10,1
11,sushant,2,1

In [51]:
products.head(1)

,product_id,product_name,order_date,customer_name,order_state,product_price,product_quantity,discount,gross_amount,net_amount,price_high_to_low_if_same_date_old_to_new,quantity_high_to_low_if_same_discount_high_to_low
8,9,watch,2020-05-17,jaya,UP,220,1,2,220,215.6,1,1

In [45]:
products.drop('quantity_high_low', axis=1, inplace=True)