In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:passwordr@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd
import numpy as np

products = pd.read_csv(r"d:\SQL\data generator\output\products.csv")
order_items = pd.read_csv(r"d:\SQL\data generator\output\order_items.csv")
orders = pd.read_csv(r"d:\SQL\data generator\output\orders.csv", parse_dates=['order_date'])
customers = pd.read_csv(r"d:\SQL\data generator\output\customers.csv")

From the orders table, find the **total number of orders** and **the number of orders that have the status 'Delivered'.** Return both values in a single row.

In [11]:
%%sql 
SELECT COUNT(order_id) AS total_orders,
    COUNT(order_id) FILTER (WHERE order_status = 'completed') AS delivered_orders
FROM retail_analysis.orders

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------+------------------+
| total_orders | delivered_orders |
+--------------+------------------+
|     1000     |       678        |
+--------------+------------------+

In [5]:
%%sql 
SELECT COUNT(order_id) AS total_orders,
    SUM(CASE WHEN order_status = 'completed' THEN 1 ELSE 0 END) AS completed_orders
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------+------------------+
| total_orders | completed_orders |
+--------------+------------------+
|     1000     |       678        |
+--------------+------------------+

In [6]:
pd.DataFrame({
    'total_orders' : [orders['order_id'].count()],
    'completed_orders' : [orders['order_status'].eq('completed').sum()]
})

   total_orders  completed_orders
0          1000               678

Exercise — Conditional Aggregation

From the orders table, find the total number of orders and the number of orders where the `payment_mode` is '*UPI*'. Return both values in a single row.

In [8]:
%%sql 
SELECT COUNT(order_id) AS total_orders, 
    COUNT(order_id) FILTER (WHERE payment_mode = 'upi') AS total_upi_payment
FROM retail_analysis.orders

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------+-------------------+
| total_orders | total_upi_payment |
+--------------+-------------------+
|     1000     |        305        |
+--------------+-------------------+

In [10]:
%%sql 
SELECT COUNT(order_id) AS total_orders,
    SUM(CASE WHEN payment_mode = 'upi' THEN 1 ELSE 0 END) AS total_upi_payment
FROM retail_analysis.orders

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------+-------------------+
| total_orders | total_upi_payment |
+--------------+-------------------+
|     1000     |        305        |
+--------------+-------------------+

In [12]:
pd.DataFrame({
    'total_orders' : [orders['order_id'].count()],
    'total_upi_payment' : [orders['payment_mode'].eq('upi').sum()]
})

   total_orders  total_upi_payment
0          1000                305

### **GREASTED()**

In [40]:
%%sql
SELECT GREATEST(10, 25, 15);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+----------+
| greatest |
+----------+
|    25    |
+----------+

Question:

From the products table, display `product_id`, `cost_price`, and `selling_price`, and create a new column called `higher_price` that contains the **higher value between `cost_price` and `selling_price`**.

In [20]:
%%sql
SELECT product_id, cost_price, selling_price,
    GREATEST(cost_price, selling_price) AS highest_price
FROM retail_analysis.products

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+------------+---------------+---------------+
| product_id | cost_price | selling_price | highest_price |
+------------+------------+---------------+---------------+
|   P_ID01   |  25000.00  |    30000.00   |    30000.00   |
|   P_ID02   |  75000.00  |    90000.00   |    90000.00   |
|   P_ID03   |  10333.00  |    12400.00   |    12400.00   |
|   P_ID04   |  16458.00  |    19750.00   |    19750.00   |
|   P_ID05   |  4479.00   |    5375.00    |    5375.00    |
|   P_ID06   |   512.00   |     615.00    |     615.00    |
|   P_ID07   |   375.00   |     450.00    |     450.00    |
|   P_ID08   |   187.00   |     225.00    |     225.00    |
|   P_ID09   |  1645.00   |    1975.00    |    1975.00    |
|   P_ID10   |  1254.00   |    1505.00    |    1505.00    |
+------------+------------+---------------+---------------+
Truncated to displaylimit of 10.

axis=0 → नीचे की तरफ → rows को aggregate करो \
axis=1 → बगल में → columns को aggregate करो

In [30]:

result = products[
    ['product_id', 'cost_price', 'selling_price']
]
result['highest_price'] = result[['cost_price', 'selling_price']].max(axis=1)
result.head()

  product_id  cost_price  selling_price  highest_price
0     P_ID01       25000          30000          30000
1     P_ID02       75000          90000          90000
2     P_ID03       10333          12400          12400
3     P_ID04       16458          19750          19750
4     P_ID05        4479           5375           5375

Exercise — GREATEST()

From the products table, display `product_id`, `cost_price`, and `selling_price`. Create a new column called `maximum_price` that **contains the higher price between** `cost_price` and `selling_price`.

In [33]:
%%sql 
SELECT product_id, cost_price, selling_price,
    GREATEST(cost_price, selling_price) AS maximum_price
FROM retail_analysis.products

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+------------+---------------+---------------+
| product_id | cost_price | selling_price | maximum_price |
+------------+------------+---------------+---------------+
|   P_ID01   |  25000.00  |    30000.00   |    30000.00   |
|   P_ID02   |  75000.00  |    90000.00   |    90000.00   |
|   P_ID03   |  10333.00  |    12400.00   |    12400.00   |
|   P_ID04   |  16458.00  |    19750.00   |    19750.00   |
|   P_ID05   |  4479.00   |    5375.00    |    5375.00    |
|   P_ID06   |   512.00   |     615.00    |     615.00    |
|   P_ID07   |   375.00   |     450.00    |     450.00    |
|   P_ID08   |   187.00   |     225.00    |     225.00    |
|   P_ID09   |  1645.00   |    1975.00    |    1975.00    |
|   P_ID10   |  1254.00   |    1505.00    |    1505.00    |
+------------+------------+---------------+---------------+
Truncated to displaylimit of 10.

In [41]:
result = products[
    ['product_id', 'cost_price', 'selling_price']
]
result['maximum_price'] = result[['cost_price', 'selling_price']].max(axis=1)
result.head()

  product_id  cost_price  selling_price  maximum_price
0     P_ID01       25000          30000          30000
1     P_ID02       75000          90000          90000
2     P_ID03       10333          12400          12400
3     P_ID04       16458          19750          19750
4     P_ID05        4479           5375           5375

### **LEAST()**

Exercise — LEAST()

From the products table, display `product_id`, `cost_price`, and `selling_price`. Create a new column called `lowest_price` that **contains the lower value between `cost_price` and `selling_price`.**

In [47]:
%%sql 
SELECT product_id, cost_price, selling_price, 
    LEAST(cost_price, selling_price) AS lowest_price
FROM retail_analysis.products

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+------------+---------------+--------------+
| product_id | cost_price | selling_price | lowest_price |
+------------+------------+---------------+--------------+
|   P_ID01   |  25000.00  |    30000.00   |   25000.00   |
|   P_ID02   |  75000.00  |    90000.00   |   75000.00   |
|   P_ID03   |  10333.00  |    12400.00   |   10333.00   |
|   P_ID04   |  16458.00  |    19750.00   |   16458.00   |
|   P_ID05   |  4479.00   |    5375.00    |   4479.00    |
|   P_ID06   |   512.00   |     615.00    |    512.00    |
|   P_ID07   |   375.00   |     450.00    |    375.00    |
|   P_ID08   |   187.00   |     225.00    |    187.00    |
|   P_ID09   |  1645.00   |    1975.00    |   1645.00    |
|   P_ID10   |  1254.00   |    1505.00    |   1254.00    |
+------------+------------+---------------+--------------+
Truncated to displaylimit of 10.

In [51]:
result = products[
    ['product_id', 'cost_price', 'selling_price']
]
result['lowest_price'] = result[['cost_price', 'selling_price']].min(axis=1)
result.head()

  product_id  cost_price  selling_price  lowest_price
0     P_ID01       25000          30000         25000
1     P_ID02       75000          90000         75000
2     P_ID03       10333          12400         10333
3     P_ID04       16458          19750         16458
4     P_ID05        4479           5375          4479

ROLLUP — Exercise 1

Question:

From the products table, calculate the total `selling_price` for each `category` and `brand`. Also **include a subtotal for each category** and a **grand total for all products**. Use ROLLUP.

In [59]:
%%sql 
SELECT category, brand, SUM(selling_price) AS total_selling_price
FROM retail_analysis.products
GROUP BY ROLLUP(category, brand)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

30 rows affected.

+----------------+---------+---------------------+
|    category    |  brand  | total_selling_price |
+----------------+---------+---------------------+
|      None      |   None  |      262098.00      |
|  Electronics   | Samsung |       6880.00       |
| Home & Kitchen |  Cello  |        780.00       |
|  Electronics   |   Asus  |       9225.00       |
|    Clothing    |   Zara  |       1100.00       |
| Home & Kitchen | Hawkins |       13020.00      |
|  Electronics   |   Acer  |       10150.00      |
|  Electronics   |  Lenovo |       23700.00      |
|    Clothing    |   Puma  |       3977.00       |
|    Clothing    |  Adidas |        900.00       |
+----------------+---------+---------------------+
Truncated to displaylimit of 10.

In [61]:
%%sql
SELECT
    COALESCE(category, 'Grand Total') AS category,
    COALESCE(brand, 'Total') AS brand,
    SUM(selling_price) AS total_selling_price
FROM retail_analysis.products
GROUP BY ROLLUP(category, brand);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

30 rows affected.

+----------------+---------+---------------------+
|    category    |  brand  | total_selling_price |
+----------------+---------+---------------------+
|  Grand Total   |  Total  |      262098.00      |
|  Electronics   | Samsung |       6880.00       |
| Home & Kitchen |  Cello  |        780.00       |
|  Electronics   |   Asus  |       9225.00       |
|    Clothing    |   Zara  |       1100.00       |
| Home & Kitchen | Hawkins |       13020.00      |
|  Electronics   |   Acer  |       10150.00      |
|  Electronics   |  Lenovo |       23700.00      |
|    Clothing    |   Puma  |       3977.00       |
|    Clothing    |  Adidas |        900.00       |
+----------------+---------+---------------------+
Truncated to displaylimit of 10.

In [63]:
%%sql 
SELECT category, brand, SUM(selling_price) AS total_selling_price
FROM retail_analysis.products
GROUP BY CUBE(category, brand)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

56 rows affected.

+----------------+---------+---------------------+
|    category    |  brand  | total_selling_price |
+----------------+---------+---------------------+
|      None      |   None  |      262098.00      |
|  Electronics   | Samsung |       6880.00       |
| Home & Kitchen |  Cello  |        780.00       |
|  Electronics   |   Asus  |       9225.00       |
|    Clothing    |   Zara  |       1100.00       |
| Home & Kitchen | Hawkins |       13020.00      |
|  Electronics   |   Acer  |       10150.00      |
|  Electronics   |  Lenovo |       23700.00      |
|    Clothing    |   Puma  |       3977.00       |
|    Clothing    |  Adidas |        900.00       |
+----------------+---------+---------------------+
Truncated to displaylimit of 10.

In [43]:
%%sql
SELECT LEAST(10, 25, 15);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------+
| least |
+-------+
|   10  |
+-------+

In [16]:
orders.head(1)

,order_id,customer_id,login_date,order_status,order_date,logout_date,delivery_date,payment_mode,time_zone
0,ord_id1,cust_id79,2020-01-01 06:59:27,cancelled,2020-01-01 10:20:46,2020-01-01 11:35:55,2020-01-05 14:57:53,NaN,Asia/Kolkata