In [1]:
print('welcome')

welcome

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:passwor@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

### **DATE TIME**

In [11]:
%%sql 
CREATE TABLE retail_analysis.customers(
    customer_id VARCHAR(20) PRIMARY KEY,
    customer_name VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL, 
    join_date DATE NOT NULL
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

++
||
++
++

In [12]:
%%sql 
CREATE TABLE retail_analysis.orders (
    order_id VARCHAR(20) PRIMARY KEY,
    customer_id VARCHAR(20) NOT NULL,
    login_date TIMESTAMP NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    order_date TIMESTAMP NOT NULL,
    logout_date TIMESTAMP NOT NULL,
    delivery_date TIMESTAMP,
    payment_mode VARCHAR(20),
    time_zone VARCHAR(50) NOT NULL,

    FOREIGN KEY (customer_id)
    REFERENCES retail_analysis.customers(customer_id)
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

++
||
++
++

In [17]:
import pandas as pd
import numpy as np

In [18]:
customers = pd.read_csv(r'd:\SQL\data generator\output\customers.csv', parse_dates = ['birth_date', 'join_date'])
orders = pd.read_csv(r'd:\SQL\data generator\output\orders.csv', parse_dates=['login_date', 'order_date', 'logout_date', 'delivery_date'])
products = pd.read_csv(r'd:\SQL\data generator\output\products.csv')
order_items = pd.read_csv(r'd:\SQL\data generator\output\order_items.csv')

Date & Time Analysis — Question 1

Find the `customer_name` and their **age in years** as of today using `birth_date`. Use PostgreSQL date/time functions.

In [22]:
%%sql 
SELECT customer_name, EXTRACT(YEAR FROM AGE(birth_date)) AS age
FROM retail_analysis.customers;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+---------------------+-----+
|    customer_name    | age |
+---------------------+-----+
|      Ikbal Dani     |  49 |
|      Oni Bobal      |  41 |
|   Garima Narayanan  |  68 |
|   Rachana Bhardwaj  |  40 |
|   Meghana Prakash   |  20 |
|     Maanas Madan    |  41 |
|     Ayaan Thaker    |  47 |
|    Harini Sharma    |  28 |
| Gayathri Srinivasan |  24 |
|      Ishwar Oak     |  71 |
+---------------------+-----+
Truncated to displaylimit of 10.

In [12]:
customers['age'] = (
    pd.Timestamp.today().year -
    customers['birth_date'].dt.year
)
customers[['customer_name', 'age']]

       customer_name  age
0         Ikbal Dani   49
1          Oni Bobal   41
2   Garima Narayanan   68
3   Rachana Bhardwaj   40
4    Meghana Prakash   20
..               ...  ...
95  Vasatika Agarwal   40
96   Darpan Chaudhry   59
97      Abhiram Garg   59
98      Varsha Misra   32
99      Watika Kapur   49

[100 rows x 2 columns]

In [15]:
today = pd.Timestamp.today()

customers['age'] = (
    today.year
    - customers['birth_date'].dt.year
    - (
        (customers['birth_date'].dt.month > today.month)
        |
        (
            (customers['birth_date'].dt.month == today.month)
            & (customers['birth_date'].dt.day > today.day)
        )
    )
)

customers[['customer_name', 'age']]

       customer_name  age
0         Ikbal Dani   49
1          Oni Bobal   41
2   Garima Narayanan   68
3   Rachana Bhardwaj   40
4    Meghana Prakash   20
..               ...  ...
95  Vasatika Agarwal   40
96   Darpan Chaudhry   59
97      Abhiram Garg   59
98      Varsha Misra   32
99      Watika Kapur   49

[100 rows x 2 columns]

In [11]:
customers['age'] =(
    pd.Timestamp.today() - customers['birth_date']
).dt.days // 365
customers[['customer_name', 'age']]

       customer_name  age
0         Ikbal Dani   49
1          Oni Bobal   41
2   Garima Narayanan   68
3   Rachana Bhardwaj   40
4    Meghana Prakash   20
..               ...  ...
95  Vasatika Agarwal   40
96   Darpan Chaudhry   59
97      Abhiram Garg   59
98      Varsha Misra   32
99      Watika Kapur   49

[100 rows x 2 columns]

Next Question

Find each customer's `customer_name` and the number of complete years they have been a customer, calculated from `join_date` up to today. Use PostgreSQL date/time functions.

In [ ]:
%%sql 
SELECT customer_name, EXTRACT(YEAR FROM AGE(join_date)) AS years_of_customer
FROM retail_analysis.customers;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+------------------+-------------------+
|  customer_name   | years_of_customer |
+------------------+-------------------+
|    Abdul Sule    |         6         |
|   Watika Kapur   |         6         |
|   Abhiram Garg   |         6         |
| Darpan Chaudhry  |         6         |
| Vasatika Agarwal |         6         |
|   Wishi Chahal   |         6         |
|  Chakrika Madan  |         6         |
|   Varsha Misra   |         6         |
|   Brinda Naidu   |         7         |
| Mohini Banerjee  |         7         |
+------------------+-------------------+
Truncated to displaylimit of 10.

Next Question

For **each order**, display `order_id`, `order_date`, and the **year, month, and day** of the **order** separately. Use EXTRACT().

In [36]:
%%sql 
SELECT order_id, order_date,
    EXTRACT(YEAR FROM order_date) AS year,
    EXTRACT(MONTH FROM order_date) AS month,
    EXTRACT(DAY FROM order_date) AS day
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+------+-------+-----+
| order_id |      order_date     | year | month | day |
+----------+---------------------+------+-------+-----+
| ord_id1  | 2020-01-01 10:20:46 | 2020 |   1   |  1  |
| ord_id2  | 2020-01-05 23:47:55 | 2020 |   1   |  5  |
| ord_id3  | 2020-01-06 15:23:36 | 2020 |   1   |  6  |
| ord_id4  | 2020-01-08 08:45:37 | 2020 |   1   |  8  |
| ord_id5  | 2020-01-08 20:11:06 | 2020 |   1   |  8  |
| ord_id6  | 2020-01-09 13:11:52 | 2020 |   1   |  9  |
| ord_id7  | 2020-01-13 23:10:04 | 2020 |   1   |  13 |
| ord_id8  | 2020-01-18 00:11:54 | 2020 |   1   |  18 |
| ord_id9  | 2020-01-18 02:16:37 | 2020 |   1   |  18 |
| ord_id10 | 2020-01-21 12:51:09 | 2020 |   1   |  21 |
+----------+---------------------+------+-------+-----+
Truncated to displaylimit of 10.

In [19]:
orders['year'] = orders['order_date'].dt.year
orders['month'] = orders['order_date'].dt.month
orders['day'] = orders['order_date'].dt.day
orders[['order_id', 'order_date', 'year', 'month', 'day']]

       order_id          order_date  year  month  day
0       ord_id1 2020-01-01 10:20:46  2020      1    1
1       ord_id2 2020-01-05 23:47:55  2020      1    5
2       ord_id3 2020-01-06 15:23:36  2020      1    6
3       ord_id4 2020-01-08 08:45:37  2020      1    8
4       ord_id5 2020-01-08 20:11:06  2020      1    8
..          ...                 ...   ...    ...  ...
995   ord_id996 2025-12-21 23:08:50  2025     12   21
996   ord_id997 2025-12-24 07:39:12  2025     12   24
997   ord_id998 2025-12-27 00:34:40  2025     12   27
998   ord_id999 2025-12-27 15:01:38  2025     12   27
999  ord_id1000 2025-12-30 22:57:38  2025     12   30

[1000 rows x 5 columns]

Next Question

For **each order**, display `order_id`, `order_date`, and the **hour, minute, and second** when the order was placed. Use EXTRACT().

In [39]:
%%sql 
SELECT order_id, order_date,
    EXTRACT(HOUR FROM order_date) AS hours,
    EXTRACT(MINUTE FROM order_date) AS minute,
    EXTRACT(SECOND FROM order_date) AS second
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+-------+--------+-----------+
| order_id |      order_date     | hours | minute |   second  |
+----------+---------------------+-------+--------+-----------+
| ord_id1  | 2020-01-01 10:20:46 |   10  |   20   | 46.000000 |
| ord_id2  | 2020-01-05 23:47:55 |   23  |   47   | 55.000000 |
| ord_id3  | 2020-01-06 15:23:36 |   15  |   23   | 36.000000 |
| ord_id4  | 2020-01-08 08:45:37 |   8   |   45   | 37.000000 |
| ord_id5  | 2020-01-08 20:11:06 |   20  |   11   |  6.000000 |
| ord_id6  | 2020-01-09 13:11:52 |   13  |   11   | 52.000000 |
| ord_id7  | 2020-01-13 23:10:04 |   23  |   10   |  4.000000 |
| ord_id8  | 2020-01-18 00:11:54 |   0   |   11   | 54.000000 |
| ord_id9  | 2020-01-18 02:16:37 |   2   |   16   | 37.000000 |
| ord_id10 | 2020-01-21 12:51:09 |   12  |   51   |  9.000000 |
+----------+---------------------+-------+--------+-----------+
Truncated to displaylimit of 10.

In [25]:
orders['hours'] = orders['order_date'].dt.hour
orders['minute'] = orders['order_date'].dt.minute
orders['second'] = orders['order_date'].dt.second
orders[['order_id', 'order_date', 'hours', 'minute', 'second']]

       order_id          order_date  hours  minute  second
0       ord_id1 2020-01-01 10:20:46     10      20      46
1       ord_id2 2020-01-05 23:47:55     23      47      55
2       ord_id3 2020-01-06 15:23:36     15      23      36
3       ord_id4 2020-01-08 08:45:37      8      45      37
4       ord_id5 2020-01-08 20:11:06     20      11       6
..          ...                 ...    ...     ...     ...
995   ord_id996 2025-12-21 23:08:50     23       8      50
996   ord_id997 2025-12-24 07:39:12      7      39      12
997   ord_id998 2025-12-27 00:34:40      0      34      40
998   ord_id999 2025-12-27 15:01:38     15       1      38
999  ord_id1000 2025-12-30 22:57:38     22      57      38

[1000 rows x 5 columns]

Next Question

For **each order**, calculate **how much time passed between order_date and delivery_date**. Display `order_id`, `order_date`, `delivery_date`, and the `delivery duration`. Use PostgreSQL date/time functions.

In [52]:
%%sql 
SELECT order_id, order_date, delivery_date,
    AGE(delivery_date, order_date) AS delivery_duration
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+---------------------+-------------------+
| order_id |      order_date     |    delivery_date    | delivery_duration |
+----------+---------------------+---------------------+-------------------+
| ord_id1  | 2020-01-01 10:20:46 | 2020-01-05 14:57:53 |  4 days, 4:37:07  |
| ord_id2  | 2020-01-05 23:47:55 | 2020-01-16 07:52:38 |  10 days, 8:04:43 |
| ord_id3  | 2020-01-06 15:23:36 | 2020-01-08 11:08:33 |  1 day, 19:44:57  |
| ord_id4  | 2020-01-08 08:45:37 | 2020-01-16 10:14:19 |  8 days, 1:28:42  |
| ord_id5  | 2020-01-08 20:11:06 | 2020-01-20 04:51:13 |  11 days, 8:40:07 |
| ord_id6  | 2020-01-09 13:11:52 | 2020-01-20 12:15:55 | 10 days, 23:04:03 |
| ord_id7  | 2020-01-13 23:10:04 | 2020-01-25 05:14:42 |  11 days, 6:04:38 |
| ord_id8  | 2020-01-18 00:11:54 | 2020-01-29 15:42:41 | 11 days, 15:30:47 |
| ord_id9  | 2020-01-18 02:16:37 | 2020-01-27 01:45:17 |  8 days, 23:28:40 |
| ord_id10 | 2020-01-21 12:51:09 | 2020-01-29 21:07:15 |  8 days, 8:16:06  |
+----------+---------------------+---------------------+-------------------+
Truncated to displaylimit of 10.

In [29]:
orders['delivery_duration'] = (
    orders['delivery_date'] - orders['order_date']
)
orders[['order_id', 'order_date', 'delivery_date', 'delivery_duration']]

       order_id          order_date       delivery_date delivery_duration
0       ord_id1 2020-01-01 10:20:46 2020-01-05 14:57:53   4 days 04:37:07
1       ord_id2 2020-01-05 23:47:55 2020-01-16 07:52:38  10 days 08:04:43
2       ord_id3 2020-01-06 15:23:36 2020-01-08 11:08:33   1 days 19:44:57
3       ord_id4 2020-01-08 08:45:37 2020-01-16 10:14:19   8 days 01:28:42
4       ord_id5 2020-01-08 20:11:06 2020-01-20 04:51:13  11 days 08:40:07
..          ...                 ...                 ...               ...
995   ord_id996 2025-12-21 23:08:50 2025-12-29 09:12:34   7 days 10:03:44
996   ord_id997 2025-12-24 07:39:12 2025-12-31 16:07:38   7 days 08:28:26
997   ord_id998 2025-12-27 00:34:40                 NaT               NaT
998   ord_id999 2025-12-27 15:01:38 2026-01-05 16:23:52   9 days 01:22:14
999  ord_id1000 2025-12-30 22:57:38 2026-01-09 16:56:02   9 days 17:58:24

[1000 rows x 4 columns]

Next Question

For **each order**, calculate the **total delivery time in hours** between `order_date` and `delivery_date`. Display `order_id` and **delivery_hours**. Use PostgreSQL date/time functions.

In [74]:
%%sql 
SELECT order_date, delivery_date, order_id,
    EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 3600 AS delivery_hours
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+---------------------+---------------------+----------+----------------------+
|      order_date     |    delivery_date    | order_id |    delivery_hours    |
+---------------------+---------------------+----------+----------------------+
| 2020-01-01 10:20:46 | 2020-01-05 14:57:53 | ord_id1  | 100.6186111111111111 |
| 2020-01-05 23:47:55 | 2020-01-16 07:52:38 | ord_id2  | 248.0786111111111111 |
| 2020-01-06 15:23:36 | 2020-01-08 11:08:33 | ord_id3  | 43.7491666666666667  |
| 2020-01-08 08:45:37 | 2020-01-16 10:14:19 | ord_id4  | 193.4783333333333333 |
| 2020-01-08 20:11:06 | 2020-01-20 04:51:13 | ord_id5  | 272.6686111111111111 |
| 2020-01-09 13:11:52 | 2020-01-20 12:15:55 | ord_id6  | 263.0675000000000000 |
| 2020-01-13 23:10:04 | 2020-01-25 05:14:42 | ord_id7  | 270.0772222222222222 |
| 2020-01-18 00:11:54 | 2020-01-29 15:42:41 | ord_id8  | 279.5130555555555556 |
| 2020-01-18 02:16:37 | 2020-01-27 01:45:17 | ord_id9  | 215.4777777777777778 |
| 2020-01-21 12:51:09 | 2020-01-29 21:07:15 | ord_id10 | 200.2683333333333333 |
+---------------------+---------------------+----------+----------------------+
Truncated to displaylimit of 10.

In [33]:
orders['delivery_hours'] = (
    ((orders['delivery_date'] - orders['order_date']).dt.total_seconds())/3600
)
orders[['order_date', 'delivery_date', 'order_id', 'delivery_hours']]

             order_date       delivery_date    order_id  delivery_hours
0   2020-01-01 10:20:46 2020-01-05 14:57:53     ord_id1      100.618611
1   2020-01-05 23:47:55 2020-01-16 07:52:38     ord_id2      248.078611
2   2020-01-06 15:23:36 2020-01-08 11:08:33     ord_id3       43.749167
3   2020-01-08 08:45:37 2020-01-16 10:14:19     ord_id4      193.478333
4   2020-01-08 20:11:06 2020-01-20 04:51:13     ord_id5      272.668611
..                  ...                 ...         ...             ...
995 2025-12-21 23:08:50 2025-12-29 09:12:34   ord_id996      178.062222
996 2025-12-24 07:39:12 2025-12-31 16:07:38   ord_id997      176.473889
997 2025-12-27 00:34:40                 NaT   ord_id998             NaN
998 2025-12-27 15:01:38 2026-01-05 16:23:52   ord_id999      217.370556
999 2025-12-30 22:57:38 2026-01-09 16:56:02  ord_id1000      233.973333

[1000 rows x 4 columns]

In [36]:
orders['delivery_hours'] = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(3600)
orders[['order_date', 'delivery_date', 'order_id', 'delivery_hours']]

             order_date       delivery_date    order_id  delivery_hours
0   2020-01-01 10:20:46 2020-01-05 14:57:53     ord_id1      100.618611
1   2020-01-05 23:47:55 2020-01-16 07:52:38     ord_id2      248.078611
2   2020-01-06 15:23:36 2020-01-08 11:08:33     ord_id3       43.749167
3   2020-01-08 08:45:37 2020-01-16 10:14:19     ord_id4      193.478333
4   2020-01-08 20:11:06 2020-01-20 04:51:13     ord_id5      272.668611
..                  ...                 ...         ...             ...
995 2025-12-21 23:08:50 2025-12-29 09:12:34   ord_id996      178.062222
996 2025-12-24 07:39:12 2025-12-31 16:07:38   ord_id997      176.473889
997 2025-12-27 00:34:40                 NaT   ord_id998             NaN
998 2025-12-27 15:01:38 2026-01-05 16:23:52   ord_id999      217.370556
999 2025-12-30 22:57:38 2026-01-09 16:56:02  ord_id1000      233.973333

[1000 rows x 4 columns]

Next Question

For **each order**, calculate the **total delivery time in days**, **including fractional days**. Display `order_id` and `delivery_days`. Use PostgreSQL date/time functions.

In [8]:
%%sql 
SELECT order_id, delivery_date, order_date,
    EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+---------------------+---------------------+
| order_id |    delivery_date    |      order_date     |    delivery_days    |
+----------+---------------------+---------------------+---------------------+
| ord_id1  | 2020-01-05 14:57:53 | 2020-01-01 10:20:46 |  4.1924421296296296 |
| ord_id2  | 2020-01-16 07:52:38 | 2020-01-05 23:47:55 | 10.3366087962962963 |
| ord_id3  | 2020-01-08 11:08:33 | 2020-01-06 15:23:36 |  1.8228819444444444 |
| ord_id4  | 2020-01-16 10:14:19 | 2020-01-08 08:45:37 |  8.0615972222222222 |
| ord_id5  | 2020-01-20 04:51:13 | 2020-01-08 20:11:06 | 11.3611921296296296 |
| ord_id6  | 2020-01-20 12:15:55 | 2020-01-09 13:11:52 | 10.9611458333333333 |
| ord_id7  | 2020-01-25 05:14:42 | 2020-01-13 23:10:04 | 11.2532175925925926 |
| ord_id8  | 2020-01-29 15:42:41 | 2020-01-18 00:11:54 | 11.6463773148148148 |
| ord_id9  | 2020-01-27 01:45:17 | 2020-01-18 02:16:37 |  8.9782407407407407 |
| ord_id10 | 2020-01-29 21:07:15 | 2020-01-21 12:51:09 |  8.3445138888888889 |
+----------+---------------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [37]:
orders['delivery_days'] = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(86400)
orders[['order_id', 'delivery_date', 'order_date', 'delivery_days']]

       order_id       delivery_date          order_date  delivery_days
0       ord_id1 2020-01-05 14:57:53 2020-01-01 10:20:46       4.192442
1       ord_id2 2020-01-16 07:52:38 2020-01-05 23:47:55      10.336609
2       ord_id3 2020-01-08 11:08:33 2020-01-06 15:23:36       1.822882
3       ord_id4 2020-01-16 10:14:19 2020-01-08 08:45:37       8.061597
4       ord_id5 2020-01-20 04:51:13 2020-01-08 20:11:06      11.361192
..          ...                 ...                 ...            ...
995   ord_id996 2025-12-29 09:12:34 2025-12-21 23:08:50       7.419259
996   ord_id997 2025-12-31 16:07:38 2025-12-24 07:39:12       7.353079
997   ord_id998                 NaT 2025-12-27 00:34:40            NaN
998   ord_id999 2026-01-05 16:23:52 2025-12-27 15:01:38       9.057106
999  ord_id1000 2026-01-09 16:56:02 2025-12-30 22:57:38       9.748889

[1000 rows x 4 columns]

For each order, 
find the **day of the week on which the order was placed**. 
Display `order_id`, `order_date`, and the **day name such as Monday, Tuesday**, etc. Use PostgreSQL date/time functions.

In [ ]:
%%sql 
SELECT order_id, order_date, TO_CHAR(order_date::DATE, 'Day') AS day
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+-----------+
| order_id |      order_date     |    day    |
+----------+---------------------+-----------+
| ord_id1  | 2020-01-01 10:20:46 | Wednesday |
| ord_id2  | 2020-01-05 23:47:55 | Sunday    |
| ord_id3  | 2020-01-06 15:23:36 | Monday    |
| ord_id4  | 2020-01-08 08:45:37 | Wednesday |
| ord_id5  | 2020-01-08 20:11:06 | Wednesday |
| ord_id6  | 2020-01-09 13:11:52 | Thursday  |
| ord_id7  | 2020-01-13 23:10:04 | Monday    |
| ord_id8  | 2020-01-18 00:11:54 | Saturday  |
| ord_id9  | 2020-01-18 02:16:37 | Saturday  |
| ord_id10 | 2020-01-21 12:51:09 | Tuesday   |
+----------+---------------------+-----------+
Truncated to displaylimit of 10.

In [41]:
orders['day'] = (
    orders['order_date'].dt.day_name()
)
orders[['order_id', 'order_date', 'day']]

       order_id          order_date        day
0       ord_id1 2020-01-01 10:20:46  Wednesday
1       ord_id2 2020-01-05 23:47:55     Sunday
2       ord_id3 2020-01-06 15:23:36     Monday
3       ord_id4 2020-01-08 08:45:37  Wednesday
4       ord_id5 2020-01-08 20:11:06  Wednesday
..          ...                 ...        ...
995   ord_id996 2025-12-21 23:08:50     Sunday
996   ord_id997 2025-12-24 07:39:12  Wednesday
997   ord_id998 2025-12-27 00:34:40   Saturday
998   ord_id999 2025-12-27 15:01:38   Saturday
999  ord_id1000 2025-12-30 22:57:38    Tuesday

[1000 rows x 3 columns]

For **each order**, find the **week number of the year in which the order was placed.** 
Display `order_id`, `order_date`, and `week_number`. 
Use EXTRACT().

In [18]:
%%sql  
SELECT order_id, order_date, EXTRACT(WEEK FROM order_date) AS week_number
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+-------------+
| order_id |      order_date     | week_number |
+----------+---------------------+-------------+
| ord_id1  | 2020-01-01 10:20:46 |      1      |
| ord_id2  | 2020-01-05 23:47:55 |      1      |
| ord_id3  | 2020-01-06 15:23:36 |      2      |
| ord_id4  | 2020-01-08 08:45:37 |      2      |
| ord_id5  | 2020-01-08 20:11:06 |      2      |
| ord_id6  | 2020-01-09 13:11:52 |      2      |
| ord_id7  | 2020-01-13 23:10:04 |      3      |
| ord_id8  | 2020-01-18 00:11:54 |      3      |
| ord_id9  | 2020-01-18 02:16:37 |      3      |
| ord_id10 | 2020-01-21 12:51:09 |      4      |
+----------+---------------------+-------------+
Truncated to displaylimit of 10.

In [43]:
orders['week_number'] = (
    orders['order_date'].dt.isocalendar().week
)
orders[['order_id', 'order_date', 'week_number']]

       order_id          order_date  week_number
0       ord_id1 2020-01-01 10:20:46            1
1       ord_id2 2020-01-05 23:47:55            1
2       ord_id3 2020-01-06 15:23:36            2
3       ord_id4 2020-01-08 08:45:37            2
4       ord_id5 2020-01-08 20:11:06            2
..          ...                 ...          ...
995   ord_id996 2025-12-21 23:08:50           51
996   ord_id997 2025-12-24 07:39:12           52
997   ord_id998 2025-12-27 00:34:40           52
998   ord_id999 2025-12-27 15:01:38           52
999  ord_id1000 2025-12-30 22:57:38            1

[1000 rows x 3 columns]

For **each order**, find the **quarter of the year in which the order was placed.** Display `order_id`, `order_date`, and `quarter`. Use EXTRACT().

In [22]:
%%sql 
SELECT order_id, order_date, EXTRACT(QUARTER FROM order_date) AS quarter_number
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+----------------+
| order_id |      order_date     | quarter_number |
+----------+---------------------+----------------+
| ord_id1  | 2020-01-01 10:20:46 |       1        |
| ord_id2  | 2020-01-05 23:47:55 |       1        |
| ord_id3  | 2020-01-06 15:23:36 |       1        |
| ord_id4  | 2020-01-08 08:45:37 |       1        |
| ord_id5  | 2020-01-08 20:11:06 |       1        |
| ord_id6  | 2020-01-09 13:11:52 |       1        |
| ord_id7  | 2020-01-13 23:10:04 |       1        |
| ord_id8  | 2020-01-18 00:11:54 |       1        |
| ord_id9  | 2020-01-18 02:16:37 |       1        |
| ord_id10 | 2020-01-21 12:51:09 |       1        |
+----------+---------------------+----------------+
Truncated to displaylimit of 10.

In [45]:
orders['quarter_number'] = (
    orders['order_date'].dt.quarter
)
orders[['order_id', 'order_date', 'quarter_number']]

       order_id          order_date  quarter_number
0       ord_id1 2020-01-01 10:20:46               1
1       ord_id2 2020-01-05 23:47:55               1
2       ord_id3 2020-01-06 15:23:36               1
3       ord_id4 2020-01-08 08:45:37               1
4       ord_id5 2020-01-08 20:11:06               1
..          ...                 ...             ...
995   ord_id996 2025-12-21 23:08:50               4
996   ord_id997 2025-12-24 07:39:12               4
997   ord_id998 2025-12-27 00:34:40               4
998   ord_id999 2025-12-27 15:01:38               4
999  ord_id1000 2025-12-30 22:57:38               4

[1000 rows x 3 columns]

Next Question

For **each order**, calculate the **number of hours between login_date and logout_date**. 
Display `order_id`, `login_date`, `logout_date`, and `session_hours`. Use PostgreSQL date/time functions.

In [25]:
%%sql 
SELECT order_id, login_date, logout_date, 
    EXTRACT(EPOCH FROM AGE(logout_date, login_date)) / 3600 AS session_hours
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+---------------------+---------------------+
| order_id |      login_date     |     logout_date     |    session_hours    |
+----------+---------------------+---------------------+---------------------+
| ord_id1  | 2020-01-01 06:59:27 | 2020-01-01 11:35:55 |  4.6077777777777778 |
| ord_id2  | 2020-01-05 12:44:57 | 2020-01-06 01:00:39 | 12.2616666666666667 |
| ord_id3  | 2020-01-06 08:15:05 | 2020-01-06 15:49:06 |  7.5669444444444444 |
| ord_id4  | 2020-01-07 22:59:04 | 2020-01-08 08:52:38 |  9.8927777777777778 |
| ord_id5  | 2020-01-08 02:17:01 | 2020-01-08 22:03:22 | 19.7725000000000000 |
| ord_id6  | 2020-01-08 15:14:55 | 2020-01-09 14:13:27 | 22.9755555555555556 |
| ord_id7  | 2020-01-13 04:31:29 | 2020-01-14 00:10:55 | 19.6572222222222222 |
| ord_id8  | 2020-01-17 00:48:31 | 2020-01-18 01:29:50 | 24.6886111111111111 |
| ord_id9  | 2020-01-17 23:34:12 | 2020-01-18 04:07:14 |  4.5505555555555556 |
| ord_id10 | 2020-01-21 04:40:32 | 2020-01-21 13:32:15 |  8.8619444444444444 |
+----------+---------------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [46]:
orders['session_hours'] = (
    orders['logout_date'] - orders['login_date']
).dt.total_seconds().div(3600)
orders[['order_id', 'login_date', 'logout_date', 'session_hours']]

       order_id          login_date         logout_date  session_hours
0       ord_id1 2020-01-01 06:59:27 2020-01-01 11:35:55       4.607778
1       ord_id2 2020-01-05 12:44:57 2020-01-06 01:00:39      12.261667
2       ord_id3 2020-01-06 08:15:05 2020-01-06 15:49:06       7.566944
3       ord_id4 2020-01-07 22:59:04 2020-01-08 08:52:38       9.892778
4       ord_id5 2020-01-08 02:17:01 2020-01-08 22:03:22      19.772500
..          ...                 ...                 ...            ...
995   ord_id996 2025-12-21 22:47:21 2025-12-22 00:51:43       2.072778
996   ord_id997 2025-12-24 00:32:49 2025-12-24 08:16:22       7.725833
997   ord_id998 2025-12-26 05:32:06 2025-12-27 01:21:58      19.831111
998   ord_id999 2025-12-26 22:52:23 2025-12-27 15:36:51      16.741111
999  ord_id1000 2025-12-30 14:01:11 2025-12-31 00:34:14      10.550833

[1000 rows x 4 columns]

Next Question

For **each order**, calculate **the number of minutes between login_date and logout_date**. Display `order_id` and `session_minutes`. Use PostgreSQL date/time functions.

In [28]:
%%sql 
SELECT order_id, login_date, logout_date,
    EXTRACT(EPOCH FROM AGE(logout_date, login_date)) / 60 AS session_minutes
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+---------------------+-----------------------+
| order_id |      login_date     |     logout_date     |    session_minutes    |
+----------+---------------------+---------------------+-----------------------+
| ord_id1  | 2020-01-01 06:59:27 | 2020-01-01 11:35:55 |  276.4666666666666667 |
| ord_id2  | 2020-01-05 12:44:57 | 2020-01-06 01:00:39 |  735.7000000000000000 |
| ord_id3  | 2020-01-06 08:15:05 | 2020-01-06 15:49:06 |  454.0166666666666667 |
| ord_id4  | 2020-01-07 22:59:04 | 2020-01-08 08:52:38 |  593.5666666666666667 |
| ord_id5  | 2020-01-08 02:17:01 | 2020-01-08 22:03:22 | 1186.3500000000000000 |
| ord_id6  | 2020-01-08 15:14:55 | 2020-01-09 14:13:27 | 1378.5333333333333333 |
| ord_id7  | 2020-01-13 04:31:29 | 2020-01-14 00:10:55 | 1179.4333333333333333 |
| ord_id8  | 2020-01-17 00:48:31 | 2020-01-18 01:29:50 | 1481.3166666666666667 |
| ord_id9  | 2020-01-17 23:34:12 | 2020-01-18 04:07:14 |  273.0333333333333333 |
| ord_id10 | 2020-01-21 04:40:32 | 2020-01-21 13:32:15 |  531.7166666666666667 |
+----------+---------------------+---------------------+-----------------------+
Truncated to displaylimit of 10.

In [47]:
orders['session_minutes'] = (
    orders['logout_date'] - orders['login_date']
).dt.total_seconds().div(60)
orders[['order_id', 'login_date', 'logout_date', 'session_minutes']]

       order_id          login_date         logout_date  session_minutes
0       ord_id1 2020-01-01 06:59:27 2020-01-01 11:35:55       276.466667
1       ord_id2 2020-01-05 12:44:57 2020-01-06 01:00:39       735.700000
2       ord_id3 2020-01-06 08:15:05 2020-01-06 15:49:06       454.016667
3       ord_id4 2020-01-07 22:59:04 2020-01-08 08:52:38       593.566667
4       ord_id5 2020-01-08 02:17:01 2020-01-08 22:03:22      1186.350000
..          ...                 ...                 ...              ...
995   ord_id996 2025-12-21 22:47:21 2025-12-22 00:51:43       124.366667
996   ord_id997 2025-12-24 00:32:49 2025-12-24 08:16:22       463.550000
997   ord_id998 2025-12-26 05:32:06 2025-12-27 01:21:58      1189.866667
998   ord_id999 2025-12-26 22:52:23 2025-12-27 15:36:51      1004.466667
999  ord_id1000 2025-12-30 14:01:11 2025-12-31 00:34:14       633.050000

[1000 rows x 4 columns]

Next Question

For **each order**, find **how many days after the customer logged in the order was placed.** Display `order_id`, `login_date`, `order_date`, and `days_to_order`. Use PostgreSQL date/time functions and return the result as fractional days.

In [ ]:
%%sql 
SELECT order_id, login_date, order_date, 
    EXTRACT(EPOCH FROM AGE(order_date, login_date)) / 86400 AS days_to_order
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+-----------+---------------------+---------------------+------------------------+
|  order_id |      login_date     |      order_date     |     days_to_order      |
+-----------+---------------------+---------------------+------------------------+
| ord_id999 | 2025-12-26 22:52:23 | 2025-12-27 15:01:38 | 0.67309027777777777778 |
| ord_id998 | 2025-12-26 05:32:06 | 2025-12-27 00:34:40 | 0.79344907407407407407 |
| ord_id997 | 2025-12-24 00:32:49 | 2025-12-24 07:39:12 | 0.29609953703703703704 |
| ord_id996 | 2025-12-21 22:47:21 | 2025-12-21 23:08:50 | 0.01491898148148148148 |
| ord_id995 | 2025-12-16 17:47:21 | 2025-12-17 15:45:34 | 0.91542824074074074074 |
| ord_id994 | 2025-12-16 10:25:59 | 2025-12-16 20:58:12 | 0.43903935185185185185 |
| ord_id993 | 2025-12-07 18:18:54 | 2025-12-08 08:51:35 | 0.60603009259259259259 |
| ord_id992 | 2025-12-07 17:24:37 | 2025-12-08 01:41:16 | 0.34489583333333333333 |
| ord_id991 | 2025-12-07 12:35:15 | 2025-12-07 14:28:03 | 0.07833333333333333333 |
| ord_id990 | 2025-12-05 03:51:32 | 2025-12-05 13:53:49 | 0.41825231481481481481 |
+-----------+---------------------+---------------------+------------------------+
Truncated to displaylimit of 10.

In [48]:
orders['days_to_order'] = (
    orders['order_date'] - orders['login_date']
).dt.total_seconds().div(86400)
orders[['order_id', 'login_date', 'order_date', 'days_to_order']]

       order_id          login_date          order_date  days_to_order
0       ord_id1 2020-01-01 06:59:27 2020-01-01 10:20:46       0.139803
1       ord_id2 2020-01-05 12:44:57 2020-01-05 23:47:55       0.460394
2       ord_id3 2020-01-06 08:15:05 2020-01-06 15:23:36       0.297581
3       ord_id4 2020-01-07 22:59:04 2020-01-08 08:45:37       0.407326
4       ord_id5 2020-01-08 02:17:01 2020-01-08 20:11:06       0.745891
..          ...                 ...                 ...            ...
995   ord_id996 2025-12-21 22:47:21 2025-12-21 23:08:50       0.014919
996   ord_id997 2025-12-24 00:32:49 2025-12-24 07:39:12       0.296100
997   ord_id998 2025-12-26 05:32:06 2025-12-27 00:34:40       0.793449
998   ord_id999 2025-12-26 22:52:23 2025-12-27 15:01:38       0.673090
999  ord_id1000 2025-12-30 14:01:11 2025-12-30 22:57:38       0.372535

[1000 rows x 4 columns]

Next Question

For **each order**, find **the month name in which the order was placed**. Display `order_id`, `order_date`, and `month_name`. Use PostgreSQL date/time functions.

In [39]:
%%sql 
SELECT order_id, order_date, TO_CHAR(order_date::DATE, 'month') AS month_name
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+------------+
| order_id |      order_date     | month_name |
+----------+---------------------+------------+
| ord_id1  | 2020-01-01 10:20:46 | january    |
| ord_id2  | 2020-01-05 23:47:55 | january    |
| ord_id3  | 2020-01-06 15:23:36 | january    |
| ord_id4  | 2020-01-08 08:45:37 | january    |
| ord_id5  | 2020-01-08 20:11:06 | january    |
| ord_id6  | 2020-01-09 13:11:52 | january    |
| ord_id7  | 2020-01-13 23:10:04 | january    |
| ord_id8  | 2020-01-18 00:11:54 | january    |
| ord_id9  | 2020-01-18 02:16:37 | january    |
| ord_id10 | 2020-01-21 12:51:09 | january    |
+----------+---------------------+------------+
Truncated to displaylimit of 10.

In [49]:
orders['month_name'] = (
    orders['order_date'].dt.month_name()
)
orders[['order_id', 'order_date', 'month_name']]

       order_id          order_date month_name
0       ord_id1 2020-01-01 10:20:46    January
1       ord_id2 2020-01-05 23:47:55    January
2       ord_id3 2020-01-06 15:23:36    January
3       ord_id4 2020-01-08 08:45:37    January
4       ord_id5 2020-01-08 20:11:06    January
..          ...                 ...        ...
995   ord_id996 2025-12-21 23:08:50   December
996   ord_id997 2025-12-24 07:39:12   December
997   ord_id998 2025-12-27 00:34:40   December
998   ord_id999 2025-12-27 15:01:38   December
999  ord_id1000 2025-12-30 22:57:38   December

[1000 rows x 3 columns]

Next Question

For **each order**, determine **whether it was placed during business hours (9 AM–6 PM)** or **outside business hours**. Display `order_id`, `order_date`, and a `time_category` column with 'Business Hours' or 'Outside Business Hours'. Use EXTRACT(HOUR FROM order_date) and CASE.

In [48]:
%%sql 
SELECT order_id, order_date,
    CASE
        WHEN EXTRACT(HOUR FROM order_date) BETWEEN 9 AND 18 THEN 'Business Hours'
        ELSE 'Outside Business Hours'
    END AS time_category
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+------------------------+
| order_id |      order_date     |     time_category      |
+----------+---------------------+------------------------+
| ord_id1  | 2020-01-01 10:20:46 |     Business Hours     |
| ord_id2  | 2020-01-05 23:47:55 | Outside Business Hours |
| ord_id3  | 2020-01-06 15:23:36 |     Business Hours     |
| ord_id4  | 2020-01-08 08:45:37 | Outside Business Hours |
| ord_id5  | 2020-01-08 20:11:06 | Outside Business Hours |
| ord_id6  | 2020-01-09 13:11:52 |     Business Hours     |
| ord_id7  | 2020-01-13 23:10:04 | Outside Business Hours |
| ord_id8  | 2020-01-18 00:11:54 | Outside Business Hours |
| ord_id9  | 2020-01-18 02:16:37 | Outside Business Hours |
| ord_id10 | 2020-01-21 12:51:09 |     Business Hours     |
+----------+---------------------+------------------------+
Truncated to displaylimit of 10.

In [51]:
orders['time_category'] = np.where(
    (orders['order_date'].dt.hour >= 9) &
    (orders['order_date'].dt.hour <= 18),
    'Business Hours',
    'Outside Business Hours'
)
orders[['order_id', 'order_date', 'time_category']]

       order_id          order_date           time_category
0       ord_id1 2020-01-01 10:20:46          Business Hours
1       ord_id2 2020-01-05 23:47:55  Outside Business Hours
2       ord_id3 2020-01-06 15:23:36          Business Hours
3       ord_id4 2020-01-08 08:45:37  Outside Business Hours
4       ord_id5 2020-01-08 20:11:06  Outside Business Hours
..          ...                 ...                     ...
995   ord_id996 2025-12-21 23:08:50  Outside Business Hours
996   ord_id997 2025-12-24 07:39:12  Outside Business Hours
997   ord_id998 2025-12-27 00:34:40  Outside Business Hours
998   ord_id999 2025-12-27 15:01:38          Business Hours
999  ord_id1000 2025-12-30 22:57:38  Outside Business Hours

[1000 rows x 3 columns]

In [54]:
orders['time_category'] = np.where(
    orders['order_date'].dt.hour.between(9, 18),
    'Business Hours',
    'Outside Business Hours'
)
orders[['order_id', 'order_date', 'time_category']]

       order_id          order_date           time_category
0       ord_id1 2020-01-01 10:20:46          Business Hours
1       ord_id2 2020-01-05 23:47:55  Outside Business Hours
2       ord_id3 2020-01-06 15:23:36          Business Hours
3       ord_id4 2020-01-08 08:45:37  Outside Business Hours
4       ord_id5 2020-01-08 20:11:06  Outside Business Hours
..          ...                 ...                     ...
995   ord_id996 2025-12-21 23:08:50  Outside Business Hours
996   ord_id997 2025-12-24 07:39:12  Outside Business Hours
997   ord_id998 2025-12-27 00:34:40  Outside Business Hours
998   ord_id999 2025-12-27 15:01:38          Business Hours
999  ord_id1000 2025-12-30 22:57:38  Outside Business Hours

[1000 rows x 3 columns]

Next Question

For **each order**, find **whether it was placed on a weekend or weekday**. Display `order_id`, `order_date`, and `day_type` as 'Weekend' or 'Weekday'.

In [61]:
%%sql 
SELECT order_id, order_date,
    CASE
        WHEN TO_CHAR(order_date::DATE, 'day') IN ('sunday','saturday') THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+----------+
| order_id |      order_date     | day_type |
+----------+---------------------+----------+
| ord_id1  | 2020-01-01 10:20:46 | Weekday  |
| ord_id2  | 2020-01-05 23:47:55 | Weekday  |
| ord_id3  | 2020-01-06 15:23:36 | Weekday  |
| ord_id4  | 2020-01-08 08:45:37 | Weekday  |
| ord_id5  | 2020-01-08 20:11:06 | Weekday  |
| ord_id6  | 2020-01-09 13:11:52 | Weekday  |
| ord_id7  | 2020-01-13 23:10:04 | Weekday  |
| ord_id8  | 2020-01-18 00:11:54 | Weekday  |
| ord_id9  | 2020-01-18 02:16:37 | Weekday  |
| ord_id10 | 2020-01-21 12:51:09 | Weekday  |
+----------+---------------------+----------+
Truncated to displaylimit of 10.

In [65]:
%%sql 
SELECT order_id, order_date,
    CASE
        WHEN EXTRACT(DOW FROM order_date) IN (0,6) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+----------+
| order_id |      order_date     | day_type |
+----------+---------------------+----------+
| ord_id1  | 2020-01-01 10:20:46 | Weekday  |
| ord_id2  | 2020-01-05 23:47:55 | Weekend  |
| ord_id3  | 2020-01-06 15:23:36 | Weekday  |
| ord_id4  | 2020-01-08 08:45:37 | Weekday  |
| ord_id5  | 2020-01-08 20:11:06 | Weekday  |
| ord_id6  | 2020-01-09 13:11:52 | Weekday  |
| ord_id7  | 2020-01-13 23:10:04 | Weekday  |
| ord_id8  | 2020-01-18 00:11:54 | Weekend  |
| ord_id9  | 2020-01-18 02:16:37 | Weekend  |
| ord_id10 | 2020-01-21 12:51:09 | Weekday  |
+----------+---------------------+----------+
Truncated to displaylimit of 10.

In [61]:
orders['day_type'] = np.where(
    orders['order_date'].dt.day_name().str.lower().isin(['sunday', 'saturday']),
    'Weekend',
    'Weekday'
)
orders[['order_id', 'order_date', 'day_type']]

       order_id          order_date day_type
0       ord_id1 2020-01-01 10:20:46  Weekday
1       ord_id2 2020-01-05 23:47:55  Weekend
2       ord_id3 2020-01-06 15:23:36  Weekday
3       ord_id4 2020-01-08 08:45:37  Weekday
4       ord_id5 2020-01-08 20:11:06  Weekday
..          ...                 ...      ...
995   ord_id996 2025-12-21 23:08:50  Weekend
996   ord_id997 2025-12-24 07:39:12  Weekday
997   ord_id998 2025-12-27 00:34:40  Weekend
998   ord_id999 2025-12-27 15:01:38  Weekend
999  ord_id1000 2025-12-30 22:57:38  Weekday

[1000 rows x 3 columns]

Next Question

For **each order**, find **the day of the month on which it was placed**. Display `order_id`, `order_date`, and `day_of_month`.

In [ ]:
%%sql 
SELECT order_id, order_date, EXTRACT(DAY FROM order_date) AS day_of_month
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+----------+---------------------+---------+
| order_id |      order_date     | extract |
+----------+---------------------+---------+
| ord_id1  | 2020-01-01 10:20:46 |    1    |
| ord_id2  | 2020-01-05 23:47:55 |    5    |
| ord_id3  | 2020-01-06 15:23:36 |    6    |
| ord_id4  | 2020-01-08 08:45:37 |    8    |
| ord_id5  | 2020-01-08 20:11:06 |    8    |
| ord_id6  | 2020-01-09 13:11:52 |    9    |
| ord_id7  | 2020-01-13 23:10:04 |    13   |
| ord_id8  | 2020-01-18 00:11:54 |    18   |
| ord_id9  | 2020-01-18 02:16:37 |    18   |
| ord_id10 | 2020-01-21 12:51:09 |    21   |
+----------+---------------------+---------+
Truncated to displaylimit of 10.

In [62]:
orders['day_of_month'] = (
    orders['order_date'].dt.day
)
orders[['order_id', 'order_date', 'day_of_month']]

       order_id          order_date  day_of_month
0       ord_id1 2020-01-01 10:20:46             1
1       ord_id2 2020-01-05 23:47:55             5
2       ord_id3 2020-01-06 15:23:36             6
3       ord_id4 2020-01-08 08:45:37             8
4       ord_id5 2020-01-08 20:11:06             8
..          ...                 ...           ...
995   ord_id996 2025-12-21 23:08:50            21
996   ord_id997 2025-12-24 07:39:12            24
997   ord_id998 2025-12-27 00:34:40            27
998   ord_id999 2025-12-27 15:01:38            27
999  ord_id1000 2025-12-30 22:57:38            30

[1000 rows x 3 columns]

Next Question

For **each order**, **extract the year-month combination from order_date** in this format: `2026-08`

In [70]:
%%sql 
SELECT order_date, TO_CHAR(order_date, 'YYYY-MM') AS year_month
FROM retail_analysis.orders;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+---------------------+------------+
|      order_date     | year_month |
+---------------------+------------+
| 2020-01-01 10:20:46 |  2020-01   |
| 2020-01-05 23:47:55 |  2020-01   |
| 2020-01-06 15:23:36 |  2020-01   |
| 2020-01-08 08:45:37 |  2020-01   |
| 2020-01-08 20:11:06 |  2020-01   |
| 2020-01-09 13:11:52 |  2020-01   |
| 2020-01-13 23:10:04 |  2020-01   |
| 2020-01-18 00:11:54 |  2020-01   |
| 2020-01-18 02:16:37 |  2020-01   |
| 2020-01-21 12:51:09 |  2020-01   |
+---------------------+------------+
Truncated to displaylimit of 10.

In [65]:
orders['year_month'] = (
    orders['order_date'].dt.strftime('%Y-%m')
)
orders[['order_date', 'year_month']]

             order_date year_month
0   2020-01-01 10:20:46    2020-01
1   2020-01-05 23:47:55    2020-01
2   2020-01-06 15:23:36    2020-01
3   2020-01-08 08:45:37    2020-01
4   2020-01-08 20:11:06    2020-01
..                  ...        ...
995 2025-12-21 23:08:50    2025-12
996 2025-12-24 07:39:12    2025-12
997 2025-12-27 00:34:40    2025-12
998 2025-12-27 15:01:38    2025-12
999 2025-12-30 22:57:38    2025-12

[1000 rows x 2 columns]

Next Question

Using **DATE_TRUNC()**, **group the orders by month** and **find the number of orders in each month.**
order_month \
total_orders

`TO_CHAR` → month-wise across all years \
`DATE_TRUNC` → year + month-wise

In [81]:
%%sql 
SELECT DATE_TRUNC('month', order_date) AS order_month, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+--------------+
|     order_month     | total_orders |
+---------------------+--------------+
| 2025-12-01 00:00:00 |      15      |
| 2025-07-01 00:00:00 |      17      |
| 2025-08-01 00:00:00 |      7       |
| 2021-02-01 00:00:00 |      15      |
| 2023-12-01 00:00:00 |      11      |
| 2024-03-01 00:00:00 |      14      |
| 2021-07-01 00:00:00 |      11      |
| 2021-04-01 00:00:00 |      18      |
| 2022-01-01 00:00:00 |      9       |
| 2021-11-01 00:00:00 |      20      |
+---------------------+--------------+
Truncated to displaylimit of 10.

In [69]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('M'))['order_id']
    .count()
    .reset_index(name= 'total_orders')
    .rename(columns={'order_date' : 'order_month'})
)
result

   order_month  total_orders
0      2020-01            12
1      2020-02            14
2      2020-03            16
3      2020-04            12
4      2020-05            18
..         ...           ...
67     2025-08             7
68     2025-09            20
69     2025-10            16
70     2025-11            13
71     2025-12            15

[72 rows x 2 columns]

In [82]:
%%sql 
SELECT TO_CHAR(order_date::DATE, 'month') AS order_month, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date::DATE, 'month');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+-------------+--------------+
| order_month | total_orders |
+-------------+--------------+
|  may        |      77      |
|  july       |      82      |
|  august     |      89      |
|  june       |      72      |
|  february   |      74      |
|  december   |      87      |
|  january    |      76      |
|  september  |      88      |
|  november   |      89      |
|  march      |      98      |
+-------------+--------------+
Truncated to displaylimit of 10.

In [72]:
result = (
    orders
    .groupby(orders['order_date'].dt.month_name())['order_id']
    .count()
    .reset_index(name='total_orders')
    .rename(columns={'order_date' : 'order_month'})
)
result

   order_month  total_orders
0        April            82
1       August            89
2     December            87
3     February            74
4      January            76
5         July            82
6         June            72
7        March            98
8          May            77
9     November            89
10     October            86
11   September            88

Next Exercise — DATE_TRUNC()

Find the number of orders for each day.

In [84]:
%%sql 
SELECT DATE_TRUNC('day', order_date) AS order_day, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('day', order_date);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

817 rows affected.

+---------------------+--------------+
|      order_day      | total_orders |
+---------------------+--------------+
| 2022-05-13 00:00:00 |      1       |
| 2021-11-11 00:00:00 |      1       |
| 2021-10-15 00:00:00 |      1       |
| 2020-11-08 00:00:00 |      1       |
| 2022-09-09 00:00:00 |      1       |
| 2020-05-30 00:00:00 |      2       |
| 2022-10-31 00:00:00 |      1       |
| 2023-03-11 00:00:00 |      1       |
| 2024-10-31 00:00:00 |      1       |
| 2025-09-26 00:00:00 |      2       |
+---------------------+--------------+
Truncated to displaylimit of 10.

In [73]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('D'))['order_id']
    .count()
    .reset_index(name='total_orders')
    .rename(columns={'order_date' : 'order_day'})
)
result

      order_day  total_orders
0    2020-01-01             1
1    2020-01-05             1
2    2020-01-06             1
3    2020-01-08             2
4    2020-01-09             1
..          ...           ...
812  2025-12-17             1
813  2025-12-21             1
814  2025-12-24             1
815  2025-12-27             2
816  2025-12-30             1

[817 rows x 2 columns]

In [85]:
%%sql 
SELECT TO_CHAR(order_date::DATE, 'day') AS order_day, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date::DATE, 'day');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+--------------+
| order_day | total_orders |
+-----------+--------------+
| monday    |     154      |
| thursday  |     135      |
| wednesday |     140      |
| tuesday   |     153      |
| saturday  |     127      |
| sunday    |     139      |
| friday    |     152      |
+-----------+--------------+

In [74]:
result = (
    orders
    .groupby(orders['order_date'].dt.day_name())['order_id']
    .count()
    .reset_index(name = 'total_orders')
    .rename(columns= {'order_date': 'order_day'})
)
result

   order_day  total_orders
0     Friday           152
1     Monday           154
2   Saturday           127
3     Sunday           139
4   Thursday           135
5    Tuesday           153
6  Wednesday           140

Next Exercise — DATE_TRUNC() + Week

Find the number of orders for each week.

Return:

order_week \
total_orders

In [86]:
%%sql 
SELECT DATE_TRUNC('week', order_date) AS order_week, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('week', order_date);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

301 rows affected.

+---------------------+--------------+
|      order_week     | total_orders |
+---------------------+--------------+
| 2021-03-08 00:00:00 |      1       |
| 2022-10-31 00:00:00 |      1       |
| 2020-02-17 00:00:00 |      4       |
| 2022-01-10 00:00:00 |      3       |
| 2025-12-01 00:00:00 |      6       |
| 2021-10-11 00:00:00 |      4       |
| 2023-03-13 00:00:00 |      3       |
| 2023-09-25 00:00:00 |      3       |
| 2023-01-09 00:00:00 |      2       |
| 2024-12-16 00:00:00 |      7       |
+---------------------+--------------+
Truncated to displaylimit of 10.

In [78]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('W'))['order_date']
    .count()
    .reset_index(name= 'total_orders')
    .rename(columns= {'order_date' : 'order_week'})
)
result

                order_week  total_orders
0    2019-12-30/2020-01-05             2
1    2020-01-06/2020-01-12             4
2    2020-01-13/2020-01-19             3
3    2020-01-20/2020-01-26             2
4    2020-01-27/2020-02-02             1
..                     ...           ...
296  2025-12-01/2025-12-07             6
297  2025-12-08/2025-12-14             2
298  2025-12-15/2025-12-21             3
299  2025-12-22/2025-12-28             3
300  2025-12-29/2026-01-04             1

[301 rows x 2 columns]

Next Exercise — DATE_TRUNC() + Year

Find the number of orders for each year.

Return:

order_year \
total_orders

In [88]:
%%sql 
SELECT DATE_TRUNC('year', order_date) AS order_year, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('year', order_date)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+---------------------+--------------+
|      order_year     | total_orders |
+---------------------+--------------+
| 2022-01-01 00:00:00 |     151      |
| 2023-01-01 00:00:00 |     185      |
| 2021-01-01 00:00:00 |     158      |
| 2025-01-01 00:00:00 |     165      |
| 2024-01-01 00:00:00 |     178      |
| 2020-01-01 00:00:00 |     163      |
+---------------------+--------------+

In [79]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('Y'))['order_id']
    .count()
    .reset_index(name = 'total_orders')
    .rename(columns = {'order_date' : 'order_year'})
) 
result

  order_year  total_orders
0       2020           163
1       2021           158
2       2022           151
3       2023           185
4       2024           178
5       2025           165

In [89]:
%%sql 
SELECT TO_CHAR(order_date::DATE, 'year') AS order_year, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date::DATE, 'year');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+------------+--------------+
| order_year | total_orders |
+------------+--------------+
|    5ear    |     165      |
|    3ear    |     185      |
|    0ear    |     163      |
|    2ear    |     151      |
|    1ear    |     158      |
|    4ear    |     178      |
+------------+--------------+

In [82]:
result = (
    orders
    .groupby(orders['order_date'].dt.year)['order_id']
    .count()
    .reset_index(name = 'total_orders')
    .rename(columns = {'order_date' : 'order_year'})
)
result

   order_year  total_orders
0        2020           163
1        2021           158
2        2022           151
3        2023           185
4        2024           178
5        2025           165

In [87]:
%%sql 
SELECT TO_CHAR(order_date::DATE, 'week') AS order_week, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date::DATE, 'week');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

5 rows affected.

+------------+--------------+
| order_week | total_orders |
+------------+--------------+
|    4eek    |     235      |
|    3eek    |     234      |
|    5eek    |      72      |
|    1eek    |     214      |
|    2eek    |     245      |
+------------+--------------+

Next Exercise — Comparing DATE_TRUNC() Levels

Find the number of orders for each month of each year, but return the month as: \
2025-01 \
2025-02 \
2025-03 \
...

In [ ]:
%%sql 
SELECT TO_CHAR(DATE_TRUNC('month', order_date), 'YYYY-MM') AS order_month, 
    COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+-------------+--------------+
| order_month | total_orders |
+-------------+--------------+
|   2025-12   |      15      |
|   2025-07   |      17      |
|   2025-08   |      7       |
|   2021-02   |      15      |
|   2023-12   |      11      |
|   2024-03   |      14      |
|   2021-07   |      11      |
|   2021-04   |      18      |
|   2022-01   |      9       |
|   2021-11   |      20      |
+-------------+--------------+
Truncated to displaylimit of 10.

In [95]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('M'))['order_id']
    .count()
    .reset_index(name= 'total_orders')
    .rename(columns = {'order_date' : 'order_month'})
)
result

   order_month  total_orders
0      2020-01            12
1      2020-02            14
2      2020-03            16
3      2020-04            12
4      2020-05            18
..         ...           ...
67     2025-08             7
68     2025-09            20
69     2025-10            16
70     2025-11            13
71     2025-12            15

[72 rows x 2 columns]

In [ ]:
%%sql 
SELECT TO_CHAR(order_date::DATE, 'YYYY-MM') AS order_month, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date::DATE, 'YYYY-MM')

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+-------------+--------------+
| order_month | total_orders |
+-------------+--------------+
|   2021-06   |      11      |
|   2021-12   |      15      |
|   2020-06   |      8       |
|   2020-09   |      13      |
|   2020-11   |      15      |
|   2020-07   |      16      |
|   2024-04   |      11      |
|   2023-12   |      11      |
|   2022-11   |      10      |
|   2022-12   |      15      |
+-------------+--------------+
Truncated to displaylimit of 10.

In [97]:
%%sql 
SELECT TO_CHAR(order_date, 'YYYY-MM') AS order_month, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM')

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+-------------+--------------+
| order_month | total_orders |
+-------------+--------------+
|   2021-06   |      11      |
|   2021-12   |      15      |
|   2020-06   |      8       |
|   2020-09   |      13      |
|   2020-11   |      15      |
|   2020-07   |      16      |
|   2024-04   |      11      |
|   2023-12   |      11      |
|   2022-11   |      10      |
|   2022-12   |      15      |
+-------------+--------------+
Truncated to displaylimit of 10.

Next Exercise — Real Analysis

Find the first order date and last order date for each customer.

Return:

customer_id \
first_order_date \
last_order_date 

Use MIN() and MAX() on order_date.

In [104]:
%%sql 
SELECT customer_id, 
    MIN(order_date) AS first_order_date, 
    MAX(order_date) AS last_order_date
FROM retail_analysis.orders
GROUP BY customer_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+---------------------+
| customer_id |   first_order_date  |   last_order_date   |
+-------------+---------------------+---------------------+
|  cust_id16  | 2020-05-30 05:38:21 | 2025-03-24 07:54:55 |
|  cust_id78  | 2020-04-01 16:36:31 | 2025-12-05 13:53:49 |
|  cust_id39  | 2020-02-06 01:38:50 | 2025-07-08 01:52:21 |
|  cust_id59  | 2020-03-07 19:01:09 | 2023-12-05 04:12:47 |
|   cust_id6  | 2020-05-08 08:09:10 | 2025-11-07 17:34:39 |
|  cust_id74  | 2020-04-22 10:46:23 | 2023-10-21 21:21:16 |
|  cust_id75  | 2020-02-25 09:50:39 | 2025-09-14 19:17:27 |
|  cust_id56  | 2020-09-20 00:22:56 | 2025-11-30 18:56:32 |
|   cust_id1  | 2020-02-03 02:39:06 | 2025-12-16 20:58:12 |
|  cust_id65  | 2021-08-11 12:56:32 | 2025-06-09 12:30:19 |
+-------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [98]:
result = (
    orders
    .groupby('customer_id')['order_date']
    .agg(['min', 'max'])
    .reset_index()
)
result

   customer_id                 min                 max
0     cust_id1 2020-02-03 02:39:06 2025-12-16 20:58:12
1    cust_id10 2020-06-25 04:48:35 2025-07-23 14:32:21
2   cust_id100 2020-08-10 16:34:32 2025-01-16 15:30:30
3    cust_id11 2020-11-08 07:32:56 2024-10-30 20:07:59
4    cust_id12 2020-01-18 00:11:54 2025-09-16 08:11:14
..         ...                 ...                 ...
95   cust_id95 2020-03-22 01:06:16 2025-07-25 15:49:29
96   cust_id96 2020-03-10 10:45:16 2025-12-07 14:28:03
97   cust_id97 2020-06-28 11:41:17 2024-09-03 16:54:44
98   cust_id98 2021-02-11 06:45:12 2024-06-23 20:39:31
99   cust_id99 2020-11-09 14:30:32 2025-12-24 07:39:12

[100 rows x 3 columns]

In [101]:
result = (
    orders
    .groupby('customer_id')
    .agg(
        first_order_date = ('order_date', 'min'),
        last_order_date = ('order_date', 'max')
    )
    .reset_index()
)
result

   customer_id    first_order_date     last_order_date
0     cust_id1 2020-02-03 02:39:06 2025-12-16 20:58:12
1    cust_id10 2020-06-25 04:48:35 2025-07-23 14:32:21
2   cust_id100 2020-08-10 16:34:32 2025-01-16 15:30:30
3    cust_id11 2020-11-08 07:32:56 2024-10-30 20:07:59
4    cust_id12 2020-01-18 00:11:54 2025-09-16 08:11:14
..         ...                 ...                 ...
95   cust_id95 2020-03-22 01:06:16 2025-07-25 15:49:29
96   cust_id96 2020-03-10 10:45:16 2025-12-07 14:28:03
97   cust_id97 2020-06-28 11:41:17 2024-09-03 16:54:44
98   cust_id98 2021-02-11 06:45:12 2024-06-23 20:39:31
99   cust_id99 2020-11-09 14:30:32 2025-12-24 07:39:12

[100 rows x 3 columns]

Next Exercise — Customer Ordering Behavior

For each customer, calculate the number of days between their first and last order.

Return:

customer_id \
first_order_date \
last_order_date \
days_between_orders 

Use MIN(), MAX(), and a PostgreSQL date/time function to calculate the difference in total days.

In [110]:
%%sql 
SELECT customer_id, 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    EXTRACT(EPOCH FROM AGE(MAX(order_date), MIN(order_date))) / 86400 AS days_between_orders
FROM retail_analysis.orders
GROUP BY customer_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+---------------------+-----------------------+
| customer_id |   first_order_date  |   last_order_date   |  days_between_orders  |
+-------------+---------------------+---------------------+-----------------------+
|  cust_id16  | 2020-05-30 05:38:21 | 2025-03-24 07:54:55 | 1756.0948379629629630 |
|  cust_id78  | 2020-04-01 16:36:31 | 2025-12-05 13:53:49 | 2070.1370138888888889 |
|  cust_id39  | 2020-02-06 01:38:50 | 2025-07-08 01:52:21 | 1978.2593865740740741 |
|  cust_id59  | 2020-03-07 19:01:09 | 2023-12-05 04:12:47 | 1364.1330787037037037 |
|   cust_id6  | 2020-05-08 08:09:10 | 2025-11-07 17:34:39 | 2006.6426967592592593 |
|  cust_id74  | 2020-04-22 10:46:23 | 2023-10-21 21:21:16 | 1275.1908912037037037 |
|  cust_id75  | 2020-02-25 09:50:39 | 2025-09-14 19:17:27 | 2024.6436111111111111 |
|  cust_id56  | 2020-09-20 00:22:56 | 2025-11-30 18:56:32 | 1897.0233333333333333 |
|   cust_id1  | 2020-02-03 02:39:06 | 2025-12-16 20:58:12 | 2140.0132638888888889 |
|  cust_id65  | 2021-08-11 12:56:32 | 2025-06-09 12:30:19 | 1394.7317939814814815 |
+-------------+---------------------+---------------------+-----------------------+
Truncated to displaylimit of 10.

In [22]:
result = (
    orders
    .groupby('customer_id')
    .agg(
        first_order_date = ('order_date', 'min'),
        last_order_date = ('order_date', 'max')
    )
    .reset_index()
)
result['days_between_orders'] = (
    result['last_order_date'].dt.day - result['first_order_date'].dt.day
)
result

   customer_id    first_order_date     last_order_date  days_between_orders
0     cust_id1 2020-02-03 02:39:06 2025-12-16 20:58:12                   13
1    cust_id10 2020-06-25 04:48:35 2025-07-23 14:32:21                   -2
2   cust_id100 2020-08-10 16:34:32 2025-01-16 15:30:30                    6
3    cust_id11 2020-11-08 07:32:56 2024-10-30 20:07:59                   22
4    cust_id12 2020-01-18 00:11:54 2025-09-16 08:11:14                   -2
..         ...                 ...                 ...                  ...
95   cust_id95 2020-03-22 01:06:16 2025-07-25 15:49:29                    3
96   cust_id96 2020-03-10 10:45:16 2025-12-07 14:28:03                   -3
97   cust_id97 2020-06-28 11:41:17 2024-09-03 16:54:44                  -25
98   cust_id98 2021-02-11 06:45:12 2024-06-23 20:39:31                   12
99   cust_id99 2020-11-09 14:30:32 2025-12-24 07:39:12                   15

[100 rows x 4 columns]

Next Exercise — Date Filtering

Find all orders placed in 2025.

Return:

order_id \
order_date \
customer_id

Use a date range with order_date rather than extracting the year.

In [112]:
%%sql 
SELECT order_id, order_date, customer_id
FROM retail_analysis.orders
WHERE EXTRACT(YEAR FROM order_date) = '2025';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

165 rows affected.

+-----------+---------------------+-------------+
|  order_id |      order_date     | customer_id |
+-----------+---------------------+-------------+
| ord_id836 | 2025-01-01 19:17:33 |  cust_id80  |
| ord_id837 | 2025-01-01 21:45:06 |   cust_id1  |
| ord_id838 | 2025-01-01 21:45:12 |  cust_id80  |
| ord_id839 | 2025-01-03 10:48:27 |  cust_id79  |
| ord_id840 | 2025-01-08 17:18:58 |  cust_id81  |
| ord_id841 | 2025-01-09 17:58:58 |  cust_id77  |
| ord_id842 | 2025-01-14 12:02:13 |  cust_id22  |
| ord_id843 | 2025-01-15 11:48:42 |  cust_id40  |
| ord_id844 | 2025-01-16 15:30:30 |  cust_id100 |
| ord_id845 | 2025-01-21 00:54:24 |  cust_id34  |
+-----------+---------------------+-------------+
Truncated to displaylimit of 10.

In [35]:
orders[
    ['order_id', 'order_date', 'customer_id']
][orders['order_date'].dt.year == 2025]

       order_id          order_date customer_id
835   ord_id836 2025-01-01 19:17:33   cust_id80
836   ord_id837 2025-01-01 21:45:06    cust_id1
837   ord_id838 2025-01-01 21:45:12   cust_id80
838   ord_id839 2025-01-03 10:48:27   cust_id79
839   ord_id840 2025-01-08 17:18:58   cust_id81
..          ...                 ...         ...
995   ord_id996 2025-12-21 23:08:50   cust_id29
996   ord_id997 2025-12-24 07:39:12   cust_id99
997   ord_id998 2025-12-27 00:34:40   cust_id36
998   ord_id999 2025-12-27 15:01:38   cust_id37
999  ord_id1000 2025-12-30 22:57:38   cust_id72

[165 rows x 3 columns]

In [121]:
%%sql 
SELECT order_id, order_date, customer_id
FROM retail_analysis.orders
WHERE order_date >= '2025-01-01' 
    AND order_date < '2026-01-01';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

165 rows affected.

+-----------+---------------------+-------------+
|  order_id |      order_date     | customer_id |
+-----------+---------------------+-------------+
| ord_id836 | 2025-01-01 19:17:33 |  cust_id80  |
| ord_id837 | 2025-01-01 21:45:06 |   cust_id1  |
| ord_id838 | 2025-01-01 21:45:12 |  cust_id80  |
| ord_id839 | 2025-01-03 10:48:27 |  cust_id79  |
| ord_id840 | 2025-01-08 17:18:58 |  cust_id81  |
| ord_id841 | 2025-01-09 17:58:58 |  cust_id77  |
| ord_id842 | 2025-01-14 12:02:13 |  cust_id22  |
| ord_id843 | 2025-01-15 11:48:42 |  cust_id40  |
| ord_id844 | 2025-01-16 15:30:30 |  cust_id100 |
| ord_id845 | 2025-01-21 00:54:24 |  cust_id34  |
+-----------+---------------------+-------------+
Truncated to displaylimit of 10.

In [38]:
orders[
    ['order_id', 'order_date', 'customer_id']
][
    (orders['order_date'] >= '2025-01-01') &
    (orders['order_date'] < '2026-01-01')
]

       order_id          order_date customer_id
835   ord_id836 2025-01-01 19:17:33   cust_id80
836   ord_id837 2025-01-01 21:45:06    cust_id1
837   ord_id838 2025-01-01 21:45:12   cust_id80
838   ord_id839 2025-01-03 10:48:27   cust_id79
839   ord_id840 2025-01-08 17:18:58   cust_id81
..          ...                 ...         ...
995   ord_id996 2025-12-21 23:08:50   cust_id29
996   ord_id997 2025-12-24 07:39:12   cust_id99
997   ord_id998 2025-12-27 00:34:40   cust_id36
998   ord_id999 2025-12-27 15:01:38   cust_id37
999  ord_id1000 2025-12-30 22:57:38   cust_id72

[165 rows x 3 columns]

Next Exercise

Find all orders placed in August 2025 using a timestamp-safe date range.

In [128]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= '2025-08-01'
    AND order_date < '2025-09-01';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+---------------------+
|  order_id |      order_date     |
+-----------+---------------------+
| ord_id930 | 2025-08-02 15:02:28 |
| ord_id931 | 2025-08-05 05:38:22 |
| ord_id932 | 2025-08-07 18:38:55 |
| ord_id933 | 2025-08-10 02:22:22 |
| ord_id934 | 2025-08-17 22:54:13 |
| ord_id935 | 2025-08-29 22:42:05 |
| ord_id936 | 2025-08-30 16:47:25 |
+-----------+---------------------+

In [39]:
orders[
    ['order_id', 'order_date']
][
    (orders['order_date'] >= '2025-08-01') &
    (orders['order_date'] < '2025-09-01')
]

      order_id          order_date
929  ord_id930 2025-08-02 15:02:28
930  ord_id931 2025-08-05 05:38:22
931  ord_id932 2025-08-07 18:38:55
932  ord_id933 2025-08-10 02:22:22
933  ord_id934 2025-08-17 22:54:13
934  ord_id935 2025-08-29 22:42:05
935  ord_id936 2025-08-30 16:47:25

In [129]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE TO_CHAR(order_date, 'YYYY-MM') = '2025-08';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+---------------------+
|  order_id |      order_date     |
+-----------+---------------------+
| ord_id930 | 2025-08-02 15:02:28 |
| ord_id931 | 2025-08-05 05:38:22 |
| ord_id932 | 2025-08-07 18:38:55 |
| ord_id933 | 2025-08-10 02:22:22 |
| ord_id934 | 2025-08-17 22:54:13 |
| ord_id935 | 2025-08-29 22:42:05 |
| ord_id936 | 2025-08-30 16:47:25 |
+-----------+---------------------+

In [40]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.strftime('%y-%m') == '25-08'
]

      order_id          order_date
929  ord_id930 2025-08-02 15:02:28
930  ord_id931 2025-08-05 05:38:22
931  ord_id932 2025-08-07 18:38:55
932  ord_id933 2025-08-10 02:22:22
933  ord_id934 2025-08-17 22:54:13
934  ord_id935 2025-08-29 22:42:05
935  ord_id936 2025-08-30 16:47:25

Next Exercise — DATE_TRUNC() + filtering

Find all orders placed in August 2025 using DATE_TRUNC().

In [134]:
%%sql 
SELECT order_id,
    DATE_TRUNC('month', order_date) AS order_month
FROM retail_analysis.orders
WHERE DATE_TRUNC('month', order_date) = '2025-08-01';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+---------------------+
|  order_id |     order_month     |
+-----------+---------------------+
| ord_id930 | 2025-08-01 00:00:00 |
| ord_id931 | 2025-08-01 00:00:00 |
| ord_id932 | 2025-08-01 00:00:00 |
| ord_id933 | 2025-08-01 00:00:00 |
| ord_id934 | 2025-08-01 00:00:00 |
| ord_id935 | 2025-08-01 00:00:00 |
| ord_id936 | 2025-08-01 00:00:00 |
+-----------+---------------------+

In [48]:
orders[
    ['order_id', 'order_date']
][orders['order_date'].dt.to_period('M') == '2025-08']

      order_id          order_date
929  ord_id930 2025-08-02 15:02:28
930  ord_id931 2025-08-05 05:38:22
931  ord_id932 2025-08-07 18:38:55
932  ord_id933 2025-08-10 02:22:22
933  ord_id934 2025-08-17 22:54:13
934  ord_id935 2025-08-29 22:42:05
935  ord_id936 2025-08-30 16:47:25

Next Exercise — Current Date

Find all orders placed in the current year using PostgreSQL's current-date function. Don't hard-code the year like 2025 or 2026.

In [162]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE EXTRACT(YEAR FROM order_date) = EXTRACT(YEAR FROM CURRENT_DATE);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [51]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.year == pd.Timestamp.today().year
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — Current Month

Find all orders placed in the current month of the current year.

Don't hard-code the year or month. Use PostgreSQL date/time functions.

In [159]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('month', order_date::DATE) = DATE_TRUNC('month', CURRENT_DATE);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [55]:
orders[
    ['order_id','order_date']
][
    orders['order_date'].dt.to_period('M') == pd.Timestamp.today().to_period('M')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

In [164]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE TO_CHAR(order_date::DATE, 'YYYY-MM') = TO_CHAR(CURRENT_DATE, 'YYYY-MM');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [56]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.strftime('%Y-%m') == pd.Timestamp.today().strftime('%Y-%m')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — Previous Month

Find all orders placed in the previous calendar month.

For example, if the current month is August 2026, return orders from July 2026 only.

Don't hard-code the month or year. Use PostgreSQL date/time functions.

In [167]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('month', order_date::DATE) 
    = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month');

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [59]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.to_period('M') == 
    (pd.Timestamp.today() - pd.DateOffset(months=1)).to_period('M')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

In [172]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE TO_CHAR(order_date::DATE, 'YYYY-MM') 
    = TO_CHAR(CURRENT_DATE - INTERVAL '1 month', 'YYYY-MM')

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [60]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.strftime('%Y-%m') ==
    (pd.Timestamp.today() - pd.DateOffset(months=1)).strftime('%Y-%m')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — Last 7 Days

Find all orders placed in the last 7 days from now.

Use the `order_date` timestamp and PostgreSQL's current date/time function. Don't hard-code any date.

In [182]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= NOW() - INTERVAL '7 days';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [68]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'] >= pd.Timestamp.today() - pd.Timedelta(days=7)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise

Find all orders placed in the last 30 days, using the same idea.

In [187]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= NOW() - INTERVAL '30 days';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [70]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'] >= pd.Timestamp.now() - pd.Timedelta(days=30)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next exercise: 

Find orders placed in the last 3 months using INTERVAL.

In [5]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= NOW() - INTERVAL '3 months';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [72]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'] >= pd.Timestamp.now() - pd.DateOffset(months=3)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — This Month vs Last Month

Find the number of orders placed in the current month and the previous month separately.

Return:

order_month \
total_orders

Use DATE_TRUNC() and CURRENT_DATE.

<PRE>order_month              total_orders
-----------------------  ------------
2026-07-01 00:00:00      145
2026-08-01 00:00:00      172</PRE>

In [24]:
%%sql 
SELECT DATE_TRUNC('month', order_date) AS order_month,
    COUNT(order_id) AS total_orders
FROM retail_analysis.orders
WHERE DATE_TRUNC('month', order_date) IN (
    DATE_TRUNC('month', CURRENT_DATE), 
    DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month')
)
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY order_month;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+--------------+
| order_month | total_orders |
+-------------+--------------+
+-------------+--------------+

In [78]:
result = (
    orders
    .groupby(orders['order_date'].dt.to_period('M'))['order_id']
    .count()
    .reset_index(name='total_orders')
    .rename(columns={'order_date' : 'order_month'})
)
result[
    result['order_month'].isin([
        pd.Timestamp.today().to_period('M'),
        (pd.Timestamp.today() - pd.DateOffset(months=1)).to_period('M')
    ])
]

Empty DataFrame
Columns: [order_month, total_orders]
Index: []

Next Exercise — Monthly Revenue

Using orders, order_items, and products, calculate the total revenue for each month.

Return:

order_month \
total_revenue

Use:

selling_price × quantity

and DATE_TRUNC('month', order_date) for the month.

In [ ]:
%%sql 
SELECT DATE_TRUNC('month', order_date) AS order_month,
    SUM(oi.quantity * p.selling_price) AS total_revenue
FROM retail_analysis.orders o 
JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
JOIN retail_analysis.products p 
ON oi.product_id = p.product_id
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY order_month ASC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+---------------+
|     order_month     | total_revenue |
+---------------------+---------------+
| 2020-01-01 00:00:00 |   192480.00   |
| 2020-02-01 00:00:00 |   163215.00   |
| 2020-03-01 00:00:00 |   922026.00   |
| 2020-04-01 00:00:00 |   223658.00   |
| 2020-05-01 00:00:00 |   539735.00   |
| 2020-06-01 00:00:00 |   299950.00   |
| 2020-07-01 00:00:00 |   236291.00   |
| 2020-08-01 00:00:00 |   347409.00   |
| 2020-09-01 00:00:00 |   349861.00   |
| 2020-10-01 00:00:00 |   162945.00   |
+---------------------+---------------+
Truncated to displaylimit of 10.

In [41]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_revenue'] = (
    merged['selling_price'] * merged['quantity']
)
result = (
    merged
    .groupby(merged['order_date'].dt.to_period('M'))['total_revenue']
    .sum()
    .reset_index(name='total_revenue')
    .rename(columns={'order_date': 'order_month'})
)
result

   order_month  total_revenue
0      2020-01         192480
1      2020-02         163215
2      2020-03         922026
3      2020-04         223658
4      2020-05         539735
..         ...            ...
67     2025-08         106735
68     2025-09         754268
69     2025-10         281925
70     2025-11         238585
71     2025-12         230170

[72 rows x 2 columns]

Next Exercise — Monthly Revenue + Customer

Using orders, order_items, and products, calculate **the total revenue generated by each customer for each month**.

Return:

customer_id \
order_month \
total_revenue

Use:

selling_price × quantity

and DATE_TRUNC('month', order_date).

In [49]:
%%sql 
SELECT o.customer_id, DATE_TRUNC('month', O.order_date) AS order_month,  
    SUM(p.selling_price * oi.quantity) AS total_revenue
FROM retail_analysis.orders o 
JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id 
JOIN retail_analysis.products p 
ON oi.product_id = p.product_id
GROUP BY o.customer_id, DATE_TRUNC('month', O.order_date)
ORDER BY customer_id ASC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

940 rows affected.

+-------------+---------------------+---------------+
| customer_id |     order_month     | total_revenue |
+-------------+---------------------+---------------+
|   cust_id1  | 2020-02-01 00:00:00 |    20300.00   |
|   cust_id1  | 2020-09-01 00:00:00 |    12900.00   |
|   cust_id1  | 2023-05-01 00:00:00 |    1290.00    |
|   cust_id1  | 2023-11-01 00:00:00 |    11263.00   |
|   cust_id1  | 2024-07-01 00:00:00 |    4100.00    |
|   cust_id1  | 2025-01-01 00:00:00 |    12800.00   |
|   cust_id1  | 2025-03-01 00:00:00 |     615.00    |
|   cust_id1  | 2025-10-01 00:00:00 |    93000.00   |
|   cust_id1  | 2025-12-01 00:00:00 |    7900.00    |
|  cust_id10  | 2020-06-01 00:00:00 |    19800.00   |
+-------------+---------------------+---------------+
Truncated to displaylimit of 10.

In [43]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
result = (
    merged 
    .assign(total_revenue = merged['selling_price'] * merged['quantity'])
    .groupby(['customer_id', merged['order_date'].dt.to_period('M')])['total_revenue']
    .sum()
    .reset_index(name='total_revenue')
    .rename(columns={'order_date' : 'order_month'})
)
result

    customer_id order_month  total_revenue
0      cust_id1     2020-02          20300
1      cust_id1     2020-09          12900
2      cust_id1     2023-05           1290
3      cust_id1     2023-11          11263
4      cust_id1     2024-07           4100
..          ...         ...            ...
935   cust_id99     2025-04           7900
936   cust_id99     2025-07          10750
937   cust_id99     2025-09          10560
938   cust_id99     2025-10           2100
939   cust_id99     2025-12            900

[940 rows x 3 columns]

Next Exercise — Monthly Average Order Value

Using orders, order_items, and products, calculate **the average order value for each month**.

Return:

order_month \
average_order_value

**Important**: first **calculate the revenue of each individual order**, then **calculate the average of those order revenues for each month**.

In [ ]:
%%sql 
SELECT order_month, AVG(revenue) AS avg_order_value
FROM (
    SELECT o.order_id, 
        DATE_TRUNC('month', o.order_date) AS order_month,
        SUM(oi.quantity * p.selling_price) AS revenue
    FROM retail_analysis.orders o 
    JOIN retail_analysis.order_items oi 
    ON oi.order_id = o.order_id 
    JOIN retail_analysis.products p
    ON p.product_id = oi.product_id
    GROUP BY o.order_id, DATE_TRUNC('month', o.order_date)
) 
GROUP BY order_month;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+-----------------------+
|     order_month     |    avg_order_value    |
+---------------------+-----------------------+
| 2024-06-01 00:00:00 |   35233.800000000000  |
| 2024-12-01 00:00:00 |   18468.250000000000  |
| 2023-05-01 00:00:00 | 7599.1176470588235294 |
| 2025-02-01 00:00:00 |   18144.000000000000  |
| 2023-09-01 00:00:00 |  135945.937500000000  |
| 2025-04-01 00:00:00 |   15392.750000000000  |
| 2020-09-01 00:00:00 |   26912.384615384615  |
| 2023-08-01 00:00:00 |   11147.900000000000  |
| 2025-03-01 00:00:00 | 8289.9444444444444444 |
| 2022-12-01 00:00:00 |   20475.333333333333  |
+---------------------+-----------------------+
Truncated to displaylimit of 10.

In [47]:
merged = (
    orders 
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
result = (
    merged
    .assign(revenue = merged['quantity'] * merged['selling_price'])
    .groupby(['order_id', merged['order_date'].dt.to_period('M')])['revenue']
    .sum()
    .reset_index(name='revenue')
    .rename(columns={'order_date' : 'order_month'})
)
result.groupby('order_month')['revenue'].mean().reset_index(name='avg_order_value')

   order_month  avg_order_value
0      2020-01     16040.000000
1      2020-02     11658.214286
2      2020-03     57626.625000
3      2020-04     18638.166667
4      2020-05     29985.277778
..         ...              ...
67     2025-08     15247.857143
68     2025-09     37713.400000
69     2025-10     17620.312500
70     2025-11     18352.692308
71     2025-12     15344.666667

[72 rows x 2 columns]

Next Exercise — Monthly Revenue Growth

Using orders, order_items, and products, calculate the **total revenue for each month and also show the previous month's revenue alongside it**.

Return:

order_month \
total_revenue \
previous_month_revenue

You may use a window function such as **LAG()**.

In [79]:
%%sql
SELECT DATE_TRUNC('month', o.order_date) AS month,
    SUM(p.selling_price * oi.quantity) total_revenue,
    LAG(SUM(p.selling_price * oi.quantity))
    OVER(
        ORDER BY DATE_TRUNC('month', o.order_date) ASC
    ) AS previous_month_revenue
FROM retail_analysis.orders o 
JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
JOIN retail_analysis.products p 
ON p.product_id = oi.product_id
GROUP BY DATE_TRUNC('month', o.order_date);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+---------------+------------------------+
|        month        | total_revenue | previous_month_revenue |
+---------------------+---------------+------------------------+
| 2020-01-01 00:00:00 |   192480.00   |          None          |
| 2020-02-01 00:00:00 |   163215.00   |       192480.00        |
| 2020-03-01 00:00:00 |   922026.00   |       163215.00        |
| 2020-04-01 00:00:00 |   223658.00   |       922026.00        |
| 2020-05-01 00:00:00 |   539735.00   |       223658.00        |
| 2020-06-01 00:00:00 |   299950.00   |       539735.00        |
| 2020-07-01 00:00:00 |   236291.00   |       299950.00        |
| 2020-08-01 00:00:00 |   347409.00   |       236291.00        |
| 2020-09-01 00:00:00 |   349861.00   |       347409.00        |
| 2020-10-01 00:00:00 |   162945.00   |       349861.00        |
+---------------------+---------------+------------------------+
Truncated to displaylimit of 10.

In [52]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
result = (
    merged
    .assign(revenue = merged['selling_price'] * merged['quantity'])
    .groupby(merged['order_date'].dt.to_period('M'))['revenue']
    .sum()
    .reset_index(name='total_revenue')
    .rename(columns={'order_date' : 'month'})
)
result['previous_month_revenue'] = (
    result['total_revenue']
    .shift(1)
)
result

      month  total_revenue  previous_month_revenue
0   2020-01         192480                     NaN
1   2020-02         163215                192480.0
2   2020-03         922026                163215.0
3   2020-04         223658                922026.0
4   2020-05         539735                223658.0
..      ...            ...                     ...
67  2025-08         106735                280335.0
68  2025-09         754268                106735.0
69  2025-10         281925                754268.0
70  2025-11         238585                281925.0
71  2025-12         230170                238585.0

[72 rows x 3 columns]

Next Exercise — Monthly Revenue Change

Using the same monthly revenue logic, calculate:

order_month \
total_revenue \
previous_month_revenue \
revenue_change

Where:

revenue_change = total_revenue - previous_month_revenue

Use LAG().

In [87]:
%%sql 
SELECT order_month, 
    total_revenue, 
    previous_month_revenue, 
    (total_revenue - previous_month_revenue) AS revenue_change
FROM (
    SELECT DATE_TRUNC('month', o.order_date) AS order_month, 
        SUM(p.selling_price * oi.quantity) AS total_revenue, 
        LAG(SUM(p.selling_price * oi.quantity))
        OVER(
            ORDER BY DATE_TRUNC('month', o.order_date) ASC
        ) AS previous_month_revenue
    FROM retail_analysis.orders o 
    JOIN retail_analysis.order_items oi 
    ON oi.order_id = o.order_id
    JOIN retail_analysis.products p
    ON p.product_id = oi.product_id
    GROUP BY DATE_TRUNC('month', o.order_date)
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+---------------+------------------------+----------------+
|     order_month     | total_revenue | previous_month_revenue | revenue_change |
+---------------------+---------------+------------------------+----------------+
| 2020-01-01 00:00:00 |   192480.00   |          None          |      None      |
| 2020-02-01 00:00:00 |   163215.00   |       192480.00        |   -29265.00    |
| 2020-03-01 00:00:00 |   922026.00   |       163215.00        |   758811.00    |
| 2020-04-01 00:00:00 |   223658.00   |       922026.00        |   -698368.00   |
| 2020-05-01 00:00:00 |   539735.00   |       223658.00        |   316077.00    |
| 2020-06-01 00:00:00 |   299950.00   |       539735.00        |   -239785.00   |
| 2020-07-01 00:00:00 |   236291.00   |       299950.00        |   -63659.00    |
| 2020-08-01 00:00:00 |   347409.00   |       236291.00        |   111118.00    |
| 2020-09-01 00:00:00 |   349861.00   |       347409.00        |    2452.00     |
| 2020-10-01 00:00:00 |   162945.00   |       349861.00        |   -186916.00   |
+---------------------+---------------+------------------------+----------------+
Truncated to displaylimit of 10.

In [57]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
result = (
    merged 
    .assign(revenue = merged['selling_price'] * merged['quantity'])
    .groupby(merged['order_date'].dt.to_period('M'))['revenue']
    .sum()
    .reset_index(name='total_revenue')
    .rename(columns={'order_date' : 'order_month'})
)
result['previous_month_revenue'] = (
    result['total_revenue']
    .shift(1)
)
result['revenue_change'] = (
    result['total_revenue'] - result['previous_month_revenue']
)
result

   order_month  total_revenue  previous_month_revenue  revenue_change
0      2020-01         192480                     NaN             NaN
1      2020-02         163215                192480.0        -29265.0
2      2020-03         922026                163215.0        758811.0
3      2020-04         223658                922026.0       -698368.0
4      2020-05         539735                223658.0        316077.0
..         ...            ...                     ...             ...
67     2025-08         106735                280335.0       -173600.0
68     2025-09         754268                106735.0        647533.0
69     2025-10         281925                754268.0       -472343.0
70     2025-11         238585                281925.0        -43340.0
71     2025-12         230170                238585.0         -8415.0

[72 rows x 4 columns]

Next Exercise — Revenue Growth %

Now calculate:

order_month \
total_revenue \
previous_month_revenue \
revenue_change \
revenue_growth_pct

Formula:

revenue_growth_pct = \
(revenue_change / previous_month_revenue) × 100

Use NULLIF() so you don't get a division-by-zero error.

In [13]:
%%sql 
SELECT order_month, total_revenue, previous_month_revenue, 
    (total_revenue - previous_month_revenue) AS revenue_change,
    (
        (total_revenue - previous_month_revenue)
        / NULLIF(previous_month_revenue, 0)
    ) * 100 AS revenue_growth_pct
FROM (
    SELECT DATE_TRUNC('month', o.order_date) AS order_month,
        SUM(p.selling_price * oi.quantity) AS total_revenue,
        LAG(SUM(p.selling_price * oi.quantity))
        OVER(
            ORDER BY DATE_TRUNC('month', o.order_date) ASC
        ) AS previous_month_revenue
    FROM retail_analysis.orders o
    JOIN retail_analysis.order_items oi 
    ON oi.order_id = o.order_id 
    JOIN retail_analysis.products p 
    ON p.product_id = oi.product_id
    GROUP BY DATE_TRUNC('month', o.order_date)
    ORDER BY order_month ASC
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+---------------+------------------------+----------------+--------------------------+
|     order_month     | total_revenue | previous_month_revenue | revenue_change |    revenue_growth_pct    |
+---------------------+---------------+------------------------+----------------+--------------------------+
| 2020-01-01 00:00:00 |   192480.00   |          None          |      None      |           None           |
| 2020-02-01 00:00:00 |   163215.00   |       192480.00        |   -29265.00    | -15.20417705735660847900 |
| 2020-03-01 00:00:00 |   922026.00   |       163215.00        |   758811.00    |   464.9149894311184600   |
| 2020-04-01 00:00:00 |   223658.00   |       922026.00        |   -698368.00   | -75.74276647296280148300 |
| 2020-05-01 00:00:00 |   539735.00   |       223658.00        |   316077.00    |   141.3215713276520400   |
| 2020-06-01 00:00:00 |   299950.00   |       539735.00        |   -239785.00   | -44.42643148952726801100 |
| 2020-07-01 00:00:00 |   236291.00   |       299950.00        |   -63659.00    | -21.22320386731121853600 |
| 2020-08-01 00:00:00 |   347409.00   |       236291.00        |   111118.00    | 47.02591296325293811400  |
| 2020-09-01 00:00:00 |   349861.00   |       347409.00        |    2452.00     |  0.70579633803384483400  |
| 2020-10-01 00:00:00 |   162945.00   |       349861.00        |   -186916.00   | -53.42578909909935660200 |
+---------------------+---------------+------------------------+----------------+--------------------------+
Truncated to displaylimit of 10.

In [ ]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
result = (
    merged 
    .assign(revenue = merged['selling_price'] * merged['quantity'])
    .groupby(merged['order_date'].dt.to_period('M'))['revenue']
    .sum()
    .reset_index(name='total_revenue')
    .rename(columns={'order_date' : 'order_month'})
)
result['previous_month_revenue'] = (
    result['total_revenue']
    .shift(1)
)
result['revenue_change'] = (
    result['total_revenue'] - result['previous_month_revenue']
)
result['revenue_growth_pct'] = (
    (result['revenue_change'] /
    result['previous_month_revenue'].mask(
        result['previous_month_revenue'] == 0)
    )
    * 100
)
result

,order_month,total_revenue,previous_month_revenue,revenue_change,revenue_growth_pct
0,2020-01,192480,NaN,NaN,NaN
1,2020-02,163215,192480.0,-29265.0,-15.204177
2,2020-03,922026,163215.0,758811.0,464.914989
3,2020-04,223658,922026.0,-698368.0,-75.742766
4,2020-05,539735,223658.0,316077.0,141.321571
...,...,...,...,...,...
67,2025-08,106735,280335.0,-173600.0,-61.925910
68,2025-09,754268,106735.0,647533.0,606.673537
69,2025-10,281925,754268.0,-472343.0,-62.622702
70,2025-11,238585,281925.0,-43340.0,-15.372883
71,2025-12,230170,238585.0,-8415.0,-3.527045

Next Exercise

For each month, find:

order_month \
total_orders

but show only the month with the highest number of orders.

Use DATE_TRUNC() and aggregation. No LIMIT yet.

In [25]:
%%sql
SELECT DATE_TRUNC('month', order_date) AS order_month,
    COUNT(order_id) AS total_order
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date)
HAVING COUNT(order_id) = (
    SELECT MAX(total_order)
    FROM (
        SELECT COUNT(order_id) AS total_order
        FROM retail_analysis.orders
        GROUP BY DATE_TRUNC('month', order_date)
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+---------------------+-------------+
|     order_month     | total_order |
+---------------------+-------------+
| 2023-03-01 00:00:00 |      21     |
+---------------------+-------------+

In [64]:
result = (
    orders 
    .groupby(orders['order_date'].dt.to_period('M'))['order_id']
    .count()
    .reset_index(name='total_orders')
    .rename(columns={'order_date' : 'order_month'})
)
result[result['total_orders'] == result['total_orders'].max()]

   order_month  total_orders
38     2023-03            21

Next Exercise — Very Important

Find the second-highest month by number of orders.

Return:

order_month \
total_orders

Do not use LIMIT or OFFSET.

Use MAX()/subqueries again.

**USING OFFSET AND LIMIT**

In [52]:
%%sql 
SELECT DATE_TRUNC('month', order_date) AS order_month,
    COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY total_orders DESC OFFSET 1
LIMIT 1

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+---------------------+--------------+
|     order_month     | total_orders |
+---------------------+--------------+
| 2021-11-01 00:00:00 |      20      |
+---------------------+--------------+

In [73]:
result = (
    orders 
    .groupby(orders['order_date'].dt.to_period('M'))['order_id']
    .count()
    .reset_index(name='total_orders')
    .rename(columns={'order_date' : 'order_month'})
)
result.sort_values('total_orders',ascending=False).iloc[1].reset_index()

          index       43
0   order_month  2023-08
1  total_orders       20

**without using offset and limit**

In [53]:
%%sql 
SELECT order_month, total_orders_2, row_number
FROM (
    SELECT DATE_TRUNC('month', order_date) AS order_month,
        COUNT(order_id) AS total_orders_2,
        ROW_NUMBER()
        OVER(
            ORDER BY COUNT(order_id) DESC
        ) AS row_number
    FROM retail_analysis.orders
    GROUP BY DATE_TRUNC('month', order_date)
)
WHERE row_number = 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+---------------------+----------------+------------+
|     order_month     | total_orders_2 | row_number |
+---------------------+----------------+------------+
| 2023-08-01 00:00:00 |       20       |     2      |
+---------------------+----------------+------------+

Next Exercise

Using the same monthly order counts, find the top 3 months by number of orders.

Use the method you already understand:

monthly count \
→ ROW_NUMBER() \
→ filter rows 1, 2, 3

No LIMIT.

In [13]:
%%sql
SELECT order_month, total_orders, order_rank
FROM (
    SELECT DATE_TRUNC('month', order_date) AS order_month, 
        COUNT(order_id) AS total_orders,
        ROW_NUMBER()
        OVER(
            ORDER BY COUNT(order_id) DESC
        ) AS order_rank
    FROM retail_analysis.orders
    GROUP BY DATE_TRUNC('month', order_date)
)
WHERE order_rank <= 3;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+---------------------+--------------+------------+
|     order_month     | total_orders | order_rank |
+---------------------+--------------+------------+
| 2023-03-01 00:00:00 |      21      |     1      |
| 2023-08-01 00:00:00 |      20      |     2      |
| 2024-12-01 00:00:00 |      20      |     3      |
+---------------------+--------------+------------+

Next Exercise

Find the month with the lowest number of orders.

Use the same approach with ROW_NUMBER(), but this time rank from lowest to highest.

In [17]:
%%sql 
SELECT order_month, total_orders, order_rank
FROM (
    SELECT DATE_TRUNC('month', order_date) AS order_month,
        COUNT(order_id) AS total_orders,
        ROW_NUMBER()
        OVER(
            ORDER BY COUNT(order_id) ASC
        ) AS order_rank
    FROM retail_analysis.orders 
    GROUP BY DATE_TRUNC('month', order_date)
)
WHERE order_rank = 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+---------------------+--------------+------------+
|     order_month     | total_orders | order_rank |
+---------------------+--------------+------------+
| 2025-08-01 00:00:00 |      7       |     1      |
+---------------------+--------------+------------+

Next Exercise — First Order of Each Customer

Using the orders table, find the first order for each customer.

Return:

customer_id \
order_id \
order_date

Use a window function. Try to use the method you already understand: ROW_NUMBER().

In [27]:
%%sql 
SELECT customer_id, order_id, order_date
FROM (
    SELECT customer_id, order_id, order_date,
    ROW_NUMBER()
    OVER(
        PARTITION BY customer_id
        ORDER BY order_date ASC
    ) AS order_rank
    FROM retail_analysis.orders
)
WHERE order_rank = 1
ORDER BY order_date ASC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+----------+---------------------+
| customer_id | order_id |      order_date     |
+-------------+----------+---------------------+
|  cust_id79  | ord_id1  | 2020-01-01 10:20:46 |
|  cust_id49  | ord_id2  | 2020-01-05 23:47:55 |
|  cust_id66  | ord_id3  | 2020-01-06 15:23:36 |
|   cust_id2  | ord_id4  | 2020-01-08 08:45:37 |
|  cust_id76  | ord_id5  | 2020-01-08 20:11:06 |
|  cust_id69  | ord_id6  | 2020-01-09 13:11:52 |
|  cust_id60  | ord_id7  | 2020-01-13 23:10:04 |
|  cust_id12  | ord_id8  | 2020-01-18 00:11:54 |
|  cust_id32  | ord_id9  | 2020-01-18 02:16:37 |
|  cust_id46  | ord_id10 | 2020-01-21 12:51:09 |
+-------------+----------+---------------------+
Truncated to displaylimit of 10.

In [15]:
result = (
    orders
    .sort_values(
        ['customer_id', 'order_date'],
        ascending=[True, True]
    )
)
result['order_rank'] = (
    result
    .groupby('customer_id')
    .cumcount() +1
)
result[
    ['customer_id', 'order_id', 'order_date']
][result['order_rank'] == 1].sort_values('order_date', ascending=True)

    customer_id   order_id          order_date
0     cust_id79    ord_id1 2020-01-01 10:20:46
1     cust_id49    ord_id2 2020-01-05 23:47:55
2     cust_id66    ord_id3 2020-01-06 15:23:36
3      cust_id2    ord_id4 2020-01-08 08:45:37
4     cust_id76    ord_id5 2020-01-08 20:11:06
..          ...        ...                 ...
295   cust_id41  ord_id296 2021-11-16 21:25:55
343   cust_id38  ord_id344 2022-03-10 18:22:09
359   cust_id83  ord_id360 2022-04-04 22:09:24
373   cust_id61  ord_id374 2022-05-24 17:46:37
527   cust_id18  ord_id528 2023-04-14 07:12:13

[100 rows x 3 columns]

Next Exercise — Last Order of Each Customer

Using the same orders table, find the last order for each customer.

Return:

customer_id \
order_id \
order_date

Use ROW_NUMBER() and PARTITION BY customer_id.

In [34]:
%%sql
SELECT customer_id, order_id, order_date
FROM (
    SELECT customer_id, order_id, order_date,
    ROW_NUMBER()
    OVER(
        PARTITION BY customer_id
        ORDER BY order_date DESC
    ) AS order_rank
    FROM retail_analysis.orders
)
WHERE order_rank = 1
ORDER BY order_date DESC

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+------------+---------------------+
| customer_id |  order_id  |      order_date     |
+-------------+------------+---------------------+
|  cust_id72  | ord_id1000 | 2025-12-30 22:57:38 |
|  cust_id37  | ord_id999  | 2025-12-27 15:01:38 |
|  cust_id36  | ord_id998  | 2025-12-27 00:34:40 |
|  cust_id99  | ord_id997  | 2025-12-24 07:39:12 |
|  cust_id29  | ord_id996  | 2025-12-21 23:08:50 |
|  cust_id69  | ord_id995  | 2025-12-17 15:45:34 |
|   cust_id1  | ord_id994  | 2025-12-16 20:58:12 |
|  cust_id44  | ord_id993  | 2025-12-08 08:51:35 |
|  cust_id47  | ord_id992  | 2025-12-08 01:41:16 |
|  cust_id96  | ord_id991  | 2025-12-07 14:28:03 |
+-------------+------------+---------------------+
Truncated to displaylimit of 10.

In [16]:
result = (
    orders
    .sort_values(
        ['customer_id', 'order_date'],
        ascending=[True, False]
    )
)
result['order_rank'] = (
    result
    .groupby('customer_id')['order_date']
    .cumcount() +1
)
result[
    ['customer_id', 'order_id', 'order_date']
][result['order_rank'] == 1].sort_values('order_date', ascending=False)

    customer_id    order_id          order_date
999   cust_id72  ord_id1000 2025-12-30 22:57:38
998   cust_id37   ord_id999 2025-12-27 15:01:38
997   cust_id36   ord_id998 2025-12-27 00:34:40
996   cust_id99   ord_id997 2025-12-24 07:39:12
995   cust_id29   ord_id996 2025-12-21 23:08:50
..          ...         ...                 ...
717    cust_id8   ord_id718 2024-05-19 16:34:37
669    cust_id9   ord_id670 2024-02-01 18:25:14
649   cust_id59   ord_id650 2023-12-05 04:12:47
625   cust_id74   ord_id626 2023-10-21 21:21:16
426   cust_id13   ord_id427 2022-09-10 02:01:03

[100 rows x 3 columns]

Next Exercise — Customers with Their First & Last Order

For each customer, return:

customer_id \
first_order_date \
last_order_date

Use one query with ROW_NUMBER() and PARTITION BY customer_id.

Try to get both the first and last order dates in the result.

In [43]:
%%sql 
SELECT customer_id, 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date
FROM retail_analysis.orders
GROUP BY customer_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+---------------------+
| customer_id |   first_order_date  |   last_order_date   |
+-------------+---------------------+---------------------+
|  cust_id16  | 2020-05-30 05:38:21 | 2025-03-24 07:54:55 |
|  cust_id78  | 2020-04-01 16:36:31 | 2025-12-05 13:53:49 |
|  cust_id39  | 2020-02-06 01:38:50 | 2025-07-08 01:52:21 |
|  cust_id59  | 2020-03-07 19:01:09 | 2023-12-05 04:12:47 |
|   cust_id6  | 2020-05-08 08:09:10 | 2025-11-07 17:34:39 |
|  cust_id74  | 2020-04-22 10:46:23 | 2023-10-21 21:21:16 |
|  cust_id75  | 2020-02-25 09:50:39 | 2025-09-14 19:17:27 |
|  cust_id56  | 2020-09-20 00:22:56 | 2025-11-30 18:56:32 |
|   cust_id1  | 2020-02-03 02:39:06 | 2025-12-16 20:58:12 |
|  cust_id65  | 2021-08-11 12:56:32 | 2025-06-09 12:30:19 |
+-------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [18]:
result = (
    orders
    .groupby('customer_id')
    .agg(
        first_order_date = ('order_date', 'min'),
        last_order_date = ('order_date', 'max')
    )
    .reset_index()
)
result[
    ['customer_id', 'first_order_date', 'last_order_date']
]

   customer_id    first_order_date     last_order_date
0     cust_id1 2020-02-03 02:39:06 2025-12-16 20:58:12
1    cust_id10 2020-06-25 04:48:35 2025-07-23 14:32:21
2   cust_id100 2020-08-10 16:34:32 2025-01-16 15:30:30
3    cust_id11 2020-11-08 07:32:56 2024-10-30 20:07:59
4    cust_id12 2020-01-18 00:11:54 2025-09-16 08:11:14
..         ...                 ...                 ...
95   cust_id95 2020-03-22 01:06:16 2025-07-25 15:49:29
96   cust_id96 2020-03-10 10:45:16 2025-12-07 14:28:03
97   cust_id97 2020-06-28 11:41:17 2024-09-03 16:54:44
98   cust_id98 2021-02-11 06:45:12 2024-06-23 20:39:31
99   cust_id99 2020-11-09 14:30:32 2025-12-24 07:39:12

[100 rows x 3 columns]

In [ ]:
%%sql
SELECT customer_id, 
    MIN(order_rank) AS first_order_rank, 
    MAX(order_rank) AS last_order_rank
FROM (
    SELECT customer_id,
    ROW_NUMBER()
    OVER(
        PARTITION BY customer_id
        ORDER BY order_date ASC
    ) AS order_rank
    FROM retail_analysis.orders
)
GROUP BY customer_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+------------------+-----------------+
| customer_id | first_order_rank | last_order_rank |
+-------------+------------------+-----------------+
|   cust_id1  |        1         |        9        |
|  cust_id10  |        1         |        8        |
|  cust_id100 |        1         |        13       |
|  cust_id11  |        1         |        12       |
|  cust_id12  |        1         |        7        |
|  cust_id13  |        1         |        4        |
|  cust_id14  |        1         |        11       |
|  cust_id15  |        1         |        19       |
|  cust_id16  |        1         |        12       |
|  cust_id17  |        1         |        13       |
+-------------+------------------+-----------------+
Truncated to displaylimit of 10.

In [22]:
result = (
    orders
    .sort_values(
        ['customer_id', 'order_date']
    )
)
result['order_rank'] = (
    result
    .groupby('customer_id')['order_date']
    .cumcount() +1
)
result = (
    result
    .groupby('customer_id')
    .agg(
        first_order_rank = ('order_rank', 'min'),
        last_order_rank = ('order_rank', 'max')
    )
    .reset_index()
)
result[
    ['customer_id', 'first_order_rank', 'last_order_rank']
]

   customer_id  first_order_rank  last_order_rank
0     cust_id1                 1                9
1    cust_id10                 1                8
2   cust_id100                 1               13
3    cust_id11                 1               12
4    cust_id12                 1                7
..         ...               ...              ...
95   cust_id95                 1                7
96   cust_id96                 1               12
97   cust_id97                 1                9
98   cust_id98                 1                8
99   cust_id99                 1               11

[100 rows x 3 columns]

Next Exercise — Date Range

Find all orders placed during the current week.

Use DATE_TRUNC('week', order_date) and DATE_TRUNC('week', CURRENT_DATE). Don't hard-code any date.

In [58]:
%%sql  
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('week', order_date) = DATE_TRUNC('week', CURRENT_DATE);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [23]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.to_period('W') == pd.Timestamp.today().to_period('W')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise

Find all orders from the previous calendar week.

Use DATE_TRUNC('week', ...) and INTERVAL '1 week'. Do not hard-code dates.

In [64]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('week', order_date) = DATE_TRUNC('week', CURRENT_DATE - INTERVAL '1 week')

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [5]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.to_period('W') == (pd.Timestamp.today() - pd.DateOffset(weeks=1)).to_period('W')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise

Find all orders from the current quarter.

Use DATE_TRUNC('quarter', order_date) and DATE_TRUNC('quarter', CURRENT_DATE).

In [68]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('quarter', order_date) = DATE_TRUNC('quarter', CURRENT_DATE)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [6]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.to_period('Q') == pd.Timestamp.today().to_period('Q')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise

Find all orders from the previous calendar quarter.

Use DATE_TRUNC('quarter', ...) and INTERVAL '3 months'.

In [72]:
%%sql
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('quarter', order_date) = DATE_TRUNC('quarter', CURRENT_DATE - INTERVAL '3 month')

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [8]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'].dt.to_period('Q') == 
    (pd.Timestamp.today() - pd.DateOffset(months=3)).to_period('Q')
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — Year to Date (YTD)

Find all orders placed from the beginning of the current year up to now.

Use DATE_TRUNC('year', CURRENT_DATE) and CURRENT_DATE/NOW(). Don't hard-code any date.

In [75]:
%%sql
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date <= NOW()
    AND order_date >= DATE_TRUNC('year',CURRENT_DATE)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [29]:
orders[
    ['order_id', 'order_date']
][
    (orders['order_date'] <= pd.Timestamp.now()) &
    (orders['order_date'] >= pd.Timestamp.today().to_period('Y').start_time)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise

Find all orders placed from the beginning of the current month up to now.

This is called MTD (Month-to-Date). Use DATE_TRUNC('month', CURRENT_DATE) and NOW().

In [6]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date <= NOW()
    AND order_date >= DATE_TRUNC('month', CURRENT_DATE);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [30]:
orders[
    ['order_id', 'order_date']
][
    (orders['order_date'] <= pd.Timestamp.now()) &
    (orders['order_date'] >= pd.Timestamp.today().to_period('M').start_time)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — QTD

Find all orders placed from the beginning of the current quarter up to now.

Use DATE_TRUNC('quarter', CURRENT_DATE) and NOW().

In [7]:
%%sql
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= DATE_TRUNC('quarter', CURRENT_DATE)
    AND order_date <= NOW();

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [31]:
orders[
    ['order_date', 'order_date']
][
    (orders['order_date'] >= pd.Timestamp.today().to_period('Q').start_time)
    & (orders['order_date'] <= pd.Timestamp.now())
]

Empty DataFrame
Columns: [order_date, order_date]
Index: []

Next Exercise

Find all orders placed in the previous 12 months, using INTERVAL.

Don't use DATE_TRUNC() yet.

In [9]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= now() - INTERVAL '12 months'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

66 rows affected.

+-----------+---------------------+
|  order_id |      order_date     |
+-----------+---------------------+
| ord_id935 | 2025-08-29 22:42:05 |
| ord_id936 | 2025-08-30 16:47:25 |
| ord_id937 | 2025-09-03 04:32:18 |
| ord_id938 | 2025-09-03 01:58:54 |
| ord_id939 | 2025-09-06 04:13:08 |
| ord_id940 | 2025-09-08 06:14:59 |
| ord_id941 | 2025-09-13 10:30:32 |
| ord_id942 | 2025-09-14 19:17:27 |
| ord_id943 | 2025-09-16 08:11:14 |
| ord_id944 | 2025-09-16 00:12:18 |
+-----------+---------------------+
Truncated to displaylimit of 10.

In [32]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'] >= pd.Timestamp.now() - pd.DateOffset(months=12)
]

       order_id          order_date
936   ord_id937 2025-09-03 04:32:18
937   ord_id938 2025-09-03 01:58:54
938   ord_id939 2025-09-06 04:13:08
939   ord_id940 2025-09-08 06:14:59
940   ord_id941 2025-09-13 10:30:32
..          ...                 ...
995   ord_id996 2025-12-21 23:08:50
996   ord_id997 2025-12-24 07:39:12
997   ord_id998 2025-12-27 00:34:40
998   ord_id999 2025-12-27 15:01:38
999  ord_id1000 2025-12-30 22:57:38

[64 rows x 2 columns]

Next Exercise — Rolling Window

Find orders placed in the last 90 days using NOW() and INTERVAL.

Return:

order_id \
order_date

No DATE_TRUNC() or EXTRACT() needed.

In [ ]:
%%sql
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= NOW() - INTERVAL '90 days'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

In [33]:
orders[
    ['order_id', 'order_date']
][
    orders['order_date'] >= pd.Timestamp.now() - pd.Timedelta(days=90)
]

Empty DataFrame
Columns: [order_id, order_date]
Index: []

Next Exercise — Rolling 30-Day Revenue

Using `orders`, `order_items`, and `products`, calculate the **total revenue generated in the last 30 days from now**.

In [11]:
%%sql
SELECT SUM(p.selling_price * oi.quantity) AS total_revenue_30_days
FROM retail_analysis.orders o
JOIN retail_analysis.order_items oi 
ON oi.order_id = o.order_id
JOIN retail_analysis.products p 
ON p.product_id = oi.product_id
WHERE order_date >= NOW() - INTERVAL '30 days'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-----------------------+
| total_revenue_30_days |
+-----------------------+
|          None         |
+-----------------------+

In [41]:
merged = (
    orders
    .merge(order_items, on='order_id')
    .merge(products, on= 'product_id')
)
merged['total_revenue_30_days'] = (
    merged['quantity'] * merged['selling_price']
)
merged[
    ['total_revenue_30_days']
][
    merged['order_date'] >= pd.Timestamp.now() - pd.Timedelta(days=30)
].sum()

total_revenue_30_days    0
dtype: int64

Next Exercise — Same-Day Delivery

Find the orders where the **order and delivery happened on the same calendar day**.

Return:

order_id \
order_date \
delivery_date

Compare only the date, not the time.

In [14]:
%%sql
SELECT order_id, order_date, delivery_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('day', order_date) = DATE_TRUNC('day', delivery_date)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+---------------------+---------------------+
|  order_id |      order_date     |    delivery_date    |
+-----------+---------------------+---------------------+
| ord_id101 | 2020-08-09 06:51:35 | 2020-08-09 15:44:27 |
| ord_id209 | 2021-04-14 03:19:41 | 2021-04-14 20:10:42 |
| ord_id335 | 2022-02-16 23:08:05 | 2022-02-16 23:47:33 |
| ord_id476 | 2023-01-13 01:44:16 | 2023-01-13 14:37:30 |
| ord_id504 | 2023-03-06 14:34:03 | 2023-03-06 15:29:43 |
| ord_id772 | 2024-09-01 13:44:38 | 2024-09-01 20:01:55 |
| ord_id976 | 2025-11-10 15:14:29 | 2025-11-10 20:11:18 |
+-----------+---------------------+---------------------+

In [42]:
orders[
    ['order_id','order_date', 'delivery_date']
][
    orders['order_date'].dt.to_period('D') == 
    orders['delivery_date'].dt.to_period('D')
]

      order_id          order_date       delivery_date
100  ord_id101 2020-08-09 06:51:35 2020-08-09 15:44:27
208  ord_id209 2021-04-14 03:19:41 2021-04-14 20:10:42
334  ord_id335 2022-02-16 23:08:05 2022-02-16 23:47:33
475  ord_id476 2023-01-13 01:44:16 2023-01-13 14:37:30
503  ord_id504 2023-03-06 14:34:03 2023-03-06 15:29:43
771  ord_id772 2024-09-01 13:44:38 2024-09-01 20:01:55
975  ord_id976 2025-11-10 15:14:29 2025-11-10 20:11:18

Next Exercise — Delivery Duration

Find all orders that **took more than 2 days to deliver**.

Return:

order_id \
order_date \
delivery_date \
delivery_days

Use AGE() + EPOCH and calculate fractional days.

In [23]:
%%sql 
SELECT order_id, order_date, delivery_date, delivery_days
FROM (
    SELECT order_id, order_date, delivery_date,
        EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
    FROM retail_analysis.orders
)
WHERE delivery_days > 2;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

754 rows affected.

+----------+---------------------+---------------------+---------------------+
| order_id |      order_date     |    delivery_date    |    delivery_days    |
+----------+---------------------+---------------------+---------------------+
| ord_id1  | 2020-01-01 10:20:46 | 2020-01-05 14:57:53 |  4.1924421296296296 |
| ord_id2  | 2020-01-05 23:47:55 | 2020-01-16 07:52:38 | 10.3366087962962963 |
| ord_id4  | 2020-01-08 08:45:37 | 2020-01-16 10:14:19 |  8.0615972222222222 |
| ord_id5  | 2020-01-08 20:11:06 | 2020-01-20 04:51:13 | 11.3611921296296296 |
| ord_id6  | 2020-01-09 13:11:52 | 2020-01-20 12:15:55 | 10.9611458333333333 |
| ord_id7  | 2020-01-13 23:10:04 | 2020-01-25 05:14:42 | 11.2532175925925926 |
| ord_id8  | 2020-01-18 00:11:54 | 2020-01-29 15:42:41 | 11.6463773148148148 |
| ord_id9  | 2020-01-18 02:16:37 | 2020-01-27 01:45:17 |  8.9782407407407407 |
| ord_id10 | 2020-01-21 12:51:09 | 2020-01-29 21:07:15 |  8.3445138888888889 |
| ord_id11 | 2020-01-21 21:17:24 | 2020-01-30 04:18:50 |  8.2926620370370370 |
+----------+---------------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [50]:
orders['delivery_days'] = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(86400)
orders[
    ['order_id', 'order_date', 'delivery_date','delivery_days']
][
    orders['delivery_days'] > 2
]

       order_id          order_date       delivery_date  delivery_days
0       ord_id1 2020-01-01 10:20:46 2020-01-05 14:57:53       4.192442
1       ord_id2 2020-01-05 23:47:55 2020-01-16 07:52:38      10.336609
3       ord_id4 2020-01-08 08:45:37 2020-01-16 10:14:19       8.061597
4       ord_id5 2020-01-08 20:11:06 2020-01-20 04:51:13      11.361192
5       ord_id6 2020-01-09 13:11:52 2020-01-20 12:15:55      10.961146
..          ...                 ...                 ...            ...
994   ord_id995 2025-12-17 15:45:34 2025-12-25 02:04:47       7.430012
995   ord_id996 2025-12-21 23:08:50 2025-12-29 09:12:34       7.419259
996   ord_id997 2025-12-24 07:39:12 2025-12-31 16:07:38       7.353079
998   ord_id999 2025-12-27 15:01:38 2026-01-05 16:23:52       9.057106
999  ord_id1000 2025-12-30 22:57:38 2026-01-09 16:56:02       9.748889

[754 rows x 4 columns]

Next Exercise

Find all **orders that were delivered within 1 day of being placed**.

Return:

order_id \
order_date \
delivery_date \
delivery_days

Use the same AGE() + EPOCH approach.

In [27]:
%%sql
SELECT order_id, order_date, delivery_date, delivery_days
FROM (
    SELECT order_id, order_date, delivery_date, 
        EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
    FROM retail_analysis.orders
)
WHERE delivery_days <= 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

18 rows affected.

+-----------+---------------------+---------------------+------------------------+
|  order_id |      order_date     |    delivery_date    |     delivery_days      |
+-----------+---------------------+---------------------+------------------------+
|  ord_id21 | 2020-02-18 22:12:42 | 2020-02-19 19:40:56 | 0.89460648148148148148 |
| ord_id101 | 2020-08-09 06:51:35 | 2020-08-09 15:44:27 | 0.37004629629629629630 |
| ord_id154 | 2020-12-03 18:32:17 | 2020-12-04 03:39:40 | 0.38012731481481481481 |
| ord_id174 | 2021-01-24 20:54:04 | 2021-01-25 13:36:06 | 0.69585648148148148148 |
| ord_id209 | 2021-04-14 03:19:41 | 2021-04-14 20:10:42 | 0.70209490740740740741 |
| ord_id335 | 2022-02-16 23:08:05 | 2022-02-16 23:47:33 | 0.02740740740740740741 |
| ord_id360 | 2022-04-04 22:09:24 | 2022-04-05 21:24:26 | 0.96877314814814814815 |
| ord_id405 | 2022-07-25 22:37:01 | 2022-07-26 05:52:51 | 0.30266203703703703704 |
| ord_id476 | 2023-01-13 01:44:16 | 2023-01-13 14:37:30 | 0.53696759259259259259 |
| ord_id504 | 2023-03-06 14:34:03 | 2023-03-06 15:29:43 | 0.03865740740740740741 |
+-----------+---------------------+---------------------+------------------------+
Truncated to displaylimit of 10.

Next Exercise — Average Delivery Time

Find the **average delivery time in days across all orders**.

Return:

average_delivery_days

Use AGE() + EPOCH.

In [28]:
%%sql 
SELECT AVG(EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400) AS avg_delivery_days
FROM retail_analysis.orders

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------------------+
|   avg_delivery_days    |
+------------------------+
| 8.72023762282690854168 |
+------------------------+

In [59]:
result = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(86400).mean()
result

np.float64(8.72023762282691)

**Next Exercise — Delivery Performance**

Find the **percentage of orders delivered within 2 days**.

Return:

percentage_within_2_days

Use CASE, COUNT() and the same fractional-day calculation.

In [18]:
%%sql 
SELECT (COUNT(delivery_days) * 100.0) / (
    SELECT COUNT(order_id)
    FROM retail_analysis.orders
) AS percentage_within_2_days
FROM (
    SELECT EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
    FROM retail_analysis.orders
)
WHERE delivery_days <= 2

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------------------+
| percentage_within_2_days |
+--------------------------+
|    3.0000000000000000    |
+--------------------------+

In [73]:
delivery_days = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(86400)
delivery_days[delivery_days <= 2].count() * 100 / orders['order_id'].count()

np.float64(3.0)

In [17]:
%%sql 
SELECT (
    SELECT COUNT(*)
    FROM (
        SELECT EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
        FROM retail_analysis.orders
    )
    WHERE delivery_days <= 2
) * 100.0 / COUNT(*) AS percentage_within_2_days
FROM retail_analysis.orders

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+--------------------------+
| percentage_within_2_days |
+--------------------------+
|    3.0000000000000000    |
+--------------------------+

Next Exercise

Find the percentage of orders delivered after more than 2 days.

In [28]:
%%sql
SELECT (COUNT(delivery_days) * 100.0) / (
    SELECT COUNT(order_id)
    FROM retail_analysis.orders
) AS percentage_after_2_days
FROM (
    SELECT EXTRACT(EPOCH FROM AGE(delivery_date, order_date)) / 86400 AS delivery_days
    FROM retail_analysis.orders
)
WHERE delivery_days > 2

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------------------+
| percentage_after_2_days |
+-------------------------+
|   75.4000000000000000   |
+-------------------------+

In [ ]:
total_orders = orders['order_id'].count()
total_seconds = (
    orders['delivery_date'] - orders['order_date']
).dt.total_seconds().div(86400)
more_2_days_orders = total_seconds[total_seconds > 2]
more_2_days_orders.count() * 100 / total_orders

np.float64(75.4)

Next Exercise

Find the **percentage of orders delivered exactly on the same calendar day as they were ordered**.

Return:

percentage_same_day

Hint: compare only the date, not the time.

In [38]:
%%sql 
SELECT (COUNT(order_id) * 100.0) / (
    SELECT COUNT(order_id)
    FROM retail_analysis.orders
) AS percentage_same_day
FROM retail_analysis.orders
WHERE DATE_TRUNC('day', order_date) = DATE_TRUNC('day', delivery_date)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------------------+
|  percentage_same_day   |
+------------------------+
| 0.70000000000000000000 |
+------------------------+

Next Exercise — Average Delivery Time by Month

Find the average delivery time (in days) for each month.

Return:

order_month \
average_delivery_days

| Order Date         | Delivery Date |                Delivery Time |
| ------------------ | ------------- | ---------------------------: |
| 2026-08-02         | 2026-08-03    |                        1 day |
| 2026-08-05         | 2026-08-07    |                       2 days |
| 2026-08-10         | 2026-08-13    |                       3 days |
| **August Average** | —             | **(1 + 2 + 3) / 3 = 2 days** |

In [67]:
%%sql
SELECT DATE_TRUNC('month', order_date) AS order_month, 
    AVG(EXTRACT(EPOCH FROM AGE(delivery_date, order_date))) / 86400 AS average_delivery_days 
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY order_month

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+-----------------------+
|     order_month     | average_delivery_days |
+---------------------+-----------------------+
| 2020-01-01 00:00:00 |   8.8276292438271605  |
| 2020-02-01 00:00:00 |   7.0209837962962963  |
| 2020-03-01 00:00:00 |   8.9570958719135802  |
| 2020-04-01 00:00:00 |   8.4377559156378601  |
| 2020-05-01 00:00:00 |   9.3443004918981481  |
| 2020-06-01 00:00:00 |   8.1459027777777778  |
| 2020-07-01 00:00:00 |   9.4929885912698413  |
| 2020-08-01 00:00:00 |   7.7642893518518519  |
| 2020-09-01 00:00:00 |   8.4460813492063492  |
| 2020-10-01 00:00:00 |   9.5830545033670034  |
+---------------------+-----------------------+
Truncated to displaylimit of 10.

Next Exercise

Find the average delivery time in days for each customer.

Return:

customer_id \
average_delivery_days

In [ ]:
%%sql 
SELECT customer_id, 
    AVG(EXTRACT(EPOCH FROM AGE(delivery_date, order_date))) / 86400 AS avg_delivery_days
FROM retail_analysis.orders
GROUP BY customer_id

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+
| customer_id |  avg_delivery_days  |
+-------------+---------------------+
|  cust_id16  |  9.7838580246913580 |
|  cust_id78  |  9.5124273989898990 |
|  cust_id39  | 10.4258188657407407 |
|  cust_id59  | 10.7089351851851852 |
|   cust_id6  |  7.7137300084175084 |
|  cust_id74  |  8.2194579475308642 |
|  cust_id75  |  9.3658805199430199 |
|  cust_id56  |  8.4234375000000000 |
|   cust_id1  |  9.8654591049382716 |
|  cust_id65  |  5.7919367283950617 |
+-------------+---------------------+
Truncated to displaylimit of 10.

Next Exercise — Customer Tenure

Using the customers table, find **how many days each customer has been a customer as of today**.

Return:

customer_id \
customer_name \
tenure_days

In [ ]:
%%sql 
SELECT customer_id, customer_name, 
    EXTRACT(EPOCH FROM AGE(CURRENT_DATE, join_date)) / 86400 AS tenure_days
FROM retail_analysis.customers

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+-----------------------+
| customer_id |    customer_name    |      tenure_days      |
+-------------+---------------------+-----------------------+
|   cust_id1  |      Ikbal Dani     | 3522.2500000000000000 |
|   cust_id2  |      Oni Bobal      | 3498.2500000000000000 |
|   cust_id3  |   Garima Narayanan  | 3497.2500000000000000 |
|   cust_id4  |   Rachana Bhardwaj  | 3488.2500000000000000 |
|   cust_id5  |   Meghana Prakash   | 3487.2500000000000000 |
|   cust_id6  |     Maanas Madan    | 3486.2500000000000000 |
|   cust_id7  |     Ayaan Thaker    | 3461.2500000000000000 |
|   cust_id8  |    Harini Sharma    | 3458.2500000000000000 |
|   cust_id9  | Gayathri Srinivasan | 3434.2500000000000000 |
|  cust_id10  |      Ishwar Oak     | 3417.2500000000000000 |
+-------------+---------------------+-----------------------+
Truncated to displaylimit of 10.

Next Exercise — Inactive Customers

Find customers whose last order was more than 90 days ago.

Return:

customer_id \
last_order_date

In [87]:
%%sql
SELECT customer_id, MAX(order_date) AS last_order_date
FROM retail_analysis.orders
GROUP BY customer_id
HAVING MAX(order_date) <= CURRENT_DATE - INTERVAL '90 days';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+
| customer_id |   last_order_date   |
+-------------+---------------------+
|  cust_id16  | 2025-03-24 07:54:55 |
|  cust_id78  | 2025-12-05 13:53:49 |
|  cust_id39  | 2025-07-08 01:52:21 |
|  cust_id59  | 2023-12-05 04:12:47 |
|   cust_id6  | 2025-11-07 17:34:39 |
|  cust_id74  | 2023-10-21 21:21:16 |
|  cust_id75  | 2025-09-14 19:17:27 |
|  cust_id56  | 2025-11-30 18:56:32 |
|   cust_id1  | 2025-12-16 20:58:12 |
|  cust_id65  | 2025-06-09 12:30:19 |
+-------------+---------------------+
Truncated to displaylimit of 10.

Next Exercise

Find customers whose last order was within the last 30 days.

Return:

customer_id \
last_order_date

In [88]:
%%sql
SELECT customer_id, MAX(order_date) AS last_order_date
FROM retail_analysis.orders
GROUP BY customer_id
HAVING MAX(order_date) >= CURRENT_DATE - INTERVAL '30 days'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+-----------------+
| customer_id | last_order_date |
+-------------+-----------------+
+-------------+-----------------+

Next Exercise — Customer Reactivation

Find customers whose first order was more than 1 year ago, but whose last order was within the last 30 days.

Return:

customer_id \
first_order_date \
last_order_date

Use MIN(), MAX(), and HAVING.

In [9]:
%%sql
SELECT customer_id, 
    MIN(order_date) AS first_order_date, 
    MAX(order_date) AS last_order_date
FROM retail_analysis.orders
GROUP BY customer_id
HAVING MIN(order_date) < CURRENT_DATE - INTERVAL '1 year'
    AND MAX(order_date) > CURRENT_DATE - INTERVAL '30 days';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+------------------+-----------------+
| customer_id | first_order_date | last_order_date |
+-------------+------------------+-----------------+
+-------------+------------------+-----------------+

Next Exercise — Repeat Purchase

Find customers **who placed at least 2 orders within the same calendar month**.

Return:

customer_id \
order_month \
total_orders

Use DATE_TRUNC('month', order_date) and GROUP BY.

In [38]:
%%sql 
SELECT customer_id, 
    DATE_TRUNC('month', order_date) AS order_month, 
    COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY customer_id, DATE_TRUNC('month', order_date)
HAVING COUNT(order_id) >= 2
ORDER BY order_month

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

59 rows affected.

+-------------+---------------------+--------------+
| customer_id |     order_month     | total_orders |
+-------------+---------------------+--------------+
|  cust_id46  | 2020-01-01 00:00:00 |      2       |
|  cust_id51  | 2020-03-01 00:00:00 |      2       |
|  cust_id96  | 2020-05-01 00:00:00 |      2       |
|  cust_id53  | 2020-06-01 00:00:00 |      2       |
|  cust_id15  | 2020-07-01 00:00:00 |      2       |
|   cust_id4  | 2020-07-01 00:00:00 |      2       |
|  cust_id37  | 2020-08-01 00:00:00 |      2       |
|  cust_id27  | 2020-09-01 00:00:00 |      2       |
|  cust_id89  | 2020-10-01 00:00:00 |      2       |
|  cust_id43  | 2020-10-01 00:00:00 |      2       |
+-------------+---------------------+--------------+
Truncated to displaylimit of 10.

Next Exercise — Order Gap

For **each customer**, find the **number of days between their first and second order.**

Return:

customer_id \
first_order_date \
second_order_date \
days_between

Use ROW_NUMBER(), AGE(), and EPOCH.

In [ ]:
%%sql 
SELECT customer_id, first_order_date, second_order_date,
    EXTRACT(EPOCH FROM AGE(second_order_date, first_order_date)) / 86400 AS days_between
FROM (
    SELECT customer_id, 
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS second_order_date
    FROM (
        SELECT customer_id, order_date,
        ROW_NUMBER()
        OVER(
            PARTITION BY customer_id
            ORDER BY order_date ASC
        ) AS order_number
        FROM retail_analysis.orders
    )
    WHERE order_number IN (1,2)
    GROUP BY customer_id
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+---------------------+---------------------+----------------------+
| customer_id |   first_order_date  |  second_order_date  |     days_between     |
+-------------+---------------------+---------------------+----------------------+
|   cust_id1  | 2020-02-03 02:39:06 | 2020-09-17 00:33:39 | 223.9128819444444444 |
|  cust_id10  | 2020-06-25 04:48:35 | 2023-01-28 07:05:40 | 943.5951967592592593 |
|  cust_id100 | 2020-08-10 16:34:32 | 2020-10-08 12:58:08 | 58.8497222222222222  |
|  cust_id11  | 2020-11-08 07:32:56 | 2021-10-13 13:20:17 | 335.2412152777777778 |
|  cust_id12  | 2020-01-18 00:11:54 | 2020-06-15 12:13:14 | 148.5009259259259259 |
|  cust_id13  | 2020-08-08 04:44:15 | 2021-11-22 17:32:27 | 469.7834722222222222 |
|  cust_id14  | 2020-12-19 02:15:24 | 2021-07-07 15:19:21 | 199.5444097222222222 |
|  cust_id15  | 2020-07-26 10:38:17 | 2020-07-29 01:51:15 |  2.6340046296296296  |
|  cust_id16  | 2020-05-30 05:38:21 | 2021-05-22 03:25:23 | 352.9076620370370370 |
|  cust_id17  | 2020-02-28 02:40:29 | 2020-10-25 12:51:06 | 236.4240393518518519 |
+-------------+---------------------+---------------------+----------------------+
Truncated to displaylimit of 10.

Next Exercise — Customer Purchase Frequency

For **each customer**, **calculate their average number of days between orders**.

Return:

customer_id \
average_days_between_orders

Hint: first calculate the gap between consecutive orders, then take AVG() for each customer.

Use LAG(), AGE(), and EPOCH().

In [17]:
%%sql 
SELECT customer_id, AVG(days_between_orders) AS avg_days_between_orders
FROM (
    SELECT customer_id,
        EXTRACT(EPOCH FROM AGE(order_date, previous_date)) / 86400 AS days_between_orders
    FROM (
        SELECT customer_id, order_date,
        LAG(order_date)
        OVER(
            PARTITION BY customer_id
            ORDER BY order_date ASC
        ) AS previous_date
        FROM retail_analysis.orders
    )
)
GROUP BY customer_id

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

100 rows affected.

+-------------+-------------------------+
| customer_id | avg_days_between_orders |
+-------------+-------------------------+
|   cust_id1  |   265.9079079861111111  |
|  cust_id10  |   263.8793419312169312  |
|  cust_id100 |   133.8504610339506173  |
|  cust_id11  |   130.2294854797979798  |
|  cust_id12  |   342.8471450617283951  |
|  cust_id13  |   252.7122222222222222  |
|  cust_id14  |   157.8243981481481481  |
|  cust_id15  |   100.5672292952674897  |
|  cust_id16  |   158.4858943602693603  |
|  cust_id17  |   173.5281847993827160  |
+-------------+-------------------------+
Truncated to displaylimit of 10.

Next Exercise — Monthly Customer Activity

**For each calendar month, find the number of distinct customers who placed at least one order during that month.**

Return:

order_month \
unique_customers

In [18]:
%%sql
SELECT DATE_TRUNC('month', order_date) AS order_month, 
    COUNT(DISTINCT customer_id) AS unique_customers
FROM retail_analysis.orders
GROUP BY DATE_TRUNC('month', order_date)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

72 rows affected.

+---------------------+------------------+
|     order_month     | unique_customers |
+---------------------+------------------+
| 2020-01-01 00:00:00 |        11        |
| 2020-02-01 00:00:00 |        14        |
| 2020-03-01 00:00:00 |        15        |
| 2020-04-01 00:00:00 |        12        |
| 2020-05-01 00:00:00 |        17        |
| 2020-06-01 00:00:00 |        7         |
| 2020-07-01 00:00:00 |        14        |
| 2020-08-01 00:00:00 |        13        |
| 2020-09-01 00:00:00 |        12        |
| 2020-10-01 00:00:00 |        12        |
+---------------------+------------------+
Truncated to displaylimit of 10.

Find only those **customers who have placed at least 1 order in each month**. Return `customer_id` and `active_months`.

<pre>
cust months
A 1           total_months 1,2 = 2
B 1           cust  active_months
C 1           A 1,2 = 2 | cust = total_distinct_month
D 1           B 1,2 = 2 | 2 = 2 ✅
A 2           C 1,2 = 2 |
B 2           D 1,  = 1 | 1 = 2 ❌
C 2           E  ,2 = 1
E 2
</pre>

In [23]:
%%sql
SELECT customer_id, COUNT(DISTINCT DATE_TRUNC('month', order_date)) AS active_month
FROM retail_analysis.orders
GROUP BY customer_id
HAVING COUNT(DISTINCT DATE_TRUNC('month', order_date)) = (
    SELECT COUNT(DISTINCT DATE_TRUNC('month', order_date))
    FROM retail_analysis.orders
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+--------------+
| customer_id | active_month |
+-------------+--------------+
+-------------+--------------+

Find only those **customers who have placed at least 2 orders in each month**. Return `customer_id` and `active_months`.

In [8]:
%%sql 
SELECT customer_id, COUNT(*) AS active_months
FROM (
    SELECT customer_id, DATE_TRUNC('month', order_date) AS order_month
    FROM retail_analysis.orders
    GROUP BY customer_id, DATE_TRUNC('month', order_date)
    HAVING COUNT(*) >= 2
) AS monthly_orders
GROUP BY customer_id
HAVING COUNT(*) = (
    SELECT COUNT(DISTINCT DATE_TRUNC('month', order_date))
    FROM retail_analysis.orders
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | active_months |
+-------------+---------------+
+-------------+---------------+

Find only those **customers who have placed at least 3 orders in each month**. Return `customer_id` and `active_months`.

In [10]:
%%sql 
SELECT customer_id, COUNT(*) AS active_months
FROM (
    SELECT customer_id, DATE_TRUNC('month', order_date) AS order_month
    FROM retail_analysis.orders
    GROUP BY customer_id, order_month
    HAVING COUNT(*) >= 3
) AS monthly_orders
GROUP BY customer_id
HAVING COUNT(*) = (
    SELECT COUNT(DISTINCT DATE_TRUNC('month', order_date))
    FROM retail_analysis.orders
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | active_months |
+-------------+---------------+
+-------------+---------------+

Next Question — Monthly Repeat Customers

For **each month**, **count the customers who placed at least 2 orders during that month**.

Return:

order_month \
repeat_customers

In [36]:
%%sql
SELECT order_month,
    COUNT(customer_id) AS repeat_customers
FROM (
    SELECT customer_id,
        DATE_TRUNC('month', order_date) AS order_month,
        COUNT(order_id) AS total_orders
    FROM retail_analysis.orders
    GROUP BY customer_id, DATE_TRUNC('month', order_date)
    HAVING COUNT(order_id) >= 2
) AS monthly_customer_orders
GROUP BY order_month
ORDER BY order_month;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

40 rows affected.

+---------------------+------------------+
|     order_month     | repeat_customers |
+---------------------+------------------+
| 2020-01-01 00:00:00 |        1         |
| 2020-03-01 00:00:00 |        1         |
| 2020-05-01 00:00:00 |        1         |
| 2020-06-01 00:00:00 |        1         |
| 2020-07-01 00:00:00 |        2         |
| 2020-08-01 00:00:00 |        1         |
| 2020-09-01 00:00:00 |        1         |
| 2020-10-01 00:00:00 |        2         |
| 2020-11-01 00:00:00 |        2         |
| 2021-03-01 00:00:00 |        2         |
+---------------------+------------------+
Truncated to displaylimit of 10.

Practice Question

Find orders placed on August 30, regardless of their time.

In [44]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date::DATE = '2026-08-30'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

30 August for each every years

In [45]:
%%sql 
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE TO_CHAR(order_date, 'MM-DD') = '08-30'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+-----------+---------------------+
|  order_id |      order_date     |
+-----------+---------------------+
| ord_id110 | 2020-08-30 18:56:17 |
| ord_id263 | 2021-08-30 15:34:53 |
| ord_id595 | 2023-08-30 20:02:56 |
| ord_id768 | 2024-08-30 09:01:42 |
| ord_id770 | 2024-08-30 16:55:53 |
| ord_id936 | 2025-08-30 16:47:25 |
+-----------+---------------------+

Next: DATE vs TIMESTAMP — Practical Question

Find orders placed between August 30, 2026 at 10:00 AM and August 30, 2026 at 6:00 PM.

In [48]:
%%sql
SELECT order_id, order_date
FROM retail_analysis.orders
WHERE order_date >= '2026-08-30 10:00:00' 
    AND order_date <= '2026-08-30 18:00:00';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+------------+
| order_id | order_date |
+----------+------------+
+----------+------------+

Find orders where delivery_date is missing (NULL).

In [51]:
%%sql
SELECT order_id, delivery_date
FROM retail_analysis.orders
WHERE delivery_date IS NULL;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

216 rows affected.

+----------+---------------+
| order_id | delivery_date |
+----------+---------------+
| ord_id13 |      None     |
| ord_id14 |      None     |
| ord_id15 |      None     |
| ord_id19 |      None     |
| ord_id25 |      None     |
| ord_id26 |      None     |
| ord_id30 |      None     |
| ord_id40 |      None     |
| ord_id41 |      None     |
| ord_id42 |      None     |
+----------+---------------+
Truncated to displaylimit of 10.

Next — DATE vs TIMESTAMP

**Find orders that were delivered on the same calendar date as they were ordered, regardless of the time.**

In [55]:
%%sql
SELECT order_id, order_date, delivery_date
FROM retail_analysis.orders
WHERE DATE_TRUNC('day', order_date) = DATE_TRUNC('day', delivery_date)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

7 rows affected.

+-----------+---------------------+---------------------+
|  order_id |      order_date     |    delivery_date    |
+-----------+---------------------+---------------------+
| ord_id101 | 2020-08-09 06:51:35 | 2020-08-09 15:44:27 |
| ord_id209 | 2021-04-14 03:19:41 | 2021-04-14 20:10:42 |
| ord_id335 | 2022-02-16 23:08:05 | 2022-02-16 23:47:33 |
| ord_id476 | 2023-01-13 01:44:16 | 2023-01-13 14:37:30 |
| ord_id504 | 2023-03-06 14:34:03 | 2023-03-06 15:29:43 |
| ord_id772 | 2024-09-01 13:44:38 | 2024-09-01 20:01:55 |
| ord_id976 | 2025-11-10 15:14:29 | 2025-11-10 20:11:18 |
+-----------+---------------------+---------------------+