In [5]:
print('welcome')

welcome

In [6]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [1]:
import pandas as pd

In [2]:
products = pd.read_csv(r'd:\SQL\data generator\output\products.csv')
customers = pd.read_csv(r'd:\SQL\data generator\output\customers.csv')
orders = pd.read_csv(r'd:\SQL\data generator\output\orders.csv')
order_items = pd.read_csv(r'd:\SQL\data generator\output\order_items.csv')

<pre>Question 21 — LEFT JOIN

Find all customers and their total number of orders. 
Include customers who have never placed an order.

customer_id
customer_name
total_orders
</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].count() as total_orders
customers *1* *2* A 
orders *1* 3 B
LEFT JOIN
</pre>

In [10]:
merged = pd.merge(customers, orders, on='customer_id', how='left')
total_orders = (
    merged
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

  customer_id  customer_name  total_orders
0   cust_id01    Teerth Nagy            25
1   cust_id02    Jagat Palan            24
2   cust_id03  Isaiah Dhawan            21
3   cust_id04   Chatura Gera            19

In [11]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(O.order_id) AS total_orders
FROM retail_analysis.customers c 
LEFT JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+--------------+
| customer_id |      customer_name       | total_orders |
+-------------+--------------------------+--------------+
|  cust_id07  |      Sanaya Oommen       |      21      |
|  cust_id39  |      Gautami Ravel       |      18      |
|  cust_id47  |        Ekaraj Dua        |      21      |
|  cust_id50  |  Mitali Balasubramanian  |      16      |
|  cust_id45  |       Raghav Sethi       |      13      |
|  cust_id35  |     Vaishnavi Baria      |      24      |
|  cust_id09  | Rajeshri Balasubramanian |      13      |
|  cust_id49  |        Qushi Sood        |      21      |
|  cust_id27  |       Jyoti Andra        |      19      |
|  cust_id08  |        Abeer Rout        |      20      |
+-------------+--------------------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 22 — LEFT JOIN + HAVING

Find customers who have placed at least 5 orders. 
Display customer_id, customer_name, and total_orders.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].count() as total_orders
having total_orders >= 5

customers 1* 2 A
orders 1* 3 B
INNER JOIN
</pre>

In [11]:
merged = pd.merge(customers, orders, on='customer_id')
total_orders = (
    merged
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders[total_orders['total_orders'] >= 5].head(4)

  customer_id  customer_name  total_orders
0   cust_id01    Teerth Nagy            25
1   cust_id02    Jagat Palan            24
2   cust_id03  Isaiah Dhawan            21
3   cust_id04   Chatura Gera            19

In [13]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) >= 5;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+--------------+
| customer_id |      customer_name       | total_orders |
+-------------+--------------------------+--------------+
|  cust_id07  |      Sanaya Oommen       |      21      |
|  cust_id39  |      Gautami Ravel       |      18      |
|  cust_id47  |        Ekaraj Dua        |      21      |
|  cust_id50  |  Mitali Balasubramanian  |      16      |
|  cust_id45  |       Raghav Sethi       |      13      |
|  cust_id35  |     Vaishnavi Baria      |      24      |
|  cust_id09  | Rajeshri Balasubramanian |      13      |
|  cust_id49  |        Qushi Sood        |      21      |
|  cust_id27  |       Jyoti Andra        |      19      |
|  cust_id08  |        Abeer Rout        |      20      |
+-------------+--------------------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 23

Find all customers who have placed orders, 
along with their total number of orders. 
Also include customers who have never placed an order.
customer_id
customer_name
total_orders</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].count() as total_orders
customers 1* 2* 
orders 1* 3
left join
</pre>

In [14]:
merged = pd.merge(customers, orders, on='customer_id', how='left')
total_orders = (
    merged
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

  customer_id  customer_name  total_orders
0   cust_id01    Teerth Nagy            25
1   cust_id02    Jagat Palan            24
2   cust_id03  Isaiah Dhawan            21
3   cust_id04   Chatura Gera            19

In [14]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
FROM retail_analysis.customers c 
LEFT JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+--------------+
| customer_id |      customer_name       | total_orders |
+-------------+--------------------------+--------------+
|  cust_id07  |      Sanaya Oommen       |      21      |
|  cust_id39  |      Gautami Ravel       |      18      |
|  cust_id47  |        Ekaraj Dua        |      21      |
|  cust_id50  |  Mitali Balasubramanian  |      16      |
|  cust_id45  |       Raghav Sethi       |      13      |
|  cust_id35  |     Vaishnavi Baria      |      24      |
|  cust_id09  | Rajeshri Balasubramanian |      13      |
|  cust_id49  |        Qushi Sood        |      21      |
|  cust_id27  |       Jyoti Andra        |      19      |
|  cust_id08  |        Abeer Rout        |      20      |
+-------------+--------------------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 24 — Right-side unmatched records

Find all orders that do not have a matching customer record. 
Display order_id and customer_id.</pre>

<pre>
orders[order_id]
customers[customer_id]
customers 1 2
orders 1 3*
RIGHT JOIN
where A is null
</pre>

In [17]:
merged = pd.merge(customers, orders, on='customer_id', how='right')
merged[
    ['order_id', 'customer_id']
][merged['customer_name'].isna()]

Empty DataFrame
Columns: [order_id, customer_id]
Index: []

In [15]:
%%sql 
SELECT o.order_id, c.customer_id
FROM retail_analysis.customers c 
RIGHT JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
WHERE c.customer_id IS NULL;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+----------+-------------+
| order_id | customer_id |
+----------+-------------+
+----------+-------------+

<pre>
Question 25 — FULL OUTER JOIN

Find all customers and all orders, 
including records that do not have a match in the other table. 
Display customer_id and order_id.
</pre>

<pre>
customers[customer_id],
orders[order_id]
customers 1* 2*
orders 1* 3*
FULL JOIN
<pre>

In [19]:
merged = pd.merge(customers, orders, on='customer_id', how='outer')
merged[
    ['customer_id', 'order_id']
].head(4)

  customer_id   order_id
0   cust_id01   ORD_ID08
1   cust_id01  ORD_ID101
2   cust_id01  ORD_ID159
3   cust_id01  ORD_ID218

In [17]:
%%sql 
SELECT c.customer_id, o.order_id
FROM retail_analysis.customers c 
FULL JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+-------------+----------+
| customer_id | order_id |
+-------------+----------+
|  cust_id30  | ORD_ID01 |
|  cust_id14  | ORD_ID02 |
|  cust_id35  | ORD_ID03 |
|  cust_id50  | ORD_ID04 |
|  cust_id23  | ORD_ID05 |
|  cust_id04  | ORD_ID06 |
|  cust_id34  | ORD_ID07 |
|  cust_id01  | ORD_ID08 |
|  cust_id47  | ORD_ID09 |
|  cust_id44  | ORD_ID10 |
+-------------+----------+
Truncated to displaylimit of 10.

<pre>
Question 26 — Full Anti Join

Find all records that exist only on one side: 
customers without orders AND orders without customers. 
Display customer_id and order_id.
<pre>

<pre>
customers[customer_id],
orders[order_id]
customers 1 2*
orders 1 3*
FULL EXCLUSIVE JOIN
</pre>

In [21]:
merged = pd.merge(customers, orders, on='customer_id', how='outer')
merged[
    ['customer_id', 'order_id']
][merged['customer_name'].isna() | merged['order_id'].isna()]

Empty DataFrame
Columns: [customer_id, order_id]
Index: []

In [19]:
%%sql 
SELECT c.customer_id, o.order_id
FROM retail_analysis.customers c 
FULL JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
WHERE c.customer_id IS NULL OR o.order_id IS NULL;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+----------+
| customer_id | order_id |
+-------------+----------+
+-------------+----------+

<pre>Question 27 — JOIN + Aggregation

Find the total number of products purchased by each customer. 
Include customers who have never placed an order. 
Display customer_id, customer_name, and total_products_purchased.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
order_items[quantity].sum() as total_product_purchased
customers 1* 2*
order_items 1* 3
LEFT JOIN
</pre>

**COALESCE(null, 23) \
NULL values replace with , num**

In [28]:
merged = (
    customers 
    .merge(orders, on='customer_id', how='left')
    .merge(order_items, on='order_id', how='left')
)
total_product_purchased = (
    merged 
    .groupby(['customer_id', 'customer_name'])['quantity']
    .sum()
).reset_index(name='total_product_purchased')

total_product_purchased['total_product_purchased'] = (
    total_product_purchased['total_product_purchased'].fillna(0)
) # this is default so not needed
total_product_purchased.head(4)

  customer_id  customer_name  total_product_purchased
0   cust_id01    Teerth Nagy                      118
1   cust_id02    Jagat Palan                      130
2   cust_id03  Isaiah Dhawan                      111
3   cust_id04   Chatura Gera                      114

In [21]:
%%sql 
SELECT c.customer_id, c.customer_name, COALESCE(SUM(oi.quantity),0) AS total_product_purchased
FROM retail_analysis.customers c 
LEFT JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id 
LEFT JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+-------------------------+
| customer_id |      customer_name       | total_product_purchased |
+-------------+--------------------------+-------------------------+
|  cust_id07  |      Sanaya Oommen       |           139           |
|  cust_id39  |      Gautami Ravel       |           126           |
|  cust_id47  |        Ekaraj Dua        |            95           |
|  cust_id50  |  Mitali Balasubramanian  |            94           |
|  cust_id45  |       Raghav Sethi       |            61           |
|  cust_id35  |     Vaishnavi Baria      |           138           |
|  cust_id09  | Rajeshri Balasubramanian |            88           |
|  cust_id49  |        Qushi Sood        |           113           |
|  cust_id27  |       Jyoti Andra        |            92           |
|  cust_id08  |        Abeer Rout        |            97           |
+-------------+--------------------------+-------------------------+
Truncated to displaylimit of 10.

<pre>Question 28 — Product Coverage

Find all products that have never been ordered.
Display product_id and product_name.<pre>

<pre>
products[product_id],
products[product_name]
products 1 2*
order_items 1 3
LEFT EXCLUSIVE JOIN
<pre>

In [29]:
merged = pd.merge(products, order_items, on='product_id', how='left')
merged[
    ['product_id', 'product_name']
][merged['order_id'].isna()]

Empty DataFrame
Columns: [product_id, product_name]
Index: []

In [24]:
%%sql 
SELECT p.product_id, p.product_name
FROM retail_analysis.products p 
LEFT JOIN retail_analysis.order_items oi 
ON p.product_id = oi.product_id
WHERE oi.order_id IS NULL;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+------------+--------------+
| product_id | product_name |
+------------+--------------+
+------------+--------------+

<pre>Question 29 — Product Sales Coverage

Find every product along with its total quantity sold. 
Include products that have never been ordered. 
For products with no orders, show 0 instead of NULL.<pre>

<pre>
products[product_name],
order_items[quantity].sum() as total_quantity_sold
products 1* 2*
order_items 1* 3
</pre>

In [33]:
merged = pd.merge(products, order_items, on='product_id', how='left')
total_quantity_sold = (
    merged
    .groupby('product_name')['quantity']
    .sum()
).reset_index(name='total_quantity_sold')
total_quantity_sold.head(4)

        product_name  total_quantity_sold
0          Air Fryer                   98
1             Blazer                   86
2  Bluetooth Speaker                  101
3        Cargo Pants                  117

In [ ]:
%%sql 
SELECT p.product_name, COALESCE(SUM(oi.quantity), 0) AS total_quantity_sold
FROM retail_analysis.products p 
LEFT JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+--------------+---------------------+
| product_name | total_quantity_sold |
+--------------+---------------------+
|    Hoodie    |         149         |
|    Dress     |          76         |
| Fitness Band |         143         |
|   Charger    |         147         |
|    Webcam    |         167         |
|  Smartphone  |         156         |
|   Printer    |          79         |
|   Scanner    |          94         |
|   T-Shirt    |          72         |
| Cargo Pants  |         117         |
+--------------+---------------------+
Truncated to displaylimit of 10.

<pre>Question 31

Find all customers who have placed orders, and display their customer_id, 
customer_name, and total number of orders. 
Include only customers with at least
one order, and sort by total_orders from highest to lowest.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].COUNT() AS total_orders
HAVING orders[order_id].count() >= 1
ORDER BY total_ordes DESC
customers 1* 2 
orders 1* 3
</pre>

In [35]:
merged = pd.merge(customers, orders, on='customer_id')
total_orders = (
    merged 
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders[total_orders['total_orders'] >= 1].sort_values('total_orders', ascending = False).head()

   customer_id    customer_name  total_orders
24   cust_id25   Harsh Bhargava            32
22   cust_id23     Jagat Chawla            28
17   cust_id18   Samarth Thakur            26
5    cust_id06  Vidhi Prabhakar            26
16   cust_id17        Abeer Raj            26

In [ ]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) >= 1 # not needed
ORDER BY total_orders DESC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+-----------------+--------------+
| customer_id |  customer_name  | total_orders |
+-------------+-----------------+--------------+
|  cust_id25  |  Harsh Bhargava |      32      |
|  cust_id23  |   Jagat Chawla  |      28      |
|  cust_id06  | Vidhi Prabhakar |      26      |
|  cust_id17  |    Abeer Raj    |      26      |
|  cust_id18  |  Samarth Thakur |      26      |
|  cust_id30  |    Kashvi Sem   |      25      |
|  cust_id01  |   Teerth Nagy   |      25      |
|  cust_id02  |   Jagat Palan   |      24      |
|  cust_id35  | Vaishnavi Baria |      24      |
|  cust_id12  |  Samuel Sanghvi |      24      |
+-------------+-----------------+--------------+
Truncated to displaylimit of 10.

<pre>
Find all customers who have placed exactly one order. 
Display customer_id, customer_name, and total_orders.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].COUNT() AS total_orders
HAVING total_orders = 1;
customers 1* 2
order 1* 3
</pre>

In [36]:
merged = pd.merge(customers, orders, on='customer_id')
total_orders = (
    merged
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders[total_orders['total_orders'] == 1]

Empty DataFrame
Columns: [customer_id, customer_name, total_orders]
Index: []

In [20]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) = 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+--------------+
| customer_id | customer_name | total_orders |
+-------------+---------------+--------------+
+-------------+---------------+--------------+

<pre>Question 33 — LEFT JOIN + Aggregation

Find all product categories and their total quantity sold. 
Include categories whose products have never been ordered. 
For categories with no sales, show 0.</pre>

<pre>
DISTINCT products[category],
order_items[quantity].sum() as total_quantity_sold (coalesce(0))
products 1* 2*
order_items 1* 3
LEFT JOIN
</pre>

In [37]:
merged = pd.merge(products, order_items, on='product_id', how='left')
total_quantity_sold = (
    merged
    .groupby('category')['quantity']
    .sum()
).reset_index(name='total_quantity_sold')
total_quantity_sold['total_quantity_sold'] = (
    total_quantity_sold['total_quantity_sold'].fillna(0)
)
total_quantity_sold.head(4)

         category  total_quantity_sold
0        Clothing                 2041
1     Electronics                 2240
2  Home & Kitchen                 1119

In [21]:
%%sql 
SELECT p.category, COALESCE(SUM(oi.quantity), 0) AS total_quantity_sold
FROM retail_analysis.products p 
LEFT JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+----------------+---------------------+
|    category    | total_quantity_sold |
+----------------+---------------------+
| Home & Kitchen |         1119        |
|  Electronics   |         2240        |
|    Clothing    |         2041        |
+----------------+---------------------+

<pre>Question 35

Find all products that have been ordered at least once, 
along with the total quantity sold for each product. 
Sort the result by total quantity sold from highest to lowest.</pre>

<pre>
DISTINCT products[product_id], 
DISTINCT products[product_name],
order_items[quantity].sum() AS total_quantity_sold
HAVING order_items[order_id].count() >= 1 # optional
ORDER BY total_quantity_sold DESC
products 1* 2
orde_items 1* 3
</pre>

In [39]:
merged = pd.merge(products, order_items, on='product_id')
total_quantity_sold = (
    merged
    .groupby(['product_id', 'product_name'])['quantity']
    .sum()
).reset_index(name='total_quantity_sold')
total_quantity_sold.sort_values('total_quantity_sold', ascending=False).head(4)

   product_id product_name  total_quantity_sold
14     P_ID15       Webcam                  167
27     P_ID28        Jeans                  157
0      P_ID01   Smartphone                  156
8      P_ID09      Earbuds                  150

In [23]:
%%sql 
SELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity_sold
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+---------------+---------------------+
| product_id |  product_name | total_quantity_sold |
+------------+---------------+---------------------+
|   P_ID15   |     Webcam    |         167         |
|   P_ID28   |     Jeans     |         157         |
|   P_ID01   |   Smartphone  |         156         |
|   P_ID09   |    Earbuds    |         150         |
|   P_ID24   |     Hoodie    |         149         |
|   P_ID18   |    Charger    |         147         |
|   P_ID12   |  Fitness Band |         143         |
|   P_ID11   |   Smartwatch  |         137         |
|   P_ID42   | Non-Stick Pan |         137         |
|   P_ID29   |    Trousers   |         134         |
+------------+---------------+---------------------+
Truncated to displaylimit of 10.

<pre>Question 36 — FULL JOIN + filtering

Find all customers and orders that do not have a matching record
 on the other side. Display customer_id and order_id.<pre>

<pre>
customers[customer_id],
orders[order_id]
customers 1 2*
orders 1 3*
</pre>

In [3]:
merged = pd.merge(customers, orders, on='customer_id', how='outer')
merged[
    ['customer_id', 'order_id']
][merged['customer_name'].isna() | merged['order_id'].isna()]

Empty DataFrame
Columns: [customer_id, order_id]
Index: []

In [27]:
%%sql 
SELECT c.customer_id, o.order_id
FROM retail_analysis.customers c 
FULL JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
WHERE c.customer_id IS NULL OR o.order_id IS NULL;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+----------+
| customer_id | order_id |
+-------------+----------+
+-------------+----------+

<pre>
Question 37 — Mixed JOIN + Aggregation

Find all customers and their total revenue. 
Include customers who have never placed an order, 
and show 0 revenue for them. 
Sort by total revenue from highest to lowest.

customer_id
customer_name
total_revenue
</pre>

<pre>
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantity]).sum() AS total_revenue
ORDER BY total_revenue DESC
customers 1* 2* (o revenue for 2*)
products 1* 3
</pre>

In [15]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_revenue'] = (
    merged['selling_price'] * merged['quantity']
)
total_revenue = (
    merged
    .groupby(['customer_name', 'customer_id'])['total_revenue']
    .sum()
).reset_index(name='total_revenue')
total_revenue.sort_values('total_revenue', ascending=False).head(4)

     customer_name customer_id  total_revenue
27   Orinder Ghose   cust_id13        1488355
46      Wazir Tank   cust_id32        1428491
47  Yashasvi Wason   cust_id38        1385715
9     Damyanti Lad   cust_id46        1360002

In [1]:
%%sql 
SELECT c.customer_name, COALESCE(SUM(p.selling_price * oi.quantity), 0) AS total_revenue
FROM retail_analysis.customers c 
LEFT JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
LEFT JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
LEFT JOIN retail_analysis.products p 
ON oi.product_id = p.product_id
GROUP BY c.customer_name,  c.customer_id
ORDER BY total_revenue DESC;

UsageError: Cell magic `%%sql` not found.

In [5]:
%%sql 
SELECT * FROM retail_analysis.customers LIMIT 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------+---------------+--------+-----+--------+-----------+------------+
| customer_id | customer_name | gender | age |  city  |   state   | join_date  |
+-------------+---------------+--------+-----+--------+-----------+------------+
|  cust_id01  |  Teerth Nagy  | female |  46 | Mysuru | Karnataka | 2024-01-03 |
+-------------+---------------+--------+-----+--------+-----------+------------+

In [4]:
%%sql 
SELECT * FROM retail_analysis.products LIMIT 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+-------------+-------+------------+---------------+
| product_id | product_name |   category  | brand | cost_price | selling_price |
+------------+--------------+-------------+-------+------------+---------------+
|   P_ID01   |  Smartphone  | Electronics |   HP  |  25000.00  |    30000.00   |
+------------+--------------+-------------+-------+------------+---------------+

In [7]:
%%sql 
SELECT * FROM retail_analysis.orders LIMIT 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+----------+-------------+------------+--------------+--------------+
| order_id | customer_id | order_date | payment_mode | order_status |
+----------+-------------+------------+--------------+--------------+
| ORD_ID01 |  cust_id30  | 2025-01-01 |     UPI      |  Cancelled   |
+----------+-------------+------------+--------------+--------------+

In [8]:
%%sql 
SELECT * FROM retail_analysis.order_items LIMIT 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+----------------+----------+------------+----------+
| order_items_id | order_id | product_id | quantity |
+----------------+----------+------------+----------+
|   ORD_ITEM01   | ORD_ID01 |   P_ID07   |    5     |
+----------------+----------+------------+----------+