In [1]:
print('welcome')

welcome

In [2]:
import pandas as pd

In [10]:
%load_ext sql

In [ ]:
%sql postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [ ]:
%%sql 
CREATE SCHEMA retail_analysis;

In [7]:
%%sql 
CREATE TABLE retail_analysis.customers(
    customer_id VARCHAR(20) PRIMARY KEY,
    customer_name VARCHAR(100),
    gender VARCHAR(20),
    age INT,
    city VARCHAR(50),
    state VARCHAR(50),
    join_date DATE
);

CREATE TABLE retail_analysis.products(
    product_id VARCHAR(20) PRIMARY KEY,
    product_name VARCHAR(50),
    category VARCHAR(20),
    brand VARCHAR(20),
    cost_price DECIMAL(10,2),
    selling_price DECIMAL(10,2)
);

CREATE TABLE retail_analysis.orders(
    order_id VARCHAR(20) PRIMARY KEY,
    customer_id VARCHAR(20),
    order_date DATE,
    payment_mode VARCHAR(20),
    order_state VARCHAR(20),

    FOREIGN KEY (customer_id)
    REFERENCES retail_analysis.customers(customer_id)
);

CREATE TABLE retail_analysis.order_items(
    order_items_id VARCHAR(20) PRIMARY KEY,
    order_id VARCHAR(20),
    product_id VARCHAR(20),
    quantity SMALLINT,
    
    FOREIGN KEY (order_id) 
    REFERENCES retail_analysis.orders(order_id),
    
    FOREIGN KEY (product_id) 
    REFERENCES retail_analysis.products(product_id)
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

++
||
++
++

**first install : pip install pgspecial**

In [ ]:
%%sql
\COPY retail_analysis.order_items
FROM 'D:\SQL\data generator\output\order_items.csv'
DELIMITER ','
CSV HEADER;

In [3]:
customers = pd.read_csv(r'd:\SQL\data generator\output\customers.csv')
orders = pd.read_csv(r'd:\SQL\data generator\output\orders.csv')
products = pd.read_csv(r'd:\SQL\data generator\output\products.csv')
order_items = pd.read_csv(r'd:\SQL\data generator\output\order_items.csv')

In [4]:
customers['join_date'] = pd.to_datetime(
    customers['join_date']
)

**Question 1 — Customer Analysis**

<pre>हमारे store में कितने unique customers ने कम-से-कम एक order place किया है?</pre>

In [ ]:
%%sql
SELECT COUNT(DISTINCT customer_id) AS unique_customers
FROM retail_analysis.orders;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------------+
| unique_customers |
+------------------+
|        50        |
+------------------+

In [22]:
pd.DataFrame({
    'unique_customers' : [orders['customer_id'].nunique()]
})

   unique_customers
0                50

<pre>हर customer ने कितने orders किए हैं? 
केवल उन customers को दिखाओ जिन्होंने कम-से-कम 1 order किया है।</pre>

In [24]:
total_orders = (
    orders
    .groupby('customer_id')['customer_id']
    .count()
).reset_index(name= 'total_orders')
total_orders[total_orders['total_orders'] >= 1].head(4)

  customer_id  total_orders
0   cust_id01            25
1   cust_id02            24
2   cust_id03            21
3   cust_id04            19

In [ ]:
%%sql 
SELECT customer_id, COUNT(customer_id) AS total_orders
FROM retail_analysis.orders
GROUP BY customer_id
HAVING COUNT(customer_id) >= 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

24 rows affected.

+-------------+--------------+
| customer_id | total_orders |
+-------------+--------------+
|  cust_id07  |      21      |
|  cust_id06  |      26      |
|  cust_id47  |      21      |
|  cust_id12  |      24      |
|  cust_id23  |      28      |
|  cust_id18  |      26      |
|  cust_id17  |      26      |
|  cust_id01  |      25      |
|  cust_id10  |      21      |
|  cust_id30  |      25      |
+-------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 3 — Customer Orders

Business asks:

ऐसे सभी customers की list निकालो जिन्होंने 2 या उससे ज्यादा orders किए हैं।<pre>

customer_id | total_orders
------------|-------------
cust_idXX   | 2
cust_idYY   | 3
...

In [30]:
customer_orders = (
    orders
    .groupby('customer_id')['customer_id']
    .count()
).reset_index(name='total_orders')
customer_orders[customer_orders['total_orders'] >= 2].head()

  customer_id  total_orders
0   cust_id01            25
1   cust_id02            24
2   cust_id03            21
3   cust_id04            19
4   cust_id05            17

In [64]:
%%sql 
SELECT customer_id, COUNT(customer_id) AS total_orders
FROM retail_analysis.orders
GROUP BY customer_id
HAVING COUNT(customer_id) >= 2;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------+
| customer_id | total_orders |
+-------------+--------------+
|  cust_id16  |      20      |
|  cust_id42  |      16      |
|  cust_id07  |      21      |
|  cust_id39  |      18      |
|  cust_id34  |      14      |
|  cust_id14  |      18      |
|  cust_id06  |      26      |
|  cust_id47  |      21      |
|  cust_id50  |      16      |
|  cust_id12  |      24      |
+-------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 4 — Order Status

Find the number of orders for each order status.<pre>

order_status | total_orders
-------------|-------------
Delivered    | ?
Pending      | ?
Cancelled    | ?
...

In [33]:
orders.groupby('order_status')['order_status'].count().reset_index(name='total_orders')

  order_status  total_orders
0    Cancelled            77
1    Confirmed            92
2    Delivered           596
3      Pending            58
4     Returned            24
5      Shipped           153

In [72]:
%%sql 
SELECT order_status, COUNT(order_status) AS total_orders
FROM retail_analysis.orders
GROUP BY order_status;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+--------------+--------------+
| order_status | total_orders |
+--------------+--------------+
|  Delivered   |     596      |
|   Shipped    |     153      |
|   Returned   |      24      |
|  Cancelled   |      77      |
|  Confirmed   |      92      |
|   Pending    |      58      |
+--------------+--------------+

<pre>Question 5 — Order Status Analysis

Find the total number of orders for each order status, 
and show only those statuses where the total number of orders is greater than 100.</pre>

order_state | total_orders
------------|-------------
Delivered   | ?
...

In [36]:
total_orders = (
    orders
    .groupby('order_status')['order_status']
    .count()
).reset_index(name='total_orders')
total_orders[total_orders['total_orders'] > 100]

  order_status  total_orders
2    Delivered           596
5      Shipped           153

In [74]:
%%sql 
SELECT order_status, COUNT(order_status) AS total_orders
FROM retail_analysis.orders
GROUP BY order_status
HAVING COUNT(order_status) > 100;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

2 rows affected.

+--------------+--------------+
| order_status | total_orders |
+--------------+--------------+
|  Delivered   |     596      |
|   Shipped    |     153      |
+--------------+--------------+

<pre>Question 6 — Customer + Order Data

Find the total number of orders placed by each customer, 
and display the customer's name along with the total order count.</pre>

customer_id | customer_name | total_orders
------------|---------------|-------------
cust_id01   | ...           | ?
cust_id02   | ...           | ?

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
orders[order_id].count() AS total_orders
customers 1* 2
orders 1* 3
</pre>

**complete version**

In [ ]:
total_orders = ( # left # right
    pd.merge(customers, orders, left_on = 'customer_id', right_on = 'customer_id', how= 'inner')
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

  customer_id  customer_name  total_orders
0   cust_id01    Teerth Nagy            25
1   cust_id02    Jagat Palan            24
2   cust_id03  Isaiah Dhawan            21
3   cust_id04   Chatura Gera            19

**short version**

In [ ]:
total_orders = (
    pd.merge(customers, orders, on='customer_id')
    .groupby(['customer_id', 'customer_name'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

   customer_id    customer_name  total_orders
24   cust_id25   Harsh Bhargava            32
22   cust_id23     Jagat Chawla            28
17   cust_id18   Samarth Thakur            26
5    cust_id06  Vidhi Prabhakar            26

In [ ]:
%%sql 
SELECT o.customer_id, c.customer_name, COUNT(o.customer_id) AS total_orders
FROM retail_analysis.orders AS o
INNER JOIN retail_analysis.customers AS c
ON o.customer_id = c.customer_id
GROUP BY o.customer_id, c.customer_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+-----------------+--------------+
| customer_id |  customer_name  | total_orders |
+-------------+-----------------+--------------+
|  cust_id25  |  Harsh Bhargava |      32      |
|  cust_id23  |   Jagat Chawla  |      28      |
|  cust_id17  |    Abeer Raj    |      26      |
|  cust_id18  |  Samarth Thakur |      26      |
|  cust_id06  | Vidhi Prabhakar |      26      |
|  cust_id01  |   Teerth Nagy   |      25      |
|  cust_id30  |    Kashvi Sem   |      25      |
|  cust_id35  | Vaishnavi Baria |      24      |
|  cust_id02  |   Jagat Palan   |      24      |
|  cust_id12  |  Samuel Sanghvi |      24      |
+-------------+-----------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 7 — Customer Order Analysis

Find all customers who have never placed an order. 
Display their customer_id and customer_name.</pre>

customer_id | customer_name
------------|--------------
cust_idXX   | ...

**Mind Graph**
<pre>
FROM orders     Left   A  
RIGHT customers Right  B
--------------------------
A      B
orders customers
1⬜      1⬜
2⬜      3🟩
------------------------
A.id is null  
<pre>

In [21]:
customer_orders = (
    pd.merge(orders, customers, on='customer_id', how='left')
)
customer_orders = customer_orders[customer_orders['order_id'].isna()]
customer_orders[
    ['customer_id', 'customer_name']
]

Empty DataFrame
Columns: [customer_id, customer_name]
Index: []

In [4]:
%%sql 
SELECT o.customer_id, c.customer_name
FROM retail_analysis.orders AS o 
RIGHT JOIN retail_analysis.customers AS c 
ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Question 8 — Product Sales

Find the total quantity sold for each product. 
Display the product_id, product_name, and total_quantity_sold.</pre>

product_id | product_name | total_quantity_sold
-----------|--------------|-------------------
P_ID01     | ...          | ?
P_ID02     | ...          | ?

<pre>
1) DISTINCT order_items[product_id] Dublicate | 1 2 | inner join 1,1
2) DISTINCT products[product_name]  Unique    | 1 3 |
3) order_items[quantity].sum()
</pre>

In [31]:
total_quantity_sold = (
    pd.merge(products, order_items, on='product_id')
    .groupby(['product_id', 'product_name'])['quantity']
    .sum()
).reset_index(name='total_quantity_sold')
total_quantity_sold.head(4)

  product_id product_name  total_quantity_sold
0     P_ID01   Smartphone                  156
1     P_ID02       Laptop                   75
2     P_ID03       Tablet                  122
3     P_ID04   Desktop PC                   62

In [12]:
%%sql 
SELECT o.product_id, p.product_name, SUM(o.quantity) AS total_quantity_sold
FROM retail_analysis.products AS p
INNER JOIN retail_analysis.order_items AS o 
ON o.product_id = p.product_id
GROUP BY o.product_id, p.product_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+--------------+---------------------+
| product_id | product_name | total_quantity_sold |
+------------+--------------+---------------------+
|   P_ID19   |  USB Cable   |         120         |
|   P_ID18   |   Charger    |         147         |
|   P_ID37   |    Dress     |          76         |
|   P_ID31   | Cargo Pants  |         117         |
|   P_ID17   |  Power Bank  |          92         |
|   P_ID01   |  Smartphone  |         156         |
|   P_ID25   |  Sweatshirt  |          93         |
|   P_ID06   |   Keyboard   |          93         |
|   P_ID15   |    Webcam    |         167         |
|   P_ID30   |    Chinos    |         119         |
+------------+--------------+---------------------+
Truncated to displaylimit of 10.

<pre>Question 9 — Product Revenue Analysis

Find the total revenue generated by each product, showing the product_id, product_name,
and total_revenue. Only include products that have generated revenue.</pre>

product_id | product_name | total_revenue
-----------|--------------|--------------
P_ID01     | ...          | ?
P_ID02     | ...          | ?

<pre>
DISTINCT products[product_id] unique 
DISTINCT products[product_name] unique
(products[selling_price] * order_items[quantity]).sum()
-----------------
products unique       1 2
order_items dublicate 1 3 1,1 inner join
</pre>

In [7]:
%%sql 
SELECT p.product_id, p.product_name, SUM(p.selling_price * o.quantity) AS total_revenue
FROM retail_analysis.products AS p
INNER JOIN retail_analysis.order_items AS o
ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+------------+---------------------+---------------+
| product_id |     product_name    | total_revenue |
+------------+---------------------+---------------+
|   P_ID40   |       Sweater       |   163240.00   |
|   P_ID41   |   Pressure Cooker   |   209440.00   |
|   P_ID18   |       Charger       |   102900.00   |
|   P_ID14   |       Scanner       |   874200.00   |
|   P_ID37   |        Dress        |   114380.00   |
|   P_ID21   |       T-Shirt       |    46440.00   |
|   P_ID20   | External Hard Drive |   1065750.00  |
|   P_ID22   |        Shirt        |    92400.00   |
|   P_ID30   |        Chinos       |   153510.00   |
|   P_ID44   |     Cookware Set    |   350550.00   |
+------------+---------------------+---------------+
Truncated to displaylimit of 10.

In [38]:
merged = pd.merge(products, order_items, on='product_id')
merged['revenue'] = merged['selling_price'] * merged['quantity']
total_revenue = (
    merged
    .groupby(['product_id', 'product_name'])['revenue']
    .sum()   
).reset_index(name = 'total_revenue')
total_revenue.head(4)

  product_id product_name  total_revenue
0     P_ID01   Smartphone        4680000
1     P_ID02       Laptop        6750000
2     P_ID03       Tablet        1512800
3     P_ID04   Desktop PC        1224500

<pre>Question 10 — Customer Revenue Analysis

Find the total revenue generated by each customer. 
Display the customer_id, customer_name, and total_revenue. 
Include only customers who have generated revenue.</pre>

customer_id | customer_name | total_revenue
------------|---------------|--------------
cust_id01   | ...           | ?
cust_id02   | ...           | ?

<pre>
DISTINCT customers[customer_id] 
DISTINCT customers[customer_name]
(order_items[quantity] * products[selling_price]).sum() AS total_revenue
customers 1 none 3
products none 2 none
order_items 1 2 none
inner join 1,1 & 2,2
</pre>

In [10]:
%%sql
SELECT c.customer_id, c.customer_name, SUM(oi.quantity * p.selling_price) AS total_revenue
FROM retail_analysis.customers c 
INNER JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
INNER JOIN retail_analysis.order_items oi
ON oi.order_id = o.order_id
INNER JOIN retail_analysis.products p 
ON p.product_id = oi.product_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+---------------+
| customer_id |      customer_name       | total_revenue |
+-------------+--------------------------+---------------+
|  cust_id07  |      Sanaya Oommen       |   927650.00   |
|  cust_id39  |      Gautami Ravel       |   454575.00   |
|  cust_id47  |        Ekaraj Dua        |   832635.00   |
|  cust_id50  |  Mitali Balasubramanian  |   468541.00   |
|  cust_id45  |       Raghav Sethi       |   316220.00   |
|  cust_id35  |     Vaishnavi Baria      |   730768.00   |
|  cust_id09  | Rajeshri Balasubramanian |   316885.00   |
|  cust_id49  |        Qushi Sood        |   219729.00   |
|  cust_id27  |       Jyoti Andra        |   390570.00   |
|  cust_id08  |        Abeer Rout        |   468799.00   |
+-------------+--------------------------+---------------+
Truncated to displaylimit of 10.

In [43]:
merged = pd.merge(customers, orders, on='customer_id')
merged = pd.merge(merged, order_items, on='order_id')
merged = pd.merge(merged, products, on='product_id')

merged['revenue'] = (
    merged['quantity'] * merged['selling_price']
)
total_revenue = (
    merged
    .groupby(['customer_id', 'customer_name'])['revenue'] # error
    .sum()
).reset_index(name='total_revenue')
total_revenue.head(4)

  customer_id  customer_name  total_revenue
0   cust_id01    Teerth Nagy         263573
1   cust_id02    Jagat Palan         241560
2   cust_id03  Isaiah Dhawan         278229
3   cust_id04   Chatura Gera         389418

In [44]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['revenue'] = (
    merged['selling_price'] * merged['quantity']
)
total_revenue = (
    merged
    .groupby(['customer_id', 'customer_name'])['revenue']
    .sum()
).reset_index(name='total_revenue')
total_revenue.head(4)

  customer_id  customer_name  total_revenue
0   cust_id01    Teerth Nagy         263573
1   cust_id02    Jagat Palan         241560
2   cust_id03  Isaiah Dhawan         278229
3   cust_id04   Chatura Gera         389418

<pre>Question 11 — Product Category Revenue

Find the total revenue generated by each product category. 
Display the category and total_revenue.</pre>

<pre>
DISTINCT products[category]
(products[selling_price] * order_items[quantity]).sum() as total_revenue
products 1 2
order_items 1 none
1,1 inner join
</pre>

In [11]:
%%sql 
SELECT p.category, SUM(p.selling_price * o.quantity) AS total_revenue
FROM retail_analysis.products p 
INNER JOIN retail_analysis.order_items o 
ON p.product_id = o.product_id
GROUP BY p.category;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+----------------+---------------+
|    category    | total_revenue |
+----------------+---------------+
| Home & Kitchen |   3447105.00  |
|  Electronics   |  19705920.00  |
|    Clothing    |   2730089.00  |
+----------------+---------------+

In [46]:
merged = pd.merge(products, order_items, on='product_id')
merged['revenue'] = (
    merged['quantity'] * merged['selling_price']
)
total_revenue = (
    merged 
    .groupby('category')['revenue']
    .sum()
).reset_index(name='total_revenue')
total_revenue

         category  total_revenue
0        Clothing        2730089
1     Electronics       19705920
2  Home & Kitchen        3447105

<pre>Question 12 — Category + Order Volume

Find the total number of units sold for each product category. 
Display the category and total_units_sold.</pre>

<pre>
DISTINCT products[category]
order_items[quantity].sum() AS total_unit_sold
products 1, 2
order_items 1 none
1,1 inner join
</pre>

In [13]:
%%sql 
SELECT p.category, SUM(o.quantity) AS total_unit_sold
FROM retail_analysis.products p 
INNER JOIN retail_analysis.order_items o 
ON p.product_id = o.product_id
GROUP BY p.category;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+----------------+-----------------+
|    category    | total_unit_sold |
+----------------+-----------------+
| Home & Kitchen |       1119      |
|  Electronics   |       2240      |
|    Clothing    |       2041      |
+----------------+-----------------+

<pre>Question 13 — Customer Spending

Find the top 5 customers based on total revenue generated. 
Display customer_id, customer_name, and total_revenue, 
ordered from highest to lowest revenue.</pre>

<pre>
DISTINCT customers[customer_id]
DISTINCT customers[customer_name]
(order_items[quantity] * products[selling_price]).sum() AS total_revenue
ORDER BY total_revenue DESC
LIMIT 5
</pre>

In [19]:
%%sql 
SELECT c.customer_id, c.customer_name, SUM(oi.quantity * p.selling_price) AS total_revenue

FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id

JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id

JOIN retail_analysis.products p
ON p.product_id = oi.product_id

GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC
LIMIT 5;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

5 rows affected.

+-------------+----------------+---------------+
| customer_id | customer_name  | total_revenue |
+-------------+----------------+---------------+
|  cust_id13  | Orinder Ghose  |   1488355.00  |
|  cust_id32  |   Wazir Tank   |   1428491.00  |
|  cust_id38  | Yashasvi Wason |   1385715.00  |
|  cust_id46  |  Damyanti Lad  |   1360002.00  |
|  cust_id16  |   Avi Andra    |   1294265.00  |
+-------------+----------------+---------------+

<pre>Question 14 — Customer Order Frequency

Find the customers who have placed more than 5 orders. 
Display their customer_id, customer_name, and total_orders, 
sorted by total_orders from highest to lowest.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
COUNT(orders[order_id]).sort_desc
HAVING orders[order_id] > 5
</pre>

In [30]:
%%sql 
SELECT c.customer_id, c.customer_name, COUNT(o.order_id) AS total_orders

FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON o.customer_id = c.customer_id 

GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 5
ORDER BY total_orders DESC;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+-----------------+--------------+
| customer_id |  customer_name  | total_orders |
+-------------+-----------------+--------------+
|  cust_id25  |  Harsh Bhargava |      32      |
|  cust_id23  |   Jagat Chawla  |      28      |
|  cust_id06  | Vidhi Prabhakar |      26      |
|  cust_id17  |    Abeer Raj    |      26      |
|  cust_id18  |  Samarth Thakur |      26      |
|  cust_id30  |    Kashvi Sem   |      25      |
|  cust_id01  |   Teerth Nagy   |      25      |
|  cust_id02  |   Jagat Palan   |      24      |
|  cust_id35  | Vaishnavi Baria |      24      |
|  cust_id12  |  Samuel Sanghvi |      24      |
+-------------+-----------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 15 — Product Performance

Find the top 5 products based on total quantity sold. Display the product_id, 
product_name, and total_quantity_sold, ordered from highest to lowest quantity sold.</pre>

product_id | product_name | total_quantity_sold
-----------|--------------|-------------------
P_IDXX     | ...          | ?

<pre>
DISTINCT products[product_id]
DISTINCT products[product_name]
order_items[quantity].sum() as total_quantity_sold
order by total_quantity_sold desc
limit 5
</pre>

In [9]:
%%sql 
SELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity_sold
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
GROUP BY  p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

5 rows affected.

+------------+--------------+---------------------+
| product_id | product_name | total_quantity_sold |
+------------+--------------+---------------------+
|   P_ID15   |    Webcam    |         167         |
|   P_ID28   |    Jeans     |         157         |
|   P_ID01   |  Smartphone  |         156         |
|   P_ID09   |   Earbuds    |         150         |
|   P_ID24   |    Hoodie    |         149         |
+------------+--------------+---------------------+

<pre>Question 16 — Average Order Value

Find the average order value for each customer. 
Display customer_id, customer_name, and average_order_value.</pre>

<pre>
DISTINCE customers[customer_id], 
DISTINCE customers[customer_name],
(products[selling_price] * order_items[quantity]).mean() AS average_order_value
</pre>

In [ ]:
%%sql 
SELECT c.customer_id, c.customer_name, AVG(p.selling_price * oi.quantity) AS average_order_value
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
JOIN retail_analysis.orders o 
ON o.order_id = oi.order_id
JOIN retail_analysis.customers c 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+------------------------+
| customer_id |      customer_name       |  average_order_value   |
+-------------+--------------------------+------------------------+
|  cust_id07  |      Sanaya Oommen       |   44173.809523809524   |
|  cust_id39  |      Gautami Ravel       |   25254.166666666667   |
|  cust_id47  |        Ekaraj Dua        |   39649.285714285714   |
|  cust_id50  |  Mitali Balasubramanian  |   29283.812500000000   |
|  cust_id45  |       Raghav Sethi       |   24324.615384615385   |
|  cust_id35  |     Vaishnavi Baria      |   30448.666666666667   |
|  cust_id09  | Rajeshri Balasubramanian |   24375.769230769231   |
|  cust_id49  |        Qushi Sood        | 10463.2857142857142857 |
|  cust_id27  |       Jyoti Andra        |   20556.315789473684   |
|  cust_id08  |        Abeer Rout        |   23439.950000000000   |
+-------------+--------------------------+------------------------+
Truncated to displaylimit of 10.

In [ ]:
%%sql
SELECT c.customer_id, c.customer_name, AVG(order_value) AS average_order_value
FROM (
    SELECT  o.customer_id, o.order_id, SUM(p.selling_price * oi.quantity) AS order_value
    FROM retail_analysis.orders o
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON p.product_id = oi.product_id
    GROUP BY o.customer_id, o.order_id
) AS order_values
JOIN retail_analysis.customers c
ON c.customer_id = order_values.customer_id
GROUP BY c.customer_id, c.customer_name;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+------------------------+
| customer_id |      customer_name       |  average_order_value   |
+-------------+--------------------------+------------------------+
|  cust_id39  |      Gautami Ravel       |   25254.166666666667   |
|  cust_id07  |      Sanaya Oommen       |   44173.809523809524   |
|  cust_id47  |        Ekaraj Dua        |   39649.285714285714   |
|  cust_id50  |  Mitali Balasubramanian  |   29283.812500000000   |
|  cust_id45  |       Raghav Sethi       |   24324.615384615385   |
|  cust_id35  |     Vaishnavi Baria      |   30448.666666666667   |
|  cust_id09  | Rajeshri Balasubramanian |   24375.769230769231   |
|  cust_id49  |        Qushi Sood        | 10463.2857142857142857 |
|  cust_id27  |       Jyoti Andra        |   20556.315789473684   |
|  cust_id08  |        Abeer Rout        |   23439.950000000000   |
+-------------+--------------------------+------------------------+
Truncated to displaylimit of 10.

<pre>Question 17 — Customer Spending

Find the top 5 customers based on their total revenue. 
Display customer_id, customer_name, and total_revenue, 
sorted from highest to lowest revenue.</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantity]).sum()
ORDER BY total_revenue DESC
limit 5
</pre>

In [10]:
%%sql 
SELECT c.customer_id, c.customer_name, SUM(p.selling_price * oi.quantity) AS total_revenue
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id

JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id

JOIN retail_analysis.products p 
ON oi.product_id = p.product_id

GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC
LIMIT 5;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

5 rows affected.

+-------------+----------------+---------------+
| customer_id | customer_name  | total_revenue |
+-------------+----------------+---------------+
|  cust_id13  | Orinder Ghose  |   1488355.00  |
|  cust_id32  |   Wazir Tank   |   1428491.00  |
|  cust_id38  | Yashasvi Wason |   1385715.00  |
|  cust_id46  |  Damyanti Lad  |   1360002.00  |
|  cust_id16  |   Avi Andra    |   1294265.00  |
+-------------+----------------+---------------+

<pre>Question 18 — Category Performance

Find the product category with the highest total revenue. 
Display the category and total_revenue.</pre>

<pre>
DISTINCT products[category], 
(products[selling_price] * order_items[quantity]).sum() AS highest_total_revenue
order by highest_total_revenue DESC
limit 1
</pre>

In [18]:
%%sql 
SELECT p.category, SUM(p.selling_price * oi.quantity) AS highest_total_revenue
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi 
ON p.product_id = oi.product_id 
GROUP BY p.category
ORDER BY highest_total_revenue DESC
LIMIT 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------+-----------------------+
|   category  | highest_total_revenue |
+-------------+-----------------------+
| Electronics |      19705920.00      |
+-------------+-----------------------+

<pre>Question 19 — Customer Order Status

Find the number of orders for each order_status. 
Display order_status and total_orders, 
sorted from highest to lowest number of orders.</pre>

<pre>
DISTINCT orders[order_status],
orders[order_id].count() AS total_orders
ORDER BY total_orders DESC
<pre>

In [19]:
%%sql 
SELECT order_status, COUNT(order_id) AS total_orders
FROM retail_analysis.orders
GROUP BY order_status
ORDER BY total_orders DESC;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+--------------+--------------+
| order_status | total_orders |
+--------------+--------------+
|  Delivered   |     596      |
|   Shipped    |     153      |
|  Confirmed   |      92      |
|  Cancelled   |      77      |
|   Pending    |      58      |
|   Returned   |      24      |
+--------------+--------------+

<pre>
Question 20 — Customers Without Orders

Find all customers who have never placed an order.
 Display their customer_id and customer_name.
<pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name]
customers 1 2 A left
orders 1 nan B
left join where b is null
<pre>

In [26]:
%%sql 
SELECT c.customer_id, c.customer_name
FROM retail_analysis.customers c 
LEFT JOIN retail_analysis.orders o
ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

In [7]:
%%sql 
SELECT * FROM retail_analysis.orders LIMIT 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+----------+-------------+------------+--------------+--------------+
| order_id | customer_id | order_date | payment_mode | order_status |
+----------+-------------+------------+--------------+--------------+
| ORD_ID01 |  cust_id30  | 2025-01-01 |     UPI      |  Cancelled   |
+----------+-------------+------------+--------------+--------------+

In [14]:
%%sql 
SELECT * FROM retail_analysis.customers LIMIT 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------+---------------+--------+-----+--------+-----------+------------+
| customer_id | customer_name | gender | age |  city  |   state   | join_date  |
+-------------+---------------+--------+-----+--------+-----------+------------+
|  cust_id01  |  Teerth Nagy  | female |  46 | Mysuru | Karnataka | 2024-01-03 |
+-------------+---------------+--------+-----+--------+-----------+------------+

In [15]:
%%sql 
SELECT * FROM retail_analysis.products LIMIT 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+-------------+-------+------------+---------------+
| product_id | product_name |   category  | brand | cost_price | selling_price |
+------------+--------------+-------------+-------+------------+---------------+
|   P_ID01   |  Smartphone  | Electronics |   HP  |  25000.00  |    30000.00   |
+------------+--------------+-------------+-------+------------+---------------+

In [16]:
%%sql 
SELECT * FROM retail_analysis.order_items LIMIT 1;

Running query in 'postgresql+psycopg://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+----------------+----------+------------+----------+
| order_items_id | order_id | product_id | quantity |
+----------------+----------+------------+----------+
|   ORD_ITEM01   | ORD_ID01 |   P_ID07   |    5     |
+----------------+----------+------------+----------+