In [1]:
print('hello')

hello

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:password@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [4]:
import pandas as pd

In [63]:
products = pd.read_csv(r"d:\SQL\data generator\output\products.csv")
order_items = pd.read_csv(r"d:\SQL\data generator\output\order_items.csv")
orders = pd.read_csv(r"d:\SQL\data generator\output\orders.csv", parse_dates=['order_date'])
customers = pd.read_csv(r"d:\SQL\data generator\output\customers.csv")

<pre>Question 1 — Single-value Subquery

Business asks:

Find all products whose selling_price is greater than 
the average selling_price of all products.</pre>

In [6]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT AVG(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

9 rows affected.

+---------------------+---------------+
|     product_name    | selling_price |
+---------------------+---------------+
|      Smartphone     |    30000.00   |
|        Laptop       |    90000.00   |
|        Tablet       |    12400.00   |
|      Desktop PC     |    19750.00   |
|       Monitor       |    5375.00    |
|     Fitness Band    |    7500.00    |
|       Scanner       |    9300.00    |
| External Hard Drive |    10150.00   |
|    Microwave Oven   |    10500.00   |
+---------------------+---------------+

In [ ]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] > products['selling_price'].mean()]

           product_name  selling_price
0            Smartphone          30000
1                Laptop          90000
2                Tablet          12400
3            Desktop PC          19750
4               Monitor           5375
11         Fitness Band           7500
13              Scanner           9300
19  External Hard Drive          10150
48       Microwave Oven          10500

<pre>Question 2 — Single-Value Subquery

Business asks:

Find all products whose selling_price is lower than 
the maximum selling_price among all products.</pre>

In [18]:
%%sql 
SELECT product_name, selling_price 
FROM retail_analysis.products
WHERE selling_price < (
    SELECT MAX(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

49 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|     Headphones    |     225.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [21]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] < products['selling_price'].max()].head(4)

  product_name  selling_price
0   Smartphone          30000
2       Tablet          12400
3   Desktop PC          19750
4      Monitor           5375

<pre>Question 3 — Single-Value Subquery

Business asks:

Find all products whose selling_price is equal to the minimum selling_price among all products.</pre>

In [24]:
%%sql
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price = (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

2 rows affected.

+--------------+---------------+
| product_name | selling_price |
+--------------+---------------+
|  Headphones  |     225.00    |
|  USB Cable   |     225.00    |
+--------------+---------------+

In [25]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] == products['selling_price'].min()]

   product_name  selling_price
7    Headphones            225
18    USB Cable            225

<pre>Question 4 — Single-Value Subquery

Business asks:

Find all orders whose order_value is greater than 
the average order_value of all orders.</pre>

In [36]:
%%sql 
SELECT oi.order_id, (p.selling_price * oi.quantity) AS order_value
FROM retail_analysis.products p
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
WHERE (p.selling_price * oi.quantity) > (
    SELECT AVG(p.selling_price * oi.quantity)
    FROM retail_analysis.products p 
    JOIN retail_analysis.order_items oi
    ON p.product_id = oi.product_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

180 rows affected.

+----------+-------------+
| order_id | order_value |
+----------+-------------+
| ORD_ID02 |   31500.00  |
| ORD_ID12 |   74400.00  |
| ORD_ID20 |   30750.00  |
| ORD_ID38 |  540000.00  |
| ORD_ID39 |  270000.00  |
| ORD_ID40 |   27900.00  |
| ORD_ID44 |   67500.00  |
| ORD_ID45 |   30750.00  |
| ORD_ID46 |   39500.00  |
| ORD_ID56 |   51250.00  |
+----------+-------------+
Truncated to displaylimit of 10.

In [42]:
merged = pd.merge(products, order_items, on='product_id')
merged['order_value'] = (
    merged['selling_price'] * merged['quantity']
)
merged[
    ['order_id', 'order_value']
][merged['order_value'] > merged['order_value'].mean()].head(4)

   order_id  order_value
0  ORD_ID39       270000
1  ORD_ID62       150000
2  ORD_ID76       240000
3  ORD_ID97       180000

<pre>Question 5 — Single-Value Subquery

Business asks:

Find all products whose selling_price is greater than the
 minimum selling_price of products in the Electronics category.</pre>

In [ ]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
    WHERE category = 'Electronics'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

48 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Laptop      |    90000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [31]:
electronics_min = products[products['category'] == 'Electronics']['selling_price'].min()
products[
    ['product_name', 'selling_price']
][products['selling_price'] > electronics_min].head(4)

  product_name  selling_price
0   Smartphone          30000
1       Laptop          90000
2       Tablet          12400
3   Desktop PC          19750

<pre>Question 6 — Single-Value Subquery

Business asks:

Find all customers whose total spending is greater than 
the average total spending of all customers.</pre>

<pre>
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantity]).sum() as total_spending
total_spending > total_spending.mean()
customers *1 2
products 1* 3
order_items 1* 4
</pre>

In [ ]:
%%sql 
SELECT c.customer_name, SUM(p.selling_price * oi.quantity) AS total_spending
FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name

HAVING SUM(p.selling_price * oi.quantity) > (
    SELECT AVG(total_spending)
    FROM (
        SELECT o.customer_id, SUM(p.selling_price * oi.quantity) AS total_spending
        FROM retail_analysis.orders o
        JOIN retail_analysis.order_items oi
        ON o.order_id = oi.order_id
        JOIN retail_analysis.products p
        ON oi.product_id = p.product_id
        GROUP BY o.customer_id
    ) customer_totals
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-----------------+----------------+
|  customer_name  | total_spending |
+-----------------+----------------+
|  Sanaya Oommen  |   927650.00    |
|    Ekaraj Dua   |   832635.00    |
| Vaishnavi Baria |   730768.00    |
|   Jagat Chawla  |   655495.00    |
|   Damyanti Lad  |   1360002.00   |
|  Anamika Walla  |   696675.00    |
|    Avi Andra    |   1294265.00   |
|    Abeer Raj    |   541385.00    |
|  Orinder Ghose  |   1488355.00   |
|  Harsh Bhargava |   1122411.00   |
+-----------------+----------------+
Truncated to displaylimit of 10.

In [11]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_spending'] = (
    merged['selling_price'] * merged['quantity']
)
result = (
    merged
    .groupby(['customer_name', 'customer_id'])['total_spending']
    .sum()
).reset_index(name='total_spending')
result[result['total_spending'] > result['total_spending'].mean()].head(4)

   customer_name customer_id  total_spending
0      Abeer Raj   cust_id17          541385
4  Anamika Walla   cust_id24          696675
5      Avi Andra   cust_id16         1294265
9   Damyanti Lad   cust_id46         1360002

<pre>Question 6 — Multi-Row Subquery

Business asks:

Find all customers who have placed at least one order in 2026.</pre>

<pre>
customers[customer_name]
customers 1* 2
orders 1* 3
WHERE YEAR(orders[order_date]) = 2026
</pre>

In [17]:
%%sql 
SELECT c.customer_name,c.customer_id
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
WHERE EXTRACT (YEAR FROM o.order_date) = 2025;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+------------------------+-------------+
|     customer_name      | customer_id |
+------------------------+-------------+
|       Kashvi Sem       |  cust_id30  |
|       Qarin Sani       |  cust_id14  |
|    Vaishnavi Baria     |  cust_id35  |
| Mitali Balasubramanian |  cust_id50  |
|      Jagat Chawla      |  cust_id23  |
|      Chatura Gera      |  cust_id04  |
|   Jagrati Narayanan    |  cust_id34  |
|      Teerth Nagy       |  cust_id01  |
|       Ekaraj Dua       |  cust_id47  |
|     Faris Sanghvi      |  cust_id44  |
+------------------------+-------------+
Truncated to displaylimit of 10.

In [21]:
merged = pd.merge(customers, orders, on='customer_id')
merged[
    ['customer_name', 'customer_id']
][merged['order_date'].dt.year == 2025].head(4)

  customer_name customer_id
0   Teerth Nagy   cust_id01
1   Teerth Nagy   cust_id01
2   Teerth Nagy   cust_id01
3   Teerth Nagy   cust_id01

<pre>Question 7 — Multi-Row Subquery

Business asks:

Find all products that have been ordered at least once.</pre>

<pre>
products[product_name],
order_items[order_id].count() >= 1
products 1* 2
order_items 1* 3
</pre>

In [ ]:
%%sql 
SELECT 
    p.product_name, 
    COUNT(oi.order_id) AS total_orders
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi 
    ON p.product_id = oi.product_id
GROUP BY p.product_name, p.product_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+---------------------+--------------+
|     product_name    | total_orders |
+---------------------+--------------+
|       Sweater       |      18      |
|   Pressure Cooker   |      18      |
|       Charger       |      23      |
|       Scanner       |      20      |
|        Dress        |      14      |
|       T-Shirt       |      14      |
| External Hard Drive |      17      |
|        Shirt        |      14      |
|        Chinos       |      22      |
|     Cookware Set    |      21      |
+---------------------+--------------+
Truncated to displaylimit of 10.

In [30]:
merged = pd.merge(products, order_items, on='product_id')
total_orders = (
    merged
    .groupby(['product_name', 'product_id'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

        product_name product_id  total_orders
0          Air Fryer     P_ID48            20
1             Blazer     P_ID27            14
2  Bluetooth Speaker     P_ID10            23
3        Cargo Pants     P_ID31            25

<pre>Find all products that have been purchased 
by customers who have placed an order worth more than ₹10,000.</pre>

<pre>
DISTINCT customers[customer_name],
products[product_name],
(order_items[quantity] * products[selling_price]) as order_worth
HAVING order_worth > 10000
customers 1* 2
products 1* 3 
order_items 1* 4
</pre>

In [ ]:
%%sql
SELECT 
    c.customer_name, 
    SUM(oi.quantity * p.selling_price) AS order_worth
FROM retail_analysis.customers c
JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_name
HAVING SUM(oi.quantity * p.selling_price) > 10000;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+-------------+
|   customer_name   | order_worth |
+-------------------+-------------+
|    Pranit Muni    |  370715.00  |
| Jagrati Narayanan |  290192.00  |
|    Jyoti Andra    |  390570.00  |
|    Amruta Puri    |  189936.00  |
|    Vinaya Reddy   |  750590.00  |
|   Gautami Ravel   |  454575.00  |
|    Damyanti Lad   |  1360002.00 |
|   Orinder Ghose   |  1488355.00 |
|  Vidhi Prabhakar  |  415565.00  |
|    Watika Samra   |  205986.00  |
+-------------------+-------------+
Truncated to displaylimit of 10.

In [21]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['value'] = (
    merged['quantity'] * merged['selling_price']
)
active_customers = (
    merged
    .groupby('customer_name')['value']
    .sum()
).reset_index(name='order_worth')
active_customers[active_customers['order_worth'] > 10000].head(4)

  customer_name  order_worth
0     Abeer Raj       541385
1    Abeer Rout       468799
2  Amaira Koshy       409675
3   Amruta Puri       189936

<pre>Question 8 — EXISTS

Find all customers who have placed at least one order.</pre>

<pre>
customers[customer_id]
customers[customer_name]
customers 1* 2
orders 1* 3
</pre>

In [24]:
%%sql 
SELECT 
    c.customer_id,
    c.customer_name
FROM retail_analysis.customers c
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

In [8]:
customers[
    customers['customer_id'].isin(orders['customer_id'])
][['customer_name', 'customer_id']].head(1)

  customer_name customer_id
0   Teerth Nagy   cust_id01

In [16]:
%%sql 
SELECT customer_id, customer_name 
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT customer_id 
    FROM retail_analysis.orders
    WHERE customer_id IS NOT NULL
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

<pre>Question 9 — NOT EXISTS

Business asks:

Find all customers who have never placed an order.</pre>

In [26]:
%%sql 
SELECT 
    c.customer_id,
    c.customer_name
FROM retail_analysis.customers c 
WHERE NOT EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

In [9]:
customers[
    ~customers['customer_id'].isin(orders['customer_id'])
][['customer_name', 'customer_id']]

Empty DataFrame
Columns: [customer_name, customer_id]
Index: []

In [ ]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id NOT IN (
    SELECT customer_id 
    FROM retail_analysis.orders
    WHERE customer_id IS NOT NULL
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

IN vs EXISTS\
IN → Checks whether a value exists in the list returned by the subquery.\
EXISTS → Checks whether at least one matching row exists in the subquery.\
NOT IN + NULL\
NOT IN can give unexpected results if the subquery contains NULL.\
Use IS NOT NULL inside the subquery to remove NULL values:

<pre>Question — Correlated Subquery

Business asks:

Find all products whose selling_price is greater than the 
average selling price of their own category.</pre>

<pre>products[product], 
products[selling_price],
where products[selling_price] > (
    DISTINCT products[category], 
    product[selling_price].mean()
)</pre>

In [10]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price > (
    SELECT AVG(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p2.category = p1.category
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

17 rows affected.

+------------+---------------------+-------------+---------------+
| product_id |     product_name    |   category  | selling_price |
+------------+---------------------+-------------+---------------+
|   P_ID01   |      Smartphone     | Electronics |    30000.00   |
|   P_ID02   |        Laptop       | Electronics |    90000.00   |
|   P_ID03   |        Tablet       | Electronics |    12400.00   |
|   P_ID04   |      Desktop PC     | Electronics |    19750.00   |
|   P_ID20   | External Hard Drive | Electronics |    10150.00   |
|   P_ID24   |        Hoodie       |   Clothing  |    1720.00    |
|   P_ID25   |      Sweatshirt     |   Clothing  |    1365.00    |
|   P_ID26   |        Jacket       |   Clothing  |    2150.00    |
|   P_ID27   |        Blazer       |   Clothing  |    3300.00    |
|   P_ID28   |        Jeans        |   Clothing  |    1609.00    |
+------------+---------------------+-------------+---------------+
Truncated to displaylimit of 10.

In [26]:
products['avg_selling_price'] = (
    products
    .groupby('category')['selling_price']
    .transform('mean')
)
products[
    ['product_id', 'product_name', 'category', 'selling_price']
][products['selling_price'] > products['avg_selling_price']].head(5)

   product_id         product_name     category  selling_price
0      P_ID01           Smartphone  Electronics          30000
1      P_ID02               Laptop  Electronics          90000
2      P_ID03               Tablet  Electronics          12400
3      P_ID04           Desktop PC  Electronics          19750
19     P_ID20  External Hard Drive  Electronics          10150

In [29]:
products[
    products['selling_price'] > products.groupby('category')['selling_price'].transform('mean')
][['product_id', 'product_name', 'category', 'selling_price']].head(5)

   product_id         product_name     category  selling_price
0      P_ID01           Smartphone  Electronics          30000
1      P_ID02               Laptop  Electronics          90000
2      P_ID03               Tablet  Electronics          12400
3      P_ID04           Desktop PC  Electronics          19750
19     P_ID20  External Hard Drive  Electronics          10150

In [28]:
%%sql 
WITH merged AS (
    SELECT product_id, product_name, category, selling_price,
    AVG(selling_price)
    OVER(
        PARTITION BY category
    ) AS avg_selling_price_category
    FROM retail_analysis.products
)

SELECT product_id, product_name, category, selling_price, avg_selling_price_category
FROM merged
WHERE selling_price > avg_selling_price_category limit 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+----------+---------------+----------------------------+
| product_id | product_name | category | selling_price | avg_selling_price_category |
+------------+--------------+----------+---------------+----------------------------+
|   P_ID24   |    Hoodie    | Clothing |    1720.00    |   1324.1500000000000000    |
+------------+--------------+----------+---------------+----------------------------+

<pre>Question — Correlated Subquery

Business asks:

Find all products whose selling_price is lower than 
the average selling price of their own category.</pre>

<pre>
products[product_id],
products[product_name],
products[selling_price]
products[selling_price] < (
    DISTINCT[category]
    products[selling_price].mean()
)
</pre>

In [54]:
%%sql
SELECT p1.product_id, p1.product_name, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price < (
    SELECT AVG(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p1.category = p2.category # PARTITION BY
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

33 rows affected.

+------------+-------------------+---------------+
| product_id |    product_name   | selling_price |
+------------+-------------------+---------------+
|   P_ID05   |      Monitor      |    5375.00    |
|   P_ID06   |      Keyboard     |     615.00    |
|   P_ID07   |       Mouse       |     450.00    |
|   P_ID08   |     Headphones    |     225.00    |
|   P_ID09   |      Earbuds      |    1975.00    |
|   P_ID10   | Bluetooth Speaker |    1505.00    |
|   P_ID11   |     Smartwatch    |    2460.00    |
|   P_ID12   |    Fitness Band   |    7500.00    |
|   P_ID13   |      Printer      |    5125.00    |
|   P_ID14   |      Scanner      |    9300.00    |
+------------+-------------------+---------------+
Truncated to displaylimit of 10.

In [32]:
products[
    products['selling_price'] < products.groupby('category')['selling_price'].transform('mean')
][['product_id', 'product_name', 'selling_price']].head(5)

  product_id product_name  selling_price
4     P_ID05      Monitor           5375
5     P_ID06     Keyboard            615
6     P_ID07        Mouse            450
7     P_ID08   Headphones            225
8     P_ID09      Earbuds           1975

<pre>
Question — Correlated Subquery

Find all products whose selling_price is equal to 
the highest selling price of their own category.</pre>

<pre>
products[proudct_id],
products[proudct_name],
products[category],
products[selling_price]
WHERE products[selling_price] = (
    DISTINCT category
    proucts[selling_price].max()
)
</pre>

In [30]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price = (
    SELECT MAX(p2.selling_price)
    FROM retail_analysis.products p2 
    WHERE p1.category = p2.category # PARITION BY
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+------------+----------------+----------------+---------------+
| product_id |  product_name  |    category    | selling_price |
+------------+----------------+----------------+---------------+
|   P_ID02   |     Laptop     |  Electronics   |    90000.00   |
|   P_ID27   |     Blazer     |    Clothing    |    3300.00    |
|   P_ID49   | Microwave Oven | Home & Kitchen |    10500.00   |
+------------+----------------+----------------+---------------+

In [33]:
products[
    products['selling_price'] == products.groupby('category')['selling_price'].transform('max')
][['product_id', 'product_name', 'category', 'selling_price']]

   product_id    product_name        category  selling_price
1      P_ID02          Laptop     Electronics          90000
26     P_ID27          Blazer        Clothing           3300
48     P_ID49  Microwave Oven  Home & Kitchen          10500

<pre>
Correlated Subquery + MIN()

Business asks:

Find all products whose selling_price is greater 
than the cheapest product in their own category.
</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price]
WHERE products[selling_price] > (
    DISTINCT category
    products[selling_price].min()
)
</pre>

In [34]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price > (
    SELECT MIN(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p1.category = p2.category # partition by
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

46 rows affected.

+------------+-------------------+-------------+---------------+
| product_id |    product_name   |   category  | selling_price |
+------------+-------------------+-------------+---------------+
|   P_ID01   |     Smartphone    | Electronics |    30000.00   |
|   P_ID02   |       Laptop      | Electronics |    90000.00   |
|   P_ID03   |       Tablet      | Electronics |    12400.00   |
|   P_ID04   |     Desktop PC    | Electronics |    19750.00   |
|   P_ID05   |      Monitor      | Electronics |    5375.00    |
|   P_ID06   |      Keyboard     | Electronics |     615.00    |
|   P_ID07   |       Mouse       | Electronics |     450.00    |
|   P_ID09   |      Earbuds      | Electronics |    1975.00    |
|   P_ID10   | Bluetooth Speaker | Electronics |    1505.00    |
|   P_ID11   |     Smartwatch    | Electronics |    2460.00    |
+------------+-------------------+-------------+---------------+
Truncated to displaylimit of 10.

In [38]:
products[
    products['selling_price'] > products.groupby('category')['selling_price'].transform('min')
][['product_id','product_name','category', 'selling_price']].head(10)

   product_id       product_name     category  selling_price
0      P_ID01         Smartphone  Electronics          30000
1      P_ID02             Laptop  Electronics          90000
2      P_ID03             Tablet  Electronics          12400
3      P_ID04         Desktop PC  Electronics          19750
4      P_ID05            Monitor  Electronics           5375
5      P_ID06           Keyboard  Electronics            615
6      P_ID07              Mouse  Electronics            450
8      P_ID09            Earbuds  Electronics           1975
9      P_ID10  Bluetooth Speaker  Electronics           1505
10     P_ID11         Smartwatch  Electronics           2460

<pre>
Correlated Subquery + Orders

Business asks:

Find customers whose total spending is greater than 
the average spending of customers who have placed at least one order.
</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantitiy]).sum() AS total_spending
WHERE total_spending > (
    AVG(WHOLE(total_spending))
    WHERE COUNT(order_id) >= 1 
)
</pre>

In [68]:
%%sql 
WITH cte AS (
    SELECT c.customer_id, c.customer_name, 
        SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
)

SELECT customer_id, customer_name, total_spending
FROM cte 
WHERE total_spending > (
    SELECT AVG(total_spending)
    FROM cte
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-------------+-----------------+----------------+
| customer_id |  customer_name  | total_spending |
+-------------+-----------------+----------------+
|  cust_id07  |  Sanaya Oommen  |   927650.00    |
|  cust_id47  |    Ekaraj Dua   |   832635.00    |
|  cust_id35  | Vaishnavi Baria |   730768.00    |
|  cust_id23  |   Jagat Chawla  |   655495.00    |
|  cust_id46  |   Damyanti Lad  |   1360002.00   |
|  cust_id24  |  Anamika Walla  |   696675.00    |
|  cust_id16  |    Avi Andra    |   1294265.00   |
|  cust_id17  |    Abeer Raj    |   541385.00    |
|  cust_id13  |  Orinder Ghose  |   1488355.00   |
|  cust_id25  |  Harsh Bhargava |   1122411.00   |
+-------------+-----------------+----------------+
Truncated to displaylimit of 10.

In [69]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_spending'] = (
    merged['selling_price'] * merged['quantity']
)
result = (
    merged
    .groupby(['customer_id', 'customer_name'])['total_spending']
    .sum()
).reset_index(name='total_spending')
result[result['total_spending'] > result['total_spending'].mean()].head(4)

   customer_id   customer_name  total_spending
6    cust_id07   Sanaya Oommen          927650
11   cust_id12  Samuel Sanghvi          518706
12   cust_id13   Orinder Ghose         1488355
15   cust_id16       Avi Andra         1294265

In [88]:
%%sql 
SELECT customer_id, customer_name, total_spending
FROM (
    SELECT c.customer_id, c.customer_name, SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
) AS derived_table
WHERE total_spending > (
    SELECT AVG(avg_spendings)
    FROM (
        SELECT o.customer_id, SUM(p.selling_price * oi.quantity) AS avg_spendings
        FROM retail_analysis.orders o
        JOIN retail_analysis.order_items oi
        ON o.order_id = oi.order_id
        JOIN retail_analysis.products p
        ON oi.product_id = p.product_id
        GROUP BY o.customer_id
    ) AS derived_table2
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-------------+-----------------+----------------+
| customer_id |  customer_name  | total_spending |
+-------------+-----------------+----------------+
|  cust_id07  |  Sanaya Oommen  |   927650.00    |
|  cust_id47  |    Ekaraj Dua   |   832635.00    |
|  cust_id35  | Vaishnavi Baria |   730768.00    |
|  cust_id23  |   Jagat Chawla  |   655495.00    |
|  cust_id46  |   Damyanti Lad  |   1360002.00   |
|  cust_id24  |  Anamika Walla  |   696675.00    |
|  cust_id16  |    Avi Andra    |   1294265.00   |
|  cust_id17  |    Abeer Raj    |   541385.00    |
|  cust_id13  |  Orinder Ghose  |   1488355.00   |
|  cust_id25  |  Harsh Bhargava |   1122411.00   |
+-------------+-----------------+----------------+
Truncated to displaylimit of 10.

<pre>
Next Question — Scalar Subquery

Find all products whose selling_price is lower 
than the average selling_price of all products.
</pre>

<pre>
DISTINCT products[product_name],
SUM(products[selling_price]) AS products_selling_price

products_selling_price < (
    AVG(WHOLE(products_selling_price))
)
</pre>

In [ ]:
%%sql 
WITH cte AS (
    SELECT product_name, SUM(selling_price) AS product_selling_price
    FROM retail_analysis.products
    GROUP BY product_name
)

SELECT product_name, product_selling_price
FROM cte 
WHERE product_selling_price < (
    SELECT AVG(product_selling_price)
    FROM cte
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [30]:
%%sql 
SELECT product_name, SUM(selling_price) AS product_selling_price
FROM retail_analysis.products
GROUP BY product_name
HAVING SUM(selling_price) < (
    SELECT AVG(total_price)
    FROM (
        SELECT SUM(selling_price) AS total_price
        FROM retail_analysis.products 
        GROUP BY product_name
    ) AS sub
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [36]:
%%sql
WITH product_summary AS (
    SELECT 
        product_name, 
        SUM(selling_price) AS product_selling_price,
        AVG(SUM(selling_price)) OVER() AS avg_selling_price
    FROM retail_analysis.products
    GROUP BY product_name
)
SELECT product_name, product_selling_price
FROM product_summary
WHERE product_selling_price < avg_selling_price;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [39]:
%%sql 
SELECT product_name, SUM(selling_price) AS product_selling_price
FROM retail_analysis.products
GROUP BY product_name
HAVING SUM(selling_price) < (
    SELECT avg_sum_price
    FROM (
        SELECT AVG(SUM(selling_price)) OVER() AS avg_sum_price
        FROM retail_analysis.products
        GROUP BY product_name
    )
    LIMIT 1
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [40]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price < (
    SELECT AVG(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|     Headphones    |     225.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
|      Printer      |    5125.00    |
|       Webcam      |    1600.00    |
|     Microphone    |    1975.00    |
|     Power Bank    |    1025.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [73]:
products[
    products['selling_price'] < products['selling_price'].mean()
][['product_name', 'selling_price']].head(4)

  product_name  selling_price
5     Keyboard            615
6        Mouse            450
7   Headphones            225
8      Earbuds           1975

In [79]:
result = (
    products
    .groupby('product_name')['selling_price']
    .sum()
).reset_index(name='selling_price')
result[
    result['selling_price'] < result['selling_price'].mean()
][['product_name', 'selling_price']].head(4)

        product_name  selling_price
0          Air Fryer           5125
1             Blazer           3300
2  Bluetooth Speaker           1505
3        Cargo Pants           1505

<pre>Next Question — Multi-row Subquery (IN)

Find all customers who have placed at least one order.

Return:

customer_id
customer_name</pre>

<pre>
customers[customer_id],
customers[customer_name],

customers[customer_id] IN (
    DISTINCT orders[customer_id]
)
</pre>

In [45]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT DISTINCT customer_id
    FROM retail_analysis.orders
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

In [83]:
customers[
    customers['customer_id'].isin(orders['customer_id'])
][['customer_id', 'customer_name']].head(4)

  customer_id  customer_name
0   cust_id01    Teerth Nagy
1   cust_id02    Jagat Palan
2   cust_id03  Isaiah Dhawan
3   cust_id04   Chatura Gera

<pre>Next Question — Multi-row Subquery with NOT IN

Find all customers who have never placed an order.

Return:

customer_id
customer_name</pre>

<pre>
customers[customer_id],
customers[customer_name],

customers[customer_id] NOT IN (
    DISTINCT orders[customer_id]
)
</pre>

In [46]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id NOT IN (
    SELECT DISTINCT customer_id 
    FROM retail_analysis.orders
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

In [84]:
customers[
    ~customers['customer_id'].isin(orders['customer_id'])
][['customer_id', 'customer_name']]

Empty DataFrame
Columns: [customer_id, customer_name]
Index: []

<pre>
Next Question — Multi-row Subquery with ANY

Find all products whose selling_price is greater
than the selling price of at least one 
product in the Clothing category.

Return:

product_id
product_name
category
selling_price
</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price],

products[selling_price] > (
    ANY products[selling_price]
    WHERE products[category] = 'Clothing'
)
</pre>

In [49]:
%%sql 
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE selling_price > ANY (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

46 rows affected.

+------------+-------------------+-------------+---------------+
| product_id |    product_name   |   category  | selling_price |
+------------+-------------------+-------------+---------------+
|   P_ID01   |     Smartphone    | Electronics |    30000.00   |
|   P_ID02   |       Laptop      | Electronics |    90000.00   |
|   P_ID03   |       Tablet      | Electronics |    12400.00   |
|   P_ID04   |     Desktop PC    | Electronics |    19750.00   |
|   P_ID05   |      Monitor      | Electronics |    5375.00    |
|   P_ID06   |      Keyboard     | Electronics |     615.00    |
|   P_ID09   |      Earbuds      | Electronics |    1975.00    |
|   P_ID10   | Bluetooth Speaker | Electronics |    1505.00    |
|   P_ID11   |     Smartwatch    | Electronics |    2460.00    |
|   P_ID12   |    Fitness Band   | Electronics |    7500.00    |
+------------+-------------------+-------------+---------------+
Truncated to displaylimit of 10.

In [88]:
clothing_min_price = products[
    products['category'] == 'Clothing'
]['selling_price'].min()
products[
    products['selling_price'] > clothing_min_price
][['product_id', 'product_name', 'category', 'selling_price']].head(10)

   product_id       product_name     category  selling_price
0      P_ID01         Smartphone  Electronics          30000
1      P_ID02             Laptop  Electronics          90000
2      P_ID03             Tablet  Electronics          12400
3      P_ID04         Desktop PC  Electronics          19750
4      P_ID05            Monitor  Electronics           5375
5      P_ID06           Keyboard  Electronics            615
8      P_ID09            Earbuds  Electronics           1975
9      P_ID10  Bluetooth Speaker  Electronics           1505
10     P_ID11         Smartwatch  Electronics           2460
11     P_ID12       Fitness Band  Electronics           7500

<pre>Next Question — Multi-row Subquery with ALL

Find all products whose selling_price is higher than
the selling price of every product in the Clothing category.

Return:

product_id
product_name
category
selling_price</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price]

products[selling_price] > (
    ALL products[selling_price]
    products[category] = 'Clothing'
)
</pre>

In [50]:
%%sql 
SELECT product_id, product_name, category, selling_price 
FROM retail_analysis.products
WHERE selling_price > ALL (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+------------+---------------------+----------------+---------------+
| product_id |     product_name    |    category    | selling_price |
+------------+---------------------+----------------+---------------+
|   P_ID01   |      Smartphone     |  Electronics   |    30000.00   |
|   P_ID02   |        Laptop       |  Electronics   |    90000.00   |
|   P_ID03   |        Tablet       |  Electronics   |    12400.00   |
|   P_ID04   |      Desktop PC     |  Electronics   |    19750.00   |
|   P_ID05   |       Monitor       |  Electronics   |    5375.00    |
|   P_ID12   |     Fitness Band    |  Electronics   |    7500.00    |
|   P_ID13   |       Printer       |  Electronics   |    5125.00    |
|   P_ID14   |       Scanner       |  Electronics   |    9300.00    |
|   P_ID20   | External Hard Drive |  Electronics   |    10150.00   |
|   P_ID45   |      Gas Stove      | Home & Kitchen |    4300.00    |
+------------+---------------------+----------------+---------------+
Truncated to displaylimit of 10.

In [91]:
clothing_max_price = products[
    products['category'] == 'Clothing'
]['selling_price'].max()
products[
    products['selling_price'] > clothing_max_price
][['product_id', 'product_name', 'category', 'selling_price']].head(6)

   product_id  product_name     category  selling_price
0      P_ID01    Smartphone  Electronics          30000
1      P_ID02        Laptop  Electronics          90000
2      P_ID03        Tablet  Electronics          12400
3      P_ID04    Desktop PC  Electronics          19750
4      P_ID05       Monitor  Electronics           5375
11     P_ID12  Fitness Band  Electronics           7500

<pre>
Question 1 — HAVING + Scalar Subquery

Find all customers whose total spending is 
greater than the overall average order value.

Return:

customer_id
customer_name
total_spending
</pre>

$$ overall\ AOV = \frac{\sum orders}{N orders} $$

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
SUM(products[selling_price] * order_items[quantity]) 
AS total_spending

total_spending > (
    SUM(products[selling_price] * order_items[quantity]) /
    DISTINCT COUNT(order_id)
)
<pre>

In [101]:
%%sql 
SELECT c.customer_id, c.customer_name, 
    SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name

HAVING SUM(p.selling_price * oi.quantity) > (
    SELECT SUM(p.selling_price * oi.quantity) / COUNT(DISTINCT o.order_id)
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+------------------------+----------------+
| customer_id |     customer_name      | total_spending |
+-------------+------------------------+----------------+
|  cust_id50  | Mitali Balasubramanian |   468541.00    |
|  cust_id49  |       Qushi Sood       |   219729.00    |
|  cust_id48  |      Divya Chahal      |   115405.00    |
|  cust_id47  |       Ekaraj Dua       |   832635.00    |
|  cust_id46  |      Damyanti Lad      |   1360002.00   |
|  cust_id45  |      Raghav Sethi      |   316220.00    |
|  cust_id44  |     Faris Sanghvi      |   570365.00    |
|  cust_id43  |      Pooja Boase       |   289120.00    |
|  cust_id42  |       Robert Deo       |   347374.00    |
|  cust_id41  |    Vincent Solanki     |   246230.00    |
+-------------+------------------------+----------------+
Truncated to displaylimit of 10.

In [109]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_spending'] = (
    merged['selling_price'] * merged['quantity']
)
avg_order_value = (
    (merged['selling_price'] * merged['quantity']).mean()
)
result = (
    merged
    .groupby(['customer_id', 'customer_name'])['total_spending']
    .sum()
).reset_index()

result[
    ['customer_id', 'customer_name', 'total_spending']
][result['total_spending'] > avg_order_value].head(4)

  customer_id  customer_name  total_spending
0   cust_id01    Teerth Nagy          263573
1   cust_id02    Jagat Palan          241560
2   cust_id03  Isaiah Dhawan          278229
3   cust_id04   Chatura Gera          389418

<pre>Next Question — HAVING + Multi-row Subquery

Find product categories whose total revenue is greater than 
the average total revenue across all categories.

Return:

category
total_revenue</pre>

<pre>
DISTINCT products[category],
SUM(products[selling_price] * order_items[quantity]) AS total_revenue
total_reveue > (
    AVG(WHOLE(total_revenue))
)
</pre>

In [13]:
%%sql 
SELECT p.category, SUM(p.selling_price * oi.quantity) AS total_revenue
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi 
ON p.product_id = oi.product_id
GROUP BY p.category
HAVING SUM(p.selling_price * oi.quantity) > (
    SELECT AVG(total_revenue)
    FROM (
        SELECT SUM(p.selling_price * oi.quantity) AS total_revenue
        FROM retail_analysis.products p 
        JOIN retail_analysis.order_items oi 
        ON p.product_id = oi.product_id
        GROUP BY p.category
    ) AS sub
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------+---------------+
|   category  | total_revenue |
+-------------+---------------+
| Electronics |  19705920.00  |
+-------------+---------------+

In [111]:
merged = pd.merge(products, order_items, on='product_id')
merged['revenue'] = (
    merged['selling_price'] * merged['quantity']
)
result = (
    merged
    .groupby('category')['revenue']
    .sum()
).reset_index(name='total_revenue')
result[
    ['category', 'total_revenue']
][result['total_revenue'] > result['total_revenue'].mean()]

      category  total_revenue
1  Electronics       19705920

**NESTED SUBQUERY**

<pre>Question

Find all products whose selling_price is greater than 
the highest average selling price among all categories.

1. Calculate average price for every category
        ↓
2. Find the highest category average
        ↓
3. Keep products whose price > that highest average

product_id
product_name
category
selling_price
</pre>

In [14]:
%%sql 
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT AVG(selling_price) AS avg_selling_price
    FROM retail_analysis.products
    GROUP BY category
    ORDER BY avg_selling_price DESC
    LIMIT 1
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+------------+---------------------+----------------+---------------+
| product_id |     product_name    |    category    | selling_price |
+------------+---------------------+----------------+---------------+
|   P_ID01   |      Smartphone     |  Electronics   |    30000.00   |
|   P_ID02   |        Laptop       |  Electronics   |    90000.00   |
|   P_ID03   |        Tablet       |  Electronics   |    12400.00   |
|   P_ID04   |      Desktop PC     |  Electronics   |    19750.00   |
|   P_ID20   | External Hard Drive |  Electronics   |    10150.00   |
|   P_ID49   |    Microwave Oven   | Home & Kitchen |    10500.00   |
+------------+---------------------+----------------+---------------+

In [127]:
category_selling_price = (
    products
    .groupby('category', as_index=False)['selling_price']
    .mean()
)
products[
    ['product_id', 'product_name', 'category', 'selling_price']
][products['selling_price'] > category_selling_price['selling_price'].max()]

   product_id         product_name        category  selling_price
0      P_ID01           Smartphone     Electronics          30000
1      P_ID02               Laptop     Electronics          90000
2      P_ID03               Tablet     Electronics          12400
3      P_ID04           Desktop PC     Electronics          19750
19     P_ID20  External Hard Drive     Electronics          10150
48     P_ID49       Microwave Oven  Home & Kitchen          10500

In [129]:
%%sql 
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT MAX(avg_selling_price)
    FROM (
        SELECT AVG(selling_price) AS avg_selling_price
        FROM retail_analysis.products
        GROUP BY category
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

6 rows affected.

+------------+---------------------+----------------+---------------+
| product_id |     product_name    |    category    | selling_price |
+------------+---------------------+----------------+---------------+
|   P_ID01   |      Smartphone     |  Electronics   |    30000.00   |
|   P_ID02   |        Laptop       |  Electronics   |    90000.00   |
|   P_ID03   |        Tablet       |  Electronics   |    12400.00   |
|   P_ID04   |      Desktop PC     |  Electronics   |    19750.00   |
|   P_ID20   | External Hard Drive |  Electronics   |    10150.00   |
|   P_ID49   |    Microwave Oven   | Home & Kitchen |    10500.00   |
+------------+---------------------+----------------+---------------+

<pre>Find the category that has the highest average selling price.</pre>

<pre>
DISTINCT products[category],
AVG(products[selling_price]) AS avg_selling_price
avg_selling_price = (
    MAX(WHOLE(avg_selling_price))
)
</pre>

In [14]:
%%sql 
SELECT category, AVG(selling_price) AS avg_selling_price
FROM retail_analysis.products
GROUP BY category
HAVING AVG(selling_price) = (
    SELECT MAX(avg_selling_price)
    FROM (
        SELECT AVG(selling_price) AS avg_selling_price
        FROM retail_analysis.products
        GROUP BY category
        ORDER BY avg_selling_price DESC # IF MORE THAN 1 MAX VALUE RETURNS
        LIMIT 1
    )
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+-------------+------------------------+
|   category  |   avg_selling_price    |
+-------------+------------------------+
| Electronics | 10117.7500000000000000 |
+-------------+------------------------+

<pre>Find all products belonging to the category 
that has the highest average selling price.</pre>

<pre>
product_id
category = max(avg(selling_price)) of category
</pre>

In [ ]:
%%sql 
WITH cte1 AS (
    SELECT product_name, category, selling_price,
    AVG(selling_price)
    OVER(
        PARTITION BY category
    ) AS avg_selling_price_category
    FROM retail_analysis.products
)
SELECT product_name, category, selling_price, avg_selling_price_category
FROM cte1
WHERE avg_selling_price_category = (
    SELECT MAX(avg_selling_price_category)
    FROM cte1
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

20 rows affected.

+-------------------+-------------+---------------+----------------------------+
|    product_name   |   category  | selling_price | avg_selling_price_category |
+-------------------+-------------+---------------+----------------------------+
|      Printer      | Electronics |    5125.00    |   10117.7500000000000000   |
|       Laptop      | Electronics |    90000.00   |   10117.7500000000000000   |
|       Tablet      | Electronics |    12400.00   |   10117.7500000000000000   |
|     Desktop PC    | Electronics |    19750.00   |   10117.7500000000000000   |
|      Monitor      | Electronics |    5375.00    |   10117.7500000000000000   |
|      Keyboard     | Electronics |     615.00    |   10117.7500000000000000   |
|       Mouse       | Electronics |     450.00    |   10117.7500000000000000   |
|     Headphones    | Electronics |     225.00    |   10117.7500000000000000   |
|      Earbuds      | Electronics |    1975.00    |   10117.7500000000000000   |
| Bluetooth Speaker | Electronics |    1505.00    |   10117.7500000000000000   |
+-------------------+-------------+---------------+----------------------------+
Truncated to displaylimit of 10.

In [15]:
%%sql 
WITH TargetCategory AS (
    SELECT category
    FROM retail_analysis.products
    GROUP BY category
    ORDER BY AVG(selling_price) DESC
    LIMIT 1
)
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE category = (SELECT category FROM TargetCategory);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

20 rows affected.

+------------+-------------------+-------------+---------------+
| product_id |    product_name   |   category  | selling_price |
+------------+-------------------+-------------+---------------+
|   P_ID01   |     Smartphone    | Electronics |    30000.00   |
|   P_ID02   |       Laptop      | Electronics |    90000.00   |
|   P_ID03   |       Tablet      | Electronics |    12400.00   |
|   P_ID04   |     Desktop PC    | Electronics |    19750.00   |
|   P_ID05   |      Monitor      | Electronics |    5375.00    |
|   P_ID06   |      Keyboard     | Electronics |     615.00    |
|   P_ID07   |       Mouse       | Electronics |     450.00    |
|   P_ID08   |     Headphones    | Electronics |     225.00    |
|   P_ID09   |      Earbuds      | Electronics |    1975.00    |
|   P_ID10   | Bluetooth Speaker | Electronics |    1505.00    |
+------------+-------------------+-------------+---------------+
Truncated to displaylimit of 10.

In [16]:
%%sql 
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE category = (
    SELECT category
    FROM retail_analysis.products
    GROUP BY category
    ORDER BY AVG(selling_price) DESC
    LIMIT 1
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

20 rows affected.

+------------+-------------------+-------------+---------------+
| product_id |    product_name   |   category  | selling_price |
+------------+-------------------+-------------+---------------+
|   P_ID01   |     Smartphone    | Electronics |    30000.00   |
|   P_ID02   |       Laptop      | Electronics |    90000.00   |
|   P_ID03   |       Tablet      | Electronics |    12400.00   |
|   P_ID04   |     Desktop PC    | Electronics |    19750.00   |
|   P_ID05   |      Monitor      | Electronics |    5375.00    |
|   P_ID06   |      Keyboard     | Electronics |     615.00    |
|   P_ID07   |       Mouse       | Electronics |     450.00    |
|   P_ID08   |     Headphones    | Electronics |     225.00    |
|   P_ID09   |      Earbuds      | Electronics |    1975.00    |
|   P_ID10   | Bluetooth Speaker | Electronics |    1505.00    |
+------------+-------------------+-------------+---------------+
Truncated to displaylimit of 10.

<pre>
Next Question — Correlated EXISTS + Data Analysis

Find all customers who have placed at least one order 
containing a product from the Electronics category.

Return:

customer_id, customer_name 
Exists in orders
category = "Electronics"
<pre>

In [26]:
%%sql 
SELECT c.customer_id, c.customer_name
FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id
WHERE p.category = 'Electronics'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

421 rows affected.

+-------------+-------------------+
| customer_id |   customer_name   |
+-------------+-------------------+
|  cust_id30  |     Kashvi Sem    |
|  cust_id23  |    Jagat Chawla   |
|  cust_id04  |    Chatura Gera   |
|  cust_id34  | Jagrati Narayanan |
|  cust_id01  |    Teerth Nagy    |
|  cust_id47  |     Ekaraj Dua    |
|  cust_id44  |   Faris Sanghvi   |
|  cust_id27  |    Jyoti Andra    |
|  cust_id28  |    Pranit Muni    |
|  cust_id23  |    Jagat Chawla   |
+-------------+-------------------+
Truncated to displaylimit of 10.

In [27]:
%%sql 
SELECT c.customer_id, c.customer_name
FROM retail_analysis.customers c
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o
    WHERE o.customer_id = c.customer_id
    AND order_id IN (
        SELECT order_id 
        FROM retail_analysis.order_items oi
        WHERE oi.product_id IN (
            SELECT product_id 
            FROM retail_analysis.products
            WHERE category = 'Electronics'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+------------------------+
| customer_id |     customer_name      |
+-------------+------------------------+
|  cust_id42  |       Robert Deo       |
|  cust_id16  |       Avi Andra        |
|  cust_id07  |     Sanaya Oommen      |
|  cust_id39  |     Gautami Ravel      |
|  cust_id34  |   Jagrati Narayanan    |
|  cust_id14  |       Qarin Sani       |
|  cust_id47  |       Ekaraj Dua       |
|  cust_id06  |    Vidhi Prabhakar     |
|  cust_id50  | Mitali Balasubramanian |
|  cust_id12  |     Samuel Sanghvi     |
+-------------+------------------------+
Truncated to displaylimit of 10.

In [28]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT DISTINCT customer_id 
    FROM retail_analysis.orders
    WHERE order_id IN (
        SELECT order_id 
        FROM retail_analysis.order_items
        WHERE product_id IN (
            SELECT product_id
            FROM retail_analysis.products
            WHERE category = 'Electronics'
        )
    )
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

<pre>
A single customer order many times. 
Suppose a customer has ordered 3 times 
-----------------------------------
customer_id | order_id | category
-----------------------------------
cust_1      |order_id_1 | A
            |order_id_2 | B
            |order_id_3 | C
-----------------------------
We have 3 kind of question for retriving data.
-----------------------------
Q1. Find customers who have placed only 
    B category products order.
Q2. Find customers who have placed at least 
    one B category product order.
Q3. Find customers who have never placed 
    (a single) B category products order ever.
---------------------------------
Q1 = (B, B, B), Q2 = (A,B,C), Q3 = (A,C,A)
------------------------------------------
WHERE category = B | WHERE category != B 
-------------------------------------------
Possible outcome                          
------------------------------------------
customer_id NOT IN ( )                   
------------------------------------------
Question 3         | Question 1   
-----------------------------------------
(B)       Y,N      | (A,C)    Y,N
( )       Y,Y *    | (A,C,A)  Y,N
(B,B,B)   Y,N      | ( )      Y,Y *
-------------------------------------------
customer_id IN (order's customer_id)
&&
customer_id NOT IN (WHERE category condition)
</pre>

### **Using IN/NOT IN**

<pre>Q1. Find customers who have placed only 'Clothing' category products.</pre>

In [6]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT customer_id
    FROM retail_analysis.orders
)
AND customer_id NOT IN (
    SELECT customer_id
    FROM retail_analysis.orders
    WHERE order_id IN (
        SELECT order_id 
        FROM retail_analysis.order_items
        WHERE product_id IN (
            SELECT product_id 
            FROM retail_analysis.products
            WHERE category != 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Q2. Find customers who have placed at least one 'Clothing category product.</pre>

In [11]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers 
WHERE customer_id IN (
    SELECT customer_id
    FROM retail_analysis.orders
    WHERE order_id IN (
        SELECT order_id 
        FROM retail_analysis.order_items
        WHERE product_id IN (
            SELECT product_id 
            FROM retail_analysis.products
            WHERE category = 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+------------------------+
| customer_id |     customer_name      |
+-------------+------------------------+
|  cust_id16  |       Avi Andra        |
|  cust_id42  |       Robert Deo       |
|  cust_id07  |     Sanaya Oommen      |
|  cust_id39  |     Gautami Ravel      |
|  cust_id14  |       Qarin Sani       |
|  cust_id34  |   Jagrati Narayanan    |
|  cust_id47  |       Ekaraj Dua       |
|  cust_id06  |    Vidhi Prabhakar     |
|  cust_id50  | Mitali Balasubramanian |
|  cust_id23  |      Jagat Chawla      |
+-------------+------------------------+
Truncated to displaylimit of 10.

<pre>Q3. Find customers who have never placed 'Clothing' category products ever.</pre>

In [13]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT customer_id 
    FROM retail_analysis.orders
)
AND customer_id NOT IN (
    SELECT customer_id 
    FROM retail_analysis.orders
    WHERE order_id IN (
        SELECT order_id 
        FROM retail_analysis.order_items
        WHERE product_id IN (
            SELECT product_id 
            FROM retail_analysis.products
            WHERE category = 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

### **Using Joins**

<pre>
Explain : 

cust_1 = (A,B,C) N,Y
cust_2 = (B,B,B) Y,Y *
COUNT(DISTINCT category) = 1
&&
MAX(category) = 'B' 
</pre>

<pre>Q1. Find customers who have placed only 'Clothing' category products.</pre>

In [12]:
%%sql
SELECT c.customer_id, c.customer_name

FROM retail_analysis.customers c
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
JOIN retail_analysis.products p 
ON oi.product_id = p.product_id

GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT p.category) = 1 
AND MAX(p.category) = 'Clothing';

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

WE CAN SOLVE IT BY USING CASE

In [13]:
%%sql 
SELECT c.customer_id, c.customer_name

FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id

GROUP BY c.customer_id, c.customer_name
HAVING COUNT(CASE WHEN p.category = 'Clothing' THEN 1 END) > 0
AND COUNT(CASE WHEN p.category != 'Clothing' THEN 1 END) = 0;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Q2. Find customers who have placed at least one 'Clothing category product.</pre>

In [27]:
%%sql 
SELECT c.customer_id, c.customer_name

FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id

WHERE p.category = 'Clothing'

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

379 rows affected.

+-------------+------------------------+
| customer_id |     customer_name      |
+-------------+------------------------+
|  cust_id35  |    Vaishnavi Baria     |
|  cust_id50  | Mitali Balasubramanian |
|  cust_id05  |      Radhika Kari      |
|  cust_id11  |      Logan Gopal       |
|  cust_id42  |       Robert Deo       |
|  cust_id10  |      Dayita Walia      |
|  cust_id02  |      Jagat Palan       |
|  cust_id35  |    Vaishnavi Baria     |
|  cust_id36  |      Watika Samra      |
|  cust_id34  |   Jagrati Narayanan    |
+-------------+------------------------+
Truncated to displaylimit of 10.

<pre>Q3. Find customers who have never placed 'Clothing' category products ever.</pre>

In [11]:
%%sql
SELECT c.customer_id, c.customer_name

FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id

GROUP BY c.customer_id, c.customer_name 
HAVING COUNT(CASE WHEN category = 'Clothing' THEN 1 END) = 0

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

### **Using EXISTS/NOT EXISTS**

<pre>Q1. Find customers who have placed only 'Clothing' category products.</pre>

In [15]:
%%sql 
SELECT c.customer_id, c.customer_name
FROM retail_analysis.customers c
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o
    WHERE c.customer_id = o.customer_id
)
AND NOT EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
    AND EXISTS (
        SELECT 1
        FROM retail_analysis.order_items oi 
        WHERE o.order_id = oi.order_id
        AND EXISTS (
            SELECT 1
            FROM retail_analysis.products p 
            WHERE oi.product_id = p.product_id
            AND p.category != 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Q2. Find customers who have placed at least one 'Clothing category product.</pre>

In [16]:
%%sql 
SELECT c.customer_id , c.customer_name
FROM retail_analysis.customers c
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE o.customer_id = c.customer_id
    AND EXISTS (
        SELECT 1
        FROM retail_analysis.order_items oi
        WHERE oi.order_id = o.order_id
        AND EXISTS (
            SELECT 1
            FROM retail_analysis.products p 
            WHERE p.product_id = oi.product_id
            AND category = 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+------------------------+
| customer_id |     customer_name      |
+-------------+------------------------+
|  cust_id16  |       Avi Andra        |
|  cust_id42  |       Robert Deo       |
|  cust_id07  |     Sanaya Oommen      |
|  cust_id39  |     Gautami Ravel      |
|  cust_id14  |       Qarin Sani       |
|  cust_id34  |   Jagrati Narayanan    |
|  cust_id47  |       Ekaraj Dua       |
|  cust_id06  |    Vidhi Prabhakar     |
|  cust_id50  | Mitali Balasubramanian |
|  cust_id23  |      Jagat Chawla      |
+-------------+------------------------+
Truncated to displaylimit of 10.

<pre>Q3. Find customers who have never placed 'Clothing' category products ever.</pre>

In [18]:
%%sql
SELECT c.customer_id, c.customer_name
FROM retail_analysis.customers c 
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
)
AND NOT EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE o.customer_id = c.customer_id 
    AND EXISTS (
        SELECT 1
        FROM retail_analysis.order_items oi 
        WHERE oi.order_id = o.order_id 
        AND EXISTS (
            SELECT 1
            FROM retail_analysis.products p 
            WHERE p.product_id = oi.product_id
            AND p.category = 'Clothing'
        )
    )
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Q1. Find customers who have placed only 'Clothing' category products.</pre>

In [ ]:
%%sql 
SELECT c.customer_id, c.customer_name

FROM retail_analysis.customers c
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi 
ON o.order_id = oi.order_id
JOIN retail_analysis.products p 
ON oi.product_id = p.product_id

GROUP BY c.customer_id, c.customer_name
HAVING MAX() = ALL (
    SELECT p.category
    FROM retail_analysis.products p
)

<pre>Question 1 — ALL Subquery

Find all products whose price is greater than the price of every Clothing product.<pre>

In [11]:
%%sql 
SELECT product_id, product_name, selling_price,category
FROM retail_analysis.products
WHERE selling_price > ALL (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+------------+---------------------+---------------+----------------+
| product_id |     product_name    | selling_price |    category    |
+------------+---------------------+---------------+----------------+
|   P_ID01   |      Smartphone     |    30000.00   |  Electronics   |
|   P_ID02   |        Laptop       |    90000.00   |  Electronics   |
|   P_ID03   |        Tablet       |    12400.00   |  Electronics   |
|   P_ID04   |      Desktop PC     |    19750.00   |  Electronics   |
|   P_ID05   |       Monitor       |    5375.00    |  Electronics   |
|   P_ID12   |     Fitness Band    |    7500.00    |  Electronics   |
|   P_ID13   |       Printer       |    5125.00    |  Electronics   |
|   P_ID14   |       Scanner       |    9300.00    |  Electronics   |
|   P_ID20   | External Hard Drive |    10150.00   |  Electronics   |
|   P_ID45   |      Gas Stove      |    4300.00    | Home & Kitchen |
+------------+---------------------+---------------+----------------+
Truncated to displaylimit of 10.

In [17]:
%%sql 
SELECT product_id, product_name, selling_price, category
FROM retail_analysis.products
WHERE selling_price > (
    SELECT MAX(selling_price)
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+------------+---------------------+---------------+----------------+
| product_id |     product_name    | selling_price |    category    |
+------------+---------------------+---------------+----------------+
|   P_ID01   |      Smartphone     |    30000.00   |  Electronics   |
|   P_ID02   |        Laptop       |    90000.00   |  Electronics   |
|   P_ID03   |        Tablet       |    12400.00   |  Electronics   |
|   P_ID04   |      Desktop PC     |    19750.00   |  Electronics   |
|   P_ID05   |       Monitor       |    5375.00    |  Electronics   |
|   P_ID12   |     Fitness Band    |    7500.00    |  Electronics   |
|   P_ID13   |       Printer       |    5125.00    |  Electronics   |
|   P_ID14   |       Scanner       |    9300.00    |  Electronics   |
|   P_ID20   | External Hard Drive |    10150.00   |  Electronics   |
|   P_ID45   |      Gas Stove      |    4300.00    | Home & Kitchen |
+------------+---------------------+---------------+----------------+
Truncated to displaylimit of 10.

<pre>Question 2 — ALL

Find all products whose selling_price is greater 
than every Clothing product's selling_price, 
AND whose selling_price is less than every Electronics product's selling_price.</pre>

In [19]:
%%sql 
SELECT product_id, product_name, selling_price, category
FROM retail_analysis.products
WHERE selling_price > ALL (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
)
AND selling_price < ALL (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Electronics' 
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+------------+--------------+---------------+----------+
| product_id | product_name | selling_price | category |
+------------+--------------+---------------+----------+
+------------+--------------+---------------+----------+

<pre>Question 1 — SOME

Find all products whose selling_price is greater 
than the selling price of at least one Clothing product.</pre>

In [20]:
%%sql 
SELECT product_id, product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > SOME (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

46 rows affected.

+------------+-------------------+---------------+
| product_id |    product_name   | selling_price |
+------------+-------------------+---------------+
|   P_ID01   |     Smartphone    |    30000.00   |
|   P_ID02   |       Laptop      |    90000.00   |
|   P_ID03   |       Tablet      |    12400.00   |
|   P_ID04   |     Desktop PC    |    19750.00   |
|   P_ID05   |      Monitor      |    5375.00    |
|   P_ID06   |      Keyboard     |     615.00    |
|   P_ID09   |      Earbuds      |    1975.00    |
|   P_ID10   | Bluetooth Speaker |    1505.00    |
|   P_ID11   |     Smartwatch    |    2460.00    |
|   P_ID12   |    Fitness Band   |    7500.00    |
+------------+-------------------+---------------+
Truncated to displaylimit of 10.

<pre>Clothing prices → 500, 800, 1200

Product price = 700

700 > 500  ✅
700 > 800  ❌
700 > 1200 ❌

At least one is TRUE → included ✅</pre>

**Subquery in SELECT**

<pre>Question 1
Show the customer_name and the total order count for each customer.</pre>

In [5]:
%%sql 
SELECT c.customer_name, (
    SELECT COUNT(o.order_id)
    FROM retail_analysis.orders o
    WHERE o.customer_id = c.customer_id
) total_orders
FROM retail_analysis.customers c

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+--------------------------+--------------+
|      customer_name       | total_orders |
+--------------------------+--------------+
|       Teerth Nagy        |      25      |
|       Jagat Palan        |      24      |
|      Isaiah Dhawan       |      21      |
|       Chatura Gera       |      19      |
|       Radhika Kari       |      17      |
|     Vidhi Prabhakar      |      26      |
|      Sanaya Oommen       |      21      |
|        Abeer Rout        |      20      |
| Rajeshri Balasubramanian |      13      |
|       Dayita Walia       |      21      |
+--------------------------+--------------+
Truncated to displaylimit of 10.

<pre>Question 2 — Subquery in SELECT

For each product, display:

product_name
selling_price
the average selling price of all products</pre>

In [19]:
%%sql 
SELECT product_name, selling_price,
    (
        SELECT AVG(selling_price)
        FROM retail_analysis.products
    ) avg_selling_price
FROM retail_analysis.products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+---------------+-----------------------+
|    product_name   | selling_price |   avg_selling_price   |
+-------------------+---------------+-----------------------+
|     Smartphone    |    30000.00   | 5241.9600000000000000 |
|       Laptop      |    90000.00   | 5241.9600000000000000 |
|       Tablet      |    12400.00   | 5241.9600000000000000 |
|     Desktop PC    |    19750.00   | 5241.9600000000000000 |
|      Monitor      |    5375.00    | 5241.9600000000000000 |
|      Keyboard     |     615.00    | 5241.9600000000000000 |
|       Mouse       |     450.00    | 5241.9600000000000000 |
|     Headphones    |     225.00    | 5241.9600000000000000 |
|      Earbuds      |    1975.00    | 5241.9600000000000000 |
| Bluetooth Speaker |    1505.00    | 5241.9600000000000000 |
+-------------------+---------------+-----------------------+
Truncated to displaylimit of 10.

In [23]:
%%sql 
SELECT product_name, selling_price, 
AVG(selling_price)
OVER() AS avg_selling_price
FROM retail_analysis.products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+---------------+-----------------------+
|    product_name   | selling_price |   avg_selling_price   |
+-------------------+---------------+-----------------------+
|     Smartphone    |    30000.00   | 5241.9600000000000000 |
|       Laptop      |    90000.00   | 5241.9600000000000000 |
|       Tablet      |    12400.00   | 5241.9600000000000000 |
|     Desktop PC    |    19750.00   | 5241.9600000000000000 |
|      Monitor      |    5375.00    | 5241.9600000000000000 |
|      Keyboard     |     615.00    | 5241.9600000000000000 |
|       Mouse       |     450.00    | 5241.9600000000000000 |
|     Headphones    |     225.00    | 5241.9600000000000000 |
|      Earbuds      |    1975.00    | 5241.9600000000000000 |
| Bluetooth Speaker |    1505.00    | 5241.9600000000000000 |
+-------------------+---------------+-----------------------+
Truncated to displaylimit of 10.

<pre>Find each product's product_name, selling_price, 
and the difference between its selling_price 
and the average selling price of all products.</pre>

In [51]:
%%sql 
SELECT product_name, selling_price,
    (
        SELECT AVG(selling_price) 
        FROM retail_analysis.products
    ) avg_selling_price,
    (selling_price - (
            SELECT AVG(selling_price)
            FROM retail_analysis.products
        )
    ) difference
FROM retail_analysis.products

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+---------------+-----------------------+------------------------+
|    product_name   | selling_price |   avg_selling_price   |       difference       |
+-------------------+---------------+-----------------------+------------------------+
|     Smartphone    |    30000.00   | 5241.9600000000000000 | 24758.0400000000000000 |
|       Laptop      |    90000.00   | 5241.9600000000000000 | 84758.0400000000000000 |
|       Tablet      |    12400.00   | 5241.9600000000000000 | 7158.0400000000000000  |
|     Desktop PC    |    19750.00   | 5241.9600000000000000 | 14508.0400000000000000 |
|      Monitor      |    5375.00    | 5241.9600000000000000 |  133.0400000000000000  |
|      Keyboard     |     615.00    | 5241.9600000000000000 | -4626.9600000000000000 |
|       Mouse       |     450.00    | 5241.9600000000000000 | -4791.9600000000000000 |
|     Headphones    |     225.00    | 5241.9600000000000000 | -5016.9600000000000000 |
|      Earbuds      |    1975.00    | 5241.9600000000000000 | -3266.9600000000000000 |
| Bluetooth Speaker |    1505.00    | 5241.9600000000000000 | -3736.9600000000000000 |
+-------------------+---------------+-----------------------+------------------------+
Truncated to displaylimit of 10.

### **CASE & SUBQUERIES**

Find the `product_name`, `selling_price`, and a `price_status` for every product. Set `price_status` to `'Above Average'` when the product's `selling_price` is greater than the overall average selling price of all products; otherwise, set it to `'Below Average'`. Use a `CASE` statement with a subquery to calculate the overall average selling price.

<pre>Question 1 — Subquery with CASE

For each product, display:

product_name
selling_price
price_status

Set price_status as:

'Above Average' if the product's selling_price is greater than 
the overall average selling price.
'Below Average' otherwise.</pre>

In [52]:
%%sql 
SELECT product_name, selling_price, 
    (
        SELECT AVG(selling_price)
        FROM retail_analysis.products
    ) overall_avg_selling_price, 
    CASE
        WHEN selling_price > (
            SELECT AVG(selling_price)
            FROM retail_analysis.products
        ) THEN 'Above Average'
        ELSE 'Below Average'
    END AS price_status
FROM retail_analysis.products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+---------------+---------------------------+---------------+
|    product_name   | selling_price | overall_avg_selling_price |  price_status |
+-------------------+---------------+---------------------------+---------------+
|     Smartphone    |    30000.00   |   5241.9600000000000000   | Above Average |
|       Laptop      |    90000.00   |   5241.9600000000000000   | Above Average |
|       Tablet      |    12400.00   |   5241.9600000000000000   | Above Average |
|     Desktop PC    |    19750.00   |   5241.9600000000000000   | Above Average |
|      Monitor      |    5375.00    |   5241.9600000000000000   | Above Average |
|      Keyboard     |     615.00    |   5241.9600000000000000   | Below Average |
|       Mouse       |     450.00    |   5241.9600000000000000   | Below Average |
|     Headphones    |     225.00    |   5241.9600000000000000   | Below Average |
|      Earbuds      |    1975.00    |   5241.9600000000000000   | Below Average |
| Bluetooth Speaker |    1505.00    |   5241.9600000000000000   | Below Average |
+-------------------+---------------+---------------------------+---------------+
Truncated to displaylimit of 10.

Find the `product_name`, `selling_price`, and a `price_category` for every product. Set `price_category` to `'Expensive'` if the product's selling price is greater than the average selling price of **Clothing products**, and set it to `'Not Expensive'` otherwise. Use a `CASE` statement with a subquery.

<pre>if selling_price > avg(clothing(selling_price)) then Expensive
else, Not Expensive</pre>

In [55]:
%%sql 
SELECT product_name, selling_price, 
    CASE
        WHEN selling_price > (
                SELECT AVG(selling_price)
                FROM retail_analysis.products
                WHERE category = 'Clothing'
            ) THEN 'Expensive'
        ELSE 'Not Expensive'
    END AS price_category
FROM retail_analysis.products;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+---------------+----------------+
|    product_name   | selling_price | price_category |
+-------------------+---------------+----------------+
|     Smartphone    |    30000.00   |   Expensive    |
|       Laptop      |    90000.00   |   Expensive    |
|       Tablet      |    12400.00   |   Expensive    |
|     Desktop PC    |    19750.00   |   Expensive    |
|      Monitor      |    5375.00    |   Expensive    |
|      Keyboard     |     615.00    | Not Expensive  |
|       Mouse       |     450.00    | Not Expensive  |
|     Headphones    |     225.00    | Not Expensive  |
|      Earbuds      |    1975.00    |   Expensive    |
| Bluetooth Speaker |    1505.00    |   Expensive    |
+-------------------+---------------+----------------+
Truncated to displaylimit of 10.

In [ ]:
products.head(1)

In [18]:
order_items.sort_values('order_id', ascending=False).head(1)

    order_item_id   order_id product_id  quantity
998   ORD_ITEM999  ORD_ID999     P_ID44         9

In [12]:
orders.head(1)

   order_id customer_id  order_date payment_mode order_status
0  ORD_ID01   cust_id30  2025-01-01          UPI    Cancelled

In [39]:
customers.head(1)

  customer_id customer_name  gender  age    city      state   join_date
0   cust_id01   Teerth Nagy  female   46  Mysuru  Karnataka  2024-01-03