In [1]:
print('hello')

hello

In [2]:
%load_ext sql

In [ ]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:[password]@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting to 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [8]:
import pandas as pd

In [37]:
products = pd.read_csv(r"d:\SQL\data generator\output\products.csv")
order_items = pd.read_csv(r"d:\SQL\data generator\output\order_items.csv")

<pre>Question 1 — Single-value Subquery

Business asks:

Find all products whose selling_price is greater than the average selling_price of all products.</pre>

In [7]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT AVG(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

c:\Users\Windows-10\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\connection\connection.py:881: JupySQLRollbackPerformed: Current transaction is aborted. JupySQL executed a ROLLBACK operation.
  warnings.warn(

9 rows affected.

+---------------------+---------------+
|     product_name    | selling_price |
+---------------------+---------------+
|      Smartphone     |    30000.00   |
|        Laptop       |    90000.00   |
|        Tablet       |    12400.00   |
|      Desktop PC     |    19750.00   |
|       Monitor       |    5375.00    |
|     Fitness Band    |    7500.00    |
|       Scanner       |    9300.00    |
| External Hard Drive |    10150.00   |
|    Microwave Oven   |    10500.00   |
+---------------------+---------------+

In [ ]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] > products['selling_price'].mean()]

           product_name  selling_price
0            Smartphone          30000
1                Laptop          90000
2                Tablet          12400
3            Desktop PC          19750
4               Monitor           5375
11         Fitness Band           7500
13              Scanner           9300
19  External Hard Drive          10150
48       Microwave Oven          10500

<pre>Question 2 — Single-Value Subquery

Business asks:

Find all products whose selling_price is lower than the maximum selling_price among all products.</pre>

In [18]:
%%sql 
SELECT product_name, selling_price 
FROM retail_analysis.products
WHERE selling_price < (
    SELECT MAX(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

49 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|     Headphones    |     225.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [21]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] < products['selling_price'].max()].head(4)

  product_name  selling_price
0   Smartphone          30000
2       Tablet          12400
3   Desktop PC          19750
4      Monitor           5375

<pre>Question 3 — Single-Value Subquery

Business asks:

Find all products whose selling_price is equal to the minimum selling_price among all products.</pre>

In [24]:
%%sql
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price = (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

2 rows affected.

+--------------+---------------+
| product_name | selling_price |
+--------------+---------------+
|  Headphones  |     225.00    |
|  USB Cable   |     225.00    |
+--------------+---------------+

In [25]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] == products['selling_price'].min()]

   product_name  selling_price
7    Headphones            225
18    USB Cable            225

<pre>Question 4 — Single-Value Subquery

Business asks:

Find all orders whose order_value is greater than the average order_value of all orders.</pre>

In [36]:
%%sql 
SELECT oi.order_id, (p.selling_price * oi.quantity) AS order_value
FROM retail_analysis.products p
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
WHERE (p.selling_price * oi.quantity) > (
    SELECT AVG(p.selling_price * oi.quantity)
    FROM retail_analysis.products p 
    JOIN retail_analysis.order_items oi
    ON p.product_id = oi.product_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

180 rows affected.

+----------+-------------+
| order_id | order_value |
+----------+-------------+
| ORD_ID02 |   31500.00  |
| ORD_ID12 |   74400.00  |
| ORD_ID20 |   30750.00  |
| ORD_ID38 |  540000.00  |
| ORD_ID39 |  270000.00  |
| ORD_ID40 |   27900.00  |
| ORD_ID44 |   67500.00  |
| ORD_ID45 |   30750.00  |
| ORD_ID46 |   39500.00  |
| ORD_ID56 |   51250.00  |
+----------+-------------+
Truncated to displaylimit of 10.

In [42]:
merged = pd.merge(products, order_items, on='product_id')
merged['order_value'] = (
    merged['selling_price'] * merged['quantity']
)
merged[
    ['order_id', 'order_value']
][merged['order_value'] > merged['order_value'].mean()].head(4)

   order_id  order_value
0  ORD_ID39       270000
1  ORD_ID62       150000
2  ORD_ID76       240000
3  ORD_ID97       180000

<pre>Question 5 — Single-Value Subquery

Business asks:

Find all products whose selling_price is greater than the
 minimum selling_price of products in the Electronics category.</pre>

In [ ]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
    WHERE category = 'Electronics'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

48 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Laptop      |    90000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [70]:
filter = (
    products['category'] == 'Electronics'
)[ products['selling_price'].mean()]
# products[
#     ['product_name', 'selling_price']
# ][products['selling_price'] > filter]
filter

KeyError: np.float64(5241.96)

In [56]:
products.head(1)

  product_id product_name     category brand  cost_price  selling_price
0     P_ID01   Smartphone  Electronics    HP       25000          30000