In [4]:
print('hello')

hello

In [5]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [6]:
%sql postgresql://postgres.zdtizyvifuiegbbfpsee:password@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres

Connecting and switching to connection 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

In [7]:
import pandas as pd

In [8]:
products = pd.read_csv(r"d:\SQL\data generator\output\products.csv")
order_items = pd.read_csv(r"d:\SQL\data generator\output\order_items.csv")
orders = pd.read_csv(r"d:\SQL\data generator\output\orders.csv", parse_dates=['order_date'])
customers = pd.read_csv(r"d:\SQL\data generator\output\customers.csv")

<pre>Question 1 — Single-value Subquery

Business asks:

Find all products whose selling_price is greater than the average selling_price of all products.</pre>

In [6]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT AVG(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

9 rows affected.

+---------------------+---------------+
|     product_name    | selling_price |
+---------------------+---------------+
|      Smartphone     |    30000.00   |
|        Laptop       |    90000.00   |
|        Tablet       |    12400.00   |
|      Desktop PC     |    19750.00   |
|       Monitor       |    5375.00    |
|     Fitness Band    |    7500.00    |
|       Scanner       |    9300.00    |
| External Hard Drive |    10150.00   |
|    Microwave Oven   |    10500.00   |
+---------------------+---------------+

In [ ]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] > products['selling_price'].mean()]

           product_name  selling_price
0            Smartphone          30000
1                Laptop          90000
2                Tablet          12400
3            Desktop PC          19750
4               Monitor           5375
11         Fitness Band           7500
13              Scanner           9300
19  External Hard Drive          10150
48       Microwave Oven          10500

<pre>Question 2 — Single-Value Subquery

Business asks:

Find all products whose selling_price is lower than the maximum selling_price among all products.</pre>

In [18]:
%%sql 
SELECT product_name, selling_price 
FROM retail_analysis.products
WHERE selling_price < (
    SELECT MAX(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

49 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|     Headphones    |     225.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [21]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] < products['selling_price'].max()].head(4)

  product_name  selling_price
0   Smartphone          30000
2       Tablet          12400
3   Desktop PC          19750
4      Monitor           5375

<pre>Question 3 — Single-Value Subquery

Business asks:

Find all products whose selling_price is equal to the minimum selling_price among all products.</pre>

In [24]:
%%sql
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price = (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

2 rows affected.

+--------------+---------------+
| product_name | selling_price |
+--------------+---------------+
|  Headphones  |     225.00    |
|  USB Cable   |     225.00    |
+--------------+---------------+

In [25]:
products[
    ['product_name', 'selling_price']
][products['selling_price'] == products['selling_price'].min()]

   product_name  selling_price
7    Headphones            225
18    USB Cable            225

<pre>Question 4 — Single-Value Subquery

Business asks:

Find all orders whose order_value is greater than the average order_value of all orders.</pre>

In [36]:
%%sql 
SELECT oi.order_id, (p.selling_price * oi.quantity) AS order_value
FROM retail_analysis.products p
JOIN retail_analysis.order_items oi
ON p.product_id = oi.product_id
WHERE (p.selling_price * oi.quantity) > (
    SELECT AVG(p.selling_price * oi.quantity)
    FROM retail_analysis.products p 
    JOIN retail_analysis.order_items oi
    ON p.product_id = oi.product_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

180 rows affected.

+----------+-------------+
| order_id | order_value |
+----------+-------------+
| ORD_ID02 |   31500.00  |
| ORD_ID12 |   74400.00  |
| ORD_ID20 |   30750.00  |
| ORD_ID38 |  540000.00  |
| ORD_ID39 |  270000.00  |
| ORD_ID40 |   27900.00  |
| ORD_ID44 |   67500.00  |
| ORD_ID45 |   30750.00  |
| ORD_ID46 |   39500.00  |
| ORD_ID56 |   51250.00  |
+----------+-------------+
Truncated to displaylimit of 10.

In [42]:
merged = pd.merge(products, order_items, on='product_id')
merged['order_value'] = (
    merged['selling_price'] * merged['quantity']
)
merged[
    ['order_id', 'order_value']
][merged['order_value'] > merged['order_value'].mean()].head(4)

   order_id  order_value
0  ORD_ID39       270000
1  ORD_ID62       150000
2  ORD_ID76       240000
3  ORD_ID97       180000

<pre>Question 5 — Single-Value Subquery

Business asks:

Find all products whose selling_price is greater than the
 minimum selling_price of products in the Electronics category.</pre>

In [ ]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price > (
    SELECT MIN(selling_price)
    FROM retail_analysis.products
    WHERE category = 'Electronics'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

48 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|     Smartphone    |    30000.00   |
|       Laptop      |    90000.00   |
|       Tablet      |    12400.00   |
|     Desktop PC    |    19750.00   |
|      Monitor      |    5375.00    |
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

In [31]:
electronics_min = products[products['category'] == 'Electronics']['selling_price'].min()
products[
    ['product_name', 'selling_price']
][products['selling_price'] > electronics_min].head(4)

  product_name  selling_price
0   Smartphone          30000
1       Laptop          90000
2       Tablet          12400
3   Desktop PC          19750

<pre>Question 6 — Single-Value Subquery

Business asks:

Find all customers whose total spending is greater than the average total spending of all customers.</pre>

<pre>
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantity]).sum() as total_spending
total_spending > total_spending.mean()
customers *1 2
products 1* 3
order_items 1* 4
</pre>

In [ ]:
%%sql 
SELECT c.customer_name, SUM(p.selling_price * oi.quantity) AS total_spending
FROM retail_analysis.customers c
JOIN retail_analysis.orders o
ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
ON o.order_id = oi.order_id
JOIN retail_analysis.products p
ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name

HAVING SUM(p.selling_price * oi.quantity) > (
    SELECT AVG(total_spending)
    FROM (
        SELECT o.customer_id, SUM(p.selling_price * oi.quantity) AS total_spending
        FROM retail_analysis.orders o
        JOIN retail_analysis.order_items oi
        ON o.order_id = oi.order_id
        JOIN retail_analysis.products p
        ON oi.product_id = p.product_id
        GROUP BY o.customer_id
    ) customer_totals
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-----------------+----------------+
|  customer_name  | total_spending |
+-----------------+----------------+
|  Sanaya Oommen  |   927650.00    |
|    Ekaraj Dua   |   832635.00    |
| Vaishnavi Baria |   730768.00    |
|   Jagat Chawla  |   655495.00    |
|   Damyanti Lad  |   1360002.00   |
|  Anamika Walla  |   696675.00    |
|    Avi Andra    |   1294265.00   |
|    Abeer Raj    |   541385.00    |
|  Orinder Ghose  |   1488355.00   |
|  Harsh Bhargava |   1122411.00   |
+-----------------+----------------+
Truncated to displaylimit of 10.

In [11]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['total_spending'] = (
    merged['selling_price'] * merged['quantity']
)
result = (
    merged
    .groupby(['customer_name', 'customer_id'])['total_spending']
    .sum()
).reset_index(name='total_spending')
result[result['total_spending'] > result['total_spending'].mean()].head(4)

   customer_name customer_id  total_spending
0      Abeer Raj   cust_id17          541385
4  Anamika Walla   cust_id24          696675
5      Avi Andra   cust_id16         1294265
9   Damyanti Lad   cust_id46         1360002

<pre>Question 6 — Multi-Row Subquery

Business asks:

Find all customers who have placed at least one order in 2026.</pre>

<pre>
customers[customer_name]
customers 1* 2
orders 1* 3
WHERE YEAR(orders[order_date]) = 2026
</pre>

In [17]:
%%sql 
SELECT c.customer_name,c.customer_id
FROM retail_analysis.customers c 
JOIN retail_analysis.orders o 
ON c.customer_id = o.customer_id
WHERE EXTRACT (YEAR FROM o.order_date) = 2025;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1000 rows affected.

+------------------------+-------------+
|     customer_name      | customer_id |
+------------------------+-------------+
|       Kashvi Sem       |  cust_id30  |
|       Qarin Sani       |  cust_id14  |
|    Vaishnavi Baria     |  cust_id35  |
| Mitali Balasubramanian |  cust_id50  |
|      Jagat Chawla      |  cust_id23  |
|      Chatura Gera      |  cust_id04  |
|   Jagrati Narayanan    |  cust_id34  |
|      Teerth Nagy       |  cust_id01  |
|       Ekaraj Dua       |  cust_id47  |
|     Faris Sanghvi      |  cust_id44  |
+------------------------+-------------+
Truncated to displaylimit of 10.

In [21]:
merged = pd.merge(customers, orders, on='customer_id')
merged[
    ['customer_name', 'customer_id']
][merged['order_date'].dt.year == 2025].head(4)

  customer_name customer_id
0   Teerth Nagy   cust_id01
1   Teerth Nagy   cust_id01
2   Teerth Nagy   cust_id01
3   Teerth Nagy   cust_id01

<pre>Question 7 — Multi-Row Subquery

Business asks:

Find all products that have been ordered at least once.</pre>

<pre>
products[product_name],
order_items[order_id].count() >= 1
products 1* 2
order_items 1* 3
</pre>

In [ ]:
%%sql 
SELECT 
    p.product_name, 
    COUNT(oi.order_id) AS total_orders
FROM retail_analysis.products p 
JOIN retail_analysis.order_items oi 
    ON p.product_id = oi.product_id
GROUP BY p.product_name, p.product_id;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+---------------------+--------------+
|     product_name    | total_orders |
+---------------------+--------------+
|       Sweater       |      18      |
|   Pressure Cooker   |      18      |
|       Charger       |      23      |
|       Scanner       |      20      |
|        Dress        |      14      |
|       T-Shirt       |      14      |
| External Hard Drive |      17      |
|        Shirt        |      14      |
|        Chinos       |      22      |
|     Cookware Set    |      21      |
+---------------------+--------------+
Truncated to displaylimit of 10.

In [30]:
merged = pd.merge(products, order_items, on='product_id')
total_orders = (
    merged
    .groupby(['product_name', 'product_id'])['order_id']
    .count()
).reset_index(name='total_orders')
total_orders.head(4)

        product_name product_id  total_orders
0          Air Fryer     P_ID48            20
1             Blazer     P_ID27            14
2  Bluetooth Speaker     P_ID10            23
3        Cargo Pants     P_ID31            25

<pre>Find all products that have been purchased 
by customers who have placed an order worth more than ₹10,000.</pre>

<pre>
DISTINCT customers[customer_name],
products[product_name],
(order_items[quantity] * products[selling_price]) as order_worth
HAVING order_worth > 10000
customers 1* 2
products 1* 3 
order_items 1* 4
</pre>

In [ ]:
%%sql
SELECT 
    c.customer_name, 
    SUM(oi.quantity * p.selling_price) AS order_worth
FROM retail_analysis.customers c
JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_name
HAVING SUM(oi.quantity * p.selling_price) > 10000;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------------+-------------+
|   customer_name   | order_worth |
+-------------------+-------------+
|    Pranit Muni    |  370715.00  |
| Jagrati Narayanan |  290192.00  |
|    Jyoti Andra    |  390570.00  |
|    Amruta Puri    |  189936.00  |
|    Vinaya Reddy   |  750590.00  |
|   Gautami Ravel   |  454575.00  |
|    Damyanti Lad   |  1360002.00 |
|   Orinder Ghose   |  1488355.00 |
|  Vidhi Prabhakar  |  415565.00  |
|    Watika Samra   |  205986.00  |
+-------------------+-------------+
Truncated to displaylimit of 10.

In [21]:
merged = (
    customers
    .merge(orders, on='customer_id')
    .merge(order_items, on='order_id')
    .merge(products, on='product_id')
)
merged['value'] = (
    merged['quantity'] * merged['selling_price']
)
active_customers = (
    merged
    .groupby('customer_name')['value']
    .sum()
).reset_index(name='order_worth')
active_customers[active_customers['order_worth'] > 10000].head(4)

  customer_name  order_worth
0     Abeer Raj       541385
1    Abeer Rout       468799
2  Amaira Koshy       409675
3   Amruta Puri       189936

<pre>Question 8 — EXISTS

Find all customers who have placed at least one order.</pre>

<pre>
customers[customer_id]
customers[customer_name]
customers 1* 2
orders 1* 3
</pre>

In [24]:
%%sql 
SELECT 
    c.customer_id,
    c.customer_name
FROM retail_analysis.customers c
WHERE EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

<pre>Question 9 — NOT EXISTS

Business asks:

Find all customers who have never placed an order.</pre>

In [26]:
%%sql 
SELECT 
    c.customer_id,
    c.customer_name
FROM retail_analysis.customers c 
WHERE NOT EXISTS (
    SELECT 1
    FROM retail_analysis.orders o 
    WHERE c.customer_id = o.customer_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>Question — Correlated Subquery

Business asks:

Find all products whose selling_price is greater than the 
average selling price of their own category.</pre>

<pre>products[product], 
products[selling_price],
where products[selling_price] > (
    DISTINCT products[category], 
    product[selling_price].mean()
)</pre>

In [29]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price > (
    SELECT AVG(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p2.category = p1.category
) limit 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+-------------+---------------+
| product_id | product_name |   category  | selling_price |
+------------+--------------+-------------+---------------+
|   P_ID01   |  Smartphone  | Electronics |    30000.00   |
+------------+--------------+-------------+---------------+

In [28]:
%%sql 
WITH merged AS (
    SELECT product_id, product_name, category, selling_price,
    AVG(selling_price)
    OVER(
        PARTITION BY category
    ) AS avg_selling_price_category
    FROM retail_analysis.products
)

SELECT product_id, product_name, category, selling_price, avg_selling_price_category
FROM merged
WHERE selling_price > avg_selling_price_category limit 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+----------+---------------+----------------------------+
| product_id | product_name | category | selling_price | avg_selling_price_category |
+------------+--------------+----------+---------------+----------------------------+
|   P_ID24   |    Hoodie    | Clothing |    1720.00    |   1324.1500000000000000    |
+------------+--------------+----------+---------------+----------------------------+

<pre>Question — Correlated Subquery

Business asks:

Find all products whose selling_price is lower than 
the average selling price of their own category.</pre>

<pre>
products[product_id],
products[product_name],
products[selling_price]
products[selling_price] < (
    DISTINCT[category]
    products[selling_price].mean()
)
</pre>

In [ ]:
%%sql
SELECT p1.product_id, p1.product_name, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price < (
    SELECT AVG(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p1.category = p2.category # PARTITION BY
) limit 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+---------------+
| product_id | product_name | selling_price |
+------------+--------------+---------------+
|   P_ID05   |   Monitor    |    5375.00    |
+------------+--------------+---------------+

<pre>
Question — Correlated Subquery

Find all products whose selling_price is equal to 
the highest selling price of their own category.</pre>

<pre>
products[proudct_id],
products[proudct_name],
products[category],
products[selling_price]
WHERE products[selling_price] = (
    DISTINCT category
    proucts[selling_price].max()
)
</pre>

In [30]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price = (
    SELECT MAX(p2.selling_price)
    FROM retail_analysis.products p2 
    WHERE p1.category = p2.category # PARITION BY
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

3 rows affected.

+------------+----------------+----------------+---------------+
| product_id |  product_name  |    category    | selling_price |
+------------+----------------+----------------+---------------+
|   P_ID02   |     Laptop     |  Electronics   |    90000.00   |
|   P_ID27   |     Blazer     |    Clothing    |    3300.00    |
|   P_ID49   | Microwave Oven | Home & Kitchen |    10500.00   |
+------------+----------------+----------------+---------------+

<pre>
Correlated Subquery + MIN()

Business asks:

Find all products whose selling_price is greater 
than the cheapest product in their own category.
</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price]
WHERE products[selling_price] > (
    DISTINCT category
    products[selling_price].min()
)
</pre>

In [6]:
%%sql 
SELECT p1.product_id, p1.product_name, p1.category, p1.selling_price
FROM retail_analysis.products p1
WHERE p1.selling_price > (
    SELECT MIN(p2.selling_price)
    FROM retail_analysis.products p2
    WHERE p1.category = p2.category # partition by
) limit 1;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

1 rows affected.

+------------+--------------+-------------+---------------+
| product_id | product_name |   category  | selling_price |
+------------+--------------+-------------+---------------+
|   P_ID01   |  Smartphone  | Electronics |    30000.00   |
+------------+--------------+-------------+---------------+

<pre>
Correlated Subquery + Orders

Business asks:

Find customers whose total spending is greater than 
the average spending of customers who have placed at least one order.
</pre>

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
(products[selling_price] * order_items[quantitiy]).sum() AS total_spending
WHERE total_spending > (
    AVG(WHOLE(total_spending))
    WHERE COUNT(order_id) >= 1 
)
</pre>

In [51]:
%%sql 
WITH cte AS (
    SELECT c.customer_id, c.customer_name, SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
)

SELECT customer_id, customer_name, total_spending
FROM cte 
WHERE total_spending > (
    SELECT AVG(total_spending)
    FROM cte
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-------------+-----------------+----------------+
| customer_id |  customer_name  | total_spending |
+-------------+-----------------+----------------+
|  cust_id07  |  Sanaya Oommen  |   927650.00    |
|  cust_id47  |    Ekaraj Dua   |   832635.00    |
|  cust_id35  | Vaishnavi Baria |   730768.00    |
|  cust_id23  |   Jagat Chawla  |   655495.00    |
|  cust_id46  |   Damyanti Lad  |   1360002.00   |
|  cust_id24  |  Anamika Walla  |   696675.00    |
|  cust_id16  |    Avi Andra    |   1294265.00   |
|  cust_id17  |    Abeer Raj    |   541385.00    |
|  cust_id13  |  Orinder Ghose  |   1488355.00   |
|  cust_id25  |  Harsh Bhargava |   1122411.00   |
+-------------+-----------------+----------------+
Truncated to displaylimit of 10.

In [88]:
%%sql 
SELECT customer_id, customer_name, total_spending
FROM (
    SELECT c.customer_id, c.customer_name, SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
) AS derived_table
WHERE total_spending > (
    SELECT AVG(avg_spendings)
    FROM (
        SELECT o.customer_id, SUM(p.selling_price * oi.quantity) AS avg_spendings
        FROM retail_analysis.orders o
        JOIN retail_analysis.order_items oi
        ON o.order_id = oi.order_id
        JOIN retail_analysis.products p
        ON oi.product_id = p.product_id
        GROUP BY o.customer_id
    ) AS derived_table2
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

16 rows affected.

+-------------+-----------------+----------------+
| customer_id |  customer_name  | total_spending |
+-------------+-----------------+----------------+
|  cust_id07  |  Sanaya Oommen  |   927650.00    |
|  cust_id47  |    Ekaraj Dua   |   832635.00    |
|  cust_id35  | Vaishnavi Baria |   730768.00    |
|  cust_id23  |   Jagat Chawla  |   655495.00    |
|  cust_id46  |   Damyanti Lad  |   1360002.00   |
|  cust_id24  |  Anamika Walla  |   696675.00    |
|  cust_id16  |    Avi Andra    |   1294265.00   |
|  cust_id17  |    Abeer Raj    |   541385.00    |
|  cust_id13  |  Orinder Ghose  |   1488355.00   |
|  cust_id25  |  Harsh Bhargava |   1122411.00   |
+-------------+-----------------+----------------+
Truncated to displaylimit of 10.

<pre>
Next Question — Scalar Subquery

Find all products whose selling_price is lower 
than the average selling_price of all products.
</pre>

<pre>
DISTINCT products[product_name],
SUM(products[selling_price]) AS products_selling_price

products_selling_price < (
    AVG(WHOLE(products_selling_price))
)
</pre>

In [27]:
%%sql 
WITH cte AS (
    SELECT product_name, SUM(selling_price) AS product_selling_price
    FROM retail_analysis.products
    GROUP BY product_name
)

SELECT product_name, product_selling_price
FROM cte 
WHERE product_selling_price < (
    SELECT AVG(product_selling_price)
    FROM cte
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [30]:
%%sql 
SELECT product_name, SUM(selling_price) AS product_selling_price
FROM retail_analysis.products
GROUP BY product_name
HAVING SUM(selling_price) < (
    SELECT AVG(total_price)
    FROM (
        SELECT SUM(selling_price) AS total_price
        FROM retail_analysis.products 
        GROUP BY product_name
    ) AS sub
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [36]:
%%sql
WITH product_summary AS (
    SELECT 
        product_name, 
        SUM(selling_price) AS product_selling_price,
        AVG(SUM(selling_price)) OVER() AS avg_selling_price
    FROM retail_analysis.products
    GROUP BY product_name
)
SELECT product_name, product_selling_price
FROM product_summary
WHERE product_selling_price < avg_selling_price;

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [39]:
%%sql 
SELECT product_name, SUM(selling_price) AS product_selling_price
FROM retail_analysis.products
GROUP BY product_name
HAVING SUM(selling_price) < (
    SELECT avg_sum_price
    FROM (
        SELECT AVG(SUM(selling_price)) OVER() AS avg_sum_price
        FROM retail_analysis.products
        GROUP BY product_name
    )
    LIMIT 1
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-----------------+-----------------------+
|   product_name  | product_selling_price |
+-----------------+-----------------------+
|      Dress      |        1505.00        |
|      Hoodie     |        1720.00        |
|     Charger     |         700.00        |
|      Webcam     |        1600.00        |
|     Printer     |        5125.00        |
|     T-Shirt     |         645.00        |
|   Cargo Pants   |        1505.00        |
|      Kurti      |        1050.00        |
|      Shirt      |        1100.00        |
| Electric Kettle |        1050.00        |
+-----------------+-----------------------+
Truncated to displaylimit of 10.

In [40]:
%%sql 
SELECT product_name, selling_price
FROM retail_analysis.products
WHERE selling_price < (
    SELECT AVG(selling_price)
    FROM retail_analysis.products
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

41 rows affected.

+-------------------+---------------+
|    product_name   | selling_price |
+-------------------+---------------+
|      Keyboard     |     615.00    |
|       Mouse       |     450.00    |
|     Headphones    |     225.00    |
|      Earbuds      |    1975.00    |
| Bluetooth Speaker |    1505.00    |
|     Smartwatch    |    2460.00    |
|      Printer      |    5125.00    |
|       Webcam      |    1600.00    |
|     Microphone    |    1975.00    |
|     Power Bank    |    1025.00    |
+-------------------+---------------+
Truncated to displaylimit of 10.

<pre>Next Question — Multi-row Subquery (IN)

Find all customers who have placed at least one order.

Return:

customer_id
customer_name</pre>

<pre>
customers[customer_id],
customers[customer_name],

customers[customer_id] IN (
    DISTINCT orders[customer_id]
)
</pre>

In [45]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id IN (
    SELECT DISTINCT customer_id
    FROM retail_analysis.orders
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+
| customer_id |      customer_name       |
+-------------+--------------------------+
|  cust_id01  |       Teerth Nagy        |
|  cust_id02  |       Jagat Palan        |
|  cust_id03  |      Isaiah Dhawan       |
|  cust_id04  |       Chatura Gera       |
|  cust_id05  |       Radhika Kari       |
|  cust_id06  |     Vidhi Prabhakar      |
|  cust_id07  |      Sanaya Oommen       |
|  cust_id08  |        Abeer Rout        |
|  cust_id09  | Rajeshri Balasubramanian |
|  cust_id10  |       Dayita Walia       |
+-------------+--------------------------+
Truncated to displaylimit of 10.

<pre>Next Question — Multi-row Subquery with NOT IN

Find all customers who have never placed an order.

Return:

customer_id
customer_name</pre>

<pre>
customers[customer_id],
customers[customer_name],

customers[customer_id] NOT IN (
    DISTINCT orders[customer_id]
)
</pre>

In [46]:
%%sql 
SELECT customer_id, customer_name
FROM retail_analysis.customers
WHERE customer_id NOT IN (
    SELECT DISTINCT customer_id 
    FROM retail_analysis.orders
)

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

+-------------+---------------+
| customer_id | customer_name |
+-------------+---------------+
+-------------+---------------+

<pre>
Next Question — Multi-row Subquery with ANY

Find all products whose selling_price is greater
than the selling price of at least one product in the Clothing category.

Return:

product_id
product_name
category
selling_price
</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price],

products[selling_price] > (
    ANY products[selling_price]
    WHERE products[category] = 'Clothing'
)
</pre>

In [49]:
%%sql 
SELECT product_id, product_name, category, selling_price
FROM retail_analysis.products
WHERE selling_price > ANY (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

46 rows affected.

+------------+-------------------+-------------+---------------+
| product_id |    product_name   |   category  | selling_price |
+------------+-------------------+-------------+---------------+
|   P_ID01   |     Smartphone    | Electronics |    30000.00   |
|   P_ID02   |       Laptop      | Electronics |    90000.00   |
|   P_ID03   |       Tablet      | Electronics |    12400.00   |
|   P_ID04   |     Desktop PC    | Electronics |    19750.00   |
|   P_ID05   |      Monitor      | Electronics |    5375.00    |
|   P_ID06   |      Keyboard     | Electronics |     615.00    |
|   P_ID09   |      Earbuds      | Electronics |    1975.00    |
|   P_ID10   | Bluetooth Speaker | Electronics |    1505.00    |
|   P_ID11   |     Smartwatch    | Electronics |    2460.00    |
|   P_ID12   |    Fitness Band   | Electronics |    7500.00    |
+------------+-------------------+-------------+---------------+
Truncated to displaylimit of 10.

<pre>Next Question — Multi-row Subquery with ALL

Find all products whose selling_price is higher than
the selling price of every product in the Clothing category.

Return:

product_id
product_name
category
selling_price</pre>

<pre>
products[product_id],
products[product_name],
products[category],
products[selling_price]

products[selling_price] > (
    ALL products[selling_price]
    products[category] = 'Clothing'
)
</pre>

In [50]:
%%sql 
SELECT product_id, product_name, category, selling_price 
FROM retail_analysis.products
WHERE selling_price > ALL (
    SELECT selling_price
    FROM retail_analysis.products
    WHERE category = 'Clothing'
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

12 rows affected.

+------------+---------------------+----------------+---------------+
| product_id |     product_name    |    category    | selling_price |
+------------+---------------------+----------------+---------------+
|   P_ID01   |      Smartphone     |  Electronics   |    30000.00   |
|   P_ID02   |        Laptop       |  Electronics   |    90000.00   |
|   P_ID03   |        Tablet       |  Electronics   |    12400.00   |
|   P_ID04   |      Desktop PC     |  Electronics   |    19750.00   |
|   P_ID05   |       Monitor       |  Electronics   |    5375.00    |
|   P_ID12   |     Fitness Band    |  Electronics   |    7500.00    |
|   P_ID13   |       Printer       |  Electronics   |    5125.00    |
|   P_ID14   |       Scanner       |  Electronics   |    9300.00    |
|   P_ID20   | External Hard Drive |  Electronics   |    10150.00   |
|   P_ID45   |      Gas Stove      | Home & Kitchen |    4300.00    |
+------------+---------------------+----------------+---------------+
Truncated to displaylimit of 10.

<pre>
Question 1 — HAVING + Scalar Subquery

Find all customers whose total spending is 
greater than the overall average order value.

Return:

customer_id
customer_name
total_spending
</pre>

$$ overall\ AOV = \frac{\sum orders}{N orders} $$

<pre>
DISTINCT customers[customer_id],
DISTINCT customers[customer_name],
SUM(products[selling_price] * order_items[quantity]) AS total_spending

total_spending > (
    SUM(products[selling_price] * order_items[quantity]) /
    DISTINCT COUNT(order_id)
)
<pre>

In [59]:
%%sql 
SELECT c.customer_id, c.customer_name, 
    SUM(p.selling_price * oi.quantity) AS total_spending
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
HAVING SUM(p.selling_price * oi.quantity) > (
    SELECT SUM(p.selling_price * oi.quantity) / COUNT(DISTINCT o.order_id)
    FROM retail_analysis.customers c
    JOIN retail_analysis.orders o
    ON c.customer_id = o.customer_id
    JOIN retail_analysis.order_items oi
    ON o.order_id = oi.order_id
    JOIN retail_analysis.products p
    ON oi.product_id = p.product_id
);

Running query in 'postgresql://postgres.zdtizyvifuiegbbfpsee:***@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres'

50 rows affected.

+-------------+--------------------------+----------------+
| customer_id |      customer_name       | total_spending |
+-------------+--------------------------+----------------+
|  cust_id07  |      Sanaya Oommen       |   927650.00    |
|  cust_id39  |      Gautami Ravel       |   454575.00    |
|  cust_id47  |        Ekaraj Dua        |   832635.00    |
|  cust_id50  |  Mitali Balasubramanian  |   468541.00    |
|  cust_id45  |       Raghav Sethi       |   316220.00    |
|  cust_id35  |     Vaishnavi Baria      |   730768.00    |
|  cust_id09  | Rajeshri Balasubramanian |   316885.00    |
|  cust_id49  |        Qushi Sood        |   219729.00    |
|  cust_id27  |       Jyoti Andra        |   390570.00    |
|  cust_id08  |        Abeer Rout        |   468799.00    |
+-------------+--------------------------+----------------+
Truncated to displaylimit of 10.

In [38]:
products.head(1)

  product_id product_name     category brand  cost_price  selling_price
0     P_ID01   Smartphone  Electronics    HP       25000          30000

In [18]:
order_items.sort_values('order_id', ascending=False).head(1)

    order_item_id   order_id product_id  quantity
998   ORD_ITEM999  ORD_ID999     P_ID44         9

In [12]:
orders.head(1)

   order_id customer_id  order_date payment_mode order_status
0  ORD_ID01   cust_id30  2025-01-01          UPI    Cancelled

In [39]:
customers.head(1)

  customer_id customer_name  gender  age    city      state   join_date
0   cust_id01   Teerth Nagy  female   46  Mysuru  Karnataka  2024-01-03